### ISSUE TITLE
Are there plans to enable Sessions for AllReady?

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1002]
so we can use things like TempData and Session? Right now, looks like AllReady does not configure it Startup.

**Comment by MisterJames** [comment]
I was looking into this. I want TempData so we can convert to PRG. 

I want to incorporate [this](http://jameschambers.com/2014/06/day-14-bootstrap-alerts-and-mvc-framework-tempdata/) into AllReady.

**Comment by mgmccarthy** [comment]
we already do PRG in some places, but we're "going back to the well" (aka, the database) way more than we have do. TempData is a GREAT tool to offload db redundant db queries into memory and really helps with PRG

as far as the article goes, we have the SAME exact thing wired up where I work. We can drop warnings and errors into TempData and let it do the work for us.

It's super useful for "confirmation" screens... which we don't really have on AllReady yet, we just redirect back to the "Index" action method in order to do a fresh ready after something like a delete, for example.

**Comment by mgmccarthy** [comment]
any plans to simply enable Session (and thus, enabling TempData) w/out the changes @MisterJames proposed? Having TempData available would make PRG much easier in controllers

**Comment by stevejgordon** [comment]
What about using the IMemoryCache to prevent duplicate DB calls and cache some of the data. I've been using this a fair amount on a current project. I suspect a combination of approaches to suit specific requirements would make sense.

Note IMemoryCache works while we're at a scale of 1. If the app scales out we might want to look at the distributed cache option also.

**Comment by mgmccarthy** [comment]
@stevejgordon caching is kind of overkill for what TempData would bring us. TempData is a nice abstraction over Session that is simple to use and doesn't have the overhead of cache management: expiration policies, stale data, etc...

Granted, I don't know anything about IMemoryCache as I've never used it before. 

Either way having Session/TempData enabled and eventually deciding on a caching strategy for AllReady would be a good thing

**Comment by stevejgordon** [comment]
@mgmccarthy TempData only lives until the next request so caching would certainly reduce DB calls if traffic gets higher from multiple users. I don't think we have much instrumentation in the code but we'd ideally want to monitor that and reduce DB calls where possible.

Agreed it might be a bit early to optimise but caching in ASP.NET Core is pretty easy with the IMemoryCache abstraction. Inject it and then a couple of lines to use it.

**Comment by mgmccarthy** [comment]
@stevejgordon, that's why I want to use TempData and not a cache for some operations. An example of where TempData is very useful is:

- initial read on Get
- post back form with changes
- redirect to a confirmation screen (I don't think we have much of these in AllReady). This is where we're use TempData to carry the changes from the post back to display to the user via a screen
- submit changes
(there are other examples I'm sure, but this is one that comes to mind)

TempData does not carry the same cognitive load as caching does, although the purpose of both is the same, to alleviate reads on the db.

If you only need the data for one redirect, use TempData. If you need the data more often, then we can use caching. 

Caching carries a cognitive load that requires a developer to know what they're doing... cache expiration policy... etc... Also, as you pointed out, if we scale out, then we need to introduce distributed caching, and that's where things like cache expiration become more difficult b/c we're dealing with multiple machines.

I like TempData b/c its's simple and easy to use. Put you data in it, redirect, then get the data back out. The cleanup of that data from Session is handled for you by the TempData implementation. No injected cache provider, no cache expiration policy, etc...

**Comment by stevejgordon** [comment]
Setting to vNext as this would be useful for some between request messaging. On the set team lead I currently cheat and return a querystring value to the details action so it knows whether to show a status message or not. This would be much better if implemented via TempData.

**Comment by mgmccarthy** [comment]
@stevejgordon, first, we need to implement TempData, which is based off of Session. For some reason, the ASP.NET Core team did not include TempData as part of the framework (not too sure why, as I find it a very useful abstraction)

**Comment by stevejgordon** [comment]
@mgmccarthy I think if we're happy with an in memory session implementation (i.e. not scalable without sticky sessions) it looks quite straightforward to get this added.

**Comment by tonysurma** [comment]
remember the beauty of issues is we can implement it that way with a limitation and log an issue (tag it as devops) that it doesn't scale without sticky so we can track later when it becomes an issue (pun intended) 😸

**Comment by mgmccarthy** [comment]
I don't think we're load balancing in the live environment, so in-memory should be safe. The IMemoryCache you added for route optimization relies on the live environment not being load balanced so we can use an in-memory cache (which is the fastest).

**Comment by mgmccarthy** [comment]
Andre Locke wrote a great blog on a TempData implemenation for ASP.NET Core [https://andrewlock.net/post-redirect-get-using-tempdata-in-asp-net-core/](https://andrewlock.net/post-redirect-get-using-tempdata-in-asp-net-core/).

After wiring up sessions, this might be a good place to start to our TempData functionality.
