### ISSUE TITLE
SendConfirmAccountEmailHandler and SendAccountConfirmationEmailHandler do the same thing...

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1026]
I'm currently working on this

@MisterJames @tonysurma @BillWagner please assign to me

this is another is a series of issues (#946 and #967) where we have two different handlers doing the exact same thing, but with different context in the message

`SendConfirmAccountEmailHandler` contains this message:
`await emailSender.SendEmailAsync(message.Email, "Confirm your allReady account", $"Please confirm your allReady account by clicking this link: <a href=\"{message.CallbackUrl}\">link</a>")`

`SendAccountConfirmationEmailHandler` contains this message:
`await emailSender.SendEmailAsync(message.Email, "Confirm your account", $"Please confirm your account by clicking this <a href=\"{message.CallbackUrl}\">link</a>")`

the only difference is `SendConfirmAccountEmailHandler` puts the word **allReady** in the message, and `SendAccountConfirmationEmailHandler` does not.

I could consolidate these two handlers into one handler once a decision is made on the verbiages of the messgae

**Comment by mgmccarthy** [comment]
@tonysurma @MisterJames @BillWagner. Can we get a decision on the "verbiage" here and I can refactor out the duplicate code?

**Comment by tonysurma** [comment]
again so, so sorry for the delay.  Please use the allready worded one and thank you so much for persistence on this @mgmccarthy
