### ISSUE TITLE
Receive request from smoke alarm portal

### ISSUE THREAD

**Issue by cecilia-donnelly** [HTBox/allReady#1055]
@MisterJames opened https://github.com/redcross/smoke-alarm-portal/issues/196 in the "get a smoke alarm" repo, and this is the corresponding half of that work:
1.  An endpoint we can hit with each new smoke alarm request that comes in.  This endpoint would receive a request object with these fields: 
   
   ```
   name, // the name of the person requesting the alarm  
   address, // their address  
   assigned_rc_region, // the Red Cross region associated with their zip code  
   city,  
   state,  
   zip,  
   phone,  
   email,  
   serial, // our unique identifier: Red Cross region code - 2-digit fiscal year - integer  
   status // currently: new, in progress, installed, or canceled  
   ```

and respond with a status and a boolean indicating whether or not AllReady will handle this request (see [this comment](https://github.com/redcross/smoke-alarm-portal/issues/196#issuecomment-213773653) for details).
1. When the status of a request changes, you can post the new status to our `/admin/requests/status/:id` endpoint.
2. You might want to hit our endpoint at `/regions` for the list of currently active regions.

**Comment by seanepping** [comment]
@tonysurma I will take a look at this one

**Comment by seanepping** [comment]
@tonysurma  Summing up out conversation:

We want to move the latter part of the above description into a new story/issue

> When the status of a request changes, you can post the new status to our /admin/requests/status/:id endpoint.

> You might want to hit our endpoint at /regions for the list of currently active regions.

We also discussed that we need to have a way for a user, when registering for an api key, could add a status change endpoint.  This would be a known status url that can be called when the status of the request changes and can be looked up internally.

Did I miss anything?

**Comment by seanepping** [comment]
I will be adding an ExternalId that will correspond to the serial portion of the request payload; this should allow us to support more unique ids from varied systems and allow us to work into a status change callback mechanism into external systems with the unique ids that they use.

I will am thinking about how the id for the above status endpoint will be received as part of the request.  I believe that it would be keyed off of the token itself, or some other id that is associated with the token.

**Comment by tonysurma** [comment]
Keeping this open so we can do further work as needed as well as validate this 'works' from the getamokearlarm side

**Comment by stevejgordon** [comment]
@MisterJames We touched on maybe using IdentityServer4 for auth between APIs. Is this something we need to figure out for this milestone, or would a fixed token that can be generated (one per campaign) be enough at this point to allow us to start creating endpoints to accept requests?

**Comment by tonysurma** [comment]
@MisterJames can you help update where we are on this?

**Comment by mgmccarthy** [comment]
@tonysurma please assign this to me

**Comment by tonysurma** [comment]
@mgmccarthy do you feel we can close this for december milestone?

**Comment by mgmccarthy** [comment]
@tonysurma we can close this

**Comment by mgmccarthy** [comment]
@tonysurma, this piece of this Issue is still not done:

> When the status of a request changes, you can post the new status to our /admin/requests/status/:id endpoint.

what we do have done is the initial request back to GASA's endpoint when we receive a new API Request.

As far as what statuses they expect us to update back to them on a request we've decided to service, I'm assuming it's these:
`status // currently: new, in progress, installed, or canceled`

I'll check with the GASA folks
