### ISSUE TITLE
Error received when trying to navigate to any /Admin/* pages

### ISSUE THREAD

**Issue by gmford** [HTBox/allReady#1057]
I am able to log in as Administrator@example.com and organization@example.com. However, an error is displayed when I try to navigate to any page under /Admin. 

![adminerror](https://cloud.githubusercontent.com/assets/20876231/17458176/c8162048-5bcf-11e6-89d7-0a0a789c810b.png)

I do not get the error when logging in as User@example.com. 

Version: 1.0.0.0 ddb2198

**Comment by tonysurma** [comment]
Talked with @mheggeseth and I am also not sure if these are exceptions and they are getting swallowed by the code and not logged out anywhere for us to view

**Comment by mheggeseth** [comment]
@tonysurma This can be closed. Superseded by the more specific #1066.
