### ISSUE TITLE
Campaign details view not binding to resources attribute

### ISSUE THREAD

**Issue by SteveStrong** [HTBox/allReady#106]
![resource not found](https://cloud.githubusercontent.com/assets/500861/10714001/a86a19a8-7aab-11e5-92c0-e80ea4dbf66c.PNG)

I do not thing the ko. view model is complete,  it is missing the field resources,  I am not sure where to go to correct this.

**Comment by mheggeseth** [comment]
Yup, it's broken. I think in campaigns.js you might find a reference to resources that isn't actually hooked up to anything. This is from work done for #26 that wasn't really functional or complete. At the very least, the issue should be reopened but I'll leave it up to @tonysurma whether to consider it in scope for November MVP.

**Comment by BillWagner** [comment]
@mheggeseth @SteveStrong Looks like this is done. Closing.  If I'm wrong, please re-open.
