### ISSUE TITLE
Errors on admin pages due to views

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#1066]
![image](https://cloud.githubusercontent.com/assets/5067595/17458915/80c211e6-5bea-11e6-8323-4a420b4e2250.png)
![image](https://cloud.githubusercontent.com/assets/5067595/17458917/94927364-5bea-11e6-95e2-ad6749d4d59d.png)
![image](https://cloud.githubusercontent.com/assets/5067595/17458920/9e5a0574-5bea-11e6-9d92-a0a57a688e4f.png)
![image](https://cloud.githubusercontent.com/assets/5067595/17458923/a94106b8-5bea-11e6-896c-9ff8f61f75fe.png)

**Comment by tonysurma** [comment]
@mheggeseth is this related to what you saw with views elsewhere I wonder?

**Comment by gftrader** [comment]
Initially, I was only seeing this problem on the Azure deployment, but have since been able to login and navigate to the Admin pages successfully. Has this been resolved or is the problem intermittent?

**Comment by tonysurma** [comment]
yep I just fixed this on the azure deployment the whole Areas directory was missing...  more slop from the RC to RTM deploymnent mess
