### ISSUE TITLE
on home page log off link is blue

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#1067]
but only on the home page

![image](https://cloud.githubusercontent.com/assets/5067595/17459134/33b67b8c-5bf2-11e6-878f-0cd843645c34.png)

**Comment by mheggeseth** [comment]
This is because `_LayoutMainPage.cshtml` doesn't cache-bust with `asp-append-version="true"`. I'll fix it.

What _should_ happen is that `_LayoutMainPage.cshtml` should die and we should only have `_Layout.cshtml`. I'll write up a separate issue for that.
