### ISSUE TITLE
Admin - Remove Address1 and Address2 fields for Itinerary on Create Event page

### ISSUE THREAD

**Issue by gmford** [HTBox/allReady#1069]
You can probably keep City and State. 

A Rally, on the other hand, would need the address fields. 

Source: App review. 

Version: 1.0.0.0 ddb2198

**Comment by gordanac** [comment]
I will take a look at this one

**Comment by tonysurma** [comment]
thx @gordanac

**Comment by tonysurma** [comment]
To clarify this, and agree/disagree @OhMcGoo the goal was to remove address 1 and 2 from being required and NOT remove the fields.  This will allow either
1313 mockingbird ln, schaumburg, il 90210 OR
Schaumburg, IL 90210 as both being valid

**Comment by gordanac** [comment]
@tonysurma thanks for clarifying
