### ISSUE TITLE
Convert Custom UserType Claims to Built-in Role Claim Types

### ISSUE THREAD

**Issue by MisterJames** [HTBox/allReady#107]
Through refactoring in #105 it was discovered that we were using custom claims to represent user roles. This could be further simplified through the use of the built in role claim types.

**Comment by tonysurma** [comment]
Is tenant admin the admin for a specific tenant our the admin of tenants (all of them) in the system as a whole in the code? Before we add direction I want to make sure we are on same page with names.

**Comment by MisterJames** [comment]
I would think that the ability to administer any given tenant is a question of role, whereas the ability to administer a specific tenant is a question of row-level security. @dpaquette would that be in line with what you've seen in the code?

There may be another role required, something in the vain of "SystemTenantAdmin" that would be for a site-level administrator to act on behalf of any tenant.

**Comment by tonysurma** [comment]
@MisterJames Ok gotcha.

From a requirements point of view we need (using names that in no way need to be what is in the code):
"AllReady Admins" that have power to CRUD organizations aka tenants and do everything on the site
"Organization Admins" they have scope within an Organization (imagine HTBox was an organization provisioned by an AllReady Admin) to create/edit campaigns, activities, tasks, volunteer assignements etc. etc.

That is what's needed now.  Over time we will want more granular rights within orgs so they can have admins/managers for volunteer mgmt. vs. content and perhaps per specific campaigns and the like.

**Comment by MisterJames** [comment]
Great, and with claims that is all doable. For example, in the future the only "role" that would be allowed to administer volunteer mgmt would be someone with "VolunteerManager" as a claim, not "OrganizationAdmin" or any other role. But since users can have multiple role claims, we would grandfather in anyone from org admin to volunteer mgmt. 

There's a lot of ways to skin this one, but most of them will handle what you're describing. My sense is that we're okay here to continue with this, if you're on board.

**Comment by tonysurma** [comment]
@MisterJames as long as it satisfies the requirements and seems logical/not overly complex we are on board and this fits all those :+1:

**Comment by tonysurma** [comment]
@MisterJames @stevejgordon still a thing?

**Comment by stevejgordon** [comment]
@tonysurma Good question. We've just popped #34 back to the top of the stack per discussions here with @RichardCampbell so this might become a related item.

**Comment by stevejgordon** [comment]
Think we can close this down as with the incoming IdentityServer, all access can be controlled within the app via access tables. We may choose to append some claims, but I have a PR in which might cover an authorization process that works for our needs. We can review that as part of IdServer integration. Do let me know if it needs to be re-opened.
