### ISSUE TITLE
Combine _LayoutMainPage.cshtml and _Layout.cshtml

### ISSUE THREAD

**Issue by mheggeseth** [HTBox/allReady#1071]
`_LayoutMainPage.cshtml` (used only for `/Home/Index`, the home view of the app) has the same purpose as `_Layout.cshtml` and is more or less a duplication of it with some non-essential differences. Reduce maintenance malarkey by combining them into one layout view.

**Comment by jonbakerappdev** [comment]
I am working on this...

**Comment by tonysurma** [comment]
@mheggeseth any chance you can review @jonbakerappdev PR for this?

Thanks @jonbakerappdev for your contributions and welcome to the project!
