### ISSUE TITLE
Display geocoded requests on build itinerary screen

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#1080]
once we have #1077 and #1078 
- [x] display requests on map as pins
- [x] vary display of pins based on status
- [ ] filter by status and other items already on screen
- [ ] tools for visual selection (lasso, click individual)
- [ ] order the list of selected items as optimized route (given start address)

**Comment by tonysurma** [comment]
cc @gftrader

**Comment by stevejgordon** [comment]
@tonysurma Looking at if I can pick any of these up with my limited js knowledge.

We currently have a map displaying the request on the select requests screen. At this point it's any unassigned requests so presume no colour coding here.

Is the requirement above also about displaying the map on the itinerary details page therefore showing the requests assigned to the itinerary and their status?

**Comment by tonysurma** [comment]
Yes it should be on itinerary page @stevejgordon

**Comment by stevejgordon** [comment]
@tonysurma Thanks. I've created a new issue to track adding the map to this page also. I'm going to have a go at getting that working with at least status colouring included.

**Comment by tonysurma** [comment]
@stevejgordon how should we update this issue?

**Comment by stevejgordon** [comment]
@tonysurma I'm not sure we need this master issue any longer as the 3 remaining broken out issues cover the requirement.
