### ISSUE TITLE
Solution architecture guide prerequisites are out of date

### ISSUE THREAD

**Issue by digitaldrummerj** [HTBox/allReady#1087]
At [https://github.com/HTBox/allReady/wiki/Solution-architecture](https://github.com/HTBox/allReady/wiki/Solution-architecture) in the "Get Started with the allReady solution" the prerequistes need to be updated to list ASP.NET Core 1.0 instead of ASP.NET 5 RC1.

The guide also does not mention Update 3 is needed.

**Comment by Bnewman** [comment]
I would like to volunteer to take this task on.

**Comment by tonysurma** [comment]
Thanks @Bnewman 

I have also invited you to join the repository as a collaborator so I can assign items to you.
