### ISSUE TITLE
Solution architecture guide - update ASP.NET 5 an EF 7 to their core names

### ISSUE THREAD

**Issue by digitaldrummerj** [HTBox/allReady#1088]
AT [https://github.com/HTBox/allReady/wiki/Solution-architecture](https://github.com/HTBox/allReady/wiki/Solution-architecture) there are a few places that still mention ASP.NET 5,  ASP.NET MVC 6 and Entity Framework 7, these should be renamed to the .NET Core names.

Entity Framework 7 = Entity Framework Core
ASP.NET 5 = ASP.NET Core 1.0
ASP.NET MCVC 6 = ASP.NET Core MVC 1.0

**Comment by Bnewman** [comment]
I would like to volunteer to take this task on. Safe to assume that the download links should be updated as well?

**Comment by digitaldrummerj** [comment]
Looks like this was is fixed and has already been merged.
