### ISSUE TITLE
On the Admin Organization list page, make the organization website URLs clickable

### ISSUE THREAD

**Issue by gmford** [HTBox/allReady#1092]
Open the link in a new tab/window, since you're taking the user away from allReady:
![adminorglisturl](https://cloud.githubusercontent.com/assets/20876231/17464114/4df1be76-5c9c-11e6-83c2-1a33c1ec32e6.png)

Discovered in Version: 1.0.0.0 8a77b3a

**Comment by binaryjanitor** [comment]
@tonysurma Working on this
