### ISSUE TITLE
geocoded requests: filter by status and other items already on screen

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#1100]
sub issue of #1080

**Comment by stevejgordon** [comment]
@tonysurma Do we just need a drop down above the table and map to allow choice of status which then shows only requests in that status. On the Itinerary Details page?

**Comment by tonysurma** [comment]
Yes on itinerary but more importantly also on the screen where you choose requests  to add to an itinerary

**Comment by stevejgordon** [comment]
@tonysurma - I did put a basic filtering facility into the select requests screen.

![image](https://cloud.githubusercontent.com/assets/3669103/19725178/0a285118-9b7c-11e6-81bb-d58c97aef38e.png)

It's a single field which will search across zip, address, name etc and return any matches. Do you envision the need to extend this to support fields for each item so a user can do a multi-field type filter?

Is that the requirement here for v1.0?

**Comment by tonysurma** [comment]
What you show covers the need @stevejgordon

**Comment by stevejgordon** [comment]
@tonysurma Great. All that's required then is to add this onto the itinerary details screen i think. I should be able to work on this one along with the other requirement. But let's leave it up for grabs for now as it might be something someone else can copy over.

**Comment by dchristensen** [comment]
I can pick this one up.

Just to clarify we are adding filtering, similar to the "SelectRequests" page to the Itinerary details page, is that correct?

**Comment by stevejgordon** [comment]
@dchristensen - Yep that's the requirement as I understand it right now. I think it's a less crucial feature on the Itinerary Details page, so we may be able to style it a little more subtly! Thanks for volunteering to pick this up, let me know if you have any issues/questions.
