### ISSUE TITLE
geocoded requests: tools for visual selection (lasso, click individual)

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#1101]
sub issue of #1080

**Comment by stevejgordon** [comment]
@tonysurma I presume this one is more related to selecting items from the Select Requests side? i.e. when displaying a list of all requests not yet assigned to an itinerary the map should show all items and allow them to be selected and then added to the current itinerary.

I can see some events we can hook into to allow map pin selection. With a bit of work I think I might be able to tie that into selecting/unselecting the requests in the table (bit of knockout needed). I have no idea if lasso is possible in bing but I thought starting with single select would be a good start.

**Comment by tonysurma** [comment]
@stevejgordon that is right

**Comment by stevejgordon** [comment]
Cool, I'll need to look at implementing some Knockout here to allow the data to be selected from the map events. I'm not 100% sure yet if I can store some kind of ID with the pin so that we can link the click back to selecting a request though. Needs a bit of investigation still.

**Comment by dchristensen** [comment]
@stevejgordon if you haven't had a chance to start on this one I can take a look at it.

**Comment by stevejgordon** [comment]
@dchristensen - Yes please go ahead, I've not had chance to get into this one yet.

**Comment by tonysurma** [comment]
closing this as we have open issues/PRs for sub items
