### ISSUE TITLE
geocoded requests: order the list of selected items as optimized route (given start address)

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#1102]
sub issue of #1080

**Comment by stevejgordon** [comment]
@tonysurma I had a quick look at this the other day and can't see an obvious way to do this with the Bing API. We can add waypoints to create a route, but it does so in the order you specify.

I'd looked at Bing since the maps we're using are from Bing. However we do use GeoCoding from Google for the request imports.

The Google API seems to allow for optimized routes of waypoints (exactly what we need) so I'd propose we use that to generate the routes. However I wanted to check before we do that since we might need to purchase a key. There is a limit on the free one of up to 8 waypoints.

cc/ @MisterJames

**Comment by tonysurma** [comment]
Thx, let's do the first 8 to see how it works without a key and we can look at cost later.  8 may actually be enough for the majority of use cases

**Comment by stevejgordon** [comment]
@tonysurma This is what I'm planning to do. Any feedback, please let me know...

**Optimise Route Feature**

On then Itinerary details page add a hyperlink to "optimise route". Click this will show a popup with fields required to calculate the optimal route (if more than 8 requests this should be greyed out and unavailable).

Clicking the popup opens a UI containing:
- Start Address 
- End Address (tick box to use same as start). If ticked then we hide the end address textbox
- Option to include unconfirmed requests? - Or what should we do with them.

On submit we'll query the Google directions API for optimal route from Start to End via the waypoints.
We'll map the response to an object so we can then arrange the requests into the optimised order.

**Display Driving Route Feature**

If possible we'll just include the route on the current map. If not easy to integrate with the map that is there then perhaps this will also be a hyperlink which opens the bing maps page with the waypoints populated. Or it could open a page on allReady which customises the display of this info.

**Comment by tonysurma** [comment]
@stevejgordon looks good, @OhMcGoo any thoughts?

As for unconfirmed, I would say that any requests added to the itinerary get included.  If they included unconfirmed use them, if not don't so to speak.  This way you don't filter/add more logic, just go with what is in itinerary and follow user's choices.  Does that work?

**Comment by stevejgordon** [comment]
@tonysurma Yep, that's fine. We can always enhance later if we need to. I will try to get to this ASAP.

**Comment by stevejgordon** [comment]
@tonysurma This is coming along and I hope nearly there. I will have a bit of refactoring and testing to include before I submit.

One further question. Would we want to store the from/to addresses against the itinerary once a route is provided? This would allow us to include those locations on our map and also make linking off to a directions map easier (i.e. no need to re-enter addresses each time).

My concern would be that I presume we'll use a volunteer's address as the start/end to plot the route for them specifically. I presume therefore saving this data which any org admin / site admin could see might need some consideration.

For this initial version I'm assuming we don't store it and we can review as enhancements for the future, but please let me know if this is not a good assumption.

**Comment by tonysurma** [comment]
@stevejgordon for our initial use case the start and stop spot will almost always be a common meeting place and or building location for the non-profit so we would be good.

I agree about the privacy concerns but in the case of this screen the 'user' of it will be the org admin anyways so whatever they enter they will already be privy to.

So, I think we are good to either store it or not for this version - your choice - and for future we will move to storing it and then later as use cases change possibly need to look at privacy level changes.

Thanks

**Comment by stevejgordon** [comment]
Thanks @tonysurma. I've got it mostly working without storing but the UX feels a bit off so I'll probably take the time to move things around and allow an itinerary to carry the start/end address details. It may add a little time to finishing this item, but in the long run it'll be better for it.

**Comment by tonysurma** [comment]
Great or if you want to put it in now and make a follow on issue to optimize the UI UX that would work too

**Comment by stevejgordon** [comment]
After a bit a of a break I'm back on this.
