### ISSUE TITLE
Views\Organizations\Index.cshmtl - missing references js/organizations.js

### ISSUE THREAD

**Issue by DanKline** [HTBox/allReady#1106]
Line 62 in index.cshtml references missing JavaScript File

 <script type="text/javascript" src="~/js/organizations.js"></script>

**Comment by bmaluijb** [comment]
I think this one is not relevant anymore and can be closed:

![organizations](https://cloud.githubusercontent.com/assets/16527331/19563306/c265c5f4-96df-11e6-8728-7209fb764406.jpg)

**Comment by bmaluijb** [comment]
@tonysurma I think this one can be closed
