### ISSUE TITLE
On the Admin Event Edit page, the Start/End Date fields are empty

### ISSUE THREAD

**Issue by gmford** [HTBox/allReady#1107]
When I view an existing event on the Admin Campaign Details page, the Start and End dates/times appear:
![admineventtimesdisplay](https://cloud.githubusercontent.com/assets/20876231/17464969/1b9672e6-5cb0-11e6-9193-c5242ac7bf30.png)

But when I edit that event, the Start Date and End Date fields are empty:
![admineventtimesmissing](https://cloud.githubusercontent.com/assets/20876231/17464970/24d705d2-5cb0-11e6-8de8-b7562c8233bf.png)

Discovered in Version: 1.0.0.0 8a77b3a

**Comment by binaryjanitor** [comment]
@tonysurma Working on this

**Comment by mgmccarthy** [comment]
@binaryjanitor @gmford 

are the start/end date fields using the
`<input asp-for="[MODEL_PROPERTY]" class="form-control datetimepicker" />`?

If so, check out Issue #1124. This might be the same problem if both UI's are using the datetimpicker

**Comment by VishalMadhvani** [comment]
This issue appear everywhere we use .datetimepicker and .datepicker.

**Comment by DanKline** [comment]
I just tested this and it appears to be fixed.  Can someone else verify this and make a request to close this issue?

**Comment by tonysurma** [comment]
will add 'needs verification' tag later

**Comment by DanKline** [comment]
OK Thanks.  That observation was on my Windows 8.00 Desktop … I.E. 11.

 

Dan

**Comment by mgmccarthy** [comment]
this Issue was fixed when PR #1025 was merged. It can be closed.
