### ISSUE TITLE
[question] Should Apache Cordova dependency be updated to 5.4.1?

### ISSUE THREAD

**Issue by Bnewman** [HTBox/allReady#1125]
When I forked the repo a few weeks back and was working through the prerequisites I found that to get the mobile project to build I had to modify taco.json and package.json to change the cordova version to 5.4.1 to match what I had installed on my machine.

This may have been a by-product of a peculiar upgrade path on my part, or the prerequisite guide being slightly out of date with what was available at the time.  In any case, should the Cordova dependency in the project should be updated to match what will generally be available when new developers start working on it?

Thanks

**Comment by tonysurma** [comment]
Hello @Bnewman @digitaldrummerj is working on upgrading the project as part of another issue/pull request right now so I think that will address that, do you agree @digitaldrummerj ?

**Comment by digitaldrummerj** [comment]
@tonysurma  @Bnewman correct, I am working on this.

**Comment by tonysurma** [comment]
closing it out as the answer is yes.  thanks @Bnewman and @digitaldrummerj
