### ISSUE TITLE
Create Task allows Negative Volunteers

### ISSUE THREAD

**Issue by DanKline** [HTBox/allReady#1132]
On the Admin Create Task screen, the component allows negatives to be entered for Volunteers Required
![image](https://cloud.githubusercontent.com/assets/3081226/17644453/ac4eabbe-614c-11e6-8f67-f165e4669211.png)

**Comment by rayhiker** [comment]
Was unable to reproduce this bug.

**Comment by rayhiker** [comment]
Fix submitted in Pull Request #1181

**Comment by DanKline** [comment]
I just tested this in both Edge and Chrome.  **Edge** doesn't display the scroll gliphs, **but the up and down arrows allow negatives**.  Chrome now correctly forbids negatives.
