### ISSUE TITLE
Review how dropdown data is handled

### ISSUE THREAD

**Issue by dpaquette** [HTBox/allReady#115]
Not urgent but I would like to review the pattern we are using for handling dropdown data. I like the idea of using Services for this as it would greatly simplify our controllers.

Reference:
http://jameschambers.com/2015/06/rethinking-our-practices-with-the-mvc-framework/
http://blog.simontimms.com/2015/06/09/getting-lookup-data-into-you-view/

**Comment by joelhulen** [comment]
Wow, I did not realize that you can now inject services directly into views in MVC 6! I read through James' and Simon's posts, and it makes a lot of sense to me to do it this way. As you observed, it takes away the responsibility of handling lists away from the controllers, where they're irrelevant, and allows the views to call that data, in a way that still prevents from directly calling into the database. Also, it's a new feature that we can use as an opportunity to show others how it can be implemented.

**Comment by bluechrometouch** [comment]
The one small drawback I can think of is that you wouldn't need a service to retrieve static data like states. One can simply switch to using a public static list. This would still be close to the same thing as the above.

**Comment by dpaquette** [comment]
We have introduced this in the Admin controllers.
