### ISSUE TITLE
Introduce IDateTimeOffsetProvider to abstract the conversion of date time offsets.

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1153]
@tonysurma pleas assign to me.

I am currently working on this.

As part of an ongoing effort to make working with DateTimeOffset's easier, I've introduced a new abstraction, IDateTimeOffsetProvider.

This provider will be injected into code that needs to reach out to DateTimeOffset and supply it a TimeZoneId along with a DateTimeOffset (usually from a ViewModel) to convert to the correct value based on TimeZoneId.

**Comment by stevejgordon** [comment]
Closing after work by @mgmccarthy in #1154 - Any further work to be discussed and addressed by future issues.
