### ISSUE TITLE
Decide on a pattern/approach for Javascript files

### ISSUE THREAD

**Issue by dpaquette** [HTBox/allReady#116]
We are using knockout for some of our views which means we will likely have a fair bit of javascript in this project. Longer term this will be easier to maintain if we use a consistent approach in terms of the structure and location of our javascript. 

Personally, I like the approach outlined in this post (http://blogs.msdn.com/b/cdndevs/archive/2015/06/09/evolving-asp-net-apps-javascript.aspx). The namespacing and javascript file per view would be the most relevant to our project. 

We should also consider using TypeScript because...well...why wouldn't we.

**Comment by joelhulen** [comment]
I agree with the approach outlined in that post. I've taken that approach as well as a dot-naming convention (views.home.index.js) along with namespacing. I think the method in that post is easier to keep track of which js files coincide with which view via a mirrored tree structure.

**Comment by SteveStrong** [comment]
I am cool with any mvvm JavaScript client approach.  so the . naming convention is cool with me.   I would also be interested in using TypeScript, it would give me a real application to try it on.  However I find it odd that this application projects all the client side data into the page as it renders, and then has knockout filter what is shown.   Are we doing this to simplify our web API surface?  normally I would be creating a client side service to pull this data from the server, and make the  service call part of the knock view model.   projecting the data in the page is quicker, but encapsulating the call in the view model may turn out to me more understandable.

**Comment by mheggeseth** [comment]
@SteveStrong There's no good reason for dumping the JSON in the page to do KO things with it other than it was fast and easy to implement (no extra AJAX request, no separate ApiController, Model already had the data, etc). I, too, would prefer the view (at least the index views) to be more or less plain HTML and then pull their data in by AJAX. That would also make scalability easier.

**Comment by dpaquette** [comment]
Dumping the JSON to the page isn't that uncommon, especially when we are doing a mix of server side and client side rendering. For now I would say leave that as is and tackle it later / separately.

**Comment by BillWagner** [comment]
Closing this, as we've set our patterns for JavaScript. Opened Issue #284 to discuss migrating to TypeScript
