### ISSUE TITLE
Can I do some UI labeling changes to help me understand the PR workflow

### ISSUE THREAD

**Issue by SteveStrong** [HTBox/allReady#117]
Hey Guys,  after reviewing the code base/application for a few days, I find things to be a little confusing to a new user.  Software that maps the business model you have in your head, to screens and labels is easy to use.

At first glance I was confused with the name Tenants and the button Show Old.
![tenants](https://cloud.githubusercontent.com/assets/500861/10809935/0603b370-7dd2-11e5-9db7-f0b1804a038f.PNG)

I would like to create a simple branch to do some name changes in the UI.  making this simple contributions will help me verify that I understand the workflow and could make larger contributions in the future.

The tenants page looks like it is where organizations go to find their campaigns.  I would suggest changing Tenant to Organization. and removing the word  organization from other places on the page.

I would also change Show Old, to something like Show Completed Campaigns, and label older campaigns in the list view as such.  Finally I would only introduce the search box if we cannot put all the campaigns on the page.

Is it OK if I create a branch to do this work?

**Comment by SteveStrong** [comment]
I also see the words 'Campaign Organizer' referring to the Tenants,  Organization and Organizer would make things consistant

**Comment by dpaquette** [comment]
Go for it!

I believe that Tenant should be Organization and Tenant Admin should be Organization Admin. @tonysurma and/or @BillWagner can confirm.

**Comment by tonysurma** [comment]
Yep .  If for admin if it is the admin in the scope of an org then it is org admin.  If it is the global scope - meaning admin across all orgs then something like already admin would be good.  Tenant should be stricken from the books :)

**Comment by ksk100** [comment]
Hi @SteveStrong, there is also a use of 'tenants' in a code block at the top of `Index.cshtml` in `Areas\Admin\Views\Tenant` :)
