### ISSUE TITLE
Date validation in non-US cultures

### ISSUE THREAD

**Issue by ksk100** [HTBox/allReady#119]
Hi everyone,

I'm new to the project; I've enjoyed investigating the source so far, and I hope I'll be able to contribute something useful.

I recently came across an issue with the date pickers on the website: the server side validation occurs according to the culture that the web server runs in.

However, the jQuery UI date picker used across the site is currently hard coded to use US date format (in `Views/Shared/_Layout`).

This means that when server is run in cultures with different date format, like the UK (where I am), the server side validation fails (the default date format here being `DD/MM/YYYY`).

Perhaps the most straightforward way to address this, at least for the time being, is to force the server to run with culture set to `en-US`.  That would make the site operational for those of us not in the US with just a few lines of code in `Startup.cs`.

Does that sound like a sensible way forward?

Thanks

Simon

**Comment by dpaquette** [comment]
In general, we need to review how we handle dates in the app. 

Date formatting is part of it although I think we are likely limited to the US for this first version.

I don't think we are using the jQuery UI date picker. I think we are using a bootstrap date picker.

 Timezones is a bigger issue I think. I recommend some variation of the approach outlined here: https://weblog.west-wind.com/posts/2015/Feb/10/Back-to-Basics-UTC-and-TimeZones-in-NET-Web-Apps

**Comment by ksk100** [comment]
Thanks for the Strahl reference, that was a useful read.  And yep, my mistake on which datepicker is being used.

The issue isn't so much date formatting, though, or even date storage.  At least as far as I can gather, the problem is that if the server is run in a non-US context then it's not possible to submit dates to the site which have a day-in-the-month value greater than 12.  E.g. if I use the date selector to pick October 29, it's formatted and sent to server as 10/29/2015, which is then rejected as an invalid date server side because ASP.NET running on my machine with a culture of en-GB thinks that date is invalid.

I think that issue is independent of how the dates are stored or subsequently re-displayed to the user.

**Comment by dpaquette** [comment]
Ah so this is getting into the globalization side of things. That's a tough one, especially since those features of MVC 6 are not well documented yet.

@tonysurma @BillWagner Are we targeting non-US cultures for this November MVP?

**Comment by ksk100** [comment]
Yes, partly at least.

But note that as it stands the application has inconsistent behaviour: parts of the app derive the culture from the execution environment, run in that culture and so then behave (e.g. with respect to the handling of dates) accordingly.  Other parts have US date format hard-coded.

If the decision is made to be US-only, this inconsistency should be ironed out so that at least the app can be run successfully in US-only mode on non-US machines.

**Comment by tonysurma** [comment]
Target is us only

**Comment by ksk100** [comment]
Okay.  Is it alright to go ahead and push the change needed to ensure US culture server side?

**Comment by tonysurma** [comment]
from my perspective yes, but I would defer to @dpaquette for the call

**Comment by dpaquette** [comment]
Yeah that sounds safe. I assume you will just force the Culture to US for now?

**Comment by ksk100** [comment]
Yes
