### ISSUE TITLE
Add setup details to prerequisites documentation section

### ISSUE THREAD

**Issue by bluechrometouch** [HTBox/allReady#121]
It took me a couple of hours to set up the web app due to a missing instruction on updating the dnx to 1.0.0-beta8 after installing WebToolsExtensionsVS14.

Without it, it was showing reference errors to the new changes from Context to HttpContext and SignOut() to await SignOutAsAsync().

The following commands need to be run in package manager console to update dnx:
1. dnx use 1.0.0-beta8
2. dnu restore

**Comment by dpaquette** [comment]
I'm not sure I see a lot of value in us re-documenting the process for setting up aspnet5.  Perhaps a link to the asp.net docs for those who don't know where to find them.

https://docs.asp.net/en/latest/getting-started/installing-on-windows.html

**Comment by bluechrometouch** [comment]
Adding the two package console command above should be enough. The instructions were very straight forward besides this.

The above link could also suffice for the upgrading to Beta8 of the documentation as it has all the details.

**Comment by bluechrometouch** [comment]
Closing as suggestion received too few feedback.
