### ISSUE TITLE
Duplicate Notifications (Signup, Un-enroll, Status Change)

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1216]
When debugging the code to evaluate work on a prior issue I noticed that the IAsyncNotificationHandlers for things such as NotifyVolunteerForTaskSignup and NotifyAdminForSignup seem to get triggered twice on each occurrence of a notification.

I can't see any obvious reason for this but suspect possibly the issue stems with the service registration / dependency resolution.

The result of this issue would be duplicated emails being sent for task notifications.

**Comment by stevejgordon** [comment]
@mgmccarthy Best way to replicate is to make sure you have an event with a task both with current date ranges. Put some breakpoints on the handlers for task signup volunteer notification and admin notification and debug in. You should see that both breakpoints are hit twice, despite a single notification being sent from the task signup handler. I messed around a bit last night taking out the ASP.NET core DI registration for Mediatr and directly registering via autofac but it made no difference. Didn't get much further than that.

**Comment by mgmccarthy** [comment]
@stevejgordon, my dev machine is down and out for the rest of the elongated weekend. The soonest I'll be able to do anything will be on Tuesday, and thats' assuming my machine can be fixed by the same Help Desk that ended up making it not even able to boot to windows anymore 😠 

Long story short, could be awhile until I can get eyes on this.

**Comment by mgmccarthy** [comment]
@tonysurma, if no one else claims this, when I get a working machine back on Tuesday, I'd be happy to look into this, especially since @stevejgordon did all the hard work of removing the concept of volunteering for Events from the system.

**Comment by tonysurma** [comment]
Neither rain, nor sleet or failing SSDs can stop @mgmccarthy 😸 
it's all yours

**Comment by mgmccarthy** [comment]
Well the SSD can ;) we'll see how I fair when visit the "Helpless Desk" this Tuesday. Hoping for the best.

**Comment by mgmccarthy** [comment]
@stevejgordon, is this still an issue?

**Comment by stevejgordon** [comment]
I haven't check the latest code but I would expect so. Meant to take a look this weekend but got side-tracked.

Sent from my Windows Phone
________________________________

**Comment by mgmccarthy** [comment]
@stevejgordon, I just replicated this on my system. Like you said, each handler is being called twice when it should only be called once. I'm investigating now.

**Comment by mgmccarthy** [comment]
@stevejgordon, I think I found the problem, and it looks like it might be related to the library Jimmy Bogard wrote to register MediatR in the StartUp.cs class.

- https://lostechies.com/jimmybogard/2016/07/19/mediatr-extensions-for-microsoft-dependency-injection-released/
- https://www.nuget.org/packages/MediatR.Extensions.Microsoft.DependencyInjection

basically, we're registering MediatR using this library like this in startup:
```
//register MediatR
//https://lostechies.com/jimmybogard/2016/07/19/mediatr-extensions-for-microsoft-dependency-injection-released/
services.AddMediatR(typeof(Startup));
```

when I took that code out and went back to the old way of registering MediatR:
```
var containerBuilder = new ContainerBuilder();
containerBuilder.RegisterAssemblyTypes(typeof(IMediator).Assembly).AsImplementedInterfaces();
containerBuilder.Register<SingleInstanceFactory>(ctx =>
{
    var c = ctx.Resolve<IComponentContext>();
    return t => c.Resolve(t);
});

containerBuilder.Register<MultiInstanceFactory>(ctx =>
{
    var c = ctx.Resolve<IComponentContext>();
    return t => (IEnumerable<object>)c.Resolve(typeof(IEnumerable<>).MakeGenericType(t));
});
```
the duplicate handling of `VolunteerSignupNotification` in both `NotifyVolunteerForTaskSignup` and  `NotifyAdminForSignup` stopped. I'm going to check in the older version of the MediatR handler code in StartUp as a fix for this Issue.

In the meantime, I'll see if I can open an Issue with MediatR about this new registration package causing handling of a notification in the same handler twice.
