### ISSUE TITLE
NullReferenceException thrown on invalid model state on Admin/Activity/Edit

### ISSUE THREAD

**Issue by ksk100** [HTBox/allReady#122]
If you post with bad data to the Admin/Activity/Edit page a `NullReferenceException` is thrown.

Here is what I think is happening:

On submission of an edit, the `Activity` object is populated by the ModelBinder and not read from the DB.  As a result it's `Campaign` property is not filled in.  

On success, `ActivityAdminController.Edit` redirects to admin's list of activities, so this doesn't matter.

But on failure - when, e.g., the user just enters no date at all - the edit view is redisplayed; this view displays `Campaign.Name` and as `activity.Campaign` is null the exception is thrown.

**Comment by ksk100** [comment]
Oh, and I'm happy to take this on if people think my assessment above sounds accurate enough.

**Comment by dpaquette** [comment]
Correct, the Campaign property should be repopulated when the model state is invalid. The Create method does this properly but the Edit method does not. Feel free to submit a PR.

**Comment by ksk100** [comment]
I just pushed this, for the interim fix.  It's attached itself to the already open PR, as I didn't use a separate branch - sorry about that.

**Comment by ksk100** [comment]
For review: https://github.com/ksk100/allReady/commit/a878fb139c0dfba2be9d82797b64b4281141ca5b

**Comment by mheggeseth** [comment]
@ksk100 Can you add "Closes #120 and closes #122" as a comment to PR #123 . That will ensure these issues are autoclosed when the PR is merged.

**Comment by ksk100** [comment]
Of course

**Comment by dpaquette** [comment]
this can be closed
