### ISSUE TITLE
Edit Task Start and End times are incorrect

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1224]
As per #1223 but for tasks

**Comment by tonysurma** [comment]
@dpaquette this fixed too?

**Comment by dpaquette** [comment]
Yeah it will be fixed for all date time inputs. It apparently isn't fixed yet but will be. Can you assign to me?

**Comment by dpaquette** [comment]
Can this be assigned to me? This is related to the javascript datetime formatting issue I mentioned in the standup today.
