### ISSUE TITLE
Dnx 1.0.0-preview2-003121 no longer available in dnvm

### ISSUE THREAD

**Issue by achasik** [HTBox/allReady#1228]
Run: dnvm install 1.0.0-preview2-003121
and get The server returned a 404 (NotFound)

**Comment by stevejgordon** [comment]
@achasik Can you provide a little more information to replicate the issue please? DNVM was retired in RTM of ASP.NET core and replaced with the dotnet CLI

**Comment by achasik** [comment]
I fork and clone repo and open AllReadyWebOnly.sln
Got a message "The project is configured to use SDK 1.0.0-preview2-003121 wich is not installed or cannot be found' I follow the link to download SDK and not found such version
Made some googles and tryed install via dnvm

**Comment by stevejgordon** [comment]
@achasik Ah I see. You will need the .NET core tooling to be able to develop this project. This sounds like the SDK tooling is not installed on your machine. Are you on Windows using VS 2015? If so you need VS 2015 update 3 installed.

You then need to install the SDK (preview 2) from https://www.microsoft.com/net/core#windows

Please do let me know if that makes sense or if you have any questions.

**Comment by achasik** [comment]
Thank you!
Install of SDK preview 2 fix problem

**Comment by stevejgordon** [comment]
@achasik you're very welcome.
