### ISSUE TITLE
Getting Externally Generated Requests into allReady

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#1241]
allReady should be able to accept service request data in two ways:
1. Internally, from a form built for a campaign within the application; **(out of scope for v1)**
2. Externally, via an API that captures the request data from an organization's own website. In many cases, allReady will be required to send information (like a fulfillment confirmation) back to the external website. **(in scope for v1)**

Additionally, there should be a public-facing campaigns page (similar to: https://publicgood.com/discover/homeless-shelters-2) that displays buttons or tiles that open campaign request forms in a new browser tab (regardless of whether the campaign page is internal or external to allReady)

_updated from Jim's additions_

**Comment by OhMcGoo** [comment]
allReady should be able to accept service request data in two ways:

1. Internally, from a form built for a campaign within the application
2. Externally, via an API that captures the request data from an organization's own website. In many cases, allReady will be required to send information (like a fulfillment confirmation) back to the external website.

Additionally, there should be a public-facing campaigns page (similar to: https://publicgood.com/discover/homeless-shelters-2) that displays buttons or tiles that open campaign request forms in a new browser tab (regardless of whether the campaign page is internal or external to allReady)

**Comment by stevejgordon** [comment]
@OhMcGoo - To clarify a little on point 1 here. I've just added some code and pages to allow and org/site admin to create a request under and event via the admin UI. Does this meet the requirement here, or is the intention to also provide an request page that could be (optionally) loaded for unregistered public visitors to allow them to register a request for themselves?

**Comment by OhMcGoo** [comment]
@stevejgordon - I'm filling in details for Tony about four December milestones (https://github.com/HTBox/allReady/milestone/15) so expect more detail as the morning progresses. To answer your question specifically, I think the latter is the case (provide a request page that could be loaded for unregistered public visitors to allow them to register a request for themselves), however, now I think about it, I'm not sure it needs to be in place for December. Any thoughts @tonysurma?

**Comment by tonysurma** [comment]
Thanks @OhMcGoo we are filling in a bunch of stuff between now and the standup so expect some churn but in short Jim is right that is not in scope for December

**Comment by stevejgordon** [comment]
@tonysurma As we have the API in place for external requests and a manual request creation for admins, do you think we should close this issue and open a set of new vNext ones around the public request creation page? If we're short on things for the code-a-thon we can then let people grab some around the final part of this.

**Comment by tonysurma** [comment]
agree
