### ISSUE TITLE
Campaign Details Page has the grid centered making the layout look odd

### ISSUE THREAD

**Issue by digitaldrummerj** [HTBox/allReady#1243]
Not sure if it is intentional of not but the grid on the Campaign details is centered and throws off the whole layout.  My assumption is that it is suppose to be right aligned right under the "Events for this Campaign" heading.

![image](https://cloud.githubusercontent.com/assets/708423/18652222/89b0d82e-7e85-11e6-9553-c877daec2faa.png)

**Comment by stevejgordon** [comment]
Having a quick lunchtime look at this to see what I can do.
