### ISSUE TITLE
NullReferenceException thrown on Index for SiteAdminControllers

### ISSUE THREAD

**Issue by bluechrometouch** [HTBox/allReady#125]
When visiting the Admin/Site page and searching for an invalid email, you will get a null reference error.

The error seems to be located in the Index [Post] method of the SiteAdmin controller.

var user = await _userManager.FindByEmailAsync(model.Email);

One way to fix this is to have a custom validation attribute along the lines of....
https://stackoverflow.com/questions/12552687/get-error-message-when-using-custom-validation-attribute

How do you guys want to handle this?

**Comment by dpaquette** [comment]
I can fix this today

**Comment by dpaquette** [comment]
I think this can be closed
