### ISSUE TITLE
Refactor AssignTaskCommandHandlerAsync

### ISSUE THREAD

**Issue by sanilpaul** [HTBox/allReady#1256]
- The queries needs to be changed to async to make async all the way. 
- The handler to assign task also has the responsibility to send notifications to the Phone Number Confirmed and email confirmed recipients. I propose to move the notification responsibility to its own handler. The AssignTaskCommandHandler will be just reponsible for assigning task to the volunteers and publish an event that new volunteers have signed up. This would make the classes and corresponding tests smaller and simple. 

@tonysurma @mgmccarthy let me know what you guys think. I can work on this.

**Comment by mgmccarthy** [comment]
@sanilpaul  (cc:@tonysurma)

This looks good. 

I like the idea of the separating the concerns to adhere to SRP, but more importantly, moving towards a true CQRS approach, where we publish notifications when things happen in the system. In this case, it's 1 to n users being assigned to a Task.

Right now, only the new handler will handle the notification, but in the future (or potentially now depending on how some of the code works), there might be other areas of the system that are interested in "doing something" when this new notification is published.
