### ISSUE TITLE
Unhandled InvalidOperationException when bad data submitted to Create Activity form

### ISSUE THREAD

**Issue by ksk100** [HTBox/allReady#126]
When creating an activity for some campaign (at `/Admin/Activity/Create/[someCampaignIdHere]`), if the validation checks fail, then an unhandled `InvalidOperationException` is produced.

This is because it can't find the appropriate view, because the create page is now using the edit view, but the action which handles the post doesn't specify this.  Just needs `"Edit"` adding as first parameter when returning the view.

**Comment by dpaquette** [comment]
I can fix this today

**Comment by ksk100** [comment]
Cool.  I noticed another couple of things in that action method too, one of which becomes visible after the "Edit" fix is made: if you submit bad data (e.g. a bad date which fails validation) and also don't create any required skills, then when the create page is reloaded an `ArgumentNullException` is thrown by line 138:

`@Json.Serialize(Model.RequiredSkills.Select(rs => new { Id = rs.SkillId }))`

in `Edit.cshtml`.  That's the line which produces the JSON for KO to populate the skills list.  On first load of the Create page the relevant action method creates an empty list, but when reloading after a failed post, `Model.RequiredSkills` comes from the post and ends up `null` if the user hasn't yet added any skills.

The second thing was that this action method isn't checking either that the campaign actually exists nor that the current user is an authorised manager of the tenant.

**Comment by dpaquette** [comment]
Yeah a lot of these problems are because we are binding directly to the model class. I'm going to clean that up to avoid these types of issues

**Comment by BillWagner** [comment]
Fixed in PR #128
