### ISSUE TITLE
Mediatr Handler Naming (Discussion)

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1262]
I think this is mostly my fault as I think I started the trend! I wanted to open a discussion around naming handlers as we start to think about documenting some of the allReady coding conventions.

Currently most handler classes which implement the IAsyncRequestHandler are named with the suffix Async e.g. EditCampaignCommandHandlerAsync

While async methods should be named in this way (based on some guidance I've seen) I'm not sure it makes much sense to explicitly name the handler class this way In my example EditCampaignCommandHandler would be sufficient. 

I'm wondering what other contributors think about revising these going forward?

cc/ @mgmccarthy @MisterJames @dpaquette

**Comment by mgmccarthy** [comment]
@stevejgordon I agree. Although "convention" says to name anything that is aysnc with the word "Async" in the name of the class, I don't think it makes much sense. It's easy to see that a class is async based on the API of the class, and in the case of MediatR, there are explicit interfaces that are implemented that already have the word "Async" in them.

I'd like to remove all "Async" works from class names... I think it would make everything easier to read. If someone tries to code against an async class and does not use async/await in their consuming code, the compiler will let them know.

**Comment by MisterJames** [comment]
There are all kinds of classes in .NET that have async methods and do not adorn the name with async. I am 100% behind not having it in the name of the class.
