### ISSUE TITLE
Change Skill.ParentSkillId to allow null

### ISSUE THREAD

**Issue by bcbeatty** [HTBox/allReady#127]
With out ParentSkillId being nullable you are unable to add the first record.

**Comment by mheggeseth** [comment]
I'll get this done with #124

**Comment by bcbeatty** [comment]
It's also a part of PR130 https://github.com/HTBox/allReady/pull/130

**Comment by mheggeseth** [comment]
Sounds good. #124 got merged anyway.

**Comment by mheggeseth** [comment]
This can be closed.

**Comment by BillWagner** [comment]
I missed hand closing this. (Note to all: Explicitly marking a PR with "Fixes" and the issue # means it will close on the merge. (I'll keep looking when we forget.)
