### ISSUE TITLE
Create a Git usage guide

### ISSUE THREAD

**Issue by digitaldrummerj** [HTBox/allReady#1273]
As I have run or participated in Hackathons for allReady, one of the consistent issues that I have run into is people not understanding how to use Git.    Many times we have had participants that it is their first time using Git or Github.  It would be nice to have a guide that walks them through the Git process for forking, cloning, commiting, pushing, submitting PR, and syncing fork with HTBox/allReady.  

Just a basic guide that walks them through what they need to know to be a successful contributor.

**Comment by digitaldrummerj** [comment]
I can take this one

**Comment by tonysurma** [comment]
For reference:
https://www.stevejgordon.co.uk/contributing-to-allready
http://www.davepaquette.com/archive/2016/01/24/Submitting-Your-First-Pull-request.aspx

have been our most successful guides to date

Thanks for jumping on this

**Comment by digitaldrummerj** [comment]
thank you for the additional links.  I will take a look at them.

**Comment by stevejgordon** [comment]
I have a draft blog post covering some Git related tips and tricks / GitHub etiquette (Gitiquette) as well which I will eventually be publishing!

**Comment by mgmccarthy** [comment]
Along with @stevejgordon's upcoming "Gititquette" blog post, this is a great link to how write a well formatted git commit message: http://chris.beams.io/posts/git-commit/.
