### ISSUE TITLE
Create install guide for required software

### ISSUE THREAD

**Issue by digitaldrummerj** [HTBox/allReady#1274]
As I have run or participated in hackathons for allReady I have gotten a bunch of questions on exact install steps for all of the required software.  Right now there is not a walk through guide and only a listing of software to install.  A lot of times participants have not used node, npm, bower, ionic, etc so they are not sure how to get them installed.  A walk through guide would make it quicker for them to get everything installed and would ensure that everyone has the same setup.

**Comment by digitaldrummerj** [comment]
I can take this one

**Comment by digitaldrummerj** [comment]
I can take this one

**Comment by tonysurma** [comment]
This would be SUPER helpful given we have 5+ events between now and end of calendar year.  Thanks!

**Comment by digitaldrummerj** [comment]
@tonysurma my goal is to get this written and submitted by next Wednesday.
