### ISSUE TITLE
Areas don't publish on build

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#1294]
This leaves all the admin pages out of date adn requires manual deployment by someone (me) which is 😿 

The fix is basically putting this commit in our project.json (looks like things were buggy early on and since we didn't start with a new project form a template we didn't get this fix.

https://github.com/aspnet/Templates/commit/9c755dea1746341d3c8fc752c479c1b26610a69f

**Comment by stevejgordon** [comment]
I can grab this in 20 mins or so.
