### ISSUE TITLE
Broken Build: Migrations don't get executed on startup in azure build

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#1298]
Something in this if clause (either check for Staging fails which is my guess) doesn't allow migrations to run in staging deployment in azure.  I think that the definition for that may have changed since early builds and might be looking at a different environment variable that what we are currently setting ("ASPNETCORE_ENVIRONMENT").

If clause https://github.com/HTBox/allReady/blob/master/AllReadyApp/Web-App/AllReady/Startup.cs#L328

**Comment by stevejgordon** [comment]
@tonysurma If we require this in all environments except production it might be better to use:

```
if (!env.IsProduction())
{
	context.Database.Migrate();
}
```

That way it'll run in all environments exception production. For the live site either setting ASPNETCORE_ENVIRONMENT to Production or leaving the environment variable blank should result in this code being skipped.

Do you want to try that and see how it goes?

**Comment by tonysurma** [comment]
@stevejgordon makes sense let's do it.

@mgmccarthy this is the staging note I was referring to

**Comment by tonysurma** [comment]
I feel like I recall that that's no longer the environment variable that is asp.net is checking but may be a bad memory

**Comment by tonysurma** [comment]
That is the right/new environment variable https://jessedotnet.com/2016/05/05/asp-net-core-1-0-asp-net-5-environment-variables/
