### ISSUE TITLE
Need to enrich Admin username and password handling

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#13]
At the moment the username and password for the global admin is primarily via config.json.

This needs to be enriched to store it elsewhere securely, have a means to add other admins, change password etc.

**Comment by shawnwildermuth** [comment]
I'll take this if someone would assign it.

**Comment by BillWagner** [comment]
@shawnwildermuth Are you still working on it?

**Comment by shawnwildermuth** [comment]
I am now. Didn't realized I signed up for it. With the Summit and all. I'll dig in tonight.

**Comment by shawnwildermuth** [comment]
Is this about site admin only or also tenant admit? I am looking at the way we're creating the initial site admin and wanting to do it on first launch but disabling that account once you create the first non-default site admin. Just trying to understand the real requirement here. Can we sit down on Saturday and get this hammered out so I understand what the need is. (e.g. I know we want to secure the admins and get them out of the config).

**Comment by tonysurma** [comment]
Per our conversations with @shawnwildermuth he is on this and we have a strategy and a plan in progres
