### ISSUE TITLE
Admin Create Event unable to select Name field at lower widths

### ISSUE THREAD

**Issue by digitaldrummerj** [HTBox/allReady#1301]
On the admin "Create Event" for a Campaign page anytime that the browser was 960px or lower in width I was unable to click into the Name field.   I can click on the description field and shift+tab to get into the Name field but I can not click on it with the mouse.

**Comment by wadewachs** [comment]
Ran into several odd interactions with this field in the Test Lab. Here is a video demonstrating some of those behaviors:

https://goo.gl/kdF4Pl

**Comment by TomWalkerCodes** [comment]
I could not reproduce this issue in Edge, Chrome or FireFox.  I tried resizing the browser window and also tested going to the create event page at a lower screen size.

**Comment by tonysurma** [comment]
Thanks @TomWalkerCodes we will consider this fixed then

**Comment by digitaldrummerj** [comment]
I can confirm that I can't replicate it anymore either.
