### ISSUE TITLE
Server Error > Campaigns does not handle exception when user isn't logged in and open an event

### ISSUE THREAD

**Issue by romanrod** [HTBox/allReady#1302]
When a guest user (not logged in) goes to a any campaign and try to open an event an unhandled exception shows up [Server Error]

Steps

Goto campaigns
Open any listed campaign
Select any event

Stacktrace:

The page cannot be displayed because an internal server error has occurred.
An unhandled exception occurred while processing the request.

NullReferenceException: Object reference not set to an instance of an object.
MoveNext in EventController.cs, line 54

Stack Query Cookies Headers
NullReferenceException: Object reference not set to an instance of an object.
MoveNext in EventController.cs
            var viewModel = await _mediator.SendAsync(new ShowEventQuery { EventId = id, UserId = user.Id });
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
ValidateEnd
MoveNext
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
MoveNext
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
MoveNext
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
MoveNext
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
MoveNext
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
GetResult
MoveNext in TokenProtectedResource.cs
            await _next(httpContext);
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
MoveNext
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
MoveNext
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
MoveNext
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
MoveNext
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
MoveNext
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
MoveNext

Show raw exception details

**Comment by stevejgordon** [comment]
Was fixed by #1327
