### ISSUE TITLE
Unhandled exception logging in with Twitter

### ISSUE THREAD

**Issue by SPConlin** [HTBox/allReady#1304]
Selecting the Twitter login option will result in an unhandled exception after logging into Twitter and authorizing the app. The error is shown below.
# 

The page cannot be displayed because an internal server error has occurred.
An unhandled exception occurred while processing the request.

InvalidOperationException: SingleUserAuthorizer needs pre-set credentials; don't call Authorize unless you've set all four credentials.
MoveNext

Stack Query Cookies Headers
InvalidOperationException: SingleUserAuthorizer needs pre-set credentials; don't call Authorize unless you've set all four credentials.
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
GetResult
MoveNext in TwitterRepository.cs
            await authTwitter.AuthorizeAsync();
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
GetResult
MoveNext in TwitterExternalUserInformationProvider.cs
            var twitterAccount = await twitterRepository.GetTwitterAccount(userId, screenName);
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
GetResult
MoveNext in AccountController.cs
            var externalUserInformation = await externalUserInformationProvider.GetExternalUserInformation(externalLoginInfo);
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
ValidateEnd
MoveNext
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
MoveNext
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
MoveNext
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
MoveNext
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
MoveNext
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
GetResult
MoveNext in TokenProtectedResource.cs
            await _next(httpContext);
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
MoveNext
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
MoveNext
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
MoveNext
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
MoveNext
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
MoveNext
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
MoveNext

Show raw exception details

**Comment by mgmccarthy** [comment]
@stevejgordon this is probably related to the code I did for the Twitter external login provider. The other odd thing is, based on the environment (`IsDevelopment` vs. `IsStaging`) that is being set in Startup, we should not be seeing the Developer exception page, but rather, the "generic" error page located at "/Home/Error".

For the testing of allReady, do you know what environment we're specificying? Based on people seeing the specific error details, my assumption is `env.IsStaging()` is true.

**Comment by stevejgordon** [comment]
@mgmccarthy The application starts by default using Development. This is set in the launchsettings. If you go to the project properties (Debug) you should see that the ASPNETCORE_ENVIRONMENT variable being set to Development. This will take affect if launching from VS.

The code in startup is:

```
if (env.IsDevelopment())
{
	app.UseBrowserLink();
	app.UseDeveloperExceptionPage();
	app.UseDatabaseErrorPage();
}
else if (env.IsStaging())
{
	app.UseDeveloperExceptionPage();
	app.UseDatabaseErrorPage();
}
else
{
	// Add Error handling middleware which catches all application specific errors and
	// sends the request to the following path or controller action.
	app.UseExceptionHandler("/Home/Error");
} 
```

So in Dev/Staging we should get the ASP.NET core dev exception page. In anything else it should be the generic error page. This seems to be the case for me, although the styling is not loading for me. That might just be me - I'll take a look on another machine tomorrow.

**Comment by mgmccarthy** [comment]
@stevejgordon, yeah I was just wondering if the deployed app we have in the cloud that people are testing against is considered `env.IsStaging()`... I'm making the assumption it is.

**Comment by tonysurma** [comment]
Allready-d is staging or should be, although I logged an issue starting there may have been a change to how that is detected

**Comment by mgmccarthy** [comment]
@tonysurma, please assign this to me.

**Comment by mgmccarthy** [comment]
@tonysurma, does the application hooked up to the live site have these four config file values filled out:
```
"Authentication": {
    "Twitter": {
      "ConsumerKey": "[twitterconsumerkey]",
      "ConsumerSecret": "[twitterconsumersecret]",
      "OAuthToken": "[twitteroauthtoken]",
      "OAuthSecret": "[twitteroauthsecret]"
    },
```

?

**Comment by mgmccarthy** [comment]
@tonysurma, regardless of what the Twitter auth settings are or how the twitter account was setup that allReady will be using in the live environment, I have a fix for this exception being thrown.

The fix basically checks the exiting Twitter auth settings to see if any of them are set to the "default" setting, and will allow the code to still run, bypassing the call to LinqToTwitter (which will fail)...

for the check, I am checking for the default settings above "[twitterconsumerkey]", etc... in the live site, what are the values set to right now? Based on this exception, my guess is that some of the settings are blank (null), or are some of the settings using these defaults?

the result is a registration screen with nothing filled out... but:
- we don't get an exception thrown
- the user can still fill in the required fields themselves and continue the registration process
