### ISSUE TITLE
Facebook throws error 

### ISSUE THREAD

**Issue by sandygarcia** [HTBox/allReady#1305]
App Not Setup: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions.

**Comment by mgmccarthy** [comment]
PR #1443 might have fixed this issue, but to be sure, we need to have a test in the live environment.

**Comment by mgmccarthy** [comment]
@sandygarcia can you please include a screegrab(s) and steps you took that shows the error? We need some more detail to help us investigate.

**Comment by stevejgordon** [comment]
Closing this as we have validated the social logins here at NDC and made some small changes to handle some issues we were seeing. In this case it sounds like Facebook dev setup issue?
