### ISSUE TITLE
'Show completed check box' not filtering correctly

### ISSUE THREAD

**Issue by atthetestlab** [HTBox/allReady#1307]
1. Open Chrome browser.
2. Type url https://starwest.atthetestlab.com/
3. Click the link 'Start Testing'
4. Click Test Environment 
5. Click the link Campaigns
6. Select the check box for 'Show Completed testing'

Actual result: The list displaying current events

Expected: The list should not display current events. If there is no completed events at all, then none of the item/events should be displayed at all.

**Comment by stevejgordon** [comment]
@tonysurma I think the intention here is to "include" completed campaigns, rather than only showing completed? Perhaps we just tweak the wording here initially?

**Comment by tonysurma** [comment]
So step 4 sent them to our allready-d site....

I just reviewed and yes I think the wording should be 'Include Completed Campaigns' or similar

**Comment by tonysurma** [comment]
clarification is that this is a wording change to 'Include Completed Campaigns' as the default behavior is to show only campaigns NOT marked complete and checking the box ALSO includes those marked complete.

This is one the default campaigns page from the homepage (not the admin campaigns page)

**Comment by gdereese** [comment]
I'll take this one.
