### ISSUE TITLE
Create Campaign Fields - Feature Enhancement

### ISSUE THREAD

**Issue by jgarbiso** [HTBox/allReady#1310]
Primary Contact 

**Phone Number** 
Actual: 
Allows letters

Expected:
Should only allow numbers in phone number format

External Link
Actual:
Allows all text and numbers

Expected
Should only allow URL

ExampleDomain.com/net/org etc....

**Primary Contact**

Email
Actual: 
Allows all text and numbers

Expected:
Only allows email formatted text

name@domain.com

**Comment by julianharty** [comment]
Improving the formatting also helps make the software more usable on mobile devices as they can display/provide a suitable on-screen keyboard

http://html5doctor.com/html5-forms-input-types/ is one of a plethora of sites that provide useful examples.

**Comment by tonylambert** [comment]
I'll try this one.

**Comment by tonysurma** [comment]
@tonylambert is this what your current PR is for? If so could you update your description on that PR to include "Fixes #1310" and then it will link and auto close?  THanks again!

**Comment by tonylambert** [comment]
@tonysurma - This is what the PR was for, but we ended up, after exploring a bit more, that we are already doing the KISS solution to this. If we want to do something more involved, then I can look around, but ultimately, as long as the validators server-side are firing, then there are probably more important fish to fry when moving to a 1.0 release?

I'll defer to the team's judgement, of course.

**Comment by tonysurma** [comment]
Agree and therefore closing
