### ISSUE TITLE
Production Error: Clicking on either My Profile or Admin > Skills causes infinite loop

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#1318]
Haven't tested it anywhere other than in production but it is 100% reproducible. CPU pegged at 100% after clicking either.

**Comment by dpaquette** [comment]
Quickly tested locally and was not able to reproduce. Possibly related to the data currently in the staging environment.

**Comment by tonysurma** [comment]
@dpaquette I will spin up a seperate db to point to and see if that makes a difference.  Interesting

**Comment by tonysurma** [comment]
pointed prod to a new, clean db and the issue went away so will find a way to capture that other database so we can figure out what the culprit was

**Comment by stevejgordon** [comment]
I've replicated this using a connection string @tonysurma provided. Locally I can see a lot of GC activity in the diagnostics. I've run out of time tonight but I'll continue looking into this issue to narrow down the cause. Looks likely it's loop in our skills data.

**Comment by stevejgordon** [comment]
update - still working on this. Main bug is fixed but working on preventing it re-occuring and testing for it.

**Comment by stevejgordon** [comment]
And still going! Main issue solved and prevented the loops, but in testing skills across the site I'm finding some other bugs I'm digging into as part of this issue. If they become large I'll break them out.
