### ISSUE TITLE
Volunteer button does nothing

### ISSUE THREAD

**Issue by jmcconda** [HTBox/allReady#1319]
![screenshot 2016-10-05 at 11 17 50 am](https://cloud.githubusercontent.com/assets/18353050/19119565/30e95f52-8aee-11e6-9e32-ffcaa2f44320.png)

When I volunteer for task 0 I click on the volunteer button in the test database for smoke detector the button does not respond. The popup screen stays up and does not respond. Screenshot is attached.

I am using a Chromebook at the Test Lab at Star West.

**Comment by mgmccarthy** [comment]
@jmcconda this works when I run the app locally. It might have something to do with the version of the code...

could you include your chrome version and what OS you're on?

**Comment by jmcconda** [comment]
Sorry, this was at the test lab at the Star West conference so I no longer have access to the computer I was using. This was an HP Chromebook though, so it's the Chrome OS. I don't know what version it was running.

**Comment by tonysurma** [comment]
needs verification, there was another item that mentioned this as well
