### ISSUE TITLE
Display URL for link in Confirmation email.

### ISSUE THREAD

**Issue by SPConlin** [HTBox/allReady#1321]
The confirmation email for new accounts currently reads:

Please confirm your allReady account by clicking this link: link

The second "link" is a hyperlink to the confirmation page. I would recommend either displaying the URL after the colon or making the first "link" the hyperlink and ending the sentence there.

In general, making the URL available is preferable since many users have become familiar with copying the url into the browser rather than clicking an obscured link.

**Comment by julianharty** [comment]
I concur, the email is somewhat stark and looks a bit like a spam email (thankfully gmail didn't mark it as such). 
<img width="531" alt="screen shot 2016-10-05 at 19 55 10" src="https://cloud.githubusercontent.com/assets/785891/19127150/b631a29a-8b35-11e6-8601-92eb7c05890a.png">

**Comment by tonysurma** [comment]
need to enhance email presentation for sure, thanks

**Comment by Odia1** [comment]
I am working on it
