### ISSUE TITLE
SMS Verification code does not appear to be sent.

### ISSUE THREAD

**Issue by SPConlin** [HTBox/allReady#1323]
After adding a phone number, the user is expected to confirm the number once they receive an SMS message. After 20 minutes, no message has been received. Selecting resend on the confirmation page does not resend the message. This was tried with two different numbers.

**Comment by julianharty** [comment]
I concur: I used my full international number for my UK mobile - nothing. I have used the 'resend code' link a couple of times so far, still nothing.

**Comment by tonysurma** [comment]
This is an infrastructure issue covered in another item (looking for issue # to reference)
