### ISSUE TITLE
Instagram icon opens Twitter

### ISSUE THREAD

**Issue by SPConlin** [HTBox/allReady#1325]
The instagram icon on the bottom of the user profile page currently opens https://twitter.com/HTbox/media.

**Comment by wadewachs** [comment]
@SPConlin  - - We selected you as a prize winner from the test lab. Either try to find me before you leave the conference, or send me your email address and I will get the prize to you.

Thanks for all of your help at the lab.

**Comment by SPConlin** [comment]
@wadewachs I'm glad I could help. Drop me a note if there is anything else I can do. My email is Spconlin@gmail.com

**Comment by SPConlin** [comment]
@wadewachs Please email me at SPConlin@gmail.com. I have a question about the prize you mentioned above.

**Comment by tonysurma** [comment]
should remove the icon
