### ISSUE TITLE
Volunteer for an event - Comments

### ISSUE THREAD

**Issue by edehaan** [HTBox/allReady#1326]
Browser - Chrome
Registered User - not an admin
Video of issue:  http://screencast.com/t/WLRo8on6ul5f
Testing as part of StarWest TestLab

After clicking on the Nieghborhood Fie Prevention Days link under All Registered Campaigns, 
Then clicking on Queen Anne Fire Prevention Day, then under task 2 clicking Volunteer.
In the popup, in the comments box I entered Adding a comment - starwest.  If I click the Volunteer button in the box nothing happens.

**Comment by mgmccarthy** [comment]
@tonysurma, I just tested this locally using Chrome and I cannot reproduce it. This issue can be closed
