### ISSUE TITLE
Review code for EventController

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1328]
Ensure that the model is populated correctly for both unauthenticated "public" users as well as signed-in users. A quick change to fix #1320 was made in #1327 but this might need enhancement.

I can look into this further.

**Comment by stevejgordon** [comment]
I've checked this over and I think it's okay for now. It's a bit hard to understand the view since a lot is hooked up via knockout but we are now only trying to load user specific data (assigned tasks etc) if a request comes from a valid signed in user.

**Comment by mgmccarthy** [comment]
my two cents, we should only be using knockout (or any other javascript library) when absolutely necessary...not just "to use it". 

It's not compile safe, there appear to be no unit tests around any of our javascript, and the only way to find out if something broke is smoke testing the entire app.

**Comment by stevejgordon** [comment]
@mgmccarthy I think this may end up being reviewed/reworked once we come to doing UX/UI redesign for that section of the site. Design focus is going on the itinerary builder/request management first though.
