### ISSUE TITLE
The Volunteer Button overlaps the date-time label on Tasks.

### ISSUE THREAD

**Issue by calaharie** [HTBox/allReady#1332]
Open the application to the following page as a user:
http://allready-d.azurewebsites.net/Event/12

The orange button covers up date time.

**Comment by julianharty** [comment]
The text is partly obscured when the width reduces. Here's a screenshot of the problem, where October is partly obscured by a button.

<img width="635" alt="screen shot 2016-10-05 at 22 57 48" src="https://cloud.githubusercontent.com/assets/785891/19133264/4b8b0aa2-8b4f-11e6-9d5d-35df48735532.png">
