### ISSUE TITLE
Create Campaign > Copy Contact Info button doesn't work

### ISSUE THREAD

**Issue by wadewachs** [HTBox/allReady#1346]
https://goo.gl/mjCnWV

In Chrome (53.0.2785.143) and Safari on Mac OS 10.10.5 the button to copy contact details while creating a campaign is completely non-functional, as shown in the video above.

I was logged in the an organization admin user (wadewachs@gmail.com) that did not have a verified phone number (the SMS gateway seems to be down). It is possible the unverified phone number is the source of the problem, but I have no way of testing that at this time.

**Comment by mgmccarthy** [comment]
In Chrome (53.0.2785.143 m (64-bit)) on Windows 7 Enterprise I don't see the Copy Contact info button at all on the UI when logged in as admin and creating a campaign.

![image](https://cloud.githubusercontent.com/assets/2428993/19255434/eba309f6-8f2b-11e6-9817-7b64ab50c84f.png)

It would be easy to explain is Safari were doing this and Chrome wasn't, but the Chrome versions between the two OS's are the exact same... so this is a little bit of a mystery.

**Comment by wadewachs** [comment]
I was logged in as the org admin, not a site admin. I believe org admin is the role you would expect to be creating campaigns, and thus the ones using the "copy contact details'" feature.

**Comment by mgmccarthy** [comment]
@wadewachs, let me try logging in as the org admin, sounds like that is why I cannot see the button. Thanks

**Comment by mgmccarthy** [comment]
@tonysurma, looks like this Issue was fixed with PR #1415. This can be closed
