### ISSUE TITLE
Org Admins should not see other organizations when creating Campaigns

### ISSUE THREAD

**Issue by wadewachs** [HTBox/allReady#1347]
When logged in as an organization admin
While creating a new campaign
I have the ability to select any organization to assign the campaign to

I would expect that as a limited user to my own organization, that I would only have visibility into my organization. 

It seems that I am unable to actually create the campaign in an organization that I am not the admin of. However, instead of a useful error, I am redirected to the login page, even though I am already logged in.

I would suggest removing the Organization field completely from the screen, and detecting the organization from my user so the user does not have to think about this at all.

**Comment by mgmccarthy** [comment]
@tonysurma, can you confirm the behavior that @wadewachs is talking about above. If I'm logged in as a org admin and creating a new campaign, should I only see a list of organizations of which I'm an administrator, or should I see all organizations?

**Comment by tonysurma** [comment]
Confirmed, filter for permissions and for org admin that is only those I am an admin for

**Comment by tonylambert** [comment]
I will try this one as my first attempt at working on HTBox.
