### ISSUE TITLE
My Tasks will disappear when a character not in the task is searched for

### ISSUE THREAD

**Issue by jona6629** [HTBox/allReady#1348]
Repro:
1. Dashboard>>Click current event
2. My Task>>Search put in a character that is not in the task
Note: My task div will disappear.

**Comment by wmay1991** [comment]
I will look into it.

**Comment by wmay1991** [comment]
I fixed it and submitted a pull request

**Comment by tonysurma** [comment]
thanks for the contribution @wmay1991 !
