### ISSUE TITLE
Edit Campaign > Add Impact Goals  - Plural descriptor is confusing

### ISSUE THREAD

**Issue by wadewachs** [HTBox/allReady#1349]
![screen shot 2016-10-06 at 9 33 55 am](https://cloud.githubusercontent.com/assets/4061222/19161698/a804f036-8ba9-11e6-9043-62522308f0fd.png)

The text description mentions "Goal**s**". However an individual campaign (it appears) may only have 1 goal attached.

I spent some time trying to figure out how to add another goal. My assumption is that an actual org admin would spend similar time and frustration as the app currently functions.

A very simple fix would be to remove the 's' from 'goals'. It may also be useful to add capabilities for multiple impact goals, but I don't know if that is desired behavior.

**Comment by maguir** [comment]
Working on this

**Comment by tonysurma** [comment]
Hello @maguir I wanted to check in after the event and see if there was a pull request to update this - knowing GitHub was down during the hackathon.  Thanks!
