### ISSUE TITLE
Create Event screen needs some css widths adjusted within the responsive design

### ISSUE THREAD

**Issue by wadewachs** [HTBox/allReady#1350]
https://goo.gl/bKrstE

Once the display is small enough, the labels on the boxes respond appropriately.
There is a point however between ~1200 pixels wide and ~1000 pixels wide where the labels are covered by the data fields

The page to create campaigns seems to handle this much better: https://goo.gl/goZ24c

**Comment by stefan-van-de-griendt-centric** [comment]
Working on this one.

**Comment by stefan-van-de-griendt-centric** [comment]
@tonysurma 
This is not applicable any more.
The only thing that's not nice is the long label `Enforce volunteer limit on tasks` and the moment the labels pop above the inputs.
