### ISSUE TITLE
Create / Save button should be at the bottom of the Create / Edit Event page

### ISSUE THREAD

**Issue by wadewachs** [HTBox/allReady#1353]
https://goo.gl/mi5zFr

As I was scrolling down the page to create an event, I got to the bottom of the page and panicked a bit that there was no 'Save' button on the page. After a few moments of panic, I scrolled up to the top of the page and found the save button squished on the top edge of the page. 

I would like to have these buttons at the bottom of the page so I can save when I get to the end of the page.

**Comment by YannickMeeus** [comment]
Looking through that page, the markup isn't quite correct. There are column specified containers without being nested in row specified containers. I've got a fix locally that I'll raise a PR for this evening.
