### ISSUE TITLE
STARWest_Test Lab Name Length limit needed 

### ISSUE THREAD

**Issue by ChicquillaLewis** [HTBox/allReady#1355]
Description: The name length for the users is not limited

This error does not limit the user name length. Then, the description field is expanded to meet the max length stored in the database.

![screenshot 2016-10-06 at 10 27 16 am](https://cloud.githubusercontent.com/assets/22665710/19166339/f2fec1ea-8bbb-11e6-9a61-b0059196d73c.png)

![screenshot 2016-10-06 at 10 28 19 am](https://cloud.githubusercontent.com/assets/22665710/19166341/f6276e9e-8bbb-11e6-94fb-6fa3802b211e.png)

Steps to Recreate: 
Access the web site.
Login as the admin user.
select the admin user name hyper link "Hello starwest.testlab@gmail.com"
Edit the first name and last name by adding 4000 chars.
Press the Save button
Press the dashboard button
Select a current event
On a task, press the volenteer button

Error: The non truncated name is displayed and scrolling to the bottom of the new window is needed to view all the info.

Suggested Resolution: Truncate the name fields

**Comment by digitaldrummerj** [comment]
@tonysurma This sounds like a task that I could pull into the hackathon I am running.  Any guidance on what you want this to actually do (e.g. truncate at 100 chars or limit the length of input to start with)?

**Comment by digitaldrummerj** [comment]
@tonysurma any guidance how you want this implemented?

**Comment by tonysurma** [comment]
Truncate and limit on input, sorry I missed this alert

**Comment by tonysurma** [comment]
Something like 200 chars
