### ISSUE TITLE
STARWest_TestLab No Cancel button #1

### ISSUE THREAD

**Issue by ChicquillaLewis** [HTBox/allReady#1356]
Description: There is no cancel buttons provided for users

This error will cause users to have to push the back button, thus not continuing in a forward flow to complete a process.

Steps to Recreate: 
Access the web site.
Login as the admin user.
select the admin user name hyper link "Hello starwest.testlab@gmail.com"

Error: There is no cancel button for the user to continue moving forward in the business process.

Suggested Resolution: Provide a cancel button to the user.

![screenshot 2016-10-06 at 11 59 35 am](https://cloud.githubusercontent.com/assets/22665710/19166455/692b368c-8bbc-11e6-92c4-1be1c97f7783.png)

**Comment by wadewachs** [comment]
@ChicquillaLewis  - - We selected you as a prize winner from the test lab. Either try to find me before you leave the conference, or send me your email address and I will get the prize to you.

Thanks for all of your help at the lab.

**Comment by ChicquillaLewis** [comment]
Hello Wade,
Thank you so much for the opportunity to participate in the testing lab to find bugs.  I really enjoy testing.  I apologize for missing this email, and I stopped by your testing site today, however your team had already packed up at the end of the conference.  I did reach out to Rachelle Sawal rsawal@techwell.com<mailto:rsawal@techwell.com> about your email and she mentioned that she would reach out to me in the near future.  So I wanted to send you this email to include you in on our conversation.  If you need further testing done on the site, please let me know.  I will do my best to continue to test it as needed.  (I do know that it is a live environment and not a testing environment, so testing will be limited)  Just let me know.  I am happy to help out in any way that I can.


Hope you made it home safely,

Happy Testing!!!
C. B. L.
Test Analyst
CERNER - MASH Claims Team
Malvern, PA
610.219.9434

**Comment by wadewachs** [comment]
Chicquilla,

Rachelle was the right person to get in touch with. She should be able to get everything to you.

Thanks again for the help in the test lab. I was really impressed by your organized and explorational approach. I specifically appreciated after your exploration session the way you asked about each of the issues you had identified, to compare your expectations to mine.

If you have any interest in continuing to test - @tonysurma may be able to direct your efforts. You can probably start by reading the document for contributing to the project: https://github.com/HTBox/allReady/blob/master/CONTRIBUTING.md

Thanks again.

-Wade-
