### ISSUE TITLE
Footer link - Instagram linked to twitter account.

### ISSUE THREAD

**Issue by atthetestlab** [HTBox/allReady#1359]
// a href="https://twitter.com/HTbox/media" target="_blank"> <img src="/images/instagram-small.png" alt="Instagram account" 
Steps to reproduce.
1) http://allready-d.azurewebsites.net/Account/ForgotPassword
2) Mouse hover on Instagram account on the footer link
3) Instagram account linked to Twitter account - https://twitter.com/HTbox/media
This is reproducible on the other pages - http://allready-d.azurewebsites.net/Campaign, http://allready-d.azurewebsites.net/Organizations, http://allready-d.azurewebsites.net/Home/About, http://allready-d.azurewebsites.net/Account/Login, http://allready-d.azurewebsites.net/Account/Register, http://allready-d.azurewebsites.net/Home/PrivacyPolicy

**Comment by mgmccarthy** [comment]
@atthetestlab, do you happen to know what the link is for HTBox on Instagram?

**Comment by tonysurma** [comment]
We don't have one so should be removed

**Comment by mgmccarthy** [comment]
@tonysurma, I can take care of this.

**Comment by wadewachs** [comment]
<img width="269" alt="screen shot 2016-10-11 at 11 09 01 pm" src="https://cloud.githubusercontent.com/assets/4061222/19296190/c6dc7166-9007-11e6-9695-554b44a8e100.png">

Checked several pages, on all of those I checked (campaigns, admin, events, home) the footer no longer has an instragram icon.

:+1:
