### ISSUE TITLE
The image used on 404 page is large that the user has to scroll down to view the complete image. Is this required to be large image, if yes. Why?

### ISSUE THREAD

**Issue by atthetestlab** [HTBox/allReady#1360]
http://allready-d.azurewebsites.net/Error/Error404 
We went off the rails and couldn’t find your page! 
Don’t worry. We’ll get back on track. 

Tested on the chrome book at the TestLab.

**Comment by julianharty** [comment]
As a suggestion, how about considering resizing the image so it fits within the visible area. Perhaps something along the lines of the solution from http://stackoverflow.com/questions/12991351/css-force-image-resize-and-keep-aspect-ratio would help. Also the image is quite large, over 600KB I think, perhaps it'd be worth finding ways to make it smaller so it consumes less bandwidth and time to transmit.

**Comment by fasia** [comment]
I am working on it

**Comment by tonysurma** [comment]
Hello @fasia I wanted to check in after the event and see if there was a pull request to update this - knowing GitHub was down during the hackathon.  Thanks!

**Comment by fasia** [comment]
Hi,
Nice to hear from you! I could not fix the error that i was getting in my
mac, so I could not resolve the issue. You can delete my comment there.
I would like to know if you found what was the cause of the problem.

Best,
Faezeh

**Comment by mattferderer** [comment]
I would be glad to jump in & try helping out with HTBox on this issue or help someone else solve it. Is there any reason this image couldn't be a jpg? That could help the file size be less than half of what it currently is. 

Also we could use media queries to download different images to also help reduce the size of the image. I'm not sure if that's making this to complex or not.

**Comment by tonysurma** [comment]
thanks @fasia I am hoping to have the mac build/compile issue figured out soon. Thanks again for your help in hunting that at Grace Hopper

**Comment by tonysurma** [comment]
@mattferderer thanks for jumping in.  there are two issues size on screen and on disk.  Open to format change etc. that solves the latter and resizing to fix the former.  

media queries etc. are great but may be overkill for this one as there is no reason for a giant image here (but if you want to add them its not a bad idea and we can reference as example for media queries else where when/if they are needed.)
