### ISSUE TITLE
Refactor ItineraryController's Confirm/RemoveRequest/TeamMember action methods

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1363]
this refactoring replaces database queries with info passed on the ViewModel for the Delete/Confirm steps for both ConfirmRemoveRequest and ConfirmRemoveTeamMember.

This will be my last "improvement" refactoring for a while as I'm going to turn my attention to the October/November/December release Issues along with bugs. Thanks

**Comment by tonysurma** [comment]
Thanks!
