### ISSUE TITLE
Refactor SkillController Delete and DeleteConfirmed action methods to reduce db calls and use strong typed ViewModel for post

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1365]
One more improvement refactoring, then I SWEAR... I'm done. This was a quick and easy one and just smoked tested it and unit tests are updated.

**Comment by tonysurma** [comment]
Making code better is addictive 👍

**Comment by mgmccarthy** [comment]
"leave the campground cleaner than you found it"... words to live by.
