### ISSUE TITLE
Question about Azure settings in conjunction with running Hangfire in IIS process

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1383]
@MisterJames @tonysurma 

I'm not too sure what "version" of an Azure web account allReady has, but apparently, if we don't have a free Azure account, running the Hangfire server in the IIS process is as simple as flipping this setting in Azure:

![image](https://cloud.githubusercontent.com/assets/2428993/19450664/59a61410-9478-11e6-9569-0646b00db3ae.png)

For more background on forcing "always on" and why it's needed when running Hangfire server in the IIS process, please refer to these docs:
http://docs.hangfire.io/en/latest/deployment-to-production/making-aspnet-app-always-running.html

For immediate development need of scheduled jobs for requestor sms confirmation text messages, I think this is a good place to start, and I have code I want to commit, but I'm not too sure if the our Azure account is a "free" or not.

That being said, I think the final solution would be moving Hangfire server to its own process and host it that way. I'll still looking around for how we would run that separate process using Azure hosting. We will also need to update our deployment script, b/c now we'll be deploying the Hangfire server and the web application. I'm going to need help with that part.

Some docs that talk about putting the Hangfire server into its own process:
http://docs.hangfire.io/en/latest/background-processing/placing-processing-into-another-process.html
http://docs.hangfire.io/en/latest/background-processing/processing-jobs-in-console-app.html

**Comment by MisterJames** [comment]
It's actually not about the account, it's about the app service profile we run the site under. We should be fine to make this config setting change. Thanks for looking into this @mgmccarthy. We're going to be okay to move ahead with this. @tonysurma would you like to try to deploy these changes first to a different deployment?

**Comment by tonysurma** [comment]
I will double check but I think AlwaysOn is already configured on.

**Comment by tonysurma** [comment]
AlwaysOn is allReadyOn ™️ so you should be good to go

**Comment by mgmccarthy** [comment]
:+1:

**Comment by mgmccarthy** [comment]
@tonysurma @MisterJames, apparently, there is also an "auto start" feature in Azure as well. Can one of you verify:

- if that option does indeed exist
- if it does, to set it on?

Thanks

**Comment by tonysurma** [comment]
auto on and auto start are set.

**Comment by mgmccarthy** [comment]
@tonysurma , let me know when you have the new db provisioned in Azure. Name of db should be "Hangfire". Thanks!

**Comment by tonysurma** [comment]
Please confirm from what config setting it picks up the connection string and fyi it will have to be a different db name than hangfire

**Comment by mgmccarthy** [comment]
@tonysurma, tell me what the db name needs to be.

config.json:
```
"Data": {
  "HangfireConnection": {
      "ConnectionString": "Server=(localdb)\\MSSQLLocalDB;Database=Hangfire;Integrated Security=true;MultipleActiveResultsets=true;"
```

Startup.cs
```
//Hangfire
services.AddHangfire(configuration => configuration.UseSqlServerStorage(Configuration["Data:HangfireConnection:ConnectionString"]));
````

is this what you need?

**Comment by tonysurma** [comment]
OK that's perfect.  Leave that in the config and that should work for local devs.  I will create db for live environments with what ever names and update that config entry like i do for the main db now.

**Comment by mgmccarthy** [comment]
Would be cool to have something for devs that would check for the existence of the hang DB when they hit F5, and if it doesn't exist, create it. If not, they can hit F5 and run the system,  but the registration of hangfire will fail. The simplest  solution is to include a sql script that they can run manually,  but that's not very intuitive.

**Comment by mgmccarthy** [comment]
@tonysurma, do we have a db for Hangfire ready to go in live environment? I'd like to know before submitting PR

**Comment by tonysurma** [comment]
The  f5 experience is what EF does,  it creates the db locally.   I have the  environment  ready to go.  However if it doesnt create the db  I don't know what will happen in the appveyor.   Either way submit it and we will test it.   Thank you
