### ISSUE TITLE
Move the Create Request button to the Event/Details page

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1385]
cc @stevejgordon 

it's not very clear to the user how to create a new request, as the button is hidden a bit. Right now to create a requst, you need to navigate to the event details page:
![image](https://cloud.githubusercontent.com/assets/2428993/19517130/567f4b98-95cd-11e6-89b7-0abba1f5f4dc.png)

where you can see the all the requests associated with that event. You then need to click on one of the event status squares to bring you to the event requests page:
![image](https://cloud.githubusercontent.com/assets/2428993/19517187/ac90e6fe-95cd-11e6-8bc1-9cbe7ca7c2f5.png)

this is where the create request button lives now.

I propose moving the Create Request button to the event details page, so it's one less click to create an event, and the button is a little easier to find for users. Since we're presenting Request information on the event details page in the form of the blocks that represent status, having the Create Request button there makes sense.

**Comment by stevejgordon** [comment]
@mgmccarthy Yep I agree it's fairly well hidden!

**Comment by maguir** [comment]
Working on this issue
