### ISSUE TITLE
Campaign/Event/Task start and end date/times are not being displayed in the users's local timezone

### ISSUE THREAD

**Issue by dpaquette** [HTBox/allReady#1388]
If a user has a local timezone specified (under the user's profile), then event date/time should be displayed in the event's local time and also the user's local time.

Expected Result:
![image](https://cloud.githubusercontent.com/assets/2531875/19581364/a9a681e8-96e9-11e6-9832-94394fccda35.png)

Actual Result:
![image](https://cloud.githubusercontent.com/assets/2531875/19581353/9b84aaf4-96e9-11e6-8004-4e88371fc65f.png)

**Comment by tonysurma** [comment]
fixed by PR
