### ISSUE TITLE
Manual Request Creation - Latitude/Longitude Lookup

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1398]
When creating a request via the admin UI and saving it via EditRequestCommandHandler we should call the Bing API to determine the latitude and longitude for storage in the DB.

We need these details when representing the requests on the map.

**Comment by mgmccarthy** [comment]
@stevejgordon FYI, there is an `IGeocoder` abstraction that I found when picking up work on PR #1111 that is also used in ImportController. ImportController allows the import of Requests via a CSV. `IGeoCoder` is implemented by `GoogleGeocoder` in Startup.cs.

Not too sure if this is the same thing, or something different, but I figured I'd point it out.

**Comment by stevejgordon** [comment]
Thanks @mgmccarthy. I've literally just stumbled on that when digging into the code!

**Comment by tonylambert** [comment]
I'm looking at this one.
