### ISSUE TITLE
Create / edit activity page error message showing 'EndDateTimeUtc' and not 'End date'

### ISSUE THREAD

**Issue by ksk100** [HTBox/allReady#140]
Very minor thing, as per the title and shown here:

![image](https://cloud.githubusercontent.com/assets/6615834/10883907/e72927fc-816c-11e5-8389-8cb33ff747e1.png)

Given the data annotation is set correctly and the pretty name is showing in the `<label asp-for="EndDateTimeUtc" ...>` but not the `<span asp-validation-for="EndDateTimeUtc" ...>` element, this might be a framework bug?

**Comment by bluechrometouch** [comment]
Was able to replicate the problem with both new MVC 6 tag helper and the old html helper for validation

The bug also occurs in other fields as well.

Tried testing with different alternative display attributes and with async removed from the controller. Same results and not sure where the bug occurs. Thinking of trying again later with an activity input viewmodel.

The validation message typically displays the formatted name.

**Comment by dpaquette** [comment]
I am reviewing the date/time pickers anyway right now so I might address this as part of that

**Comment by ksk100** [comment]
I suspect a framework bug (the problem occurs with a single form on a brand new project), and raised an issue for it here: https://github.com/aspnet/Mvc/issues/3476

**Comment by ksk100** [comment]
They confirmed a framework bug which is (very probably) causing this; it's fixed in RC1.

**Comment by BillWagner** [comment]
Adding the Framework label so we can close this upon upgrade to RC 1 and the fix for https://github.com/aspnet/Mvc/issues/3476

**Comment by tonysurma** [comment]
@dpaquette can you re look at this per your comment when you get a chance

**Comment by dpaquette** [comment]
Safe to close this one now. I tested the date pickers and I can't figure out a way to get an invalid date in there
