### ISSUE TITLE
Check for local Hangfire db and if doesn't exist, create it.

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1407]
This is based on a comment from Issue #1399. Currently, if you do not have a Hangfire db created Server=(localdb)\\MSSQLLocalDB, the application throws an exception when you start it.

We want a developer-friendly F5 experience, so I added code in Startup.cs that checks for the existence of a Hangfire db, and if it does not exist, to create one.

I had to use ADO's SqlConnection and SqlCommand, which felt really dirty and brought back bad memories of being a .NET developer 10 years ago, but since Entity Framework does not know about the Hangfire db (and it shouldn't), I needed some way to check and create if missing

**Comment by tonysurma** [comment]
Yikes definitely getting in deep with ADO and tsql :)

After we can verify someone else without the db sees it work/create it then I will merge to prevent any "It works on my machine:tm:" issues 😸

**Comment by mgmccarthy** [comment]
@tonysurma, the result would still be an exception in case the connection cannot be made or something else happens on the dev's local machine... so, we get an exception now, and if this fails... we get an exception.

Either way, the db will still need to be created locally.

If anyone has a better idea that does not involve SqlConnection and SqlCommand, then I'm definitely open to that discussion.

**Comment by tonysurma** [comment]
@mgmccarthy - wasn't editorializing about the approach was just being cute related to your comment about getting dirty with ADO (or at least was trying to be cute)

also was just figuring worth a test on another machine - and totally agree on optimizing for F5 and thanks for adding
