### ISSUE TITLE
Restrict access to the Hangfire dashboard

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1417]
Hangfire includes a dashboard where you can see jobs in all different states. Because some of the information presented on the dashboard, Hangfire allows you to secure it by implementing `IDashboardAuthorizationFilter`.

@tonysurma. for allReady, we need to decide which type of user has access to the Hangfire dashboard. Would it be an OrgAdmin, a SiteAdmin... or maybe a new type of user that is more of a "admin"-based role that is not tied to an individual (or group of) Organizations or Sites?

Once we decide which user/role needs access to the dashboard, I can implement `IDashboardAuthorizationFilter` to secure the Hangfire dashboard.

**Comment by tonysurma** [comment]
For now lets authorize Site Admins as that is 'super user level mode' and later we can add a new level.  Thanks
