### ISSUE TITLE
Implement skipped tests in ItineraryAdminControllerTests

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1424]
@tonysurma please label with jump-in

**Comment by HamidMosalla** [comment]
@mgmccarthy I don't think we can check for equality by reference in this test, because we don't have the same object when `ToList()` is called as the comment in test case suggest, unless we change the `AddRequests` method signature to take a List<string>, I don't know if the sequence equality is acceptable here:

```
        [Fact]
        public async Task AddRequestsSendsAddRequestsCommandWhenThereAreSelectedRequests()
        {
            const int orgId = 1;

            var itineraryId = It.IsAny<int>();
            var selectedRequests = new[] { "request1", "request2" };

            var mockMediator = new Mock<IMediator>();
            mockMediator.Setup(x => x.SendAsync(It.IsAny<OrganizationIdQuery>())).ReturnsAsync(orgId);
            mockMediator.Setup(x => x.SendAsync(It.IsAny<AddRequestsToItineraryCommand>())).ReturnsAsync(true);

            var sut = new ItineraryController(mockMediator.Object, null);
            sut.MakeUserAnOrgAdmin(orgId.ToString());

            await sut.AddRequests(itineraryId, selectedRequests);

            mockMediator.Verify(x => x.SendAsync(It.Is<AddRequestsToItineraryCommand>(y => y.RequestIdsToAdd.SequenceEqual(selectedRequests.ToList()))), Times.Once);
        }
```
If this is acceptable, tell me to create a PR.

**Comment by mgmccarthy** [comment]
we want to assert that the correct RequestIds are going to be added to the Itinerary. If it works with changing the `string [] selectedRequests` to `List<string> Requests`, then I'd say it's worth the update.

**Comment by HamidMosalla** [comment]
@mgmccarthy If I change it, couple of other tests are going to break too, but it must be trivial to correct, should I go ahead with it?

**Comment by mgmccarthy** [comment]
@HamidMosalla, I'd say go for it. If it works locally, and you smoke test your changes and everything looks good, please submit a PR.

**Comment by tonysurma** [comment]
Thanks in advance @HamidMosalla
