### ISSUE TITLE
Consolidate test code in EditEventCommandHandlerShould2 into EditEventCommandHandlerShould1

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1429]
- delete `EditEventCommandHandlerShould2`
- rename `EditEventCommandHandlerShould1` to `EditEventCommandHandlerShould`

@tonysurma please label with jump-in

**Comment by GitaGunnam** [comment]
I am taking this

**Comment by HamidMosalla** [comment]
I think this issue can be closed, it has been addressed in #1428

**Comment by EmilyLuijbregts** [comment]
Closed - per comment from @HamidMosalla
