### ISSUE TITLE
Implement skipped tests in EventDetailQueryHandlerShould

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1430]
@tonysurma please label with jump-in

**Comment by FvdG** [comment]
Looking into this.

**Comment by stevejgordon** [comment]
Hi @FvdG - Just checking if you're still working on this?

**Comment by FvdG** [comment]
I have the solution, i will try to make a pull request tonight. If this
fails for some reason i will notify you.

Frank

Op 30 nov. 2016 5:12 p.m. schreef "Steve Gordon" <notifications@github.com>:

**Comment by stevejgordon** [comment]
No rush - thanks @FvdG - I was looking at something that was in the same area but will avoid it until your PR is in.

**Comment by SarahMarz** [comment]
Looking at this one now

**Comment by mgmccarthy** [comment]
this is as close as I can get it...
the input field is below and to the right of the gsc-input-box div element...
I can't believe google does not have a way to allow you customize the values on the input element that does not involve hacking javascript...

**Comment by stevejgordon** [comment]
Looks like the pr from @FvdG resolved this. We didn't get an auto closure though so closing manually.

Thanks for getting the PR in @FvdG - Just one small note, when you submit the PR, if you include text along the lines of "Fixes #1430" it'll auto close the issue once the PR is merged.
