### ISSUE TITLE
Implement skipped tests in EditItineraryCommandHandlerShould

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1432]
@tonysurma please label with jump-in

**Comment by HamidMosalla** [comment]
@mgmccarthy There was just one skipped test in it with the name `AddsNewItineraryWhenItDoesNotExist` that was marked `[Fact(Skip = "RTM Broken Tests")]`, but when I removed the Skip argument and ran the test, the test passed, I don't know if a pull request is necessary for this.

**Comment by mgmccarthy** [comment]
please submit a PR. We're trying to fix/correct any of the unit tests that are still commented out with RTM Broken Tests".
