### ISSUE TITLE
Implement skipped tests in EventsByGeographyQueryHandlerShould

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1437]
@tonysurma please label with jump-in

**Comment by peerhenry** [comment]
picked up.
This is similar to #1438 
The problem was an extension method that can't be mocked in the test. I decided to wrap the extension method call.

**Comment by mgmccarthy** [comment]
@peerhenry cc @tonysurma there should be no unit test for this.  Check my comments on PR #1542 for clarification.
