### ISSUE TITLE
Implement skipped tests in EventViewModelShould

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1439]
@tonysurma please label with jump-in

**Comment by waesbende** [comment]
Implemented this test.

**Comment by johnmwright** [comment]
I'm not seeing any tests still marked as `[Skip]` in `EventViewModelShould`, so it appears the fix for #1539 may have fixed this issue.  @tonysurma is this still something that needs work? If so, can you please provide more details?

**Comment by mgmccarthy** [comment]
@johnmwright, if there are no more `[Skip]`'s in the EventViewModelShould test class, then this issue can be closed.

**Comment by BillWagner** [comment]
Closing per @mgmccarthy
