### ISSUE TITLE
Activity and task validation needed for time

### ISSUE THREAD

**Issue by bluechrometouch** [HTBox/allReady#144]
/Activity/Edit
/Activity/Create
Default Start date and end date comes with extraneous time
Allows null name
End date can be < Start date

/Task/Edit
/Task/Create
Starting time and ending Time date picker does not include time
End time can be < Start time

**Comment by bluechrometouch** [comment]
I can start working on this one.

**Comment by bluechrometouch** [comment]
aec2e48ea35a915091112b32ca1fe0586d9cb6dc Should fix most of the issues.

dpaquette is reviewing the date time picker. This will tie into the date picker not including time for tasks.

Not sure it's proper to place data annotation validation in the activity model instead of a activity view model.

**Comment by dpaquette** [comment]
Yes, looking at the whole time thing. Anyone have a good suggesting for a time picker control?

**Comment by bluechrometouch** [comment]
Were you looking for anything other features in a time picker?

The bootstrap time picker can be customized. Here is are some examples that show controls for time and date by themselves.

https://eonasdan.github.io/bootstrap-datetimepicker/

**Comment by dpaquette** [comment]
I think this can be closed

**Comment by BillWagner** [comment]
Yes, it can. I missed closing it when merging #149
