### ISSUE TITLE
Mobile-App: missing npm commands for starting ionic

### ISSUE THREAD

**Issue by digitaldrummerj** [HTBox/allReady#1440]
In the contributor guide, it mentions using the NPM Task Runner in Visual Studio to start up the ionic serve and ionic serve --lab but these commands are not in the mobile app's package.json file.

**Comment by digitaldrummerj** [comment]
I am working on this one.

**Comment by digitaldrummerj** [comment]
@tonysurma can you add the label mobile app instead of documentation?  The docs are correct but the functionality is missing from the mobile app project.

**Comment by tonysurma** [comment]
thanks for the catch @digitaldrummerj
