### ISSUE TITLE
Campaign bugs and issues

### ISSUE THREAD

**Issue by bluechrometouch** [HTBox/allReady#145]
Campaign/Edit
Campaign/Create
Null name causes ongoing crashes in Admin Campaign tab
Managing Tenant → Managing Organization
Picture URL not accepting pictures
End date can be < Start date

**Comment by joelhulen** [comment]
I'll take this on since it relates to the issue I'm currently working.

**Comment by BillWagner** [comment]
@joelhulen I can't find a pull request that references this. Let me know if it's already done.

**Comment by ksk100** [comment]
There's a mention of 'tenant' in `Areas\Admin\Views\Tenant\Create.cshtml`

**Comment by tonysurma** [comment]
Can anyone see if this still an issue?  looks @dpaquette or @ksk100 may have solved elsewhere?

**Comment by dpaquette** [comment]
I did a quick search in the code and looks like Tenant has been successfully removed.

**Comment by dpaquette** [comment]
Most of these issues seem to be fixed but End Date can still be < Start Date
