### ISSUE TITLE
bug: login page giving this.optional is not a function for custom email validation rule

### ISSUE THREAD

**Issue by digitaldrummerj** [HTBox/allReady#1456]
The custom email validation rule is throwing errors for me in the dev tools console when the page loads.  I do have the username and password saved in the browser and auto filled.  

![image](https://cloud.githubusercontent.com/assets/708423/20027692/03a55e7c-a2d8-11e6-9df2-f646ef6c0546.png)

**Comment by pranap** [comment]
Working on this
