### ISSUE TITLE
Edit Activities, Javascript Error

### ISSUE THREAD

**Issue by bcbeatty** [HTBox/allReady#147]
I get the following JavaScript error on the Edit Activities page

```
Syntax error, unrecognized expression: select[data-bind='attr: { name: 'RequiredSkills[' + $index() + '].SkillId' }, options: $root.availableSkills, optionsText: 'Name', optionsValue: 'Id', value: Id']
```

IE11, Windows 8, In Memory and SQL databases.
http://localhost:33310/Admin/Activity/Edit/4

**Comment by mheggeseth** [comment]
Does the error come from browser link? If so, it doesn't break any functionality.

**Comment by bcbeatty** [comment]
No, not from a direct link. I put that in for a reference.

**Comment by bcbeatty** [comment]
Similar issues happens with Admin Task Edit

**Comment by mheggeseth** [comment]
What I mean is: what file throws the error? If it's browserLink.js, then the error only affects Visual Studio's integration with the view, not the main function of the view. In other words, running the app in prod should produce no such error.

**Comment by bcbeatty** [comment]
Javascript throwing the error in knockout.js, but because of an invalid binding. knockout can't find RequiredSkills, or RequiredSkills[].SkillId or similar property. 
But if I continue after the error, a Select does get populated on the form and it doesn't block the save. It could be a timing/sequence of events issue. 
I get the same error with F12 tools being my debugger and not VS.

**Comment by dpaquette** [comment]
Strange. I can't reproduce this. @mheggeseth are you seeing this error?

**Comment by mheggeseth** [comment]
I get an error, but it comes from browserLink, not Knockout. If I move the string-concat into a function on the view model, everything is 200 OK.
![image](https://github-cloud.s3.amazonaws.com/assets%2F775229%2F10957758%2Fe38d6d1c-832c-11e5-98eb-b2d3a0b4d254.png)
