### ISSUE TITLE
You can create an Itinerary in the past

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1490]
On the Event Details page, where you can create an Itinerary:
![image](https://cloud.githubusercontent.com/assets/2428993/20290125/22fc46f6-aaac-11e6-8757-55b317cba31f.png)

when you click the Create Itinerary button, a modal window pops up with a date pre-selected:
![image](https://cloud.githubusercontent.com/assets/2428993/20290145/433ba290-aaac-11e6-82ce-11a9ef3a3f6a.png)

the date is in the past in this scenario b/c the create Itinerary model uses the event's start time as the default date for the Scheduled Date field.

This allows a user to create an Itinerary in the past, which doesn't make any sense. We should either:
- no pre-populate the date field, but have validations on it that dont' allow a date before "today"
- pre-populate the date field with today's date

**Comment by HamidMosalla** [comment]
I'm working on this, also I'd suggest we do both, because even if we set the date to today's date, user still can change the date to the day after the event start, but before the current date, and validator doesn't have any problem with this:
![datevalidation](https://cloud.githubusercontent.com/assets/11329074/20311098/babd527a-ab63-11e6-9ed4-7fd65de53701.png)
Which from what I gather from what you've said doesn't making any sense.

**Comment by mgmccarthy** [comment]
@HamidMosalla, what we really should be checking for here is:
- if the Event start date is in the future, then we make sure the user cannot create the Itinerary before the start date of the event
- if the Event start date is in the past, then we make sure the user cannot create the Itinerary before today

both of those type of dates should be returned to the user as a validation error.

**Comment by HamidMosalla** [comment]
I made a pull request Michael, I'm not entirely sure about my test cases, please check them out, thanks.

**Comment by mgmccarthy** [comment]
@HamidMosalla, I just commented, but it's for another team member. We've just added a new model binder that transforms inbound DateTimeOffsets to a TimeZoneId (also specificed on the model), so by the time the `ItineraryEditModelValidator` is invoked, I think the offset value has already been transformed into an offset that reflects the timezone... 

based on my assumption, I'm not too sure if we can use DateTimeOffset.Now to do the comparison or not.
