### ISSUE TITLE
Unit tests for EditItineraryCommandHandler

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1497]
Following on from #1495 we need unit tests to cover the required behaviour in the EditItineraryCommandHandler

**Comment by YannickMeeus** [comment]
I believe a previous (pull request (1602))[https://github.com/HTBox/allReady/pull/1602] already added full coverage to the EditItineraryCommandHandlerShould test cases, but you might want to make sure.

**Comment by tonysurma** [comment]
Thanks @YannickMeeus 

@stevejgordon please close this if it looks complete to you. Thanks to you both
