### ISSUE TITLE
Add descriptive text to campaign data field for URL

### ISSUE THREAD

**Issue by schuback** [HTBox/allReady#1498]
Creating a campaign data fields - does it have to have http(s) within the data field?  If so, needs an example text in light grey on the side

**Comment by tonysurma** [comment]
@schuback which field of campaign are you referring to?  Once we identify the field this issue is to put some example text next to or placeholder text in the edit box to show it is a url.

**Comment by schuback** [comment]
Added a screen shot.  Example text should be added next to "External Link" with the required URL format. www.htbox.org or http://www.htbox.org

<img width="951" alt="screenshot 2016-11-18 08 29 54" src="https://cloud.githubusercontent.com/assets/830036/20431657/36dcbc36-ad69-11e6-9c62-7733014049e7.png">
