### ISSUE TITLE
Add "new skill" shortcut button on admin view of creating a task page

### ISSUE THREAD

**Issue by schuback** [HTBox/allReady#1500]
Required Skills box - needs to have a create button to the right to create a new skill requirement - currently you have to go to the top menu and click on skills to then create a skill.  Having a shortcut would help with total time to create task and the number of clicks an admin has to take

**Comment by tonysurma** [comment]
@stevejgordon @MisterJames I feel like we had an issue and created this functionality at some point (the ad-hoc addition of skills during task creation).  Did we or am I dreaming?  Thanks

**Comment by stevejgordon** [comment]
@tonysurma - You're not dreaming. I think you were thinking of issue #316

**Comment by tonysurma** [comment]
duplicate
