### ISSUE TITLE
Address verification process/click to show exact location

### ISSUE THREAD

**Issue by schuback** [HTBox/allReady#1501]
Address field - needs to have a mapping button to confirm locations and to help pinpoint the location more.  Think like Uber and how it as you to verify your pick up location. Helps with big parking lots or buildings with multiple unmarked entries.

In the uber example it is like when it asks you to verify your location

**Comment by tonysurma** [comment]
cc @stevejgordon 

Adding a bit more detail this is for where addresses are provided for events and/or tasks.  The update would be to both add lat/long to the models for those items as well as the UI to have the user enter an address (already there) and then have it display that on a map with a pin (new functionality) and optionally move/select a different pin spot to be the lat/long stored with the model.

**Comment by stevejgordon** [comment]
@tonysurma We do have lat/long on some (maybe all) of the models. We have a geo-service that gets the lat/long from Google for the address. It's that lat/long we then store and use for the pins in other maps.

So I think really we just need to expose the lat/long details and as you suggest, make it possible to adjust using the map. I think this is possible with the APIs from either Google or Bing. Might need a bit of javascript expertise to make it happen dynamically.

**Comment by tonysurma** [comment]
@stevejgordon is this handled by the other issues I saw you entered or is there still a gap?  THanks

**Comment by stevejgordon** [comment]
@tonysurma I think there's still some work we can do here. We haven't exposed the lat/long details on the UI yet as far as I know.

**Comment by dchristensen** [comment]
I can work on this, however I would like some clarification on where this feature is required.  Is this going to be added to the Event Add/Edit screen in the Admin section?  The Task screen was mentioned earlier as well, but I don't see an address associated with a Task.

@tonysurma @stevejgordon

**Comment by dchristensen** [comment]
I have got the javascript working in a local branch to be able to move a point on the map and bind the lat/lon to a pair of hidden fields on a form.  I just need to know which screens need this functionality.

Right now the only place we're tracking Lat/Lon in the DB is on the request, so anything else will need to have changes made to the EF models.  @stevejgordon can you advise as to where this needs to be implemented?

**Comment by stevejgordon** [comment]
@dchristensen I think the request add/edit page is most relevant to this requirement.

We also store the start and (optionally) end address lat/long for Itineraries. This is only on the edit view where the address(es) can be set. The flow is a little complex there though. Neither are required. You can optionally choose to one once location as the start and end of a itinerary route. Or you can select and enter different addresses.

We don't directly store the lat/long for the other models at the moment.

**Comment by stevejgordon** [comment]
@tonysurma @schuback - Do you think we need map address selection for the campaign, event etc? We don't lat/long lookup those at the moment and simple display the address details on the UI.
