### ISSUE TITLE
Stars?  What are they. 

### ISSUE THREAD

**Issue by schuback** [HTBox/allReady#1504]
Campaign Admins - What are the stars referencing? My own campaigns? New Campaigns? Need to add definition of what these stars mean and do.

**Comment by tonysurma** [comment]
@schuback - can you provide a screenshot of which stars you are referring to and the urls on which they appear?

**Comment by schuback** [comment]
<img width="1377" alt="screenshot 2016-11-18 09 02 18" src="https://cloud.githubusercontent.com/assets/830036/20432559/bc989f3a-ad6d-11e6-8e12-421e3949e1d8.png">

URL of the page I screen grabbed - http://allready-d.azurewebsites.net/Campaign

**Comment by DanielSchiavini** [comment]
I added a legend to the page on PR #1532

**Comment by BillWagner** [comment]
closed in PR #1532
