### ISSUE TITLE
Pop up window issue

### ISSUE THREAD

**Issue by schuback** [HTBox/allReady#1505]
When in a campaign and signing up to volunteer and write a comment.  When I hit "volunteer" after writing my comments the window does not close. I have to go to the X. Would be good for it to close.

**Comment by tonysurma** [comment]
clicking the action button for volunteering should close the popup

**Comment by tonysurma** [comment]
Now that I see #1518 what url is this for @schuback and @OhMcGoo ?  Also how is this different from that issue? are you logged in as a different type of user?

**Comment by schuback** [comment]
Here is a screen shot from a user logged in trying to sign up for a task in a campaign.  Includes the URL in the screen shot.  When I click the blue button in the window it does not close. 

<img width="1391" alt="screenshot 2016-11-18 09 06 45" src="https://cloud.githubusercontent.com/assets/830036/20432689/55d89d3a-ad6e-11e6-8dd9-800e2ae576a3.png">

**Comment by Hamels** [comment]
I'll take this up during the Hackathon in Eindhoven.

**Comment by Hamels** [comment]
I can't reproduce this issue in the dev environment. I can reproduce this on the  http://allready-d.azurewebsites.net/. It seems the dev and test environments are not in sync.

**Comment by tonysurma** [comment]
@Hamels the site gets updated with every accepted pull request and I just verified it is up to date.  Perhaps this is due to the OS/browser combo that @schuback was using?

**Comment by tonysurma** [comment]
@Hamels verified that the code on the site and in the repo are now in sync (there was a build issue in azure).  @schuback can you verify if you still have this issue live?  Thanks

**Comment by tonysurma** [comment]
ping @schuback

**Comment by tonylambert** [comment]
@tonysurma, @schuback  - This likely isn't helpful but I cannot reproduce this on my dev machine nor can I on http://allready-d.azurewebsites.net/

However, I do see some errors in the console (both on my dev machine and on the http://allready-d.azurewebsites.net/ site): 

![javscript console errors](https://cloud.githubusercontent.com/assets/688221/21630075/c0017cfc-d1fb-11e6-99a4-4210bfb4410c.gif)

Cleaner video if the above one isn't helpful enough: http://screencast.com/t/lGRCZptTY3C

**Comment by johnmwright** [comment]
What's the status of this issue?  Is it still a valid issue for people looking to "jump in" (ie: take on first/second task)?

**Comment by mk0sojo** [comment]
Tried this quickly and can't reproduce

**Comment by stevejgordon** [comment]
Looks like this cannot be reproduced
