### ISSUE TITLE
Pop up window closing requires page refresh for update (connected to #1505)

### ISSUE THREAD

**Issue by schuback** [HTBox/allReady#1506]
When in a campaign and signing up  to volunteer, after writing a comment and clearing the window box, it goes back to the volunteer list. It does not show that I have signed up. Even after page refresh.

**Comment by tonysurma** [comment]
We need to review this workflow and have the page (post submitting to the server and closing the popup) either refresh or reditect to a page that would show the new volunteer 'result' or some other indication of success

**Comment by stevejgordon** [comment]
@schuback - I'm struggling to replicate this either locally or on the test site.

I go to an event and volunteer for a task

![image](https://cloud.githubusercontent.com/assets/3669103/21619506/e25807d0-d1e7-11e6-9f5c-e137b46c238f.png)

after add comments I hit volunteer - this is the result

![image](https://cloud.githubusercontent.com/assets/3669103/21619480/c4746100-d1e7-11e6-9bbd-abf743aee200.png)

Are you able to advise is this is the same flow you followed when creating the issue? Or are the different replication steps I can try?

**Comment by shahiddev** [comment]
I've just tried to repro this and get same result as @stevejgordon

**Comment by mipre100** [comment]
I have been able to reproduce an issue here. When I volunteered, I got a number of System.InvalidOperationException exceptions, but I also get a slightly different screen from @stevejgordon 
<img width="713" alt="screen shot 2017-01-16 at 14 05 28" src="https://cloud.githubusercontent.com/assets/4063056/21985913/e52f1fe0-dbf4-11e6-92f3-8e2c03153c3f.png">
Example exception: [here](https://gist.github.com/mipre100/9206fd50356cfdb4b35cc8573110c684)

**Comment by BillWagner** [comment]
Fixed in PR #1724
