### ISSUE TITLE
Need a definition for tag line

### ISSUE THREAD

**Issue by schuback** [HTBox/allReady#1507]
Using  MacOS with FireFox.  Logged in as a user and went to campaign to event to sign up for a task.  Picked Install Team Safety.  Pop up window had comments and then a check box for medical requirement. "Associate new skills?" tag line does not really make sense. It seems like it is asking you about someone else

**Comment by tonysurma** [comment]
@schuback can you clarify what is wanted and perhaps share a screenshot?  THanks

**Comment by schuback** [comment]
"Associate new skills?" should be changed as it does not make sense in their point of view.  This task requires (set be admin who created the task) the following skills/capabilities.  Might need some discussion with @OhMcGoo with the language. 

<img width="1391" alt="screenshot 2016-11-18 09 06 45" src="https://cloud.githubusercontent.com/assets/830036/20432842/0d7c00da-ad6f-11e6-81e8-68d4db0af03e.png">

**Comment by tonysurma** [comment]
@OhMcGoo @schuback let us know the wording you would like

**Comment by BillWagner** [comment]
Here at NDC, I'll make the recommendation that we say:

"This Task requires the following skills. Check the box to indicate that you have those skills."

@OhMcGoo If you prefer other language, let us know.

**Comment by OhMcGoo** [comment]
This works for me. Down the road, we may want to consider the option of only showing volunteers tasks for which they have had skills pre-assigned by the Org.

**Comment by Diana380** [comment]
i can take this one

**Comment by Diana380** [comment]
this change has been applied in PR https://github.com/HTBox/allReady/pull/1733

**Comment by BillWagner** [comment]
Closed. I merged PR #1733
