### ISSUE TITLE
Admin Organization CRUD pages improvements

### ISSUE THREAD

**Issue by ksk100** [HTBox/allReady#151]
I couldn't find an open issue covering these (although perhaps partially covered with #145?):

* Remaining references to 'tenant' on list/create pages
* Create page shows ID label
* No validation on create / edit pages
* No pretty names for fields

Happy to take this on if indeed it's not covered by anything anyone else is doing.

**Comment by dpaquette** [comment]
We will be reviewing our requirements and doing some planning on Friday.

**Comment by BillWagner** [comment]
@dpaquette It looks like this was also addressed in #16. If not, can you please reopen.
