### ISSUE TITLE
Button overlap issues

### ISSUE THREAD

**Issue by schuback** [HTBox/allReady#1513]
Buttons covering over text with window at half screen size. 
<img width="555" alt="screenshot 2016-11-15 12 52 26" src="https://cloud.githubusercontent.com/assets/830036/20375684/af1129b0-ac4e-11e6-9ce8-ea6717d6fbbd.png">

**Comment by tonysurma** [comment]
Issue is UI overlap on Mark Complete buttons on the event page correct @schuback ?

**Comment by bmaluijb** [comment]
I'll take this one

**Comment by schuback** [comment]
Yes.  Looks to be UI.  

FYI.  Using MacOS with safari and Firefox.

**Comment by GITS-ONLINE** [comment]
![capture](https://cloud.githubusercontent.com/assets/23016965/20455637/b2ad10a2-ae60-11e6-8c90-9181e4afeca7.PNG)

Solved!
