### ISSUE TITLE
Volunteer Dashboard  calendar text is hard to read. 

### ISSUE THREAD

**Issue by schuback** [HTBox/allReady#1514]
<img width="922" alt="screenshot 2016-11-15 12 55 01" src="https://cloud.githubusercontent.com/assets/830036/20375697/c4c773ae-ac4e-11e6-834f-0f43b80ac3e8.png">

**Comment by tonysurma** [comment]
For this issue would need to look at both layout/font size as well as colors

**Comment by stefan-van-de-griendt-centric** [comment]
Picking this one

**Comment by stefan-van-de-griendt-centric** [comment]
Was already fixed.
![image](https://cloud.githubusercontent.com/assets/23572640/20455845/cceee1e8-ae65-11e6-84e0-e3ac303d56e1.png)

**Comment by EmilyLuijbregts** [comment]
@tonysurma can this issue be closed?

**Comment by tonysurma** [comment]
why yes it can.
