### ISSUE TITLE
Auto fill event address in task creation process

### ISSUE THREAD

**Issue by schuback** [HTBox/allReady#1515]
While creating an event, being able to quickly put in the event address in from main page would be great.  Having to put in the address  for all the events can be time consuming if the event is at the same single location.  Could it auto grab the event address as a default for every task under that event unless changed at that time?

**Comment by tonysurma** [comment]
What does 'from main page' in event creation refer to? Campaign Address?
Also it sounds like their is a requirement to default address of event from campaign and task from campaign?
Is that right @schuback @OhMcGoo ? If so seperate issues can be created for both

**Comment by stevejgordon** [comment]
This functionality now exists
