### ISSUE TITLE
Include more data in volunteers grid on tasks (currently only name)

### ISSUE THREAD

**Issue by schuback** [HTBox/allReady#1520]
Going in to a tasking page and seeing the volunteers who have signed up, the admin for the org should be able to see the name, address, phone, certifications and email of the volunteers.
<img width="986" alt="screenshot 2016-11-15 21 45 40" src="https://cloud.githubusercontent.com/assets/830036/20375879/fc1fb784-ac4f-11e6-8aed-9c5a930855ed.png">

**Comment by tonysurma** [comment]
should add additional fields to the grid that should already be surfaced int the volunteer data so primarily a UI update

**Comment by DanielSchiavini** [comment]
I'm gonna try to fix this one

**Comment by DanielSchiavini** [comment]
@tonysurma I assume that certifications are the skills that the user can fill in. The address field doesn't exist in the user model and I couldn't find a page where the user would be able to fill it in, so I assume it doesn't exist and that would be out of the scope for a jump-in issue. I'll add all fields except the address to the model and UI.

**Comment by DanielSchiavini** [comment]
PR #1531

**Comment by BillWagner** [comment]
Closed in PR #1531
