### ISSUE TITLE
Change phone number to mobile phone number when gathered on user registration screens

### ISSUE THREAD

**Issue by schuback** [HTBox/allReady#1521]
User page needs to change "phone number" to "mobile phone number" and put in the line about cost for SMS and using this service.

**Comment by tonysurma** [comment]
@schuback @OhMcGoo can you provide the text for the cost of SMS we should add?

**Comment by bmaluijb** [comment]
I'll take this one

**Comment by BillWagner** [comment]
Fixed in PR #1529
