### ISSUE TITLE
Can't add task in a pre existing campaign

### ISSUE THREAD

**Issue by schuback** [HTBox/allReady#1523]

**Comment by mgmccarthy** [comment]
@schuback can yo list reproduction steps and screen grabs/videos to get us more information?

**Comment by EmilyLuijbregts** [comment]
@schuback - are you able to provide the reproduction steps as requested by @mgmccarthy or do you need further support in reproducing it?

**Comment by tonysurma** [comment]
@schuback pinging back in.  thanks

**Comment by mgmccarthy** [comment]
cc @tonysurma @EmilyLuijbregts 

@schuback, is the reason you cannot add a task to an existing Campaign b/c of this newly opened Issue/bug?

Issue #1645

I'm only asking, b/c when I create a new Campaign, new Event, then add a Task to that Event, it works:

![image](https://cloud.githubusercontent.com/assets/2428993/21290681/f6d0338a-c491-11e6-8916-eed26286939a.png)

**Comment by tonysurma** [comment]
@schuback please help with repro steps as I am unsure of the issue steps and our testing shows it working so either still an issue or got 'fixed' by something else.  thanks

**Comment by MisterJames** [comment]
Closing as retro/scoped-out.
