### ISSUE TITLE
Edit Itinerary - Start Address Not Saved Correctly

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1569]
**Steps to Reproduce:**

1. Create an itinerary
2. Edit the itinerary and provide a start address, tick the use start address as end address checkbox
3. Save the itinerary
4. Edit the itinerary and untick the use start address as end address checkbox
5. Edit the end address
6. Save the itinerary

**Expected behaviour:** Start Address will remain unchanged, End Address will have been saved, use start address as end address checkbox will not be ticked

**Actual behaviour:** Start address is blank

**Comment by dchristensen** [comment]
I will take a look at this one.
