### ISSUE TITLE
Edit Itinerary - Enhance - Improve UX

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1575]
If the use start address as end address is checked we should hide the end address fields on the form.

**Comment by joro550** [comment]
Hey there, I was going to lok to do this, but it seems that this allready happens, someone at some point added some javascript at the bottom of the cshtml to allow this to happen, couple of points on this page though.

* Having the class "form-control" on the checkbox makes it really big on the screen but very difficult to click for me - not sure if this is just my browser though, I had to click the top edge of the box overwise it wouldn't see it as me clicking the box
* Information is mis-spelt on the page - small thing

I have a branch fixing these two smaller points, not sure if you want to fix the first issue or whether I should open a seperate card - I'll wait for feedback

**Comment by stevejgordon** [comment]
Hi @joro550. Thanks for taking a look at this. You are correct the show/address was closed in #1631. That was my mistake for not linking back to this original master issue.

I agree that the checkbox is a bit large so if you have code to improve that and the spelling error, please do submit those as a PR. Thanks for contributing.

**Comment by EmilyLuijbregts** [comment]
@joro550  - thanks for picking this one up! Just wanted to check in and see if you had any update? or if you needed any support?

**Comment by joro550** [comment]
@EmilyLuijbregts There was a pull request that was merged a few days ago #1575

**Comment by EmilyLuijbregts** [comment]
Great- thanks - i'll close this issue.
