### ISSUE TITLE
Question: Clarification of the Request Life-cycle

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1581]
@tonysurma @MisterJames @stevejgordon @dpaquette @OhMcGoo 

Currently, the Request life-cycle has had some changes made to it as a result of the implementation of confirmation messages going out to requestor's, and those requestor's either confirming or canceling the request (the Hangfire jobs run those scheduled sends based on the request status of each request added to an itinerary).

I wanted to sum up a couple current functionality points here as well as lay out what I perceive to be one problem with the current life-cyle that is affected by the source of the request (UI vs. API/CSV)

- I want to confirm that ALL requests added to an itinerary, regardless of the source of the request (UI/API/CSV) require the confirmation message to go out to each requestor to either confirm or cancel the request. Currently, this is how the system works, but I'm not too sure if we want to send the sms confirmation messages to requestor's that were added via the UI.

Regarding the request life cycle, this is where I think we have a glitch and need to make a decision:

- request created -> `Unassigned`
- assign request to itinerary via UI -> `Assigned`
- when request is `Assigned` we publish `RequestsAssignedToItinerary` from `AddRequestsToItineraryCommandHandler`, which set the status to -> `PendingConfirmation` and then sends out sms confirmation messages

**this is where the problem is:**
- when requestor confirms the request via sms the request status is set to -> `Confirmed`
- BUT when request is `PendingConfirmation` on UI, you can move it immediately to `Completed`, skipping the `Confirmed` status.

If all requests that are added to an itinerary need to be `Confirmed` regardless of the source of the request, then the UI needs to be updated to not allow a request that is `PendingConfirmation` to be moved to `Completed`. 

The UI should be updated to move a `Confirmed` request to `Completed`.

The request cannot be `Confirmed` until the requestor confirms the request via sms.

**Comment by mgmccarthy** [comment]
ping @tonysurma @MisterJames @stevejgordon @dpaquette @OhMcGoo...

can you please get back to me on the questions/problems I outlined above in the Request lifecycle as it pertains to sms messages to requestors as well as status lifecycle of a request?

**Comment by mgmccarthy** [comment]
ping @tonysurma @MisterJames @OhMcGoo...

still waiting to hear back about request life-cycle as it relates to sms confirmation messages being sent to requestors, regardless of the Request source...

**Comment by mgmccarthy** [comment]
@tonysurma please assign to me, and I will need to eventually discuss this with someone. Thanks!

**Comment by tonysurma** [comment]
I am working on getting you an answer.  @cecilia-donnelly

**Comment by mgmccarthy** [comment]
@tonysurma, yes to the above.

basically, two things:

1. I want to confirm (this is existing functionality) that all Requests (regardless or origin) will follow the same "life-cycle" that they do now. This involves a request being assigned to an Itinerary. Once the assignment happens, we send sms confirmation messages to those requestors to confirm or cancel the request (per your comment above "confirm that 12/17 will work for you for an install") regardless if the origin of the Request

2. I need feedback that my proposed fix for Requests originating from the UI is correct... that we do **not** allow a UI Request to move from `PendingConfirmation` to `Completed`. The Request first needs to move to `Confirmed` (via the requestor sms messaging us back confirming date of install, please see #1 above). The UI should be updated to only allow moving a `Confirmed` request to `Completed`.

**Comment by tonysurma** [comment]
For (1) - yes that is true.  Date scheduling is fully within the app and so is the confirmation regardless of source

For (2) I need to walk that through in my head.  But current thinking is that you should as an admin be able to move from pendingconfirm to confirmed if you get confirmation via another means from the requestor.  But not directly to completed

**Comment by mgmccarthy** [comment]
@tonysurma 

> For (2) I need to walk that through in my head. But current thinking is that you should as an admin be able to move from pendingconfirm to confirmed if you get confirmation via another means from the requestor. But not directly to completed

I believe my code already handles this. For each Hangfire job handler, I query Requests based on the request Id's that were initially added to the Itinerary. If any of those Request Id's do NOT have a status of `PendingConfirmation`, then they are not included in the outgoing confirmation sms messages...

so, in theory, a requestor could get the first sms confirmation message, never reply confirm/cancel back to us, but the Request on the UI could be moved from `PendingConfirmation` directly to `Completed`, and this would disclude them from the rest of the sms confirmation pipeline.

That being said, it sounds like we might be able to close this Issue without any type of impact to the code. As long as we're sure that we want to allow the UI to be able to override/circumvent the requestor needing to respond to AllReady to confirm or cancel their request.

**Comment by tonysurma** [comment]
agree @mgmccarthy closing per current codebase
