### ISSUE TITLE
Claims are not working on the Site Admin menu...

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1584]
When going to the Site Admin menu option under Admin:
![image](https://cloud.githubusercontent.com/assets/2428993/20755532/4ecc7534-b6dd-11e6-81f3-865943e324cb.png)

Claims are not working correctly as any user can see all of the action icons, when each action icon is controller explicitly by claims:
![image](https://cloud.githubusercontent.com/assets/2428993/20755565/6ef650c8-b6dd-11e6-805c-a206e80c7f3a.png)

This used to work, as is outlined in PR #964 (which has been merged)

Currently, the list of claims for a user is coming back as empty after logging on... we need someone to investigate why this is happening.

**Comment by tonysurma** [comment]
@YannickMeeus (I am feeling deja vu so if I already asked I apologize) but is this fixed/better/same with your latest PR that moved this to a modal?

**Comment by YannickMeeus** [comment]
@tonysurma I didn't change how the claims based access works, I only changed content and rejigged layout, so if this was a bug prior to my PR, it'll still be an issue.

**Comment by tonysurma** [comment]
thanks @YannickMeeus I will keep it open

**Comment by dchristensen** [comment]
I've fixed this issue (via #1649), however with the claims working its much easier to see an issue with the new buttons in the modal.  

The "Edit" button is only ever opening for the first entry in the User list, so it is impossible to make any changes to any of the other users.  Not sure this needs to go into a new issue or re-open #1635.  This issue exists on the current production systems.

/cc @YannickMeeus

**Comment by YannickMeeus** [comment]
Having a look at this now.

**Comment by YannickMeeus** [comment]
@tonysurma @dchristensen I've got a fix for this ready, which issue do we want this fix against?

**Comment by tonysurma** [comment]
For speed go against this issue and we will close once the fix is on
