### ISSUE TITLE
Add page to display public request details

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1585]
Breakout from #704

Add a simple page which displays a request's status and (if available) planned deployment date.
No private info (names or addresses etc) should be shown on this page.

**Comment by HamidMosalla** [comment]
@stevejgordon Can you be more specific about the requirement?

**Comment by pmarshallandrew** [comment]
WIP

**Comment by tonysurma** [comment]
@pmarshallandrew anything we can do to help you as you work on this cc @stevejgordon

**Comment by stevejgordon** [comment]
@tonysurma - I know @pmarshallandrew is on vacation until the NDC London code-a-thon event. I also know he'd made some progress with this. I'm happy to jump in and resolve this issue if you think it will be needed before NDC London? If not @pmarshallandrew is joining me there so could finish off at that point?

**Comment by pmarshallandrew** [comment]
Picking this back up today after coming back off holiday.
