### ISSUE TITLE
Token Protection Middleware generated token is not recognized on post back to endpoint

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1586]
When invoking an endpoint in our system (any controller's action method with the `[Route("api/request")]` attribute), the code invoked by the filter, `TokenProtectedResource`, is not recognizing a token that was issued from the site admin page:

![image](https://cloud.githubusercontent.com/assets/2428993/20755758/24ac6f38-b6de-11e6-8f6b-17297c43fd3c.png)

The token by first enabling the API token functionality:
![image](https://cloud.githubusercontent.com/assets/2428993/20755789/3b764d42-b6de-11e6-937b-abced1355d47.png)

and then clicking the key icon to assign a token:
![image](https://cloud.githubusercontent.com/assets/2428993/20755812/50367a0e-b6de-11e6-8c3e-f0b855255540.png)

more information about how to generate this token is in PR #964.

To test this, the developer should
- create a new Controller and decorate that controller's action method with `[Route("api/request")]` and decorate the action method with `[HttpPost]` and [HttpPost]`
- log in, generate a token for one of the users (preferably, the user you will be using to test this)
- once the token has been generated, copy that information down
- using [Postman](https://www.getpostman.com/), put together an http POST to the newly created endpoint and put both the `ApiUser` and `ApiToken` key/values into the Http headers. The user should be the username for which you generated the token, and the ApiToken shoudl be the value that was shown to you when you generated a token for that user
- set a breakpoint in the `Invoke` method in `TokenProtectedResource`, then send the http post request to the endopint via Postman
- note when `VerifyUserTokenAsync` is called, it returns false for authorized. The exception it's throwing is `Microsoft.AspNetCore.Identity.UserManager: Warning: VerifyUserTokenAsync() failed with purpose: api-request-injest for user d2964736-5e52-473c-b3b5-e56ade40f227.` The userid will change based on which user you've added the token to

**Comment by mgmccarthy** [comment]
@tonysurma, can you assign to @MisterJames? I think he's looking into this now.

**Comment by EmilyLuijbregts** [comment]
@MisterJames - just wanted to check in on this task and see how you were getting on? Do you have an update?

**Comment by mgmccarthy** [comment]
@MisterJames, did you ever get a chance to figure this out? We need the tokens working for the v1 release to handle incoming GASA Requests.

**Comment by EmilyLuijbregts** [comment]
@MisterJames - Just checking in as this is a P1 bug. Any chance you could give us an update?

**Comment by BillWagner** [comment]
@MisterJames We've got someone here in London at the NDC event who is starting to look at this. Can you add a comment with any progress to date?  /cc @recumbent
