### ISSUE TITLE
When creating a Request from the Event Details page, we should pre-populate the Request's city/state/zip values with the values from the Event as read-only fields on the Request creation UI

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1587]
@tonysurma @stevejgordon @MisterJames @dpaquette @OhMcGoo 

When creating a Request via the UI, you do so in the context of an Event:

![image](https://cloud.githubusercontent.com/assets/2428993/20768937/dc9efc12-b70d-11e6-8fa4-b000929979ad.png)

Since every Request has an EventId/Event property that needs to be populated to associate a Request with an Event in order for the ~~Event~~ Request to be assigned to an Itinerary, would it make more sense to pre-populate the Create Request page with the City, State and Zip from the Event?

![image](https://cloud.githubusercontent.com/assets/2428993/20769038/44a7f570-b70e-11e6-956b-ef817f57a17e.png)

Here you can see the user can enter any City/State/Zip value they want. The problem with this approach is ~~we can only see Requests that are associated with an Event in the Event Details page. This is how Requests get assigned to Itineraries.~~ users could create a Request outside the "serviceable" area of the Event. So although the Request is associated with the Event, the Request could be outside the serviceable area of the Event, which will pose a problem when a Request is added to an Itinerary.

I would also assume we want our Requests created to be aligned with the Event's city/state/zip so we know when that Request is added to an Event's Itinerary, it can be serviced b/c it's in the serviceable area of the event.

So, these fields should really not be assignable at all, but instead appear as read-only on the Create Request page and the information should be copied from the Event in which the Request creation is taking place.

Thoughts?

**Comment by stevejgordon** [comment]
@mgmccarthy The request in our domain represents an install location. So I can request a smoke alarm at my home address. That is the address which is stored as part of the request. If you then made a request you would have your address stored there.

This most commonly will happen via API calls from getasmokealarm We'll need to assign those to an event based on whatever rule set we apply. The next option is CSV import which is more a backup that a main input method as I understand it.

For the manual request creation (which is a final fallback more than anything else and I suspect will be rarely used) we set the EventId on the request to match the event from which the Create Request button was clicked. So it will always be set to the correct event. In the screenshot you can see the correct event is set already.

I agree we might end up with orphaned requests from API or CSV depending on how we determine we should handle those and map them to events.

There's also the possibility that we end up with requests, linked to an event but which fall outside of that event's intended service area. In that case an Admin would probably just cancel the request.

I'm not sure how Zip codes work in the US but is it not possible that multiple zip codes will be covered by one event across say a large city? In the UK at least our postal codes are very specific so requests on different streets next to each other could and usually will have a distinct code.

Not sure if I've interested your query correctly but hopefully that answers the query?

**Comment by mgmccarthy** [comment]
@stevejgordon, thanks for the feedback. I'm looking over what i initially wrote, and it's wrong (most of which you picked up in your reply to me). I wrote it in a hurry, so I made mistakes. I just corrected it. I'll weigh in on the other things you mentioned in your reply as well when I get to work.

Thanks

**Comment by tonysurma** [comment]
> For this issue, the problem still remains that when creating a Request via the UI, we're allowing a user to enter city/state/zip, and all that information could be outside the serviceable area of the Event. If this Request gets added to an Event's Itinerary, then we could essentially be sending out sms confirmation messages to a requestor that is in a completely different state than the Event.

@mgmccarthy that concern isn't a concern from a user/UI/requirements perspective.  All of that data is and should be enterable by the user.  Even for our current use case for the initial roll out, we can't model restrictions that may or may not exist as it gets super complicated.  For example, as @stevejgordon referred to zip code density is variable so in some areas it would be insane for it to be another zip code but in others it is very likely several zip codes could be in same itinerary.  Same goes for even state boundaries as those can be arbitrary and one part of a neighborhood is in MO and the other is in IL etc.

For that reason I am going to close this issue as we don't need to make this change from a requirements perspective but great discussion and glad we are closing out all these types of areas as we get closer to release.

That being said we definitely need to get some ideas from @OhMcGoo @schuback on how to map the requests coming in to events as that is not a logical process (aka if a to b then goto event X) and more based on delivery and organizational structure of the red cross's work on this campaign.

**Comment by stevejgordon** [comment]
@mgmccarthy 

In terms of the csv and manual creation being backups, I will defer to @tonysurma but I think the goal is for things to come in via the API in most cases. If that's not ready at go live I believe csv is a fallback. I would assume this remains true for any other organizations/campaigns as they come online since there could be integration work that means csv is needed.

For the issue at hand here. It will only be an org admin (or perhaps site admin) creating the requests so the assumption is that they will only add requests they intend to service. Presumably only test requests and perhaps in cases where they have manually signed up people. Therefore I don't think there's a major risk here. If the org admin puts in a request outside of their area then I'm not sure how we can validate that directly. Unless we havea set of geocoded points representing the area for an event which we can compare the location against.

**Comment by tonysurma** [comment]
@stevejgordon also to validate you are right that manual entry is kinda last stop/last resort.  PRimarily there for testing and secondarily there for some random ad-hoc add a request but otherwise GASA API is primary as you said and CSV is secondary.

**Comment by mgmccarthy** [comment]
@stevejgordon @tonysurma thanks guy! I do feel more informed about how the system should be working from the conversation above... especially the comments about zip code density.

that being said, we'll still need to tackle the task of assigning a Request to an Event when we create a request (from API/CSV)

One idea is to NOT associate a Request to an Event for the API/CSV imports. If this were done, we would need a way to still which Requests could be a potential match for adding to an Itinerary based on zip code/zip code density/ regions etc...

We would need to update our current UI to pull back all Requests based on zip code that could be eligible for that particular Event/Itinerary.

that way, we're not not forcing an Event to a Request association until the Request is ready to be acted on (aka, ready to be assigned to an Itinerary)

**Comment by tonysurma** [comment]
@mgmccarthy interesting idea and then have the admin also have an 'associate' request just like the create request on the event.  We could at least dump the requests under the organization at ingestion then so that Tony Org can't see requests that came in to Steve Org for example.

Should we continue discussion here and change name (again 😸 ) or move to another issue?

**Comment by stevejgordon** [comment]
@tonysurma Sounds sensible to have somewhere we can view "orphaned" requests. We could have a few issues and possibly address this at the code-a-thon. Something like

- Add Org level page (or maybe campaign level if we can at least determine campaign via API) to list requests without an event id set
- Clicking on a request displays a page/modal allowing an campaign and event to be set

If that sounds reasonable I can break out some issues along those lines

For CSV as it's a manual process to import I presume on the import screen we can/or should be able to choose the event we're importing under? With the assumption that data is validated by the admin prior to importing?

**Comment by mgmccarthy** [comment]
the discussion about not associating an incoming Request with an Event has been broken out into Issue #1591

**Comment by mgmccarthy** [comment]
@tonysurma @stevejgordon @MisterJames I've broken this issue out into #1591. We can track convos/decisions there. Thanks!
