### ISSUE TITLE
Possible forgery of campain.ManagingTenantId

### ISSUE THREAD

**Issue by rynowak** [HTBox/allReady#159]
This check is used in several places in the app for determining if the current user is allowed to administrate a given campaign:

```
        public async Task<IActionResult> Edit(Campaign campaign)
        {
            if (campaign == null)
            {
                return HttpBadRequest();
            }

            if (!User.IsTenantAdmin(campaign.ManagingTenantId))
            {
                return HttpUnauthorized();
            }

            ...
        }        
```

`campaign` is populated from model binding, and would allow a malicious user to specify `ManagingTenantId`. A more secure approach would be to retrieve the `ManagingTenantId` from the DB (based on `campaign.Id`) to verify privileges.

I'd also recommend using `[BindNever]` or similar on the model to disallow binding this field from user input.

**Comment by ksk100** [comment]
I'll take this if no one else is working on it, and it doesn't clash with other work being done.

**Comment by dpaquette** [comment]
We are working in this area so best to hold off for now.

**Comment by ksk100** [comment]
Okay
