### ISSUE TITLE
Request CSV Import creates Requests in the system with no associated Event.

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1590]
Need project/product owner feedback on this issue: cc @tonysurma @MisterJames @OhMcGoo 

We want to make sure when adding a Request to the Request table, that we're associating an Event to the Request.

Request's w/out an associated Event will appear "orphaned" to our UI that is responsible for assigning Requests to Itineraries.

Most likely, the same lookup mechanism that will be used to match incoming Requests from our API to Events could be used for this import as well.

**Comment by tonysurma** [comment]
Yes @mgmccarthy same rules as API ingestion should be used for CSV ingestion

**Comment by mgmccarthy** [comment]
@tonysurma, don't know if you have any time to chat about how we make the association with Request to Event, but regardless of if we use the zip code or somehow use the region (which we would need to figure out how to represent in our system), but it would probably help me sumbmit something that makes sense.

Maybe pulling @MisterJames in on the convo would help... Skype (in person would be best), but we could always use Slack as well

**Comment by tonysurma** [comment]
paging @OhMcGoo and @schuback as we need to get the red cross view of how to do this assignment (how do we map a request from get a smoke alarm) to the right region/event/etc. in our system.  What happens now with GetASmokeAlarm.org for instance - how do they get from their system to the right folks at ARC?  Maybe they can duplicate that for us and we can just map regions to events or something...

**Comment by MisterJames** [comment]
@mgmccarthy @tonysurma I'm not sure that I'm opposed to orphaned requests, but there are two ways that come to mind immediately to solve this.

1) If we decide that orphaned requests are okay, we simply display a warning/alert at the top of every event page (for admins) and prompt them to "assign" the requests to the event. This could be done via a list with a filter set at the top/selection. This would be more work, but might allow finer-grained control.
2) If we prefer direct assignment, we could add an event drop down as part of the CSV import process. This would be trivial but would mean that all requests would have the same event assignment (which is likely okay).

**Comment by stevejgordon** [comment]
@MisterJames +1 to option 2

**Comment by tonysurma** [comment]
Option 2 works for CSV but not API but like it.  It can even be optional.

for option 1 we can have orphan (but at least tagged to org per comment above/somewhere else) and I think we can do a variation of it where the Steve's create request buttons appear.

**Comment by mgmccarthy** [comment]
the discussion about not associating an incoming Request with an Event has been broken out into Issue #1591

**Comment by mgmccarthy** [comment]
@MisterJames @tonysurma @stevejgordon, I'm going to pick up the work on Request CSV Import. 

To sum up, I'll be adding an Event drop-down to the UI which will allow a user to associate this "batch" of incoming requests with a given Event.

Unless the decision is to also funnel the CSV Import to the "orphaned Requests" Organization page and then let he user associate that Request with an Event for that org?

I don't see any input on this issue or Issue #1591 about what the final decision is.

**Comment by mgmccarthy** [comment]
@MisterJames @tonysurma @OhMcGoo since I'm pickup up work on this, I'm assuming:

1. this is an all-or-nothing operation. If one or more rows of the import fails, the entire import fails
2. the CSV import handles new requests only (inserts)

please "yay" or "nay" this.

**Comment by tonysurma** [comment]
1.) going to rely on @MisterJames thoughts but I think the answer is 'yay'
2.) yay

is that how it was implemented in #1641 and other PRs? can we close this or is there more work?  thanks for the help clarifying

**Comment by mgmccarthy** [comment]
I broke out the parts of this Issue surround the CSV import only to Issue#1654
