### ISSUE TITLE
Add OrganizationId to the EF Request Model (Step 1)

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1595]
Breakout requirement from the master discussion #1591

STEP 1

For v1 release we have agreed that on creation/import each request will be assigned an organization id to link it to an allReady Organization (i.e. Red Cross).

We need the model updating and a migration created to add this property and a foreign key back to the Organization.

**Comment by stevejgordon** [comment]
We'll hopefully tackle this during our code-a-thon on Monday 5th

**Comment by chris-sargood** [comment]
Work in progress
