### ISSUE TITLE
Add Org Level Page To List Requests (Step 2)

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1596]
Breakout requirement from the master discussion #1591

STEP 2 - After #1595 is merged

We need an admin page that can be accessed from the organization admin homepage/dashboard via a link. This page will list any requests which have an org id matching that organization and where there is no event id currently set.

- Add a view and action for the request lister
- Add a Mediatr query message and handler to get the required view model for the page
- Add a link from the Org homepage which links to this new page. Ideally include the count of unlinked requests so an admin knows there are requests to link.

**Comment by chris-sargood** [comment]
WIP

**Comment by stevejgordon** [comment]
@tonysurma @MisterJames  - We have a quick query on this. @chris-sargood has made good progress with an initial page to list the requests which currently he's added via a link on the Org details page (admin area).

However, currently that page is only accessed by SiteAdmins (in fact all Org admin pages are only open to the site admins). Therefore we need to work out the best controller to locate this action on, and where to present the link to an Org Admin so that they can access their unlinked requests.

One option would be to make modifications to the Org admin area so that an Org admin can access their Org Details page (view only). This is not too complex but would require changes to the flow from the lister onwards including the checks to ensure org admins only see their org's data. 

Another would be to put the unlinked request lister on it's own controller and route, and find somewhere sensible to locate a URL for the Org Admin for now. For v1 it might be best to go with this as the quickest option and just add a link from the menu for org admins which just takes them to unlinked requests. However this might be confusing as it's not all requests. Any linked requests would be managed via the Itinerary level admin pages.

Thoughts?

cc @mgmccarthy

**Comment by mgmccarthy** [comment]
@stevejgordon, I vote for this option:

>  to put the unlinked request lister on it's own controller and route, and find somewhere sensible to locate a URL for the Org Admin for now.

we should be aiming for smaller controllers in general, and I think this would be fine for something to keep around post v1. Thanks for bringing the question up.

**Comment by tonysurma** [comment]
agree with @mgmccarthy own controller and lets make sure org admins can access.  thanks

**Comment by stevejgordon** [comment]
@tonysurma @mgmccarthy - Sounds good to me.

@chris-sargood Can you make a new controller with the relevant action to handle the route /Admin/UnlinkedRequests. This can be the same code (I think) as you showed me yesterday. We just need to ensure requests are filtered only to those for the Org id of the user (if an org admin). I can't remember your code 100%, you might already have that!).

Recommend for now that we add an item to the menu for Org admins called "Unlinked Requests"

![image](https://cloud.githubusercontent.com/assets/3669103/21049603/c38cfc72-be0d-11e6-807b-4ef76fd9051e.png)

Let me know if you have any questions or need a hand/code review? If you tackle it over the weekend and want eyes on it, feel free to drop in a WIP PR and mention me in the comment.

@tonysurma - This would solve the requirement for Org admins specifically. We might want to extend the requirement to later update this so that Site Admins can view all requests (from any org) and assign them to events. However this does complicate the logic a little for the assignment step, so might be a good future enhancement once we have this first part working?

**Comment by tonysurma** [comment]
Looks good @stevejgordon @chris-sargood 

@stevejgordon for that last bit we can toss an issue in the feature backlog to not lose track of it

**Comment by chris-sargood** [comment]
@stevejgordon 
Sorry for the delay on this. Pretty much there now I think. Will be submitting a pull request tomorrow.

**Comment by stevejgordon** [comment]
Thanks @chris-sargood

**Comment by tonysurma** [comment]
thanks as well @chris-sargood @stevejgordon anything we can do to help get the PR in?
