### ISSUE TITLE
Organization Request List - Assign One or More Requests to an Event (Step 3)

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1597]
Breakout requirement from the master discussion #1591

STEP 3 - After #1596 is merged

From the "unlinked" Request lister each request should have a checkbox against it. One or more requests can be checked. A button should be available to "link request(s)" which will open a model. Inside the modal a campaign and event (or maybe just event for v1) can be selected. Clicking continue, will update all selected requests with the relevant Event Id

Note: Wording might need to change here. @tonysurma Any preference of what we call a request that has an org but no event? We already use the term unassigned to designate requests under an event which are not in an itinerary. Might be confusing to use it twice?

- UI work to include checkboxes, button and modal
- Controller action to handle the POST event on submiting the event assignment
- Mediatr message and handler which is called from the action to update the records in the DB
- Redirect back to the lister page

**Comment by tonysurma** [comment]
@stevejgordon what is unassigned used for already?

**Comment by stevejgordon** [comment]
@tonysurma We use assigned/unassigned as language to identity whether a request is assigned (or not) to an itinerary.

I think we said we use linked/unlinked for whether a request is linked (or not) to an event.

I think we also suggested a request could be optionally associated (or not) to a campaign as well.

**Comment by tonysurma** [comment]
agree with @stevejgordon 

all requests belong to an org so no need for a word there (aka one cannot exist without org assignment)

requests are then linked/unlinked to events

requests are then assigned/unassigned to an itinerary.

no words needed for campaign because the link is direct to event.

Thanks!

**Comment by stevejgordon** [comment]
@tonysurma just to clarify on:

> all requests belong to an org so no need for a word there (aka one cannot exist without org assignment)

If we manually create a request via the UI it is linked to an event. This means we can navigate to the original Org via event > campaign > org, but in the db we don't assign an Org Id value (it's null).

On the API we currently hard code the Org ID to 1 for v1 and Red Cross. This is because we don't know the event to link them to.

On the CSV you can now select the event to add them to. Again as with manual requests these don't have their Org Id set in the DB but we can navigate through the layers to find the Org.

We used the Org Id only for API as a means to associate the request to the Org which we can work out from the API token. So you're correct that all requests belong to an Org in the system. The means to navigate to the Org do differ. We could solve this by ensuring we always set the Org ID from the API and Manual UI process also? At least then we have consistency. If you agree, I can open a couple of small issues to cover this.

**Comment by tonysurma** [comment]
I don't see a reason not to do it and I like it for consistency.  Let's add then.  Thanks

**Comment by stevejgordon** [comment]
@tonysurma - Added #1667

**Comment by chris-sargood** [comment]
@tonysurma @stevejgordon 

Could one of you assign this issue to me and I'll pick it up?

**Comment by tonysurma** [comment]
Done and thanks!
