### ISSUE TITLE
As an administrator, I want to be able to define actionable items for a given campaign, so people can volunteer for those items

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#16]
This needs to be fully documented out and split into multiple enhancement issues for what is not yet implemented fully.

This user story covers both the definition of activities and tasks. 

Each campaign is split into a set of activities that are tied to a certain geographical location. Each activity, in turn, is split into a set of tasks that the administrator can assign to volunteer that have applied for the activity.

**Comment by dpaquette** [comment]
I am going to start looking in to the 'Activities' portion of this. Any additional information you can provide @tonysurma

**Comment by dpaquette** [comment]
I'm working on the Create / Edit Activities views right now. Currently, we have a single page that lists out all Activities for all Campaigns and all Organizations. From a UX perspective, this seems a little clumsy. I would expect that a user would start by selecting a particular Campaign before trying to Create or Edit an activity. 

I propose removing the page that lists *all* activities and move the Create / Edit actions to an Admin Campaign Details page.

Would like some feedback from @tonysurma and/or @BillWagner before proceeding.

**Comment by tonysurma** [comment]
@dpaquette absolutely right.  CRUD of activities is scoped within an organization and tasks within activities for that matter.

A logical example that is made up is like this:
Organization A has a campaign to lessen the impact of fire related disasters in individual homes.  They run 3 activities: an awareness fair/booth/whatever on a given set of days at a given spot, a canvassing activity to get to all the homes in neighborhood N and see who needs/wants smoke dectors, and an activity to install smoke dectectors in that home.  In the last example there will be tasks for sets of days and locations for installs.  Volunteers can volunteer for activities and then admins can assign them to individual tasks or admins can directly assign (which is really a request for assignment as a volunteer can of course say no) volunteers to tasks as they may already have awareness of different volunteers and which tasks are most likely good for them.

**Comment by dpaquette** [comment]
Okay great. I will start by scoping activities to a particular campaign. Once that is done we can tackle scoping tasks to a particular activity instead of a single list of all tasks.

**Comment by dpaquette** [comment]
Taking a look at Task Admin now

**Comment by dpaquette** [comment]
I have some ideas for restructuring the admin pages a little for better flow. Rather than having a grid of Campaigns with all the actions at the end, I am envisioning a grid of campaigns where you click on the campaign to see the details. From that details page you would see all the details and a list of Activities. You would then be presented with options to Edit the details, Add Activities, etc.  The same approach would be used for Activities and Tasks.  

Looking for some feedback before I get too far along on this. What do people think? This is pretty rough but should show the concept at least. Does this make sense to people?

![Campaign List](https://cloud.githubusercontent.com/assets/2531875/10953212/c3f347fa-82fb-11e5-998a-da1e65e0c8ca.png)

![Campaign Details](https://cloud.githubusercontent.com/assets/2531875/10953262/05396352-82fc-11e5-9426-caecd542c26b.png)

**Comment by dpaquette** [comment]
Looking at the screenshots I think it might also make sense to move the delete action out of the grids and on to the Details pages.

**Comment by dpaquette** [comment]
Pinging @tonysurma and @BillWagner for feedback

**Comment by bcbeatty** [comment]
Are we worrying about mobile experience for this? A delete could be a swipe-left.
Clicking on the name could goto detail
A swipe right could be give you additional actions.
Apple's mail app follows this flow, Google's Inbox is similar

**Comment by dpaquette** [comment]
@bcbeatty That would be pretty cool. Maybe for a the next version? I'm not sure we can pull that off for the November MVP

**Comment by BillWagner** [comment]
@dpaquette I like this. It does make the list view more-or less read-only. You would have to explicitly enter "edit" mode to start modifying items.

@tonysurma Thoughts?

**Comment by dpaquette** [comment]
Okay cool. I also added a breadcrumb which really helps with the navigation and visibility of 'where you are'.

**Comment by dpaquette** [comment]
Got this done for Campaigns and Activities.  Working on the Tasks section now.

Activity Details:
![Activity Details](https://github-cloud.s3.amazonaws.com/assets%2F2531875%2F10956958%2Fcbd78bfc-8314-11e5-9015-60c48179d338.png)

**Comment by mheggeseth** [comment]
I like it. Especially the addition of the breadcrumbs.

**Comment by tonysurma** [comment]
Like it a lot, this is not a list like email that has a lot of triage and deletes so moving it in detail is better

**Comment by dpaquette** [comment]
Cool, I will finish this off tonight then.

**Comment by bcbeatty** [comment]
I'm going to start on #162

**Comment by BillWagner** [comment]
@dpaquette I think this one is ready to close, in that any additional work is defined in #162 and #189. Please re-open if I'm wrong.
