### ISSUE TITLE
View Activities: Geo Location -- lookupAddress isn't always set when attempting to display map.

### ISSUE THREAD

**Issue by bcbeatty** [HTBox/allReady#160]
IE11 I sometimes gets a javascript error when attempting to display the map.
The lookupAddress is an empty address which causes the geocodeRequest return an empty result.resourceSets throwing a javascript error when attempting to read resourceSets[0].

As a work around I added to the getGeoCoordinates method in site.js for my next PR
    if (lookupAddress.trim() == "") {
        return;
    }

**Comment by tonysurma** [comment]
needs verification
