### ISSUE TITLE
Write unit test for GetMyEventsQueryHandler

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1603]
@stevejgordon, another one for your codeathon

**Comment by lhughesbrighton** [comment]
I'll pick this one up

**Comment by tonysurma** [comment]
@lhughesbrighton checking in to see if we can help at all?  Thanks for your contribution

**Comment by mgmccarthy** [comment]
ping @lhughesbrighton are you still working on this?

**Comment by NRKirby** [comment]
I'm new to this project & looking for a first issue to pick up.

I can't find `GetMyEventsQueryHandler` in the project? Could someone advise if this issue still needs a unit test & point me where if so?

**Comment by chinwobble** [comment]
@NRKirby If you open up the "AllReadyWebOnly" solution, you can find the `GetMyEventsQueryHandler` class under `Web/AllReady/Features/Volunteers/GetMyEventsQueryHandler`

where `Web` is the solution folder and `AllReady` is the c# project.

**Comment by NRKirby** [comment]
Thanks @chinwobble, I was indeed in the wrong project.

Just trying to fix a .NET Core error I'm getting & then I'll take a look at this...

**Comment by chinwobble** [comment]
@NRKirby have you installed the .net core v1.0.x LTE sdk https://go.microsoft.com/fwlink/?LinkID=836281
and the visual studio 2015 .net core tooling?

**Comment by NRKirby** [comment]
I had an old version..

FYI @shahiddev had the same error & pointed me to the correct source here: https://github.com/dotnet/cli/releases

**Comment by chinwobble** [comment]
@mgmccarthy I guess its okay on this since the assignee hasn't responded in a while?

**Comment by mgmccarthy** [comment]
@chinwobble, you guess what is ok? That @NRKirby works on this issue?

**Comment by NRKirby** [comment]
If you're happy for me to do so I would like to take this on....

A quick question: what format should the names of test classes take? Looking in the unit test project some end `Should` and some end `Tests`?

**Comment by mgmccarthy** [comment]
@NRKirby, any unit tests that are not controller unit tests should end in "Should"

**Comment by NRKirby** [comment]
Thanks @mgmccarthy  

I'm new to this project and just trying to fix some build errors- once I've done this I will try writing the test & submit a PR

**Comment by marigerr** [comment]
Hi, I noticed the comments on this issue were a few months old.  I created a test for this as a way to start learning about the project.  I can make pull request, if it's not being worked on otherwise?

@NRKirby , @mgmccarthy

**Comment by mgmccarthy** [comment]
@marigerr, please submit your PR.

**Comment by marigerr** [comment]
@mgmccarthy, okdoke thanks.  I submitted the PR.

**Comment by BillWagner** [comment]
Fixed in PR #2000
