### ISSUE TITLE
Homepage - Remove featured campaign from all campaigns list

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1608]
The latest UI code being added to list all campaigns under the featured campaign on the homepage requires a small view model change. We end up with the featured campaign appearing twice. We should ensure that the ActiveOrUpcomingCampaigns list is updated to remove the featured campaign on the view model.

Will be required after #1607 is merged.

**Comment by tonysurma** [comment]
#1670 has been merged

**Comment by YannickMeeus** [comment]
Quick question re this issue, is it possible for multiple campaigns to be featured at any given time? Or is there an implicit restriction on this? There are no explicit restrictions from what I can see but if the list of ActiveOrUpcomingCampaign is filtered, then all but the featured campaign with the lowest Id will be shown on screen, everything else is filtered out.

**Comment by tonysurma** [comment]
Logically there should be only one @YannickMeeus but you are right we don't have logic enforcing that.  Perhaps we can create a seperate issue for the technical backlog on that.

**Comment by YannickMeeus** [comment]
Fair enough, I'll try and apply the opposite predicate to the query that returns upcoming campaigns, instead of just filtering out every featured campaign. At least it'll be consistent that way.
