### ISSUE TITLE
Decide what status to report back to GASA Endpoint when API Request is assigned to an Org on import

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1609]
@tonysurma, please assign to me.

Issue created as a breakout from [this dicussion](https://github.com/HTBox/allReady/pull/1598#issuecomment-265218644).

> pending a discussion with cecilia-donnelly regarding my last comment on Issue 196 about what we can report back to GASA when we assign an API Request to an Organization. One possibility is: we return a false, then when we associate a Request to an Event, we invoke their endpoint again and return true. Problem is, I don't know if their code can handle this change in workflow. For now, the code in this PR invokes their API with a status of false when we import an API Request, and does not assign it to an Org nor associated it with an Event. I can easily change the code in a separate PR to assign an Org to the Request now that we have the OrgId/Org props on the Request model. Also, we're currently invoking their demo server, so nothing is for "real" yet as far as how this is wired up.

Ongoing conversation's with Cecilia will be tracked on [this GASA Issue](https://github.com/redcross/smoke-alarm-portal/issues/196) starting with [this comment](https://github.com/redcross/smoke-alarm-portal/issues/196#issuecomment-264457770).

This Issue will serve as a place to discuss the impact to AllReady code based on discussions about the GASA endpoint invocation based on [our decision to no longer associate an API Request to an Event on import](https://github.com/HTBox/allReady/issues/1591).

**Comment by mgmccarthy** [comment]
@tonysurma. just wanted to sum up the decision on this.

When an API Request is associated to an Org on import, we will set the acceptance flag to `true` on the call back to GASA's endpoint. This means we will service all requests on which we can validate the incoming token is legit, and the user that token belongs to is associated with an Org.

It is this OrgId we use for the association (fall-back plan is to hard-code for an Org is we can't get the token generation/validation working in time for v1)

**Comment by tonysurma** [comment]
@mgmccarthy yes with one tweak.

They supply a regionID and we need to also check that it is a region we support.  @OhMcGoo will give us the list of regions for when we go live and you can implement a function that is hardcoded to check for say regions 8 and 9 (or whatever) and then later we can replace updated that.  cc @MisterJames @stevejgordon who were in the conversation to add any additional notes

**Comment by tonysurma** [comment]
@mgmccarthy want to make sure we (including @OhMcGoo ) get you what ever you need to finish this

**Comment by mgmccarthy** [comment]
@TheTopher @OhMcGoo I just need the list of regions and that should do it

**Comment by mgmccarthy** [comment]
@tonysurma, FYI, this should be changed to v1

**Comment by mgmccarthy** [comment]
@tonysurma any update on that list of approved regions? It would be good to get that in the code now.

**Comment by EmilyLuijbregts** [comment]
@tonysurma - Would you have the time to look at the question from @mgmccarthy ? Thanks!

**Comment by tonysurma** [comment]
Thanks, we won't know this until we finalize who/where it is being used at deployment so maybe we can make it a config value @mgmccarthy ?

THanks

**Comment by mgmccarthy** [comment]
@tonysurma, I'll have to take a look at the code. I figured we'd just stick the approved region list directly into code, but sounds like we'll have to do some type of configuration work here.

**Comment by mgmccarthy** [comment]
Closing this b/c Issue #1699 is closed.
