### ISSUE TITLE
Question: Can we get rid of using IGeoCoder API to retrieve lat/long in ProcessApiRequests b/c incoming Request from GASA does not contain lat/long?

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1617]
@tonysurma @MisterJames @stevejgordon

**Comment by stevejgordon** [comment]
@mgmccarthy - Not sure I understand the question. If the GASA doesn't have the lat/long we need to call GeoCoding to get the data?

**Comment by mgmccarthy** [comment]
@stevejgordon, is the `IGeoCoder` abstraction "hiding" an RPC call to some type of web service? I'm assuming it is, but I don't know much about it.

**Comment by tonysurma** [comment]
@mgmccarthy - clarifying: does the incoming request from GASA include the lat/long or not?

**Comment by mgmccarthy** [comment]
@tonysurma the incoming request form GASA does NOT include lat/long. If we required lat/long on Request creation, it looks like the IGeoCoder call has to stay

**Comment by stevejgordon** [comment]
@mgmccarthy - I think IGeoCoder might wrap the bing API but I'd need to look to be sure. I think we might want to use Google API anyway going forward since we have to use Google for the routing stuff (Bing didn't provide an obvious optimize route type feature).

**Comment by mgmccarthy** [comment]
@tonysurma, this can be closed. I got the answer I needed. Thanks!
