### ISSUE TITLE
Question: Now that we've added a Published property to a Campaign, can someone tell me what the Locked property is for?

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1630]
@tonysurma @stevejgordon @MisterJames 

In Issue #1583 (which I'm currently doing a code review for in PR #1627), we've added a `Published` property to the `Campaign` model. From reading the issue, it looks like this change was made to allow a user to "front-load" the creation of Campaigns in the system without making those Campaigns available to "do anything" with yet...

But, there is also a property called `Locked`. Can someone please explain to me what is a Locked Campaign/what does it mean in the business sense to the system? Also, how does Locked affect Published, and vice-versa?

I'm opening this issue b/c I'm starting to see code like this on reads:
```
return _context.Campaigns
    .Include(x => x.ManagingOrganization)
    .Include(x => x.Events)
    .Include(x => x.ParticipatingOrganizations)
    .Where(c => !c.Locked && c.Published)
    .ToViewModel()
    .ToList();
```

**.Where(c => !c.Locked && c.Published)**

and I want to make sure we're not missing a higher-level business concept here, and I also want to make sure that a "Locked" Campaign is a valid business concept that is still applicable to the project.

Thanks!

**Comment by stevejgordon** [comment]
@mgmccarthy Locked was added as a way for a SiteAdmin to be able to block a campaign from the site. I think the likelihood of it being used is slim, but should a campaign be added that a SiteAdmin deems inappropriate, they can quickly lock it until the situation is resolved. I think we have some issues buried in the backlog around added a message to the OrgAdmin explaining the reason for a lock occurring etc.

Locked should therefore take precedence in all cases, a locked campaign should never be shown on the public facing part of the site.

**Comment by mgmccarthy** [comment]
@stevejgordon, exactly what I was looking for. Thanks!

**Comment by EmilyLuijbregts** [comment]
@mgmccarthy - are you happy to close this issue based upon the response from Stevejgordon?

**Comment by mgmccarthy** [comment]
@EmilyLuijbregts, yes. thanks.

**Comment by stevejgordon** [comment]
Closing per above

**Comment by mgmccarthy** [comment]
thanks @stevejgordon, I should have close this Issue myself, seeing how I'm the one that opened it ;)
