### ISSUE TITLE
Seeding Bug with all seeded Events

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1645]
Looks like the Event's start date time is after the event's end date time:
![image](https://cloud.githubusercontent.com/assets/2428993/21290649/f059b0b8-c490-11e6-977b-03fa214ff32d.png)

this should not be possible when creating an Event through the UI

Looks like this problem extends to all Events under all Campaigns for any seeded data.

**Comment by tonysurma** [comment]
@mgmccarthy the screen shot shows it going from Nov 2016 to Jan 2017 and that seems okay?  Am I reading wrong?

**Comment by mgmccarthy** [comment]
@tonysurma  LOL! that's the last time I open an Issue/bug at 11pm at night. Apparently, my eyes were playing tricks on me month/year...

I'm closing this as it's not an issue
