### ISSUE TITLE
Update which status a Request can be set to in an Itinerary on Itinerary Details UI

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1646]
cc @tonysurma @stevejgordon 

When importing a Request via the API and assigning the Request to an Itinerary, the Request is correctly set to `Pending Confirmation`
![image](https://cloud.githubusercontent.com/assets/2428993/21291418/c3795f3c-c4ac-11e6-863d-4d6e1412bfab.png)

the problem here is we want to allow the UI user to set the Request to Confirmed w/out relying on the requestor to confirm the request via sms. Currently we only allow the Request to move to `Incomplete`

We need to allow a Pending Confirmation Request to move to Confirmed or Incomplete via the UI

**Comment by mgmccarthy** [comment]
@tonysurma @stevejgordon 

this **might** need to be moved to P1 for now. If #1405 does not get finished (this is the sms response to confirm/cancel requests) in time for December release, then the only way to set a request from pending confirmation to confirmed will be this UI.

Thanks

**Comment by tonysurma** [comment]
good point @mgmccarthy

**Comment by joro550** [comment]
I was thinking of picking this up, I was wondering how you would like to achieve this, through buttons on the ui i.e. "Complete Request" (which alters the state), or a popup where we could have a drop down list of states to change to?

**Comment by mgmccarthy** [comment]
@tonysurma, unless we get a new icon that can represent `Set to Confirmed`, we might need to go with a drop-down approach on screens where a Request can move to more than one status, and a text approach where a Request can move to only one status. You can't really tell what the icons mean without mousing over them.

Here is a screen grab of Request that is in the PendingConfirmation state:
![image](https://cloud.githubusercontent.com/assets/2428993/21567002/9c57ceec-ce76-11e6-92fa-2f03067a1785.png)

We need to show two options here, the one already shown (set Request to Incomplete), and a new one, Set Request to Confirmed. We want to allow the UI to set a Request to Confirmed as a backup in case there is a problem with Requestor communication via sms confirmation messages

We have the following icons that represent the following Request status transitions:
- set Request to Incomplete: 
![image](https://cloud.githubusercontent.com/assets/2428993/21567011/aacf1214-ce76-11e6-8aa4-7b72572b93e7.png)

- set Request to Complete:
![image](https://cloud.githubusercontent.com/assets/2428993/21567086/68a3507a-ce77-11e6-987b-b7e687f430b2.png)

We need an icon to represent Set Request To Confirmed... OR we need to just show that text as a hyperlink which will clear up the ambiguity that using icons causes.

Thoughts?

**Comment by mgmccarthy** [comment]
@joro550, I'm going to make an executive decision here, and say let's stick with the icons for now until I hear back from the project owners.

The icon that should represent Set Request to Confirmed should be this icon from font awesome:
http://fontawesome.io/icon/thumbs-up/

make the background green. This can probably be accomplished using this code:

```
<button type="submit" class="btn btn-success submit-form" title="Mark this request as confirmed"><span class="fa fa-thumbs-up"></span></button>
```

the only time we should show the ability to mark the request as Confirmed is when the Request is currently PendingConfirmation.

Let me know if you have any questions. I'm not too sure how the conditional logic looks in the View, but I have a feeling you'll be making some changes there.

Thanks.

**Comment by tonysurma** [comment]
Totally support your exec decision! Thanks to you both

**Comment by joro550** [comment]
I must admit I'm a little confused, I'm going to lay out what I see the logic doing and hope someone can help me out a little.

When adding a request to an Itinerary item there is a button to mark the request as ```Incomplete``` however this seems to changed the status of the request to ```Assigned```, which changes the interface:
![assigned request](https://cloud.githubusercontent.com/assets/1705979/21620743/aed64d6c-d1ed-11e6-8153-f139e7d52a36.png)

As you can see this changes the button, now it is this icon from font awesome:
[http://fontawesome.io/icon/check/](url)

This button does as it suggests and changes the status of the request to complete:
![completedrequest](https://cloud.githubusercontent.com/assets/1705979/21620850/45e700e8-d1ee-11e6-97e6-c4adcee3b087.png)

I have two main questions about this:
* Is the "Reset this request to incomplete" functionality correct
* Have the requirements for the ability to change the request status to complete been met here

**Comment by mgmccarthy** [comment]
@joro550, you don't have to change any existing functionality, only add new functionality. The behavior you're seeing above is correct.

You'll need to add code like this to Areas\Admin\Views\Itinerary\Details.cshtml:
```
else if (request.Status == RequestStatus.PendingConfirmation)
{
    <form asp-action="MarkConfirmed" asp-controller="Itinerary" asp-area="Admin" asp-route-itineraryId="@Model.Id" asp-route-requestId="@request.Id" class="right-action-btn">
        <button type="submit" class="btn btn-success submit-form" title="Mark this request as confirmed"><span class="fa fa-thumbs-up"></span></button>
    </form>
    <form asp-action="MarkUnassigned" asp-controller="Itinerary" asp-area="Admin" asp-route-itineraryId="@Model.Id" asp-route-requestId="@request.Id" class="right-action-btn">
        <button type="submit" class="btn btn-danger submit-formm" title="Mark this request as unassigned"><span class="fa fa-ban"></span></button>
    </form>
}
```

in between this existing code:
```
@if (request.Status == RequestStatus.Assigned)
{
    <form asp-action="MarkComplete" asp-controller="Itinerary" asp-area="Admin" asp-route-itineraryId="@Model.Id" asp-route-requestId="@request.Id" class="right-action-btn">
        <button type="submit" class="btn btn-success submit-form" title="Mark this request as complete"><span class="fa fa-check"></span></button>
    </form>
}

[INSERT ELSE IF HERE]

else
{
    <form asp-action="MarkIncomplete" asp-controller="Itinerary" asp-area="Admin" asp-route-itineraryId="@Model.Id" asp-route-requestId="@request.Id" class="right-action-btn">
        <button type="submit" class="btn btn-warning submit-form" title="Reset this request to incomplete"><span class="fa fa-ban"></span></button>
    </form>
}
```

then you'll need to create two new action methods:
```
public async Task<IActionResult> MarkConfirmed(int itineraryId, Guid requestId)
public async Task<IActionResult> MarkUnassigned(int itineraryId, Guid requestId)
```

which sends the `ChangeRequestStatusCommand` with the correct new status.

let me know if you have any more questions.

**Comment by joro550** [comment]
Apologies, think I was just getting a little confused, thanks for the feedback.

**Comment by EmilyLuijbregts** [comment]
Hi @joro550  - just checking to see if this issue can be closed? I see that you've referenced it with a merged ticket so wanted to check.

**Comment by mgmccarthy** [comment]
@EmilyLuijbregts, yes this issue can be closed.
