### ISSUE TITLE
Write unit tests for RemoveRequestCommandHandler

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1648]

**Comment by chinwobble** [comment]
please assign to me.

**Comment by mgmccarthy** [comment]
@chinwobble, I can't assign you for some reason. For now, you can just update you comment above that you are working on this issue. Let me know if you have any questions. Thanks

**Comment by tonysurma** [comment]
@chinwobble @mgmccarthy and I invited you to the repo (github required step 1 of 2 before we can assign you) and you should have a notification from github to accept (github required step 2 of 2) and then we can assign you to the issue.

Thanks for contributing!

**Comment by chinwobble** [comment]
Thanks for the help! I accepted the invitation.

**Comment by stevejgordon** [comment]
@chinwobble - Thanks, I've now officially assigned you.

**Comment by chinwobble** [comment]
This issue should be closed.

**Comment by mgmccarthy** [comment]
@chinwobble FYI, to automatically close an Issue once the PR for that Issue has been merged, you can put:
Fixes #[PR NUMBER] 

in the body of the PR. When the PR is merged, it automatically closes the issue.
