### ISSUE TITLE
Add Event dropdown to Request CSV Import Page

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1654]
Breakout Issue from discussions originating from Issue #1590 in [this comment](https://github.com/HTBox/allReady/issues/1590#issuecomment-266754845), [this comment](https://github.com/HTBox/allReady/issues/1590#issuecomment-264197849), and [this comment](https://github.com/HTBox/allReady/issues/1590#issuecomment-264198784)

Add an Event drop down to the CSV Import Page:

- show only Event's for the logged in user's Organization
- all imported Requests will be associated with this Event

**Comment by mgmccarthy** [comment]
@tonysurma @MisterJames @stevejgordon 

do we want to show all Events across all Orgs, or only the Events for which the org user has a claim to?

the ImportController has the `[Authorize("SiteAdmin")]` attribute, so I'm not too sure if we'd want to build a list of all Events across all org's, or use either/both of these claim checks to filter the list:
- `User.GetOrganizationId();`
- `(!User.IsOrganizationAdmin(orgId))`

it's a Site Admin performing this role, so my assumption is a site admin should have claims to all orgs in the system in order to do work like this.

**Comment by stevejgordon** [comment]
@mgmccarthy As you say, at the moment this is defined as a site admin function, so I believe listing all events, perhaps listed as...

Org > Campaign > Event

would be best. I'm not sure if it's intended for an Org admin to be able to import data. If we need that facility that we would need to open this to org admins and filter accordingly.

**Comment by mgmccarthy** [comment]
@stevejgordon, that's exactly what I had a in mind... if we're showing all Events, we can put them in "context" by showing them with their realted Org's and Campaigns. Thanks again for the feedback, it's helpful.

**Comment by tonysurma** [comment]
Actually this should be primarily an org admin and thus the list should be itinerary events filtered by their permissions.

Can we make it either only org admin or org and site admins access?  If we do site admin then we should list as Steve said above

**Comment by mgmccarthy** [comment]
@tonysurma, we can make it pretty much anything we want to. I need to know if it is an org admin function, site admin function, or both.

as you pointed out, it might make more sense for this to be org admin related, b/c it sounds like an org admin would be using this import for their organization, whereas a site admin really might not use this at all.

Right now, the events drop down shows all events across all organizations.

**Comment by tonysurma** [comment]
Please do both org and site thanks

**Comment by mgmccarthy** [comment]
@tonysurma, I'm looking into this now, and because ImportController has the `[Authorize("SiteAdmin")]` attribute, and b/c it seems it's not possible to set a user as both an Org and a Site admin at the same time, I'm not going to be able to do both.

In other words, if a user is an Org admin, they'll never have the authority to view the ImportController b/c of the `[Authorize("SiteAdmin")]` attribute.

This attribute was put here in @MisterJames original code, so I could get rid of it or add authorization for "OrgAdmin" as well.

Thoughts?

**Comment by tonysurma** [comment]
I apologize in advance as I think I am getting this wrong.

The ideal requirement is that this be accessible to users that are _either_ an OrgAdmin _or_ SiteAdmin 

If we can't say 'either or' then secondary requirement is that this be accessible to users that are OrgAdmin as that is the priority.

Hope that makes sense and thanks again
