### ISSUE TITLE
Eligible Requests no longer show up on the "add selected requests" page of the Itinerary

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1658]
cc @dchristensen, this **might** be related to a change you made to the \Areas\Admin\Views\Itinerary\SelectRequess.cshtml file? as par of your work on "Select request by clicking on the map."? But I'm not too sure...

I have a Request with an EventId of 1 which should be showing up on the Selected Requests page for an Itinerary under the same Event:

![image](https://cloud.githubusercontent.com/assets/2428993/21322520/7f33af26-c5e7-11e6-8bea-3f0c12c49be0.png)

looks like we're using some type of client-side library to render the eligible requests to the UI. Here is the client code:

```
<tbody data-bind="foreach: requests">
<tr>
    <td><input type="checkbox" name="selectedRequests" data-bind="value: Id, checked: selected"</td>
    <td data-bind="text: Name"></td>
    <td data-bind="text: Address"></td>
    <td data-bind="text: City"></td>
    <td data-bind="text: Postcode"></td>
    <td data-bind="text: DateAddedString"></td>
</tr>
</tbody>
```

when I replace the code that was added as part of commit the page works: https://github.com/HTBox/allReady/pull/1633/commits/0d121302b0f44f390eac628cbfde08bc2a45ffe2#diff-30af8125d113171ccbda042ef842ed71

here is the older code:
```
@foreach (var req in Model.Requests)
{
    <tr>
    <td>
        <input type="checkbox" name="selectedRequests" value="@req.Id" @Html.Raw(req.IsSelected) ? "checked" : "" ) />
    </td>
    <td>@req.Name</td>
    <td>@req.Address</td>
    <td>@req.City</td>
    <td>@req.Postcode</td>
    <td>@req.DateAdded</td>
    </tr>
}
```

replacing the original code renders the request information to the screen:
![image](https://cloud.githubusercontent.com/assets/2428993/21322631/086e55de-c5e8-11e6-9e66-f55893bb9ae0.png)

for what it's worth, I'm currently using Chrome as my browser.

**Comment by dchristensen** [comment]
@mgmccarthy interesting. It certainly looks related to the changes I made.  I can take a look at it.  Please assign to me.

**Comment by mgmccarthy** [comment]
thanks @dchristensen
