### ISSUE TITLE
Ensure all requests have an Org Id set in the DB (CSV and Manual Creation)

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1667]
For consistency we should update where appropriate to ensure that we always set the Org ID when adding requests via the CSV and Manual UI screens? Currently in those cases we set the Event directly.

As we expect requests to have an Org Id when added via the API it'll ensure that all requests then have a direct relationship to the organization.

**Comment by stevejgordon** [comment]
Working on this

**Comment by EmilyLuijbregts** [comment]
Hi @stevejgordon - just doing a quick follow up. Do you have an update for us? or need any support?

**Comment by stevejgordon** [comment]
@EmilyLuijbregts - Yep, PR is in for this - so once that's accepted, this is done :smile:
