### ISSUE TITLE
Validate Request Phone Numbers on Creation

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1680]
Breakout from #1405 

To ensure that phone numbers are both valid and also stored in the correct E.164 format we should utilise the Twilio lookup API during request creation (API, CSV and Manual). To do this we will need to utilise the Twilio Lookup Tool at https://www.twilio.com/lookup.

We need to do this to ensure we can properly match SMS responses to the originating request. As the returned SMS response phone number will be the E.164 format, ensuring we store this with the request at creation will be a requirement for v1 to function properly.

On creation via any method, phone numbers should be posted to the lookup and where valid, saved in the proper format within the DB (instead of the original input). Unmatched numbers should be handled appropriately (TBD)

It might also be worth us including a test endpoint with the app to use in developer mode to simulate possible responses? Although that might be too much for v1 it's worth thinking about. For now I could create a faked service implementing the same interface which we can use when this is in development mode.

Questions for @tonysurma 

1. The lookup tool appears to be a separate service. The basic lookup is free but the type lookup (landline vs mobile) is chargeable. From your previous reply on the earlier issues I believe you think this may be included with the allReady/Htbox account or something the project can fund. Are you able to test if your account has the access? It'll require specific code if we intend to use the type information.
2. What would we want to do for CSV/API requests where the number is not valid (Twilio cannot process)? Should these be immediately rejected / not imported? Or should they be stored with some other status for review? Is possible a human may need to validate oddly formatted numbers that Twilio can't handle. For manually created requests we can probably include a UI validation message for phone numbers we can't process. At the moment we require a phone number for all requests. Is it possible that those without a valid phone number might need to be stored and handled in the future via email?
3. Similar to q2. If the number is a landline, how would we handle the new request creation?

I'd be happy to pick this one up next since it's close to what I've worked on so far. I had a very quick play with the API when looking into other issues.

cc / @mgmccarthy as once we clarify the above it might be worth putting heads together on this before I get coding.

**Comment by mgmccarthy** [comment]
@stevejgordon 

> as once we clarify the above it might be worth putting heads together on this before I get coding.

I'm ready when you are. Based on the API and CSV, we might be able to take different approaches since the API allows more of an async update back to GASA, but the CSV needs to enforce all data on posting to the site.

**Comment by mgmccarthy** [comment]
@stevejgordon, looks like the mobile phone number validation is more important than we thought.

@cecilia-donnelly just [said that GASA is not validating that the phone numbers on Requests that are collected by them (and then passed onto us)](https://github.com/redcross/smoke-alarm-portal/issues/196#issuecomment-270429433) are mobile numbers.

**Comment by mgmccarthy** [comment]
on a side note, can someone from GitHub please move the "Close and comment" button to the RIGHT of the Comment button. Thanks! :man_facepalming:

**Comment by stevejgordon** [comment]
@mgmccarthy - Important to know for sure. I'll try to start off the basic work need to perform the lookups.

@tonysurma - Would making the initial decision to reject requests via API that do not have a valid phone number be suitable? Do we need to log them / store with a specific status though so we can see them somewhere inside allReady?

**Comment by mgmccarthy** [comment]
@stevejgordon @tonysurma 

> Would making the initial decision to reject requests via API that do not have a valid phone number be suitable? Do we need to log them / store with a specific status though so we can see them somewhere inside allReady?

This is a great question. If we end up saving these "bad" requests somewhere, what is our course of action to correct the phone numbers? Would we have org admins (or other users) trying to reach out to the source of the request and asking them if they have a mobile number?

IMHO, my guess is that we don't really have a compensating action that makes sense, or will be realistic when talking about non-UI sourced Requests. Bad data is bad data, and when it comes from outside the system, there is not much more we can do then return a 400 to the API, and add a check for the validation errors the are shown on the CSV import.

Thoughts?

**Comment by mgmccarthy** [comment]
@stevejgordon let me know if you need some help with any of this...

**Comment by stevejgordon** [comment]
@mgmccarthy - I think for v1 timescale rejecting them is best course with a suitable HTTP error is best course of action for now. We could potentially add a log table on our end so during initial use of the application we can at least get an idea for how often a number is bad. Logging rather than a table would be better really, but we've yet to cover logging for allReady. AppInsights might give us what we want though as their API allows you to log from code (https://docs.microsoft.com/en-us/azure/application-insights/app-insights-search-diagnostic-logs)

**Comment by mgmccarthy** [comment]
@stevejgordon, I have all my Twitter values set in my user secrets file that correspond to the Twitter values in config.json:

```
"Twitter": {
      "ConsumerKey": "[twitterconsumerkey]",
      "ConsumerSecret": "[twitterconsumersecret]",
      "OAuthToken": "[twitteroauthtoken]",
      "OAuthSecret": "[twitteroauthsecret]"
    },
```

and the code is not throwing any errors, but I'm getting a null back for name and email. I know we already discussed email, and we're giving up on it b/c Twitter makes it impossible, but in your testing, could you at least retrieve the name of the user?

**Comment by EmilyLuijbregts** [comment]
Hi Steve - just doing a quick follow up to see if there's any update on this ticket?

**Comment by stevejgordon** [comment]
Hi @EmilyLuijbregts - Yes, I think this will be closed out soon. The PR was in as WIP and has been checked over. So after some final tweaking I've removed the WIP tag so it can be reviewed and merged.

**Comment by mgmccarthy** [comment]
@stevejgordon, question for you on the Twilio configuration.

in Startup, you're checking if `Configuration["Authentication:Twilio:Sid"]` and `Configuration["Authentication:Twilio:Token"]` are not empty, if so, you're wiring up the real TwilioPhoneNumberLookupService.

The problem I'm seeing is those two config calls pull back the "default" values config.json, and automatically use the real TwilioPhoneNumberLookupService:

![image](https://cloud.githubusercontent.com/assets/2428993/21866044/8265ae74-d816-11e6-8385-c7d3a286dbe6.png)

I would think we'd want to have a development/F5 experience of unless you explicitly set a outbound/inbound service to "on" (usually via a true/false flag in config similar to a call like this):
```
if (Configuration["Geocoding:EnableGoogleGeocodingService"] == "true")
{
    services.AddSingleton<IGeocoder>(new GoogleGeocoder(Configuration["Geocoding:GoogleGeocodingApiKey"]));
}
else
{
    //implement null object pattern to protect against IGeocoder not being passed a legit reference at runtime b/c of the above conditional
    services.AddSingleton<IGeocoder>(new NullObjectGeocoder());
}
```

that we use the "fake" provider. Is that what you intended?

if so, I can add the appropriate code for true/false, the setting in config.json, etc... to get the `FakePhoneNumberLookupService` to be the default when hitting F5

**Comment by stevejgordon** [comment]
@mgmccarthy Absolutely agree! I think I had that in my todo notes on my desk somewhere. Good catch! I agree that a more explicit enable/disable setting would be better and clearer.
