### ISSUE TITLE
Task Signup migrations failing

### ISSUE THREAD

**Issue by dchristensen** [HTBox/allReady#1691]
The EF migrations are failing on my local machine.  I believe this is related to PR #1681 (@mgmccarthy)

Also looks like http://allready-d.azurewebsites.net/ is failing.

The error I get when the migration fails is:

> An exception of type 'System.Data.SqlClient.SqlException' occurred in Microsoft.EntityFrameworkCore.Relational.dll but was not handled in user code
> 
> Additional information: Conversion failed when converting the nvarchar value 'Assigned' to data type int.

**Comment by mgmccarthy** [comment]
@dchristensen, we're aware of the issue and working with project owners to figure out what we want to do.

Drop your db on your local machine and allow it to be recreated when you hit F5. The live site will be down until we figure out what we want to do.

cc @tonysurma

**Comment by tonysurma** [comment]
Thanks @dchristensen 
from that info and what I found it looks like the migration doesn't work with existing data @mgmccarthy ?

I will drop and recreate the db for live when I get a moment. Thanks all.

**Comment by mgmccarthy** [comment]
@tonysurma, yes, unfortunate, that's the case. 100% my fault. I was probably switching branches too quickly and was dropping the db instead of using Update-Database after the migration. I'm sure if I had done that, I would have known about the problem before pushing my changes.

I will not let that happen again.

**Comment by tonysurma** [comment]
No worries I just get happy we actually know what the problem is and what caused it. at this point migrations are kind of extra anyhow tho soon that'll be a different story, thanks

**Comment by stevejgordon** [comment]
Resolved on live. For local dev, either:

1) Drop the DB and let it recreate
2) Clear all existing TaskSignup Records and let the DB Migrate
3) Adjust the Status for each Signup Record to use the numeric enum value as appropriate. Then the DB should migrate the column successfully from a nvarchar to int column type.
