### ISSUE TITLE
Add ValidatePhoneNumberRequest to UI Request Creation

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1697]
Tied to #1680

For whoever ends up working on this, please reach out to me with any questions

**Comment by HamidMosalla** [comment]
@mgmccarthy You want to do the same thing you did in `RequestApiController` with `ImportController` am I correct? if so, what should I do about not having the `CountryCode`? I assumed I should validate against `List<ImportRequestViewModel>` and I only have `Phone` in `ImportRequestViewModel`, I saw @stevejgordon's todo for converting country to country code, should I wait for that or do it myself or go ahead without it? sorry for so many questions :)

**Comment by tonysurma** [comment]
@HamidMosalla I am sure @mgmccarthy will have something more/better to say here but in short you can assume CountryCode is 1 (US) for this initial release, note that in the PR and then post this initial release we will fix/adapt that to support additional countries.  I recall this being an approach we used somewhere else ( @stevejgordon @mgmccarthy might remember where)

**Comment by tonysurma** [comment]
Also no apologies for asking questions @HamidMosalla it's awesome you care to know what is wanted!

**Comment by HamidMosalla** [comment]
@tonysurma Thank you, I can go ahead with the current info, but it would've been better if I had more detail, for example in the `RequestApiController` we have only one phone number, we validate it, and if it wasn't valid we return `BadRequest();`, but in the case of the current issue we have a list of phone numbers, should I return with an error message and do nothing else even if one of them wasn't valid? or I only accept the valid ones and show a message that says theses numbers weren't valid, more important than that is `PhoneNumberResource.FetchAsync` a remote call? if it is validating so many numbers over the wire is problematic, there should be some kind of method that accepts a list of `ValidatePhoneNumberRequest`, is there any thing like that exist in the project that I don't know about?

**Comment by HamidMosalla** [comment]
@tonysurma Looks like this issue has been fixed even before I made a comment, I should've paid more attention ():

**Comment by mgmccarthy** [comment]
@hamidmosalla, I already have PR  #1706 done and waiting to be merged for this issue.

**Comment by mgmccarthy** [comment]
@HamidMosalla, it's my fault about the confusion. I never assigned this Issue to myself  and I should have. Sorry about that.
