### ISSUE TITLE
As an anomyous user, I want to be able to volunteer for an activity, so I can help the overall campaign

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#17]
Needs to be fully documented and then issues logged for any gaps

**Comment by mheggeseth** [comment]
I think this could piggyback nicely on the work I did for #29 if you want to assign it to me @BillWagner. What would be pretty simple would be to collect the Name, Email, Phone, and an optional string comment of an not-logged in user who wants to volunteer. It would work the same as a logged-in user volunteering just without a reference to a user record.

Optional goodies (please comment on whether you think any of these should be required):
* Detect whether entered email matches an existing user email and suggest logging in.
* Allow anonymous users to associate skills (though we have good existing patterns for this, it's a non-trivial change).
* Persist whether an anonymous user has volunteered in browser cookies so the user can come back to the page and see that they actually did volunteer for the activity.

**Comment by tonysurma** [comment]
Thanks @mheggeseth In retrospect the missing detail was that an anonymous user should see the option volunteer but it should then require them to login etc.  I believe that is what you already did.

The only potential open item for this issue or another related one would be making sure that registering/logging in via username & password on our site (not with a social media login) is an additional option.  Right now (or at least mid day yesterday) ms account, facebook and twitter were the only options.

**Comment by mheggeseth** [comment]
Sounds good. Then this issue can probably be closed and split off into a separate "site user registration" issue. If that's required for the MVP, you could assign that to me.

**Comment by tonysurma** [comment]
Agree.  @BillWagner and @shawnwildermuth can you coordinate with @mheggeseth to see if there is an issue for this already and if anyone is working on it?
