### ISSUE TITLE
Incomplete social login for Twitter results in 404

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1707]
If you don't fully complete the social login registration (test with Twitter but may affect other services) it's possible to get into a position where you cannot use that provider any longer.

Steps to reproduce:

- Ensure you have user-secrets setup for Twitter with a valid key and secret
- On the login page choose to login with Twitter
- On redirect you will be taken to a page to complete your name and email etc.
- Navigate away from this page, without completing the process
- Go back to the login screen and choose Twitter again.
- You will get a 404 error from the site

The local solution is to delete the cookies for the site which removes the Identity.External cookie and allows you to retry the process.

The flow of the site may need review to see if we can prevent this situation.

**Comment by BillWagner** [comment]
Adding ready issues to the Dec V1 milestone.

**Comment by shahiddev** [comment]
@BillWagner I'll take a look at this

**Comment by shahiddev** [comment]
FYI for anyone trying to setup twitter auth for testing, you need to provide a url for callback in the twitter app page - localhost doesn't work but any url should work. Without this you'll run into a 401 error before you even see the consent screen

**Comment by shahiddev** [comment]
@stevejgordon I can't seem to reproduce this exactly as you've described. If I cancel or navigate away from the twitter consent screen and then return to AllReady login screen and try Twitter again it works as expected. 

However if/when I press the cancel button it gives me an option to return back to AllReady page, that currently fails.
![image](https://cloud.githubusercontent.com/assets/11890711/21992206/749ef0d4-dc0d-11e6-9ece-ce11db9394fb.png)

I have a potential solution for this
