### ISSUE TITLE
Add Polly library for HttpClient retries (OptimizeRoute)

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1708]
We have discussed adding in the Polly retry library to allReady to support fluent retry logic. We will implement this in areas were we perform Http calls that could experience transient errors/delays.

We will need to review in each case, how many retries and under what delay is acceptable for the user in each given scenario. @mgmccarthy  and I have discussed and believe that the optimize route service can experience a small delay for retry as it's an expected slower operation.

I have initial code started for this.

**Comment by BillWagner** [comment]
@stevejgordon Can you share the code and have someone here at NDC bring this to completion?
