### ISSUE TITLE
Improved UI notification for OptimizeRoute failures

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1709]
Currently if the optimize route process fails (lack of connection to Google / some other error) we do not feed this information back to the end user. We simply return the requests in their original order (un-optimized but do not notify the user that no optimization occurred)

We should ensure that we include a response type that allows us to display an appropriate on screen message to the user in such cases.

This may require a simple messaging framework which will be reviewed. If so, we should split that requirement out into it's own issue.

**Comment by chinwobble** [comment]
hi @stevejgordon. I was wondering if this is issue is dependent on #1708 (retry logic for http). Should the UI surface whether the app is trying its first or second attempt to optimise the route?

**Comment by stevejgordon** [comment]
@chinwobble Good question. I wasn't thinking that way when I put the issue in. It might be a nice enhancement but I presume we'd need to be using something like websockets/Signalr to notify the UI mid flow.

I started stubbing this out yesterday as I plan to be working on it during the NDC code-a-thon. We trigger the optimize route from a modal box which fire off to the post action and onto the OptimizeRouteCommandHandler. One returning back to the action we simply reload the details page which includes the list of ordered requests. However those may not change order if the optimize failed for example.

My current thoughts are to cache a result message for a few minutes, keyed to the user. On loading the details page, I will check that cache to see if there is a status message for that user. If so we can load the message into the view model and render it out. Clearing the cache at the same time.

**Comment by BillWagner** [comment]
@stevejgordon Is this another we can throw someone at here in London?

**Comment by stevejgordon** [comment]
@BillWagner Working on this currently as finished off the slightly related retry logic which was easier to get in first.
