### ISSUE TITLE
Editing a task with invalid data disables the Cancel button.

### ISSUE THREAD

**Issue by mjmilan** [HTBox/allReady#1718]
Create an Itinerary event
Create an associated task that has a end date not on the same day as the start date.
When you try to save the task you will be given a helpful validation warning message - but if you now click the "Cancel" button, nothing happens...

We should be able to cancel out of the edit operation on the task regardless of the information on the task, valid or not.

**Comment by stevejgordon** [comment]
Tested the steps and it blows with NullReferenceException inside the DetailsQueryHandler

**Comment by joro550** [comment]
Do you mind me trying my hand at this? :)

**Comment by shahiddev** [comment]
I can pick this up if its not being worked on - have some time on my hands at the moment so would be great to pick off some of these Jan v1 milestones ones

**Comment by bergerb** [comment]
@shahiddev  I have a pull request for this bug.  Looking for feedback.  I have not worked a lot in MVC.

**Comment by shahiddev** [comment]
@bergerb Haven't pulled the code and run it yet but change looks sensible to me

**Comment by bergerb** [comment]
Incoming Revert?

**Comment by c0g1t8** [comment]
@bergerb Oops. I did that in error.  I pulled your fix and likely clicked on something in error.  My apologies.

**Comment by bergerb** [comment]
No problem.  👍

**Comment by mjmilan** [comment]
I thought I had already fixed this - but nevermind - so long as it is
working now...

**Comment by stevejgordon** [comment]
Checked today and this looks fixed
