### ISSUE TITLE
Move unfinished/skipped phone number unit tests in ManageControllerTests to new class and implement those tests

### ISSUE THREAD

**Issue by DavidArno** [HTBox/allReady#1736]
With reference to #641, it has been agreed with @mgmccarthy that we should split this class up into a number of separate classes, focused on email, phone number, password etc tests, respectively.

This issue relates specifically to the phone number tests:

1. Split out the phone number tests into a new `ManageControllerPhoneNumberTests` class,
2. Implement those tests.

@stevejgordon could you tag this with "NDC London", please?

**Comment by stevejgordon** [comment]
@DavidArno done 😄

**Comment by DavidArno** [comment]
One test remains marked as "skip" and fails if enabled. Needs a further PR to fix this.

**Comment by mgmccarthy** [comment]
@DavidArno can this issue be closed seeing as PR #1740 was merged?

**Comment by DavidArno** [comment]
@mgmccathy,

Unfortunately it needs to stay open for a little longer as I made a mistake and another small PR is needed to fix that. I'm aiming to create that PR tomorrow lunchtime (GMT) so ought to be ready for when you come online.
