### ISSUE TITLE
No text on the About page

### ISSUE THREAD

**Issue by ResaWildermuth** [HTBox/allReady#174]
About page has no descriptor of the app.

![image](https://cloud.githubusercontent.com/assets/15706343/11016427/391ac5f8-8536-11e5-8720-bffcc4409199.png)

**Comment by bluechrometouch** [comment]
As you can see, your layout appears much different then the current version layout. Maybe you have an older version?

![12](https://cloud.githubusercontent.com/assets/14866579/11018321/c1aebfc0-8589-11e5-9fb9-38553e3756ce.JPG)

**Comment by BillWagner** [comment]
Closing as @ResaWildermuth was testing on the July public site. As mentioned above, the iconography of the ants is explained here.
