### ISSUE TITLE
Remove any "Returns(Task.FromResult(() => ))" calls in unit tests used in conjunction with "mediator.SendAsync()" and instead use ".ReturnsAsync()"

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1743]
Remove any "Returns(Task.FromResult(() => ))" calls used in conjunction with "mediator.SendAsync()" from unit tests and instead use ".ReturnsAsync()"

- the syntax is nicer and easier to understand
- we're utilizing Mock's async API to its fullest
- for MediatR 3.0 upgrade, "SendAsync" is going away and so is "Returns", so this is a refactoring step towards that eventual upgrade
- re-wrote some unit tests in SmsResponseControllerTests to align asserting the data sennt on a MediatR message is correct with how we test it in the rest of the codebase.

**Comment by DavidArno** [comment]
@mgmccarthy,

There only appear to be 19 occurrences of this pattern, so I'll take on this task to change them.

**Comment by mgmccarthy** [comment]
@DavidArno I've already submitted a pull request for this, so please do not work on it.

**Comment by DavidArno** [comment]
@mgmccarthy 

Oh yeah, missed that PR amongst all your title renames! 😝
