### ISSUE TITLE
tsc.exe exit with error for web project

### ISSUE THREAD

**Issue by premsai** [HTBox/allReady#1750]
Hi.
Getting error tsc.exe exited with code 1 when trying to run compile the project in VS2015 Enterprise edition

<VsTsc
      ToolPath="$(TscToolPath)"
      ToolExe="$(TscToolExe)"
      TSConfigFile="%(ConfigFiles.Identity)"
      YieldDuringToolExecution="$(TscYieldDuringToolExecution)"
      ProjectDir="$(ProjectDir)"
      ToolsVersion="$(TypeScriptToolsVersion)"
      TypeScriptCompileBlocked="$(TypeScriptCompileBlocked)"
      ComputeOutputOnly="false">

      <Output TaskParameter="GeneratedJavascript" ItemName="emittedFiles" />
    </VsTsc>

the version of typescript I had before was 1.8

also getting more errors when I install type script for VS2015 ver 2.1.5.
Please help

Thanks
Prem

**Comment by stevejgordon** [comment]
Hi @premsai 

We've seen some issues with the latest versions of typescript. I believe version 2.0.6 should be okay. In addition if your're running VS 2017 RC I've found the early versions of that caused me issues compiling the site in VS 2015.

**Comment by premsai** [comment]
@stevejgordon Thanks a lot ver 2.0.6 worked. !!!!

**Comment by premsai** [comment]
Issue fixed
