### ISSUE TITLE
Verify production deployment configuration is accurate

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#1756]
Here is the 'fields' we have configured currently

![image](https://cloud.githubusercontent.com/assets/5067595/22176800/8613b82c-dfd7-11e6-82d3-074c4c184ade.png)

@stevejgordon @mgmccarthy @MisterJames what else am I missing?

I want to document this and am also creating a new deploy for -d as I think there is too much cruft in there from a million deploys since first beta of .net core that is creating issues.

Thanks for your help

**Comment by stevejgordon** [comment]
Looks like we're missing a couple we need for Google social login

Authentication:Google:ClientId
Authentication:Google:ClientSecret

We also need

Mapping:EnableGoogleGeocodingService set to true
Mapping:GoogleMapsApiKey set with a valid API key for google so we can geocode addresses and optimize routes.

There's also a setting missing for ApplicationInsights:InstrumentationKey

There's a new setting for ApprovedRegions in the config with sub settings. These are set from the config so would only need to be in the deployment env vars if they need to be overridden.

**Comment by tonysurma** [comment]
per @stevejgordon and @mgmccarthy I will also review config.json for missing ones.  There are some 'enableX' settings that may explain why we aren't getting txt messages and such sent

**Comment by EmilyLuijbregts** [comment]
@tonysurma - Just wanted to check in. Are there any further ones to be added?
