### ISSUE TITLE
Should we still record an ApiRequest in our db when the ApiRequest is not in the list of supporeted regions?

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1757]
@billwagner @OhMcGoo @tonysurma  cc @stevejgordon @MisterJames

I'm looking at the code for [this closed PR now](https://github.com/HTBox/allReady/pull/1726) which has to do with the "approved" list of regions that we service based on incoming requests from GASA (at least for v1 launch). 

Based on the implementation of this PR, it looks like we're still writing the Request to our db but then reporting back to GASA that we will not service it? Is this correct? If the code is correct, for all these Requests we're writing to our db, what is the plan to eventually be able to service them?

my understanding is if the Request is not serviceable b/c of its region, we don't write the Request to our db at all. If so, we could simply return a 400 to GASA from RequestApiController

**Comment by stevejgordon** [comment]
@mgmccarthy Your understanding matches how I'd interpreted the requirement also but we need this validated by the project owners.

**Comment by mgmccarthy** [comment]
thanks for taking a look @stevejgordon.

**Comment by mgmccarthy** [comment]
pint @tonysurma, have you had a  chance to look at this yet?

**Comment by tonysurma** [comment]
Correct we should only record a request if we will do anything with it. So for ones we won't service we should not store it in the DB.

**Comment by mgmccarthy** [comment]
Okay, I'm going to work on fixing this next.
