### ISSUE TITLE
Activities Description needed

### ISSUE THREAD

**Issue by ResaWildermuth** [HTBox/allReady#176]
The activities description box shows "ActivityViewModel.cs: Needs a Description"
If no description, maybe it should be blank instead, or require a description in the form before moving forward.

![image](https://cloud.githubusercontent.com/assets/15706343/11016442/c597c922-8536-11e5-95ab-59163770aee9.png)

**Comment by bluechrometouch** [comment]
Hmmm, you might have an earlier version of allReady. Be sure to update and test again.

**Comment by BillWagner** [comment]
Closing. This was also found against the July public preview.
