### ISSUE TITLE
tsconfig.json in Allready web app

### ISSUE THREAD

**Issue by ricky68** [HTBox/allReady#1764]
File seems to require a script file to compile.
If no typescript is to be used in this project I suggest removing the tsconfig.json file, otherwise app will need a dummy file until it is used.

I've just installed the web application for the first time and run into this problem so perhaps not an issue for existing devs?

Ricky

C:\projects\allReady\AllReadyApp\Web-App\AllReady.UnitTest\error CS0006: Metadata file 'C:\projects\allReady\AllReadyApp\Web-App\AllReady\bin\Debug\netcoreapp1.0\AllReady.dll' could not be found	AllReady.UnitTest	C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets	262	

Build:No inputs were found in config file 'C:/projects/allReady/AllReadyApp/Web-App/AllReady/tsconfig.json'. Specified 'include' paths were '["**/*"]' and 'exclude' paths were '["node_modules","wwwroot","bin/output"]'.	AllReady	C:\projects\allReady\AllReadyApp\Web-App\AllReady\tsc	1

**Comment by stevejgordon** [comment]
HI @ricky68 

I suspect you're running into the same as in #1750 

VS 2017 RC had also broken VS 2015 typescript for me so I removed that.

**Comment by ricky68** [comment]
Hi Steve,
I have installed 2017 RC. Did you remove the whole thing or a specific part?
Probably don't need 2017 just yet.

Thanks,
Ricky

**Comment by stevejgordon** [comment]
@ricky68 - In my case I gave up and removed the whole thing. I didn't spent too long working out the exact cause of the problem.

**Comment by ricky68** [comment]
The two suggestions I've given seem to work for me. I'm going to need 2017 soon for work, so I'm tempted to leave it on.
Richard Campbell suggested I look into one of the HTBox projects at the NDC as I was wanting to get some experience in using core. If you have any suggestions of a good starting point I could help with in the project, that would be great.

**Comment by ricky68** [comment]
@stevejgordon - Sorry new to github, I'll look at the jump-in stuff.

**Comment by stevejgordon** [comment]
@ricky68 - No problem. Any questions, let us know and we can help, but yes, any unclaimed jump-ins would be a good place to start.
