### ISSUE TITLE
Write unit tests for SendInProgressStatusToGetASmokeAlarmHandler

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1765]

**Comment by DavidArno** [comment]
I'll grab this one, if I may.

**Comment by mgmccarthy** [comment]
@DavidArno yours

**Comment by EmilyLuijbregts** [comment]
@DavidArno - Just wanted to follow up on the current status of this ticket. Shall I assign you to this ticket?

**Comment by YannickMeeus** [comment]
I'll be picking this up if that's alright.
