### ISSUE TITLE
Write unit tests for SendRequestStatusToGetASmokeAlarmHandler

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1766]

**Comment by DavidArno** [comment]
I'll grab this one, if I may.

**Comment by mgmccarthy** [comment]
@DavidArno, please do. There are other unit tests that show how to mock/test IBackgroundJobClient, let me know if you have any questions.

**Comment by DavidArno** [comment]
OK, will do. Thanks.

**Comment by stevejgordon** [comment]
@DavidArno - I've sent you a invite to the repo which once accepted should allow us to assign to your formally.

**Comment by DavidArno** [comment]
Ah, OK. I did wonder what the purpose of the invite was. I have accepted it. Thanks.

**Comment by EmilyLuijbregts** [comment]
@DavidArno  - Just wanted to follow up on this ticket. Have you had a chance to look at it yet?

**Comment by DavidArno** [comment]
@EmilyLuijbregts,

Apologies, no. After volunteering I then ended up going on holiday and haven't looked at allReady for over a week. I shall start tackling it this week though as things are quieter now.

**Comment by DavidArno** [comment]
Really sorry all, but I've still not had time to look at this and I'm busy on other stuff at the moment. @EmilyLuijbregts (or others), please jump in and take this if you want to.

**Comment by YannickMeeus** [comment]
I've picked this up, will be raising a PR in a bit.

**Comment by mgmccarthy** [comment]
@YannickMeeus thanks. There are other unit tests that show how to mock/test IBackgroundJobClient, let me know if you have any questions.

**Comment by NRKirby** [comment]
Should this be closed? 

Taking a look at the source on master it looks like this test has been implemented [here](https://github.com/HTBox/allReady/blob/df98a357de82aa03a32ff6fe74bac3bf33ba5e5b/AllReadyApp/Web-App/AllReady.UnitTest/Areas/Admin/Features/Requests/SendRequestStatusToGetASmokeAlarmHandlerShould.cs)

**Comment by BillWagner** [comment]
Closing per @YannickMeeus
