### ISSUE TITLE
On smaller views, buttons become invisible.

### ISSUE THREAD

**Issue by ResaWildermuth** [HTBox/allReady#178]
Changed my browser to typical mobile size, buttons are not visible but am able to click on them. Home button and hamburger menu both not visible. Also, home button is to the left by the logo, hamburger is justified right.

![image](https://cloud.githubusercontent.com/assets/15706343/11016507/8f0602c8-8538-11e5-8f59-993aa59229fa.png)

![image](https://cloud.githubusercontent.com/assets/15706343/11016505/7c409658-8538-11e5-9cb1-6f6510d203c0.png)

![image](https://cloud.githubusercontent.com/assets/15706343/11016504/73702976-8538-11e5-95d2-5aa1d8ccb37d.png)

**Comment by BillWagner** [comment]
Closing, fixed since the July public preview.
