### ISSUE TITLE
Rename all instances of "Zip" or "ZipCode" to "PostalCode"

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#1782]
A "Zip" or "ZipCode" is very specific to the USA. allReady can be run anywhere. "PostalCode" is a bit more generic on locale than "ZipCode", so I'm thinking it makes more sense internationally.

@stevejgordon this one is for you ;)

**Comment by shahiddev** [comment]
Happy to pick this up if Steve doesn't want it :)

**Comment by mgmccarthy** [comment]
all yours @shahiddev

**Comment by shahiddev** [comment]
@mgmccarthy  For the data import would you expect the field name in the CSV data to remain being called "Zip" as this is the format of data expected from the 3rd party system or should we expect this to be called PostalCode too?

We are already mapping the imported fields from the CSV files so we can easily cope with the external data being called "Zip" and mapping this to PostalCode for AllReady to use internally.

**Comment by mgmccarthy** [comment]
@shahiddev, that is a great question. My answer to that is I would expect the import to be named PostalCode as well.

Please translate the 3rd-party Zip into AllReady's PostalCode so when users are importing data, they're seeing Postal Code on the column.

Thanks!

**Comment by shahiddev** [comment]
Just submitted a PR for this, its one of those horrible one that has a large number of changed files so please let me know if I can do anything to minimise the impact on others. 
All tests that I can run are fine and I've tried to smoke test as much as possible through the front end but there are areas of the app that I'm not familiar with so could have missed something.

It also contains a DB migration which looks like needs a particular workflow (according to the wiki), I may need some hand-holding through this for the first time

**Comment by EmilyLuijbregts** [comment]
@shahiddev - has anyone answered your PR request? Just wanting to check so i can push this if needed :)

**Comment by rheslar** [comment]
no, I wanted to test it on the server first, but I don't have an azure account set up

go ahead and push, if you want to I will start something else


p.s I have not commited anything yet


________________________________

**Comment by shahiddev** [comment]
I think this one is held up a little until the other big rename/refactor is done.

**Comment by rheslar** [comment]
i will wait until the final the final refactor is done, it should not effect anything

________________________________

**Comment by shahiddev** [comment]
@rheslar Just want to check you're not trying to pick up this work item? This is done and in a PR awaiting merge. 
Maybe I'm just getting confused by your responses?

**Comment by rheslar** [comment]
I did not commit in my changes, so you are ok


disregard my other emails


any more issuesthat need to be fixed?

________________________________

**Comment by shahiddev** [comment]
Ah ok, thanks for clarifying.
Take a look for any "jump-in" tagged items, if you want to pick them up please ask one of the team to assign the item to themselves (or you) to ensure others know that its being worked on.
