### ISSUE TITLE
Request - Add a "Notes" Property

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1785]
Add a notes property to requests so that any special requirements or request specific information can be stored against the request.

This will need to be added to the data model, db migration and the UI for managing requests.

@schuback - We don't receive special instructions from the 3rd party (GetASmokeAlarm.org) integration. There I presume we consider this an org admin function to update a specific request's instructions if required?

**Comment by schuback** [comment]
Ok. Also figured out what GASA is. 

Yes. Org admin levels (campaign, event manager and team leads) will need to be able to add special instruction notes to individual install details.

**Comment by shahiddev** [comment]
I'd be happy to try and pick this up could it be assigned to me please :)

**Comment by shahiddev** [comment]
@stevejgordon @schuback  Do we also want to see the notes field in the grid list of requests or just on the details of the request? 
We would probably want to truncate longer notes if we do show it on the grid.

![image](https://cloud.githubusercontent.com/assets/11890711/24085848/27e25302-0cfb-11e7-8e0a-256c1b3fd205.png)
