### ISSUE TITLE
Powered by Humanitarian Toolbox link does not direct to a page.

### ISSUE THREAD

**Issue by resafabulous** [HTBox/allReady#179]
At the bottom of the page, link 'Humanitarian Toolbox' doesn't go anywhere. Tried on all available pages.

![image](https://cloud.githubusercontent.com/assets/15706343/11016522/e33c66f2-8538-11e5-8e1a-6fd34a99c61d.png)

**Comment by dpaquette** [comment]
Duplicate of #142
