### ISSUE TITLE
Solution Architecture - link to external providers broken

### ISSUE THREAD

**Issue by c0g1t8** [HTBox/allReady#1812]
Link for _Enabling authentication using external providers_ under **Authentication** heading broken.

I think the new URL should be [https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/index](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/index).

**Comment by c0g1t8** [comment]
I just updated the link directly in the wiki.  Not sure if that's the correct process.

**Comment by shahiddev** [comment]
Thanks for updating, yes for straightforward corrections like that I would amend the Wiki directly and no need to open issue.

**Comment by tonysurma** [comment]
agree, either path is good, always love an issue for tracking but don't want to cause too much pain from process :)

thanks @c0g1t8 and @shahiddev
