### ISSUE TITLE
Team lead Can View Itinerary Details

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1821]
Follows #1813 

A team lead should be able to view the itinerary details admin page for any itinerary they are team lead for. We should also include a suitable menu navigation item when they are a team lead, which allows them to navigate to their itineraries.

We should be careful to ensure that a team lead can only view itineraries to which they are currently set as team lead.

**Comment by stevejgordon** [comment]
I'm working on a pre-requisite PR to support easier authorization of such actions

**Comment by c0g1t8** [comment]
@stevejgordon @tonysurma This can be closed as per my comments in #1787.
