### ISSUE TITLE
When a Registered User Unvolunteers, what to do with their assigned tasks

### ISSUE THREAD

**Issue by bcbeatty** [HTBox/allReady#183]
When a volunteer un-volunteers/un-registers  
what happens to their tasks if they're accepted, completed or rejected?

Will the user still see the list of tasks?
Does the admin get a notification?

Linked to #43

**Comment by MKSessions** [comment]
Can @OhMcGoo or @smille1834 answer @bcbeatty 's questions above?

**Comment by OhMcGoo** [comment]
@bcbeatty, are you suggesting a scenario where a volunteer is 'unregistering' from the allReady altogether or simply choosing not to volunteer to complete certain tasks?

**Comment by bcbeatty** [comment]
We actually need both. But my original thought was unregistering from an activity

**Comment by smille1834** [comment]
If a volunteer had accepted a task, but then decides not to participate, that task needs to free up and the Activity lead on the Admin side needs to be notified via e-mail that a task they thought was filled is now open again. 

If the volunteer is leaving the activity all together, I don't see why they need to see the tasks, but I don't think it hurts anything for them to. If they are just rejecting a task, but still want to participate elsewhere, then yes, they should see what other opportunities are present in the activity. 

Does that help?

**Comment by tonysurma** [comment]
To add what @smille1834 I would agree and add once they 'unregister' (either way) they fall back to being the same as before they volunteered which means they can no longer see tasks as one of our 'rules' is that a user can see campaigns and activities for all but can only ever see any task if they are assigned to it.

However they become unassigned they lose visibility to the task via that rule

**Comment by trayburn** [comment]
I'm working on this on my branch `trayburn/allReady/unvolunteer`

**Comment by trayburn** [comment]
Split off notifying organizer into issue #473 to make this a more manageable PR.
