### ISSUE TITLE
Highlight the Team Lead in the Itinerary Details List

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1833]
If a team lead is set we should bold and/or set a different colour for the team lead in the team lister so that they are more easily identified.

Currently they look like

![image](https://cloud.githubusercontent.com/assets/3669103/23508931/b31b0774-ff4b-11e6-996a-b6c29562ce7d.png)

**Comment by c0g1t8** [comment]
I've got #1834 already.  I'm going to take this one too if there are no objections.

**Comment by stevejgordon** [comment]
@c0g1t8 - Sure, go for it!

**Comment by stevejgordon** [comment]
If you want to update the Lastname, Firstname UI we could do that here also.

**Comment by c0g1t8** [comment]
@stevejgordon - I've got most of this working 😄.  Team member names are displayed _LastName, FirstName_.  Any particular style for displaying the team lead?  I've got the team lead name in red currently.

**Comment by c0g1t8** [comment]
I created a PR for this last night 😄

**Comment by stevejgordon** [comment]
Closing this as PR merged - @c0g1t8 if you type "fixes" then the #xxxx issue number in the PR description, it should auto close the issue for us once merged. Git-magic!
