### ISSUE TITLE
Display Team Lead first in the Itinerary Details List

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1834]
Currently the team list (on the admin itinerary details page) is not specifically sorted. We should at least ensure that the team lead appears at the top of the list to they can be quickly identified. It would probably make sense that we then sort alphabetically by surname after that.

**Comment by c0g1t8** [comment]
I'm new 😄.  I'll take this if no ones got it yet.

**Comment by tonysurma** [comment]
thanks @c0g1t8 if you accept our invitation to the repository we can assign the task to you.  Thanks for joining to help contribute

**Comment by c0g1t8** [comment]
Invitation accepted 😄

**Comment by stevejgordon** [comment]
Welcome to the project @c0g1t8 - Any questions, do let us know.

**Comment by c0g1t8** [comment]
I left a message in the Slack channel as well.  Sorry for the spam.

**Background**
I cloned but did not fork the repository several weeks ago to get familiar with this project.  I was able to get it to build and run.  It looked interesting so I decided to jump in.
- deleted my local repo
- created a fork
- cloned

**Problem**
When I tried to build, I got a _Object reference not set to an instance of an object_ in the _AllReady_ project. I spent several hours researching but still no luck.  I also attempted to build directly from the command line.  Still no joy.

```
PS C:\Windows\system32> cd C:\repos\allReady\AllReadyApp

PS C:\repos\allReady\AllReadyApp> dotnet --version
1.0.0-preview2-003156

PS C:\repos\allReady\AllReadyApp> dotnet restore
log  : Restoring packages for C:\repos\allReady\AllReadyApp\AllReady.Core\project.json...
log  : Restoring packages for C:\repos\allReady\AllReadyApp\AllReady.NotificationsWebJob\project.json...
log  : Restoring packages for C:\repos\allReady\AllReadyApp\Web-App\AllReady\project.json...
log  : Lock file has not changed. Skipping lock file write. Path: C:\repos\allReady\AllReadyApp\AllReady.Core\project.lock.json
log  : C:\repos\allReady\AllReadyApp\AllReady.Core\project.json
log  : Restore completed in 721ms.
log  : Restoring packages for C:\repos\allReady\AllReadyApp\Web-App\AllReady.UnitTest\project.json...
log  : Lock file has not changed. Skipping lock file write. Path: C:\repos\allReady\AllReadyApp\AllReady.NotificationsWebJob\project.lock.json
log  : C:\repos\allReady\AllReadyApp\AllReady.NotificationsWebJob\project.json
log  : Restore completed in 1103ms.
log  : Restoring packages for tool 'Microsoft.AspNetCore.Razor.Tools' in C:\repos\allReady\AllReadyApp\Web-App\AllReady\project.json...
log  : Restoring packages for tool 'Microsoft.AspNetCore.Server.IISIntegration.Tools' in C:\repos\allReady\AllReadyApp\Web-App\AllReady\project.json...
log  : Restoring packages for tool 'Microsoft.EntityFrameworkCore.Tools' in C:\repos\allReady\AllReadyApp\Web-App\AllReady\project.json...
log  : Restoring packages for tool 'Microsoft.Extensions.SecretManager.Tools' in C:\repos\allReady\AllReadyApp\Web-App\AllReady\project.json...
log  : Restoring packages for tool 'Microsoft.VisualStudio.Web.CodeGeneration.Tools' in C:\repos\allReady\AllReadyApp\Web-App\AllReady\project.json...
log  : Lock file has not changed. Skipping lock file write. Path: C:\repos\allReady\AllReadyApp\Web-App\AllReady\project.lock.json
log  : C:\repos\allReady\AllReadyApp\Web-App\AllReady\project.json
log  : Restore completed in 14156ms.
log  : Lock file has not changed. Skipping lock file write. Path: C:\repos\allReady\AllReadyApp\Web-App\AllReady.UnitTest\project.lock.json
log  : C:\repos\allReady\AllReadyApp\Web-App\AllReady.UnitTest\project.json
log  : Restore completed in 16965ms.

PS C:\repos\allReady\AllReadyApp> dotnet build .\Web-App\AllReady
Project AllReady.Core (.NETStandard,Version=v1.3) will be compiled because Input items removed from last build
Compiling AllReady.Core for .NETStandard,Version=v1.3

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:00.9853754
Project AllReady (.NETCoreApp,Version=v1.0) will be compiled because dependencies changed
Compiling AllReady for .NETCoreApp,Version=v1.0
dotnet : Object reference not set to an instance of an object.
At line:1 char:1
+ dotnet build .\Web-App\AllReady
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Object referenc...e of an object.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
C:\Program Files\dotnet\dotnet.exe compile-csc @C:\repos\allReady\AllReadyApp\Web-App\AllReady\obj\Debug\netcoreapp1.0\dotnet-compile.rsp returned Exit Code 1

Compilation failed.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:02.6358739


PS C:\repos\allReady\AllReadyApp>
```
Any suggestions?

**Comment by c0g1t8** [comment]
@stevejgordon This is related #1855 and can be closed.

**Comment by c0g1t8** [comment]
@stevejgordon I've got something working.  Team lead is listed first with the other volunteers ordered alphabetically by their display name.  I'm ordering the team members in the _ItineraryDetailQueryHandler_ class.

_TeamListViewModel_ class does not expose _LastName_ and _FirstName_.  I can change the ordering of the non Team Lead volunteers by surname but it will mean altering the _TeamListViewModel_ class.

Thoughts?

**Comment by c0g1t8** [comment]
Slept on this.  I may be able to change the LINQ used to build _itineraryDetails_ to accomplish this without changing the _TeamListViewModel_ class.

**Comment by c0g1t8** [comment]
Got it working - PR coming

**Comment by stevejgordon** [comment]
@c0g1t8 Sorry, missed your question. Were you able to add a PR and I can review / assist?

**Comment by c0g1t8** [comment]
@stevejgordon  I thought it was merged in already.  Please take a look at the commits on March 9 and March 10.

**Comment by stevejgordon** [comment]
@c0g1t8 - Your correct, sorry I couldn't see a PR listed so I missed that it was actually in. I'll close. Thanks again for your contribution.
