### ISSUE TITLE
Itinerary Details Page - Add Team Member AJAX

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1835]
If you add a team member to the team for an itinerary, the team lead dropdown is not shown/updated without a full page reload - this is because some of the page functions via ajax/js code. We need to either refactor to update the knockout model so we can show/hide the team lead section as part of the ajax result  or remove the ajax code on this page.

**Comment by c0g1t8** [comment]
@stevejgordon @tonysurma 

Since I've been working on some of the Itinerary related issues.  I decided to take a look at this one as well 😄

**Comment by stevejgordon** [comment]
Thanks @c0g1t8 - I'm inclined to suggest we factor out the ajax and knockout here. While it provides a nice no postback style update, it does increase our barrier to entry. It's been removed in most other places.

**Comment by c0g1t8** [comment]
@stevejgordon  I've factored out the ajax and knockout as you suggested.  This also required a little reworking of the associated view.  Testing it now.

**Comment by c0g1t8** [comment]
@stevejgordon Looking at your implementation of **RemoveTeamLead** and **SetTeamLead** in the **ItineraryController** class.  Noted your comments in the **RemoveTeamLead** method and am using it as a pattern for **AddTeamMember**.

**Comment by c0g1t8** [comment]
Need to review this fix once #1864 is closed.
