### ISSUE TITLE
How to add and configure a campaign - User Doc

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1836]
Breakout from #1362

We should add a documentation page describing the creation of a campaign in allReady

**Comment by DanKline** [comment]
In Progress .... Daniel C Kline

**Comment by DanKline** [comment]
Pull request submitted 8/6/2017 4:06.  After merge of #1836 additional documentation issues can be created with the Userdoctemplate.mdt template.  After copying the  template in the local repository file system, changing the name, then the extension to md, then the new md file can be edited with a Markdown editor and committed.

**Comment by MisterJames** [comment]
Thanks @DanKline!
