### ISSUE TITLE
How to message volunteers - User Doc

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1842]
Breakout from #1362

We should add a documentation page describing how to message volunteers from allReady

**Comment by wmay1991** [comment]
Would the documentation be put in the wiki?

**Comment by stevejgordon** [comment]
@wmay1991 I think best option is to build Markdown pages to sit under allready/docs/user_documentation

**Comment by iloabn** [comment]
I think documentation is suuuper interesting so I've started to try and write some for this project.

I'd love to receive feedback including if I'm doing something completely wrong 😋

**Comment by iloabn** [comment]
@stevejgordon What more work is required on this before you can consider this issue closed? 🙂

**Comment by stevejgordon** [comment]
I'd say that your documentation covers this requirement for now. Thanks!
