### ISSUE TITLE
Conversion to csproj\VS 2017

### ISSUE THREAD

**Issue by naeemsarfraz** [HTBox/allReady#1852]
Visual Studio 2017 RTMs on Tuesday and I believe so does the DotNet Core tooling.

Have any thoughts been given as to when this project will be upgraded? Upgrading it will mean you'll no longer be able to use VS 2015. Those that don't have licensing to upgrade to 2017 should be able to use the community edition.

cc/ @stevejgordon @mgmccarthy  @MisterJames

**Comment by stevejgordon** [comment]
@naeemsarfraz I've been pondering the same thing. The main consideration as you state is that we basically break ties with VS 2015 at the point of making this change. It's something we're going to have to do but we may want to wait to make sure VS 2017 is stable for a little while before making the leap. VS code is also an option for developing for anyone unable/unwilling to upgrade.

We also need to consider the appVeyor builds as well.

**Comment by tonysurma** [comment]
Agree on the thoughts.  I think we will need to wait a bit as said to see how the transition shakes out to 2017 as @stevejgordon said.  We want to create the broadest opportunity for those to contribute while balancing that with staying relatively up to date.

**Comment by naeemsarfraz** [comment]
Good points. We do have to be aware that there probably won't be any more tooling update for Core projects in VS2015. Essentially it'll be unsupported as I understand it so we probably should wait too long.

**Comment by stevejgordon** [comment]
I tweeted with Damian Edwards on the tooling in VS 2015 and had it confirmed not to expect any form of RTM tooling there. A slightly bitter taste left by the almost forced upgrade, despite using supported ASP.NET Core versions! In fact I have a blog post I'll be launching tomorrow covering that a little deeper.

Agreed though that we want to avoid waiting too long and I plan to review the migration process at some point soon.

**Comment by stevejgordon** [comment]
Per the standup this week, we plan to migrate in early April once everyone has a time to get VS 2017 installed and AppVeyor builds support the new csproj format.

@tonysurma Not sure if you can see anything in the appVeyor portal about csproj support. I Googled and found some suggestion that VS 2017 images are available, but not using appVeyor myself, I'm not sure if it means we're good to go?

**Comment by stevejgordon** [comment]
@tonysurma Actually, looks like an image is available and can be controlled via the yml file so when we migrate we can try that. Guessing it might be good to get a test branch going sooner rather than later though to test the waters?

**Comment by tonysurma** [comment]
@stevejgordon agree.  I created a vs2017 branch we can do pull requests against to start to make this move.

**Comment by stevejgordon** [comment]
Will have a look at this after the codeathon is safely completed. Already the links to the SDKs are a little less obvious now, so probably sooner rather than later is good since the barrier to entry will increase if the SDK's are hard to find.
