### ISSUE TITLE
login page - seperate tabs for login and register [JT]

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#1873]
like other sites so that login and register are top tab items and UI is different for both

**Comment by stevejgordon** [comment]
@tonysurma Just to check, this is a menu item in top right, so we have login and also register as links?

**Comment by babagy** [comment]
Hi, currently looking into this issue. Thanks.

**Comment by stevejgordon** [comment]
Fixed in #1927 so closing this out
