### ISSUE TITLE
login page - shrink, decolor and place social  media logins on register and login tabs [JT]

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#1874]
- [ ] place social media logins on register page
- [ ] reduce size of services buttons
- [ ] change title on register page to "Register with one of these services"

**Comment by baba-gana** [comment]
Hi, I am looking into this issue. Thanks, Baba.

**Comment by babagana-zannah** [comment]
![login in](https://cloud.githubusercontent.com/assets/26461588/24299410/07823e66-10a1-11e7-8833-218b055bc41e.png)
![register in](https://cloud.githubusercontent.com/assets/26461588/24299415/0cba1976-10a1-11e7-8d31-a13adfecb167.png)

**Comment by babagana-zannah** [comment]
Hi tonysurma, 

I have attached the screenshots. Please let me know if more can be done on this. 

Cheers, Baba.

**Comment by tonysurma** [comment]
Thanks, I just added some clarification as we were vague with the issue - thanks for your patience.

I think this address the first `place social media logins on register page` and second `reduce size of services buttons` items above, correct?  

If you could also change the header to 'Register with these services' then I will merge in the PR and we this will address the issue.

Thanks!

**Comment by babagana-zannah** [comment]
So tonysurma my bad for the miss-spelling. I will correct it ASAP.

**Comment by tonysurma** [comment]
@babagana-zannah  no need for the 'my bad' 😄 

Thanks again

**Comment by babagana-zannah** [comment]
All done @tonysurma
