### ISSUE TITLE
Social media buttons at bottom of screen don't go anywhere.

### ISSUE THREAD

**Issue by ResaWildermuth** [HTBox/allReady#188]
The buttons don't do anything.

![image](https://cloud.githubusercontent.com/assets/15706343/11016830/257cbc62-8541-11e5-85aa-d71a825d67b1.png)

**Comment by ksk100** [comment]
Where should these buttons go?  Should they be share buttons or should they link to the project's pages on these networks?  

The `img` alt text suggests the latter, but I couldn't find URLs for Instagram/Youtube.

(Relevant URLs: FB: `https://www.facebook.com/allReadyApp/`, Twitter: `https://twitter.com/htbox`).

**Comment by BillWagner** [comment]
Assigned to @JesseLiberty  based on email conversation.

**Comment by BillWagner** [comment]
Fixed in PR #397
