### ISSUE TITLE
campaign setup/edit page preview function [JT]

### ISSUE THREAD

**Issue by schuback** [HTBox/allReady#1882]
I have set up a campaign and filled in the details, saved it. I then presume that the "preview" button is there for me to see what it would look like. I click preview and it just a blank page (well there is the overall AllReady header/footer, but no campaign details. 

http://allready-d.azurewebsites.net/Admin/Campaign/Edit/8
<img width="1304" alt="screenshot 2017-03-15 04 29 22" src="https://cloud.githubusercontent.com/assets/830036/23946565/18b232b0-0938-11e7-942b-3391cc7c4904.png">

**Comment by tonysurma** [comment]
@OhMcGoo and I found the same thing yesterday and I hadn't logged it yet.  Thanks!

**Comment by chris-sargood** [comment]
@tonysurma 

I've had a look into this one. 

Whenever the preview button is clicked, the POST is resulting in a 500 response:
![image](https://cloud.githubusercontent.com/assets/24384148/24072118/85bcabb2-0bd9-11e7-8ef1-5353560ae375.png)

The odd thing is this doesn't seem to affect my local build, only http://allready-d.azurewebsites.net.

The controller itself is very simple. It takes a model and passes it through to the view. That's it. The one thing I have noticed is that the action has a 'ValidateAntiForgeryToken' attribute. By sticking a duff value in the anti forgery cookie I can get a 500 response locally and a blank preview tab replicating what we're seeing on http://allready-d.azurewebsites.net

To see if this forgery token idea is a red herring or not, would it be possible to get access to any sort of logs that may give us any further clues as to what is happening when the 500 response is being produced?

**Comment by chris-sargood** [comment]
@tonysurma 
Don't worry about the logs - I've recreated this locally. Turns out I was on a old version of the code. Doh!

**Comment by tonysurma** [comment]
Ok! Thanks
