### ISSUE TITLE
Campaign Goals description details [JT]

### ISSUE THREAD

**Issue by schuback** [HTBox/allReady#1883]
http://allready-d.azurewebsites.net/Admin/Goal/Edit/3

The numeric goal and current goal level descriptions need to be non technical.  I out in 20 for numeric and 1 for current goal level, save and then see on the campaign page it says it's at 5 already.  Something must not be right. 

<img width="1284" alt="screenshot 2017-03-15 04 32 37" src="https://cloud.githubusercontent.com/assets/830036/23946704/b1c01238-0938-11e7-886a-fb9bacf8f653.png">

**Comment by SarahMarz** [comment]
I can take this one
