### ISSUE TITLE
Create ManagementInvite Page

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1886]
Breakout from #1804 and follow on to #1885

We should create a controller to handle invites with an action and view to support creating / sending an invite. This should accept an email address and optional custom message

Sending the invite should utilise a handler to update the database to record the invite details.

In a future issue we will add a notification to trigger sending an email.

**Comment by pmarshallandrew** [comment]
picking up

**Comment by EmilyLuijbregts** [comment]
Hi @pmarshallandrew - just wanted to check in and see how you were getting on?

**Comment by mk0sojo** [comment]
I can look into this one

**Comment by mk0sojo** [comment]
Submitted pull request for this one. Feel free to review.

**Comment by mk0sojo** [comment]
Hi @stevejgordon, one thing that came up during the review of the PR is where the user should be redirected after the invite is created.
I think this depends on where it is created from (where the "Create Invite" button is).
My thought is that it would be under ~/Admin/Event/Details/X and ~/Admin/Campaign/Details/X (X is the ID) and after the invite is created will be redirected back to this page (in the same way as "Create Resource").
What is your view?

**Comment by stevejgordon** [comment]
@mk0sojo That sounds perfect to me.

**Comment by mk0sojo** [comment]
Should I do the Invite section on the campaign / event admin details pages as part of this issue or is that a separate task? Don't mind doing here, just wanted to check so no one else does it somewhere else as well.

**Comment by mk0sojo** [comment]
Sorry, just another question. If an invite already exists for a user and you try to send another one, should we update the record in the database or show an error?

**Comment by TimBibb** [comment]
Wrong email man, sorry.

**Comment by TimBibb** [comment]
But it’s funny because I’ve been looking into HTBox

**Comment by mgmccarthy** [comment]
@stevejgordon @mk0sojo I'll start to look into the messaging (email) portion of this issue...

**Comment by BillWagner** [comment]
closed per #2009
