### ISSUE TITLE
Add ManagementInvite Lister

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1887]
Breakout from #1804

Add a page for org admins to view status of all management invites. This should be a lister page that an org admin can view, showing all invites organised by type.

Should show the date sent, status etc.

NOTE: Once access is granted to other user levels, such as event managers, we may need to limit the types of invite we show. A single view hopefully can handle this though.

**Comment by wmay1991** [comment]
Should revoked invites be shown?

**Comment by stevejgordon** [comment]
@wmay1991 Good question. I think it's probably useful to show these somewhere. We'd want to avoid them interfering with the main flow, so possibly we'd want to place them in a separate lister on the same page?

**Comment by mk0sojo** [comment]
Happy to pick up this one unless @wmay1991  wants it.

**Comment by mk0sojo** [comment]
@stevejgordon: Is it a good idea to have a checkbox for "show revoked" and possibly "show accepted" like "Show closed events" check box in the "campaign details" page?

**Comment by jgauffin** [comment]
Should this one be closed? Since #2029 exists? @stevejgordon

**Comment by MisterJames** [comment]
@jgauffin you bet, closing. Thanks!
