### ISSUE TITLE
Acceptance of ManagementInvite

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1891]
Breakout from #1804

Upon clicking the accept invite link, a user should to be taken to the accept invite page. 

@schuback - Should clicking the link immediately accept the invite for a logged in user (and take them to a invite accepted page? Or should we redisplay the details and require an explicit accept button click to take place?

We should require login to access this page. If the user does not have an account, they will need to create one first.

We might need to consider the flow to direct the user to the accept invite page if they are newly created after their first full login? This would enable a slightly nicer user journey. We can review that and enhance as necessary.

Upon accepting the invite, we should update the invite table and set the user in the appropriate management table - i.e CampaignManager

**Comment by mk0sojo** [comment]
Can pick up this one
