### ISSUE TITLE
Event Managers can view list of Managed Events

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1898]
Breakout from #1803

Update event lister if possible or add a new lister page where an event manager can see links to all events(s) they have access to manage.

Clicking the link should take them to the admin event page.

**Comment by stevejgordon** [comment]
A couple of options for this:

1. We allow event managers to view the campaign details page for the campaigns owning events they are allowed to manage. This would require us to hide buttons on those pages and possibly limit the information they can see.

2. We develop a new lister specifically for event managers. This would list all events they are able to manage, which in most cases will be limited to one event.

Now that I think this through I believe option 2 is probably easier since it prevents any risk of event managers having access to campaign data they do not need and have not been granted access to.

@tonysurma @schuback Unless you have any objections I'm going to start on the code for option 2.

**Comment by tonysurma** [comment]
thanks @stevejgordon lets go with option 2 and I will connect with emily to see if there is a variation on that from Jim/Pascal/Others

**Comment by tonysurma** [comment]
cc @EmilyLuijbregts
