### ISSUE TITLE
Privacy Policy Link in Footer Fails from an Admin Page

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1904]
If I click the privacy policy link in the footer when viewing an admin page, I get a not found error. The route is incorrectly including the Admin part of the path. I believe the link needs to be amended to include the correct area.

![image](https://cloud.githubusercontent.com/assets/3669103/24016384/c84f2178-0a83-11e7-9859-ef9eda36ddd0.png)

**Comment by SarabjotSingh1986** [comment]
@stevejgordon I'm looking into it

**Comment by johnmwright** [comment]
@SarabjotSingh1986 Are you still looking into this one? It looks like a fix was merged, so perhaps this issue needs to be closed?
