### ISSUE TITLE
No "friendly" 404 page for missing content

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1905]
If I visit a page which does not exist, I do not get a friendly 404 page.

We used to display a nicer page and should certainly add something using the error pages flow.

e.g. http://localhost:48408/sometiing

**Comment by babagy** [comment]
Hi, 

Looking into this issue at the moment. 

Thanks, Baba.

**Comment by babagy** [comment]
Fixed. Pull request created. https://github.com/HTBox/allReady/pull/1916
