### ISSUE TITLE
Login with Twitter also lets me set a password.

### ISSUE THREAD

**Issue by ResaWildermuth** [HTBox/allReady#192]
I'm able to use login with Twitter (yay!). But when I look at my profile settings, it has a password function that allows me to set a password. I never have an opportunity to use that password since I'm using Twitter to login-- yet I also can't delete the password.

![image](https://cloud.githubusercontent.com/assets/15706343/11016921/fab899bc-8543-11e5-8fd4-2c66d65b84da.png)

**Comment by BillWagner** [comment]
This was fixed Nov 7, but the PR did not mention this issue. Verified and closed Nov 8
