### ISSUE TITLE
Removing team leader from itinerary does not remove team lead flag

### ISSUE THREAD

**Issue by c0g1t8** [HTBox/allReady#1928]
To reproduce:
- add team member
- set team member as team lead
- remove team member
- add removed team member 

Encountered this when testing fix for #1835.  This can result in having multiple team leads. 

Possible solutions:
- prevent removal of team lead by disabling remove
- automatically remove member as team lead before removing member

I can implement either solutions.

@stevejgordon @tonysurma Comments ❓

**Comment by c0g1t8** [comment]
I've implemented the second option and have it stashed.

**Comment by stevejgordon** [comment]
@c0g1t8 - That sounds reasonable for now.

**Comment by c0g1t8** [comment]
This is what the issue looks like:
![image](https://cloud.githubusercontent.com/assets/23250332/24205794/a1483506-0ed9-11e7-81cc-419a803d8ff8.png)

@stevejgordon If you can assign me, I can create a PR with the fix.
