### ISSUE TITLE
Order of parameters calling UploadEventImageAsync incorrect in PostEventFilemethod of the EventController class

### ISSUE THREAD

**Issue by c0g1t8** [HTBox/allReady#1931]
The order of parameters calling `UploadEventImageAsync` incorrect in `PostEventFilemethod` of the `EventController` class.

![image](https://cloud.githubusercontent.com/assets/23250332/24225991/fbada638-0f20-11e7-8d7e-c2f50d1f82e6.png)

- Issue found while working on #684.
- Same method is called in other `EventController `methods

**Comment by c0g1t8** [comment]
I've got a fix ready to go.  Please assign to me.

**Comment by tonysurma** [comment]
You can send in pull request before we assign.  The silly mobile version of GitHub doesn't have assign function.

**Comment by c0g1t8** [comment]
@tonysurma Something strange is happening with GitHub.  I created a PR but it looks like it's going to a different repository.  I'm seeing

![image](https://cloud.githubusercontent.com/assets/23250332/24226686/1a45047a-0f25-11e7-9f0c-850cafc8badf.png)

**Comment by tonysurma** [comment]
It's okay, I'll explain why in a bit

**Comment by tonysurma** [comment]
it's back to normal (emoji for whew)
