### ISSUE TITLE
Task Attachment Renames

### ISSUE THREAD

**Issue by DanielSchiavini** [HTBox/allReady#1939]
In PR #1660 some inconsistencies were introduced that should be fixed:
- The interface ITaskAttachmentService should be renamed to IVolunteerTaskAttachmentService. The taskId parameter of the method UploadAsync should be volunteerTaskId.
- The class TaskAttachmentService should be renamed to VolunteerTaskAttachmentService. The taskId parameter of the method UploadAsync should be volunteerTaskId. Finally the Azure path should be `'volunteerTask/'` instead of `'task/'`
- The fields of FileAttachmentModel should be renamed: TaskId should be VolunteerTaskId and Task should be VolunteerTask. This will require a proper database migration.

**Comment by mk0sojo** [comment]
I can take this one.

**Comment by NRKirby** [comment]
Hi, I went ahead & made a pull request for this issue & just realised @mk0sojo said he'd take this one!
