### ISSUE TITLE
Rename task views and view models

### ISSUE THREAD

**Issue by DanielSchiavini** [HTBox/allReady#1940]
There are some inconsistencies in the code that should be fixed to conclude the task to volunteer task rename:
- The admin views in `AllReadyApp/Web-App/AllReady/Areas/Admin/Views/Task/` should be moved to ` AllReadyApp/Web-App/AllReady/Areas/Admin/Views/VolunteerTask/`
- The view models in ` AllReadyApp/Web-App/AllReady/Areas/Admin/ViewModels/Task/` should be moved to ` AllReadyApp/Web-App/AllReady/Areas/Admin/ViewModels/VolunteerTask/`

This was noticed in PR #1660. This fixes the admin area, but we should also check the customer area.

**Comment by YannickMeeus** [comment]
I can pick this up.
