### ISSUE TITLE
Unhandled exception when viewing task detail

### ISSUE THREAD

**Issue by c0g1t8** [HTBox/allReady#1954]
I was working on another issue when I found this one.  I navigated to http://localhost:48408/Admin/Event/Details/4 and clicked on **Task # 0**.

![image](https://cloud.githubusercontent.com/assets/23250332/24740391/cb8d826c-1a55-11e7-9a14-45173e835552.png)

http://localhost:48408/Admin/Task/Details/64 returned **an unhandled exception**.

![image](https://cloud.githubusercontent.com/assets/23250332/24740579/b343c47c-1a56-11e7-99f0-549a980289de.png)

The `FileAttachment` table is missing from the SQL database.

I went back through the commit history and believe a database migration is missing.  @DanielSchiavini submitted a PR #1660 that added the attachment functionality.   I believe @DanielSchiavini unintentionally deleted a required [commit ](https://github.com/HTBox/allReady/commit/32f6a6e82c58840a2004f38b69055bbf55635b1e) from his original PR.

**Comment by DanielSchiavini** [comment]
@c0g1t8 sorry for this, I had to add and remove the migration several times and in the last commit I forgot to add them. #1956 fixes this

**Comment by c0g1t8** [comment]
@DanielSchiavini No problem.  I can see how this can happen.  I've been through _rebase hell_ too 😄.

This _could have/should have_ been caught during some sort of integration testing.  But they seem to be broken #1938.

BTW - Great work. I looked into the history of the original PR.  Learned a few things myself 😄.

**Comment by tonysurma** [comment]
Thank you @DanielSchiavini for the PR - I know we went around and around with rebases with your PR...

Thanks @c0g1t8 for the kind words for @DanielSchiavini and for finding the issue!

**Comment by DanielSchiavini** [comment]
Thanks 😄
