### ISSUE TITLE
Replacing Image Deletes Updated Image

### ISSUE THREAD

**Issue by dchristensen** [HTBox/allReady#1961]
There is an error in the logic around replacing images.  I believe it exists for all images types (organization, campaign & event).  The following steps will reproduce the error (note this must be done on a copy that is using the Azure based `IImageService` such as http://allready-d.azurewebsites.net/):

1. Upload an image
1. Verify the image is visible
1. Edit the org/campaign/event again and upload the same image again.
1. After saving the image is now broken and throws an exception if you try and update again.

This will occur with any two images that use the same filename.  The problem stems from the way we are currently naming our blobs and the fact that we always upload and then delete the old one.  If they are using the same filename, we upload the replacement and then immediately delete it.

**Comment by wmay1991** [comment]
How to do you upload an image? I have tried as an organization admin. Can you show screenshots?

**Comment by dchristensen** [comment]
@wmay1991 when logged in as an organization admin it looks like you can only update the event images:

![Edit Event](https://cloud.githubusercontent.com/assets/427494/24916298/fcfa1afa-1e96-11e7-939b-e8e465ee24e8.png)

As a site admin you will see a similar upload option when editing organizations and campaigns.

**Comment by c0g1t8** [comment]
@wmay1991 Did you look into this further?

**Comment by wmay1991** [comment]
Looking into this

**Comment by c0g1t8** [comment]
@wmay1991 

I've been looking at `EventAdminController.cs` as part of another issue and found the possible cause.   It appears that the wrong parameter is being passed to the `UploadEventImageAsync` method in `public async Task<IActionResult> Edit(EventEditViewModel eventEditViewModel, IFormFile fileUpload)`.  `campaign.Id is` being passed.  It should be `eventEditViewModel.Id`.  This erroneous parameter could result in clashes if the same image file is being used for multiple events. 

I corrected a similar issue (PR #1931) a coupe of weeks ago in the same controller.

I hope this helps.

**Comment by c0g1t8** [comment]
@dchristensen 

From above
> This erroneous parameter could result in clashes if the same image file is being used for multiple events.

Does this sound like what you may have done?

**Comment by dchristensen** [comment]
@c0g1t8
While that may be an issue, I don't think it is the specific issue I am reporting.  I found this error while working on PR #1955, which originally suffered from the same problem.  The core issue is that when *updating* an image, if the new image's filename matches the original image's filename, the image just gets replaced in Blob Storage, however the code in the handler first uses the `IImageService` to save the image, then calls `DeleteImage` passing in the old image path.  Since the original and new images have the same path, the new image gets deleted and we're left with a record that points to an image that no longer exists.

In my eyes there are two ways of fixing this.
1. In the `ImageService` class make sure that every image has a unique path. (This is the approach I used for the `FileImageService`, but I don't know how important semantic/pretty paths are)
2. Fix the handlers that call into 'IImageService` to check the old path before trying to delete it to make sure its not the same path that was just returned when saving the new image.

As an aside, it might be nice to have some error handling around the Azure calls, since I've borked one of the campaigns now so that whenever you try to upload an image it throws an exception: http://allready-d.azurewebsites.net/Admin/Event/Edit/2

**Comment by c0g1t8** [comment]
@dchristensen 

First, nice work on the `FileImageService`.  That simplified local testing a lot. 😄 

I think you've hit it on the head.  `DeleteImageAsync `should be called before `UploadEventImageAsync`.  Something like this should work:
```
                    if (fileUpload.IsAcceptableImageContentType())
                    {
                        var existingImageUrl = eventEditViewModel.ImageUrl;
                        if (!string.IsNullOrEmpty(newImageUrl))
                        {
                            eventEditViewModel.ImageUrl = newImageUrl;
                            if (existingImageUrl != null)
                            {
                                await _imageService.DeleteImageAsync(existingImageUrl);
                            }
                        }
                        var newImageUrl = await _imageService.UploadEventImageAsync(campaign.OrganizationId, eventEditViewModel.Id, fileUpload);
                    }
```

This would be the easiest fix and would handle the case where the actual image has changed but the filename has not.

I looked at the `CampaignController` implementation.  A similar fix should also work.  `OrganizationController` is implemented differently so I don't think this problem applies.

@wmay1991 Didn't mean to hijack the issue.  Curiosity got the better of me.

**Comment by dchristensen** [comment]
@c0g1t8 I think deleting after saving is the correct behavior, we wouldn't want to have something go wrong on the save and end up with no image at all.  I think comparing `existingImageUrl` and `newImageUrl` before actually calling `DeleteImageAsync` would resolve the issue.

**Comment by c0g1t8** [comment]
@dchristensen You have a good point.  But you would only be comparing the URLs not the actual image files.  In the case the user wished to replace the image file with a different image file with the same name, they would need to first delete before uploading.  

It sounds like we would need a _swap/replace_ a method on the `IImageService` to maintain _consistency_.

In the short term, I would go with the simple fix.
1. It would resolve the problem immediately.
2. My previous experience with Azure blob storage has shown that it is remarkably reliable and resilient.  Though the issue you've pointed out is valid, the odds of it occurring and impact is low.

This is above my _pay-grade_ 😄.  So I think we need the higher powers make the long term decisions.

**Comment by dchristensen** [comment]
@c0g1t8 I think comparing image URLs would be ok, since that is the identifier that is both returned from the `Upload` method and used to perform the `Delete`.

**Comment by c0g1t8** [comment]
@dchristensen  I think I understand what you mean now.
```
if (fileUpload.IsAcceptableImageContentType())
{
    var existingImageUrl = eventEditViewModel.ImageUrl;
    var newImageUrl = await _imageService.UploadEventImageAsync(campaign.OrganizationId, campaign.Id, fileUpload);
    if (!string.IsNullOrEmpty(newImageUrl))
    {
        eventEditViewModel.ImageUrl = newImageUrl;
        if (existingImageUrl != null && existingImageUrl != newImageUrl)
        {
            await _imageService.DeleteImageAsync(existingImageUrl);
        }
    }
}
```
I like it 😄.  It preserves the old image in case the upload fails since that would be caught as an exception.  And it allows the user to replace the old image with a new one even if the filename is the same.

**Comment by wmay1991** [comment]
The fix sounds good to me. Sorry I have been unavailable the past couple days.

**Comment by c0g1t8** [comment]
@wmay1991 If you don't mind, I'll push a PR on this.

**Comment by wmay1991** [comment]
Sure
