### ISSUE TITLE
 PR #1947 Breaks integration test

### ISSUE THREAD

**Issue by c0g1t8** [HTBox/allReady#1976]
The fix for #1877 changed a tag in `_AdminNavigationPartial.cshtml` on which the integration tests requires.

**Comment by dchristensen** [comment]
I'll get this fixed.

**Comment by c0g1t8** [comment]
@dchristensen I pushed up a PR just before you 😄.  I was testing #1803 when I encountered this problem.  

My fix was just to fix the test since your changes to the app worked.

**Comment by tonysurma** [comment]
thanks @dchristensen and @c0g1t8 - I merged in @c0g1t8 fix but let me know if I should merge in @dchristensen's PR as well?

**Comment by c0g1t8** [comment]
@dchristensen I think you are best to judge which one should be merged  I'll leave it to you 😄

**Comment by dchristensen** [comment]
@c0g1t8  I honestly don't know enough about how canopy's selectors work to know if this is even an issue, but the reason I took the approach of adding the `.dropdown-admin` class back in was because the `li.dropdown` selector is not unique to the admin menu, it also matches the Account/Logout menu.

**Comment by tonysurma** [comment]
thanks @dchristensen and @c0g1t8.  Given that I merged in #1978.  If we that does it - great, if not then I will merge in #1977 as well...

**Comment by c0g1t8** [comment]
@dchristensen I'm on a similar learning curve with Canopy and am a newbie when it comes to CSS.  Been do a little more reading on [Canopy ](https://lefthandedgoat.github.io/canopy/index.html) as well.  

Canopy uses the same selectors as CSS as well as text for selection.  It's selection is in the context of the current page.

The benefit of you fix is that it ensures uniqueness even if we make further changes to the page 😄 I like that.  

@tonysurma Closing PR #1977
