### ISSUE TITLE
Team Management by Team Lead

### ISSUE THREAD

**Issue by c0g1t8** [HTBox/allReady#1992]
Breaking this out from #1787 Itinerary Team Lead EPIC.  

I made the following comment:
>At the moment, the Team Lead can manage team membership including changing the Team Lead which I don't think is a good idea. The Team Lead should only be able to add and remove non-team lead members. 

IMO - this is a _business rule_ related question.  Thoughts?  Is this even an issue?

**Comment by stevejgordon** [comment]
@c0g1t8 Sorry for the delay. I discussed this with one of the project owners and agree that a Team Lead should not be able to manage teams members at this stage. We will limit that functionality to the next layers of authorization (event/campaign managers, org and site admins).

**Comment by stevejgordon** [comment]
I'll take a look at this one.

**Comment by stevejgordon** [comment]
Update: Correctly forbidden by the current authorization code. Just requires an update to hide the team management UI when not authorized. Working on that now.
