### ISSUE TITLE
Analysis on centralizing FakeUserManager

### ISSUE THREAD

**Issue by HamidMosalla** [HTBox/allReady#1999]
There is a class called `FakeUserManager` that copied and pasted across the project, to provide mock for `UserManager`, as discussed on #1997 , @mgmccarthy suggested that we create a centralized version of this class, we already have `AllReady.UnitTest.MockHelper.CreateUserManagerMock` in the project, but I need a version that can provide the `GetUserAsync` method for controllers that are dependent on `UserManager`.

**Comment by mgmccarthy** [comment]
@HamidMosalla please close this issue. I don't know if we want to centralize it yet, and I want to do analysis on what it's needed across multiple test classes, and if it is needed, why so many fakes are needed on FakeUserManager. Just leave it in the test classes for now.

**Comment by mgmccarthy** [comment]
@HamidMosalla cc @stevejgordon  I'm going to take a look at this. @HamidMosalla for now, just leave the FakeUserManager in the test class that was part of the PR and the code review I did for you. Thanks!
