### ISSUE TITLE
update domainurl in service.js of mobile app

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#2]
For now there is a soon to be - if not already - dead url for domainurl in service.js of the mobile app.

We need to make this configurable/changeable for devs to set to local urls and for us to set as we package the apps for testing and production

**Comment by jonatwabash** [comment]
Two points of clarification:
1) Is the file with the bad url AllReadyApp/www/app/services.js?
2) Where is configuration currently supposed to go?

**Comment by MKSessions** [comment]
Completed.

**Comment by jonatwabash** [comment]
What was the final solution for making the domain url configurable? Does it simply have to be updated by hand in the services.js file, or is there some automated process that will change what currently looks like a hard-coded string while building and deploying the app?
