### ISSUE TITLE
Update to work with latest dnx beta6 build

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#20]
Make this change on the web project as below and fix/update to build and run with the newest build.
[Should now be beta7]

<img width="483" alt="dnxbeta6" src="https://cloud.githubusercontent.com/assets/5067595/9114151/f9b6b2fc-3c1d-11e5-883c-a304443f8922.png">

**Comment by BillWagner** [comment]
I updated a smaller project to Beta 6 and found both of these resources to be very helpful:

http://www.elanderson.net/2015/08/migration-from-asp-net-5-beta-5-to-beta-6/

http://stackoverflow.com/questions/31745539/how-to-upgrade-asp-net-5-vnext-from-beta5-to-beta6

**Comment by tonysurma** [comment]
Updated title and we are now looking at beta7 as it was just released today

http://blogs.msdn.com/b/webdev/archive/2015/09/02/announcing-availability-of-asp-net-5-beta7.aspx

**Comment by joelhulen** [comment]
I forked and cloned the project the other day. On launch, it threw an error about DNX Beta 5 being unavailable. I ran `dnvm list`, and saw I only had Beta 7.

It may be helpful to note for others that you can install a specific version of DNX on your system via this command line expression via a PowerShell console:

    dnvm install -r clr 1.0.0-beta5

**Comment by BillWagner** [comment]
One thing I've found: updating 1 version at a time (beta 5 -> beta 6 -> beta 7) is *much* easier.

@joelhulen Are you going to take this on?

**Comment by joelhulen** [comment]
@BillWagner - happy to help however I can. Do you mean take on noting to others how to install the DNX version, or help with getting it to work on Beta 7?

If the former, would it make sense to post these instructions on the project's readme file?

**Comment by BillWagner** [comment]
@joelhulen The latter. I like to make sure the core team knows who's working on any issue: There's plenty of work without volunteers each taking the same tasks.

I'll update the readme. MOst of that will be pointers to the asp.net vNext Home

**Comment by joelhulen** [comment]
@BillWagner I'll take on this issue. Is there a process I should follow to indicate that I am working an issue, or is that just communicated internally?

**Comment by BillWagner** [comment]
@joelhulen Just adding the comment here, as you've done above.

**Comment by shawnwildermuth** [comment]
@joelhulen - are you taking this on? If not, i'll do it. Please let me know and I'll get started if needed...

**Comment by shawnwildermuth** [comment]
This is inprogress, I don't think I have rights to mark it as such. I'll drop a pull request soon with it.

**Comment by shawnwildermuth** [comment]
Updated to Beta 7 via Pull Request https://github.com/HTBox/allReady/pull/79

**Comment by BillWagner** [comment]
Closed via PR #79
