### ISSUE TITLE
AllReady.UnitTest build failing

### ISSUE THREAD

**Issue by joshuahysong** [HTBox/allReady#2007]
AllReady.UnitTest fails to build with error "The name 'MockHelper' does not exist in the current context"

This object is referenced on line 386, 400, and 418 in Allready.UnitTest.Controllers.CampaignControllerTests

![capture](https://cloud.githubusercontent.com/assets/8880993/26408562/2508b2e4-406c-11e7-9d2b-c4c0279466d7.PNG)

**Comment by mgmccarthy** [comment]
@joshuahysong, sorry about that. Looks like it's my fault. A ReSharper "rename" that never picked up these other items.

I'm working on the fix now and will have a PR in shortly

**Comment by mgmccarthy** [comment]
@tonysurma cc @joshuahysong,

I have PR #2008 to fix this problem. Should be a simple merge. Thanks!
