### ISSUE TITLE
"An unhandled exception occurred while processing the request" when creating an event

### ISSUE THREAD

**Issue by arnonax** [HTBox/allReady#2010]
Repro steps:
1. Login as org admin (organization@example.com)
2. Create a new campaign
3. From the new campaign, create a new Event
Expected result: the new event is displayed
Actual result: An error page appears, with the details mentioned below and in the attached image.

Note: I was able to fix this problem easily by changing Task to VolunteerTask at Details.cshtml:125, but then I reached as similar error when adding a task, which I couldn't find the root cause so easily.

Error details:
========

```
An unhandled exception occurred while processing the request.

InvalidOperationException: The partial view '~/Areas/Admin/Views/Task/_List.cshtml' was not found. The following locations were searched:
~/Areas/Admin/Views/Task/_List.cshtml
Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper+<RenderPartialCoreAsync>d__60.MoveNext()
```
![htboxbug-createevent](https://user-images.githubusercontent.com/9963202/27087686-5895a8f4-505e-11e7-866f-e1c284af5528.png)

**Comment by mk0sojo** [comment]
I think renaming TaskController to VolunteerTaskController and update all "asp-area="Admin" asp-controller="Task"" to "asp-area="Admin" asp-controller="VolunteerTask"" should solve it.

**Comment by jamesatgreymetis** [comment]
I've just been found this bug and was going to log it. Happy to jump in if no one else has claimed it.

**Comment by stevejgordon** [comment]
@jamesatgreymetis Feel free, it's up for grabs.

**Comment by stevejgordon** [comment]
@jamesatgreymetis Sorry, I've ended up grabbing this as it was fairly blocking for some other bits I wanted to review / work on today.
