### ISSUE TITLE
Maps: Able to add/duplicate tasks to an existing pin on a map

### ISSUE THREAD

**Issue by EmilyLuijbregts** [HTBox/allReady#2023]
This is a breakout from #2021 

As a user I want to be able to add or duplicate tasks that are already in an existing pin in the map feature to increase the speed that I can use the map functionality. Any changes made should be saved.

**Definition of done:**
- The user with the right permissions should be able to add a task by clicking on the existing pin in the map feature
- The user should be able to add/duplicate tasks without leaving the map/pin functionality
- The user should be able to either add or duplicate an existing task listed under the pin

**Comment by MisterJames** [comment]
Closed as not in scope.
