### ISSUE TITLE
After logging in via Twitter there is no indication of log-in status

### ISSUE THREAD

**Issue by Harmonym** [HTBox/allReady#203]
After logging in via Twitter and authorizing the app, the use is brought to the home page, but there is no indication that the user is logged in or what to do next to access the site content for users.

<img width="909" alt="image" src="https://cloud.githubusercontent.com/assets/8798159/11017352/25e240b8-8551-11e5-8500-0d00c6a385fe.png">

**Comment by BillWagner** [comment]
Fixed on Nov 7
