### ISSUE TITLE
AllReady.ScenarioTest - tests failing due to incompatible dates in non-US cultures

### ISSUE THREAD

**Issue by jimparsley** [HTBox/allReady#2033]
Hi, I'm new to this project and would like to help out with the development. 

Whilst getting my environment set up, I noticed that the selenium tests were failing due to my machine's culture not matching the app culture (I'm in Germany). I looked through the existing issues, and discovered that the web app culture is hard-coded to US.

Therefore, I propose hard-coding the AllReady.ScenarioTest to US culture to match the web application. 

Does that sound like a good plan?

I'm happy to make this change if so.

**Comment by MisterJames** [comment]
@jimparsley I think this sounds reasonable, thanks for the suggestion (and reporting the bug). Please proceed and submit a PR.

Thanks!

**Comment by jimparsley** [comment]
@MisterJames You're welcome. OK, will do.
