### ISSUE TITLE
App launch in debug error - context.Database.Migrate

### ISSUE THREAD

**Issue by DanKline** [HTBox/allReady#2036]
System.Data.SqlClient.SqlException occurred
  HResult=0x80131904
  Message=Conversion failed when converting the nvarchar value 'Assigned' to data type int.
The statement has been terminated.
  Source=Core .Net SqlClient Data Provider
C:\Users\dan\Documents\GitHub\allReady\AllReadyApp\Web-App\AllReady\Startup.cs:line 201

**Comment by stevejgordon** [comment]
Hi Dan.

There was a breaking change a while back around some data column changes. This sounds like that issue. Best solution in this case would be to drop your local copy of the database and let it be rebuilt and seeded.

**Comment by DanKline** [comment]
Hmmm ... I just checked and I don't have a local copy of SQL running.  I thought VS always installed that.  I'm working remotely so I'm not attached to the SQL instance on my domain.  I'll install express and see if that resolves the issue.

**Comment by stevejgordon** [comment]
It usually uses (localdb)\mssqllocaldb

**Comment by DanKline** [comment]
OK... After uninstalling a few prior versions of SQL and SQL 2016, then reinstalling SQL Express 2016, and  deleting my local repository and cloning my fork of the current GitHub code, I am able to populate the database on localdb, however, I'm still seeing a conversion type error on "Assigned'.  I think there may still be an error in the mappings used.

**Comment by DanKline** [comment]
Scratch that ... second attempt at dropping the database seems to have worked,  It's not in the code... something was cached on my machine.

**Comment by DanKline** [comment]
In case you didn’t see it, I got everything working.  I think there was an issue with having installed the3 SQL2016 RC3 and the localdb instance.  It didn’t show in SSMS but after uninstalling several versions of SQL and reinstall 2016 SQLExpress it was there.  Unfortunately, I needed to be be dropped.  But wen it regenerated the Already DB, everything was fine.  I’m guessing the old DB was there but hidden in SMS.

 

At any rate… all is good and the code and the install instructions are valid.

**Comment by DanKline** [comment]
In summary, if previous contributors have used SQL2016 RC3, you may have a localdb that does not appear in SSMS.  The DB is probably there and causing this issue.  The uninstall of previous versions of SQL and reinstallation of the SQLExpress 2016 will expose the localdb which must then be dropped and regenerated by reloading the solution in Visual Studio.
