### ISSUE TITLE
Best Way to ask project Question?

### ISSUE THREAD

**Issue by SteveKennedy** [HTBox/allReady#2038]
1. What is the best mechanism to ask general question about this allReady project?  Is it to open an issue? Is there a Slack channel? Email?

2. Where is the dev/test web app published to? What url? Can you point to documentation on where it's published?

**Comment by MisterJames** [comment]
Hi @SteveKennedy. You have a few options, as you've suggested:

- We can connect you with @tonysurma who can get you into our slack channel
- You can create an issue
- You can join in on our bi-weekly community standup (from our YouTube channel, next is Tuesday at 9:30 AM Central)

I'll get you the URL and will hold this issue open until I can line that up for you.

Cheers!

**Comment by MisterJames** [comment]
@SteveKennedy 

You can access the auto-deployed version here: http://allready-d.azurewebsites.net/Manage

Cheers!
