### ISSUE TITLE
Remove Blog Page Link

### ISSUE THREAD

**Issue by Harmonym** [HTBox/allReady#204]
Update: Issue is now to remove the blog link altogether

The Blog link in the nav does not appear to link to anything/even a placeholder page like the About page.  On hover the mouse will point as if it is a live link, but nothing happens. 

I assume this still needs to be built or set to redirect to whatever blog engine they want to use.
![image](https://cloud.githubusercontent.com/assets/8798159/11017371/a2442ef0-8551-11e5-81c8-cc68ed3999af.png)

**Comment by ResaWildermuth** [comment]
There was a suggestion with #194 that this has been fixed, but I don't see the fix on testing.

**Comment by BillWagner** [comment]
If you are logged in as Admin, it goes to the htbox.org/blog page (which is close. @tonysurma will supply the correct URL for all-ready specific blog posts.

The volunteer and public (anonymous) pages go to the allready home page. These should also go to the htbox/blog page that is specific to the allready posts.

**Comment by stevejgordon** [comment]
@tonysurma It seems the concept of a blog in no longer in the application currently. Is there a wider requirement to include a blog concept or is this an issue that is now redundant?

**Comment by digitaldrummerj** [comment]
@tonysurma bump

**Comment by tonysurma** [comment]
we should remove this link altogether

**Comment by stevejgordon** [comment]
@tonysurma I think the link is gone? Maybe just needs someone to check the views though to validate that.

**Comment by tonysurma** [comment]
will assume it is gone and it can come back up as an issue if it still is somewhere, thanks.
