### ISSUE TITLE
EVENTS: Ability to create an event as a Campaign Manager

### ISSUE THREAD

**Issue by EmilyLuijbregts** [HTBox/allReady#2040]
This is a breakout from: Events Epic #2039 

**Requirement:**
- As a  Campaign Manager I want to be able to create events which I can then manage as an admin

**Definition of Done:**
- The role will be created
- The role will have the necessary permissions to add, and edit events.

**Additional information:**
- Info from @stevejgordon : PARTIALLY COMPLETE. Currently Site and Org admins can create events inside Campaigns. We are adding the concept of a Campaign Manager role, which will also be able to create events inside the Campaign(s) they manage.

**Comment by MisterJames** [comment]
There is pre-work for this. If someone would like to pick these up, please create new issues and reference this issue along with the epic #2039. 

 - Add a campaign manager role
 - Update the admin page for user management

I'll remove my assignment when we get the prework done.

**Comment by stevejgordon** [comment]
@MisterJames The following EPICs also overlap on this requirement #1802 and #1804 

The work to define a table to record campaign manager + a bunch of authorization logic is in place already to support the concept of the campaign manager. I'll need to double check how much is in place but I think the core of this may be very close/done.

**Comment by stevejgordon** [comment]
I've tested the site and this functionality is completed. Marking as closed.
