### ISSUE TITLE
EVENTS: Admin’s can assign volunteers to tasks

### ISSUE THREAD

**Issue by EmilyLuijbregts** [HTBox/allReady#2047]
This is a breakout from the Events Epic #2039 

**Requirement**:
As an admin I want to be able to assign volunteers that are already users in the system to specific tasks listed under a request.

**Definition of Done:**
- There is the option to be able to assign users to the tasks within allready

**Additional Information:**
Information from @stevejgordon : NOT COMPLETE. As we only have task volunteering we don’t have a system to assign volunteers to other tasks. Currently, a volunteer would volunteer for a task directly. 

**Questions for @OhMcGoo @Schuback**
- Should the volunteer receive a confirmation once they've been assigned to a task?
- Do you have feedback based upon the feedback from Steve?

**Comment by MisterJames** [comment]
We can add this.

Use a prompt for a message to the user. The admin can opt out of sending a message. If they choose to send one, it will go via SMS or email through our existing pattern (azure table storage/web jobs to be later updated to Service Bus/Azure Functions).

**Comment by stevejgordon** [comment]
Presumably this needs to be limited to showing users who have volunteers for a previous task in the organisation? In a multi-org system, would we want to expose users details that may have signed up but whom have only volunteered against another Org?

**Comment by jgauffin** [comment]
working on this one.

**Comment by jgauffin** [comment]
Added PR #2120
