### ISSUE TITLE
EVENTS: Admins can remove volunteers from assignments and tasks

### ISSUE THREAD

**Issue by EmilyLuijbregts** [HTBox/allReady#2048]
This is a breakout from the Events Epic #2039 

**Requirement**:
As an admin I want to be able to remove volunteers that are already signed up for assignments or tasks.

**Definition of Done:**
An admin should be able to remove any assigned volunteers from an event. This may result in no volunteers being assigned to a task.

**Additional Information:**
Information from @stevejgordon : NOT COMPLETE. We also don’t have a feature to allow admins remove volunteers from tasks.

**Questions** for @OhMcGoo and @schuback:
- Do you have any feedback from the comment from Steve?
- If a volunteer is removed from an assignment, should they be notified? If yes, via what communication method? (e.g. email)

**Comment by MisterJames** [comment]
This can be progressed. For org admins, they should see some UI to remove a volunteer. They should be prompted for a message to be sent to the user. They should be able to opt-out of sending a message. If they elect to send a message, we should queue up an email per our existing pattern to Azure table storage/web jobs (a later update will move this to Service Bus/Azure Functions).

**Comment by jgauffin** [comment]
working on this one

**Comment by jgauffin** [comment]
PR in #2107
