### ISSUE TITLE
EVENTS: Update to state events

### ISSUE THREAD

**Issue by EmilyLuijbregts** [HTBox/allReady#2053]
This is a breakout from Events Epic: #2039 

**Requirement**: 
As an administrator I want to be able to have the following states available to be selected in a request:
- Requested
- Scheduled
- Confirmed
- Completed.

**Definition of Done:**
- There will be a check in the system before this issue is started to make sure that no unnecessary work is performed.
- The states mentioned in the requirement are listed in the system and ready for the admin to select as needed.

**Additional Information:**
- Comment from @stevejgordon : PROBABLY COMPLETE. We have unassigned, assigned, pending confirmation, confirmed, canceled and completed states.

**Questions**::
@OhMcGoo and @schuback: Based upon Steve's comment the only additional state that would be needed is: Requested. Is this correct?

**Comment by MisterJames** [comment]
The update here will be to add the new status in the enum.

**Comment by devfables** [comment]
Mine! :)

**Comment by MisterJames** [comment]
Thanks @DanKline!
