### ISSUE TITLE
Correct menu header to stay fixed as scrollbars on page are used

### ISSUE THREAD

**Issue by devfables** [HTBox/allReady#2060]
When viewing content on a page within the allReady application (campaigns, events etc), the menu options do not stay affixed at the top of the page as you scroll within the content of the page. Think it would be intended for these to always be present at top of page for consistent look/feel and easy access to main application options. This would be a UX/UI consideration.

**Comment by ryanEcomp** [comment]
will do asap

**Comment by ryanEcomp** [comment]
I added pull request #2096
