### ISSUE TITLE
.NET Summer Hackfest - Signup Here!

### ISSUE THREAD

**Issue by MisterJames** [HTBox/allReady#2079]
Our project is participating in the .NET Foundation's Summer Hackfest.

If you'd like more information about our event, check out our [Hackfest Primer](/HTBox/allReady/blob/master/dotnetSummer.md).

If you would like to join in, please **add a comment on this issue** so that we can better keep track of our contributors.  You can also use this issue to request to join our Slack channel.

Thanks for helping to move our cause forward!

**Comment by BlueNinjaSoftware** [comment]
I'm interested in contributing! I'd be glad to chat on Slack or via another means to get up to speed and have a way to ask any questions I run into. Thanks!

**Comment by Pothulapati** [comment]
I would like to contribute. 👍

**Comment by marigerr** [comment]
I would like to contribute!  Would be great to join Slack channel.

**Comment by VenkateshSrini** [comment]
I would like to contribute

**Comment by VenkateshSrini** [comment]
is there a place where I can see a running instance of this app to understand the functionality

**Comment by stevejgordon** [comment]
@VenkateshSrini - Please see our live site which updates with master builds - http://allready-d.azurewebsites.net/ - You can find the admin login details which will be seeded in there from the appsettings.json file.

**Comment by stevejgordon** [comment]
cc @BillWagner for Slack additions

**Comment by sneh1** [comment]
I would like to contribute. Please add me to Slack channel.

**Comment by BillWagner** [comment]
I added those whose email addresses are listed in their GitHub profiles.

@Pothulapati  @marigerr @VenkateshSrini @sneh1 Please send me an email at Bill.Wagner <at> htbox.org and I'll add you to the slack channel

**Comment by BillWagner** [comment]
invites sent to all those who emailed me.

**Comment by sdekok** [comment]
I would like to contribute.  I have emailed @BillWagner for access to the slack channel

**Comment by waiholiu** [comment]
Hi, I would like to contribute. Please add me to the slack channel.
cheers

**Comment by maulikk2000** [comment]
hi,
 I'd also like to contribute. Please add me to the slack channel. 
cheers,
Maulik

**Comment by BillWagner** [comment]
@waiholiu @maulikk2000 Can you email me with the email address I should invite to Slack?  I'm bill.wagner <at > htbox org

**Comment by stevejgordon** [comment]
Closing as this has finished now.
