### ISSUE TITLE
Unable to setup upstream connection after

### ISSUE THREAD

**Issue by VenkateshSrini** [HTBox/allReady#2087]
Hi,
When I try to setup upstream connection I get this error
![untitled](https://user-images.githubusercontent.com/1167152/29682036-39fb258e-8927-11e7-9a0a-7e8ee74fdf8e.png)
Please help with the same

**Comment by VenkateshSrini** [comment]
I had used Vs 2017 to clone from VenkateshSrini/already which is my fork

**Comment by dchristensen** [comment]
You need to be in the directory that the repo is cloned into in order to use any of the git commands.

**Comment by VenkateshSrini** [comment]
Thanks resolved
