### ISSUE TITLE
User first time profile development workflow needed

### ISSUE THREAD

**Issue by Harmonym** [HTBox/allReady#209]
There does not appear to be a first time user registration workflow beyond connecting to Twitter, FB, et al for authentication.  There should be a prompt and workflow for users to submit basic information such as name and e-mail information.  There also needs to be a more in depth user profile workflow for registering zip code for activity/task location filtering, skills, et al.

**Comment by stevejgordon** [comment]
This flow is now in place. I will validate each client and raise new issues should any fail
