### ISSUE TITLE
Where can new contributors start?

### ISSUE THREAD

**Issue by waiholiu** [HTBox/allReady#2093]
Hi,

I would like to start helping with this project. I've got the project running and debugging on my local machine, I've spent some time understanding the code base and architecture and had a look at the documentation and issues. 

I know .Net fairly well but I'm unfamiliar with working on open source projects so I want to contribute but I'm not sure where to start. I notice that almost all of the issued listed under "Jump in" all seem to have comments indicating that someone is working on it or have a PR submitted for it.

Is there an issue or task that is available that could be assigned to a newbie such as myself to get my feet wet?

Thanks,

Wai

**Comment by anil-kk** [comment]
Same here ;) a newbie

**Comment by BillWagner** [comment]
Great Question.

I'd start with any issues in the current milestone: https://github.com/HTBox/allReady/milestone/21

We also tagged quite a few issues with the 'dotnetsummer' tag. Those are listed here: https://github.com/HTBox/allReady/issues?q=is%3Aopen+is%3Aissue+label%3Adotnetsummer

If any of those interest you, add a comment to say you are working on it.

If not, just let me know and we'll find something for each of you.

**Comment by waiholiu** [comment]
Thanks Bill I'll take a look tonight and see how I can contribute.

**Comment by MisterJames** [comment]
We also use the tags "Good First Issue" and "Help Wanted", hope those can give you some leads!
