### ISSUE TITLE
Investigate issue with TimeZoneNameTagHelper being matched on head / body

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#2094]
As with TimeTagHelper this is being matched for head and body tags resulting in some odd errors.

For now we have null check TimeZoneId which will be null when matched for head and body tags and result in an error if we attempt to use a null Id in the FindSystemTimeZoneById method.

Ideally we need to understand this behaviour to avoid the temporary fix.

Related to issue #2089

**Comment by dpaquette** [comment]
This is really strange
