### ISSUE TITLE
Logged-in user shows Hello [e-mail]! at the top right corner

### ISSUE THREAD

**Issue by Harmonym** [HTBox/allReady#210]
The Hello or Welcome should show the user's first name or full name instead of e-mail address.  This will be contingent upon issue #209 being completed to request the users name during registration.

![image](https://cloud.githubusercontent.com/assets/8798159/11017511/feabc8d4-8555-11e5-8695-12dca0c80448.png)

**Comment by tonysurma** [comment]
Duplicated of #273
