### ISSUE TITLE
Web Accessibility

### ISSUE THREAD

**Issue by csharpfritz** [HTBox/allReady#2112]
Let's revisit the accessibility of the links and icons used in the application.

As a new developer on the project, I'm not familiar with what the icons and buttons lead to.  Let's ensure that appropriate link text is added to all buttons and links

**Comment by csharpfritz** [comment]
I don't think the tota11y plugin is accurately detecting "unclear text" in our application

**Comment by MisterJames** [comment]
@csharpfritz Is it fair to say that we can close this one per #2114 and perhaps organize an accessibility sweep across the UX?

**Comment by csharpfritz** [comment]
Agreed...  folks who are more familiar with accessibility could be focused on that sweep and help set some guidelines for future development

**Comment by stevejgordon** [comment]
I've opened a new high level UX discussion issue at #2197. Based on the above I'll close this one.
