### ISSUE TITLE
Display location on the activities page for a campaign

### ISSUE THREAD

**Issue by Harmonym** [HTBox/allReady#212]
Recommend displaying the location (at least the city & state detail in text - or ideally neighborhood if that field is included in the activity setup page for admins) next to the Map link on the activities summary page for a campaign to allow users to identify applicable locations with a minimum number of clicks.

![image](https://cloud.githubusercontent.com/assets/8798159/11017732/07fdef18-855e-11e5-8c26-e35b3360f603.png)

**Comment by MisterJames** [comment]
I'll start poking on this one.

**Comment by MisterJames** [comment]
@Harmonym I have taken this approach...seem reasonable?

![image](https://cloud.githubusercontent.com/assets/1197383/13549248/55dc9c86-e2c7-11e5-836e-b5f12e48a2e3.png)

This facilitates the display of both the campaign and activity location, if present.
