### ISSUE TITLE
Discussion: Remove Bower dependency

### ISSUE THREAD

**Issue by dchristensen** [HTBox/allReady#2127]
Currently when running `npm install` for the first time, we are getting the following warning:

```
npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path, but please help to create it: https://github.com/bower/bower/issues/2467
```

I think it would make sense to remove the additional Bower dependency and just use npm to manage client side dependencies.  This should remove a couple of steps from the initial project setup and in general make it easier for new contributors to get started.

**Comment by SteveStrong** [comment]
this is the right thing to do.
