### ISSUE TITLE
STARWEST USABILITY - Unhandled Exception when Selecting my organisation on main tab

### ISSUE THREAD

**Issue by robsab1960** [HTBox/allReady#2129]
When selecting the My Organization tab in the main page an unhandled exception is generated which leads to a stack trace and confusing error message.

The consequence of leaving this behaviour in the live system is that operators may be distracted and loose their focus or confidence in trying to confirm they are associated with the correct organization. 
[RS001_2017-10-04_10-34-52.pdf](https://github.com/HTBox/allReady/files/1356828/RS001_2017-10-04_10-34-52.pdf)

**Comment by dchristensen** [comment]
This issue should be moved to https://github.com/HTBox/crisischeckin

**Comment by stevejgordon** [comment]
Opened in crisis checking - closing here as not the correct repo
