### ISSUE TITLE
Registration - Organization Issue

### ISSUE THREAD

**Issue by polinav12** [HTBox/allReady#2130]
When registering, organization is not marked as mandatory, even though it is. Cannot register without organization.

**Comment by dchristensen** [comment]
This issue should be moved to https://github.com/HTBox/crisischeckin

**Comment by bharathbs** [comment]
Hello Team,

I would like to work on this issue.I am a newbie.Can anyone let me know whether I can pick this issue?

**Comment by dchristensen** [comment]
@bharathbs as I mentioned in my previous comment this issue actually belongs as part of the crisis checkin project, not AllReady.

**Comment by bharathbs** [comment]
@dchristensen I understood it.But I dont see this issue in the issue tracker for crisis project.Am I missing anything?

**Comment by dchristensen** [comment]
@bharathbs No, you are not missing anything. I had originally hoped that the project admins could move the issue, but that doesn't seem to be possible, so it will just need to be submitted on the Crisis Checkin issue tracker and this one closed.

**Comment by bharathbs** [comment]
@dchristensen ..Sorry to bother you..Can I submit it to Crisis Checkin Issue tracker or can anyone of the other participants do it?Would like to work on this item.

**Comment by dchristensen** [comment]
@bharathbs You can submit it, I would just reference this issue when submit it.

**Comment by bharathbs** [comment]
I have created a pull request for this issue in crisischeckin branch.Please feel free to close the issue.

https://github.com/HTBox/crisischeckin/pull/713
