### ISSUE TITLE
Mandatory Fields on Home Screen Issue

### ISSUE THREAD

**Issue by polinav12** [HTBox/allReady#2131]
Home Screen (once logged in) >> Make New Commitment >> Fill In All Fields and Click Volunteer >> fields under "Report New Data" is marked even though it is a separate field and you cannot make a new commitment. Even if you fill in the description field, it still shows an error.

**Comment by dchristensen** [comment]
This issue should be moved to https://github.com/HTBox/crisischeckin

**Comment by stevejgordon** [comment]
I've raised an issue in crisischecking - closing this as not correct repository
