### ISSUE TITLE
Campaign Manager can't create new Goals under "Manager Campaign" page

### ISSUE THREAD

**Issue by polinav12** [HTBox/allReady#2138]
Login as campaign manager. Click the "Manage Campaign" button and select a campaign. Click on the "Create New" button under Goals. You will see "Access denied due to insufficient permissions" on the page

**Comment by stevejgordon** [comment]
Closing as duplicate of #2146 

NOTE: this was raised first but have started discussion on #2146 already for validation of the permissions
