### ISSUE TITLE
CAMPAIGN MANAGER UNABLE TO EDIT EXISTING CAMPAIGN #STARWEST #FUNCTION

### ISSUE THREAD

**Issue by robsab1960** [HTBox/allReady#2139]
using AllReady Version: 1.0.0.0 c3ea2f2

Logged in as campaign manager: (campaignmanager@example.com)
- select campaigns
- select manage campaigns
- select an existing campaign
- select edit 
- change data in name field (we appended the text with one character)
- select save
- an unhandled exception takes place
- change has not been saved
[Gmail - Blowups happen.pdf](https://github.com/HTBox/allReady/files/1357151/Gmail.-.Blowups.happen.pdf)

**Comment by VishalMadhvani** [comment]
This was due to a the organisation dropdown not being populated as the CampaignManager user is not a Site or Organisation Admin.
In this case, it will now display the Organisation Name, instead of allowing the user to select an Organisation in a dropbox.
