### ISSUE TITLE
Social Share Buttons for Campaigns do not work

### ISSUE THREAD

**Issue by Harmonym** [HTBox/allReady#214]
It looks like the social share button functionality for a campaign has not yet been set up.
![image](https://cloud.githubusercontent.com/assets/8798159/11017743/3cbb8c2e-855e-11e5-9031-c806188b2ff6.png)

**Comment by JesseLiberty** [comment]
Duplicate of issue #188 (closed)

**Comment by BillWagner** [comment]
@JesseLiberty is right. Duplicate. Closed.
