### ISSUE TITLE
Campaign Manager Cannot Create a Campaign #STARWEST #Usability

### ISSUE THREAD

**Issue by robsab1960** [HTBox/allReady#2145]
There is no capability available through the manage campaign tab to allow a campaign manager to create a campaign.

It looks like you must have MORE priv than a campaign manager to create a campaign.

User was campaignmanager@example.com

**Comment by stevejgordon** [comment]
@robrich I believe this is correct. Only an Org or Site Admin can create new campaigns. A campaign manager can simply manage 1 or more campaigns after being granted access to them.
