### ISSUE TITLE
Campaign Manager Cannot add goals to a campaign STARWEST FUNCTIONALITY

### ISSUE THREAD

**Issue by robsab1960** [HTBox/allReady#2146]
Campaign manager cannot add goals to a campaign.

Attempting to add a goal to a campaign by a campaign manager generates an error message:

Access denied due to insufficient permissions.

Rob

**Comment by stevejgordon** [comment]
@schuback based on our earlier discussion regarding access I would assume we expect a campaign manager to be able to add goals. Just checking that you agree here?

**Comment by GProulx** [comment]
Hi @stevejgordon and @schuback 

I started working on fixing unit tests as mention on #2164 but I checked the original bug before going to far. Can you confirm that it's really the the expected behavior?

**Comment by MisterJames** [comment]
Yeah, I feel like either more is needed now to explain the original report (desired, intended, current behavior) else we should just close these out. Any thoughts here @robsab1960 or @stevejgordon ?
