### ISSUE TITLE
Some validations issues at Form

### ISSUE THREAD

**Issue by sofilibi** [HTBox/allReady#2148]
1.- Go to http://allready-test.azurewebsites.net/Account/Register
2.- Complete the form
![evidence_defect_form_validation_chrome](https://user-images.githubusercontent.com/4973956/31241074-61207878-a9c8-11e7-83dc-3d5ab49bf264.jpg)

3.- There are some missing validations, like: Name/last name should allow only alpha values
4.- Phone number text should allow only numbers

**Comment by joro550** [comment]
Raised https://github.com/HTBox/allReady/pull/2160 for this issue

**Comment by stevejgordon** [comment]
Closing as a PR was merged for this issue.

**Comment by thelem** [comment]
This has been implemented differently to what is described above, see #2160 for details (the pull request mentioned looks to be a followup rather than the main changes)
