### ISSUE TITLE
Privacy Policy missing Content

### ISSUE THREAD

**Issue by sofilibi** [HTBox/allReady#2149]
1.- Go to llready-test.azurewebsites.net/Home/PrivacyPolicy
2.- There is no content for PrivacyPolicy setting

![evidence_defect_privacypolicy_chrome](https://user-images.githubusercontent.com/4973956/31241437-77b91c92-a9c9-11e7-8b35-8e6556d30b09.jpg)

**Comment by stevejgordon** [comment]
@BillWagner I remember way back you were looking into the content for allReady privacy policy. Relevant also to #2103
