### ISSUE TITLE
Activity summary page for campaigns should have a campaign description summary field

### ISSUE THREAD

**Issue by Harmonym** [HTBox/allReady#215]
On the activity summary page for a campaign, above the activities, there should be a field that pulls a campaign summary description if the admin setting up the campaign provides one during set-up.  Should not be required, but would be helpful for users to be able to see descriptions of the campaign as a whole.

Placement recommendation: below the campaign name & date and above the "Activities for this campaign" header.  http://allready-dev.azurewebsites.net/Campaign/1 

![image](https://cloud.githubusercontent.com/assets/8798159/11017761/67bda43e-855e-11e5-8f3b-721850301ab5.png)

**Comment by danielepo** [comment]
It looks like this have been already solved

![campain](https://cloud.githubusercontent.com/assets/6214856/17480411/140fcb4e-5d78-11e6-9115-b6c5e5d20759.png)
