### ISSUE TITLE
Safety Kit Assembly Volunteer Day menu 404 error

### ISSUE THREAD

**Issue by atilabayat** [HTBox/allReady#2150]
1) Select - Safety Kit Assembly Volunteer Day 
2) Select - Humanitarian toolbox 
Result:  404 error with the following message

"404 :(

We went off the rails and couldn’t find your page! 
Don’t worry. We’ll get back on track."

Virtual

**Comment by VishalMadhvani** [comment]
I also noticed the "Campaigns" breadcrumb is unnecessary.
One would expect it to only show Campaigns for the given organisation, which is achieved by clicking on the Organisation.

**Comment by MisterJames** [comment]
This one is fixed/closed with #2156.
