### ISSUE TITLE
StarWest Usability - Safety Kit Distribution Weekend - Task - Calendar filtering reset

### ISSUE THREAD

**Issue by userstar00** [HTBox/allReady#2155]
As a User in the - Safety Kit Distribution Weekend - Task sections - After filtering using the calendar by a specific date, there was not an option to reset the calendar to see all the tasks.  

Additionally allow for the ability to filter the calendar by a series of dates.  For example, allow for selecting a weekend to check for tasks to volunteer for when available.

**Comment by mk0sojo** [comment]
It is possible to clear the filter with "Recycle Bin" icon at the bottom of the date picker.
If we want to use a range using something like this http://www.daterangepicker.com/ would look good I think or we can use two pickers of the one we are currently using like this (http://eonasdan.github.io/bootstrap-datetimepicker/#linked-pickers), but doesn't look as nice I think.
<img width="768" alt="dateselect" src="https://user-images.githubusercontent.com/15338483/32688767-302e627e-c6cf-11e7-8419-3e92464aa105.png">

**Comment by thomfresn** [comment]
Hi,

I've started adding a [Date Range Picker](http://www.daterangepicker.com/). 

![image](https://user-images.githubusercontent.com/31652551/33989870-58e24564-e0c9-11e7-906f-091bec357867.png)


I have a few questions regarding the current implementation using knockout.js. Would that be possible to be added to the Slack channel to see if these points were already adressed?

Thanks,

Thom

**Comment by jonparker** [comment]
Hi Tom @MisterJames should be able to add you.

**Comment by thomfresn** [comment]
Ok I had also sent an email to @tonysurma. 

Thanks.
