### ISSUE TITLE
Slack Channel Access Request

### ISSUE THREAD

**Issue by SteveKennedy** [HTBox/allReady#2159]
How active is the slack channel? When contributors have questions, it might be easier to get quick Q/A on Slack vs. opening an GitHub Issue.  Just my two cents.  I've sent a number of emails asking for access, but haven't gotten a reply. Can someone please add me?

**Comment by tonysurma** [comment]
I believe I found your email sent recently and added you just now, my apologies for any delays and thanks for reaching out and contributing!

**Comment by dchristensen** [comment]
@tonysurma can I get an invite as well?

**Comment by tonysurma** [comment]
email me at tony  dot   surma    at htbox.org  Thanks

**Comment by SteveKennedy** [comment]
This worked out great for me. Thank you. I think this issue can be closed, if @dchristensen thinks so too?

**Comment by MisterJames** [comment]
Thanks all!
