### ISSUE TITLE
moment javascript package contains security issues according to Node Security Platform

### ISSUE THREAD

**Issue by thomfresn** [HTBox/allReady#2184]
Hi,

I'm new on this project and while looking at the Web-App package.json file I noticed that, according to [https://nodesecurity.io/advisories/55](url), _moment is vulnerable to regular expression denial of service when user input is passed unchecked into moment.duration() blocking the event loop for a period of time._

It is suggested to update to version 2.11.2 or greater.

I'm note sure that the vulnerable function is actually used, but as it is referenced in the package dependencies, I thought it might be useful to report this warning.

Regards,

Thom

**Comment by jonparker** [comment]
Hi Tom,

Welcome to HTBox.
Thanks for creating this issue. I believe the vulnerability is only in the case where moment is running on a server and accepting multiple requests from clients. 
An attacker could then bring down the server with a denial of service attack.
However allReady doesn't have any nodejs running on the server side so this vulnerability shouldn't be an issue.
But thanks for raising it anyway.
Jon

**Comment by thomfresn** [comment]
Thanks for clarifying Jon.
