### ISSUE TITLE
Nomenclature for completed or archived Activities or Tasks

### ISSUE THREAD

**Issue by Harmonym** [HTBox/allReady#220]
There should be a standard naming convention for completed tasks or activities associated with an activity or campaign.  Currently "Show Old" is used on the Activity detail page and "Show Completed Activities" is used on the Campaign Activities summary page.

![image](https://cloud.githubusercontent.com/assets/8798159/11017776/50d456d6-855f-11e5-9d96-b4a91181f543.png)

![image](https://cloud.githubusercontent.com/assets/8798159/11017780/5a20f014-855f-11e5-9266-f7761fadb8b4.png)

I would recommend "Completed" or "Closed" as a uniform nomenclature.

**Comment by bluechrometouch** [comment]
I'd like to take this as it's similar to the bugs I'm working on. As some tasks or activities can be cancelled, Closed will be used.

**Comment by BillWagner** [comment]
Fixed in PR #310
