### ISSUE TITLE
Admin Forgotpassword view is missing

### ISSUE THREAD

**Issue by jonparker** [HTBox/allReady#2202]
http://allready-d.azurewebsites.net/Admin/ForgotPassword

An unhandled exception occurred while processing the request.
InvalidOperationException: The view 'ForgotPassword' was not found. The following locations were searched:
/Views/Admin/ForgotPassword.cshtml
/Views/Shared/ForgotPassword.cshtml
Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable<string> originalLocations)

Line 126 of AdminController.cs:
        //
        // GET: /Admin/ForgotPassword
        [HttpGet]
        [AllowAnonymous]
        public IActionResult ForgotPassword()
        {
            return View();
        }

**Comment by stevejgordon** [comment]
Reserved for codeathon

**Comment by duncangoodall** [comment]
I will assign this to me
