### ISSUE TITLE
Campaign Details (Admin) - Preview image should be limited to a thumbnail

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#2217]
When logged in as a site admin or org admin and viewing the campaign details page (in the admin area), the preview image may be very large if the uploaded image is big. We should limit the size of the image displayed to a much smaller scale so that it doesn't fill the page and push the main UI too far down.

See http://allready-d.azurewebsites.net/Admin/Campaign/Details/8

![image](https://user-images.githubusercontent.com/3669103/34955921-90dc4faa-fa1e-11e7-8d83-192ffc91f3da.png)

**Comment by stevejgordon** [comment]
Reserved for the .NET South East codeathon

**Comment by thelem** [comment]
I'm working on this

**Comment by thelem** [comment]
Before:
![image](https://user-images.githubusercontent.com/526619/35184476-16cd7616-fdee-11e7-9cfe-d751aee469b7.png)

**Comment by thelem** [comment]
After:
![image](https://user-images.githubusercontent.com/526619/35184594-c3fa8c2e-fdef-11e7-88e2-d8fe3130701b.png)

**Comment by stevejgordon** [comment]
PR merged
