### ISSUE TITLE
Campaign Details (Admin) - Edit button Not Clear

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#2218]
When logged in as a site admin or org admin and viewing the campaign details page (in the admin area), the edit button currently uses an icon but it's not very obvious from a UX perspective what this means.

We'll review the wider UX improvements but short term, recommend we at least adjust this to make the button say "Edit" rather than showing an icon.

**Comment by stevejgordon** [comment]
Reserved for the .NET South East codeathon

**Comment by jamesatgreymetis** [comment]
I'll take this
