### ISSUE TITLE
Campaign Details (Admin) - Delete button Not Clear

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#2220]
When logged in as a site admin or org admin and viewing the campaign details page (in the admin area), the delete button currently uses an icon but it's not very obvious from a UX perspective what this means.

We'll review the wider UX improvements but short term, recommend we at least adjust this to make the button say "Delete" rather than showing an icon.

**Comment by stevejgordon** [comment]
Reserved for .NET South East codeathon

**Comment by chdbdm** [comment]
I am working on this
