### ISSUE TITLE
Create Event - Display Campaign Date Range

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#2221]
When logged in as a site admin, org admin or campaign manager, you can create events in allReady.

The current rule is that the date on which the event occurs must be within the date range of the parent Campaign. Therefore, it would be better from a UX perspective to display the campaign start and end dates above the "Start Date" form field so that a user knows the allowed date range. This may help prevent validation failures which can be frustrating.

**Comment by stevejgordon** [comment]
Reserved for .NET South East codeathon

**Comment by jamesatgreymetis** [comment]
I'll take this one

**Comment by stevejgordon** [comment]
Closed in #2289
