### ISSUE TITLE
Campaign Details (Admin) - Hide Create New Event button when Campaign in Past

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#2222]
When logged in as a site admin or org admin or campaign manager, you can create events in allReady.

This is initiated from the admin campaign details page (e.g. http://allready-d.azurewebsites.net/Admin/Campaign/Details/1)

Above the events list there is a "Create New" button. It makes sense to hide this button when the end date of the campaign is in the past. This will avoid someone trying to create new events in the past also.

It would be best to hide the button and instead display a message such as:
"It is now past the end date for this campaign. No new events can be created."

**Comment by stevejgordon** [comment]
Reserved for .NET South East codeathon

**Comment by samsonprojects** [comment]
I will work on this

**Comment by chdbdm** [comment]
EventViewModel.IsClosed parameter can be used for checking visibility
