### ISSUE TITLE
Create Resource - Form changes (Part 1)

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#2233]
When logged in as a site admin, organization admin or campaign manager, the user can create new resources against a campaign in allReady.

Having reviewed the UX of this form we should add a visual clue (probably an asterisk) to required fields. Currently a user cannot identify these fields until they submit a form with any incomplete, required fields.

The following fields are currently considered required and should be marked with a red asterisk:
Resource Name
Resource URL

We should include a message "Fields marked with an * are required" message at the top of the form.

**Comment by stevejgordon** [comment]
Reserved for .NET South East

**Comment by thelem** [comment]
I'll pick this up
