### ISSUE TITLE
Send Campaign Manager Invite - Form changes

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#2234]
When logged in as a site admin, organization admin or campaign manager, the user can invite people to become Campaign Managers for a campaign in allReady.

Having reviewed the UX of this form we should add a visual clue (probably an asterisk) to required fields. Currently a user cannot identify these fields until they submit a form with any incomplete, required fields.

We should make the following changes on this form:
- The Email field is considered required and should be marked with a red asterisk
- We should include a message "Fields marked with an * are required" message at the top of the form.
- We should rename the "Message" field label to say "Custom message"

**Comment by stevejgordon** [comment]
Reserved for .NET South East

**Comment by redware** [comment]
I will look at this.
