### ISSUE TITLE
Send Campaign Manager Invite - Missing cancel button

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#2235]
_**NOTE: To be picked up after #2234 is completed and merged.**_

When logged in as a site admin, organization admin or campaign manager, the user can invite people to become Campaign Managers for a campaign in allReady.

Currently if you navigate to the send invite page, there is no way to cancel and return. The breadcrumbs allow navigating back but this might not be obvious for a user. Can we add a "Cancel" button as we have on other forms that also returns the user to the correct Campaign Details page.

**Comment by stevejgordon** [comment]
Reserved for .NET South East codeathon

**Comment by redware** [comment]
I will look at this.
