### ISSUE TITLE
Event Details (Admin) - Edit button Not Clear

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#2237]
When logged in as a site admin or org admin and viewing the event details page (in the admin area), the edit button currently uses an icon but it's not very obvious from a UX perspective what this means.

We'll review the wider UX improvements but short term, recommend we at least adjust this to make the button say "Edit" rather than showing an icon.

**Comment by stevejgordon** [comment]
Reserved for .NET South East codeathon

**Comment by MartinDigon** [comment]
I'm looking at this one. Are we talking about this icon?
![image](https://user-images.githubusercontent.com/205956/35182572-9498c8c6-fdcf-11e7-9dae-96b974c06425.png)

**Comment by stevejgordon** [comment]
@MartinDigon - It's actually the button on a URL such as http://allready-d.azurewebsites.net/Admin/Event/Details/1

**Comment by MartinDigon** [comment]
That icon is in use in 9 places; do we want it change to text "Edit" in all of them, or just the Event details page?
![image](https://user-images.githubusercontent.com/205956/35183012-e027d50a-fdd6-11e7-9eda-93bb556c48d7.png)
