### ISSUE TITLE
Create Task - Form Changes

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#2239]
When logged in as a site admin, organization admin, campaign manager or event manage, the user can create new tasks against an event in allReady.

Having reviewed the UX of this form we should add a visual clue (probably an asterisk) to required fields. Currently a user cannot identify these fields until they submit a form with any incomplete, required fields.

Please make the following changes:

1. The Name field is considered required and should be marked with a red asterisk
2. We should include a message "Fields marked with an * are required" message at the top of the form.
3. The "Name" label should be renamed to "Task Name"

**Comment by stevejgordon** [comment]
Reserved for .NET South East codeathon

**Comment by djhmateer** [comment]
Working on this

**Comment by stevejgordon** [comment]
PR Merged
