### ISSUE TITLE
Create Task - Display Event Date Range

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#2240]
When logged in as a site admin, org admin, campaign manager or event manager, you can create tasks for an event in allReady.

The current rule is that the date on which the task occurs must be within the date range of the parent Event. Therefore, it would be better from a UX perspective to display the event start and end dates above the "Start Date" form field so that a user knows the allowed date range. This may help prevent validation failures which can be frustrating.

**Comment by stevejgordon** [comment]
Reserved for .NET South East codeathon

**Comment by jamesatgreymetis** [comment]
I'll take this one

**Comment by MartinDigon** [comment]
May be worth you doing #2221 at the same time, sounds very similar.
