### ISSUE TITLE
Event Details (Admin) - Hide Create New Task button when Event in Past

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#2241]
When logged in as a site admin or org admin, campaign manager or event manager, you can create Tasks for Events in allReady.

This is initiated from the admin campaign details page (e.g. http://allready-d.azurewebsites.net/Admin/Event/Details/18)

Above the tasks list there is a "Create Task" button. It makes sense to hide this button when the end date of the event is in the past. This will avoid someone trying to create new tasks in the past also.

It would be best to hide the button and instead display a message such as:
"It is now past the end date for this event. No new tasks can be created."

**Comment by stevejgordon** [comment]
Reserved for .NET South East codeathon

**Comment by redware** [comment]
I will look at this if that is OK.
