### ISSUE TITLE
Task Details - Message All Volunteers model required fields

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#2243]
When logged in as a site admin, org admin, campaign manager or event manager, you can view the details of tasks for an event in allReady. Once in the task details page you can then click a button to "Message All" volunteers.

This displays a modal which includes two fields. Both are required.

Having reviewed the UX of this form we should add a visual clue (probably an asterisk) to required fields. Currently a user cannot identify these fields until they submit a form with any incomplete, required fields.

We should highlight both fields as required using a red asterisk and include a message "Fields marked with an * are required" message on the form.

**Comment by stevejgordon** [comment]
Reserved for .NET South East

**Comment by redware** [comment]
I will have a look here if that is OK.

**Comment by redware** [comment]
Steve - the solution you proposed was to hard code the div containing the required field as follows and (elsewhere) modify the CSS:
 <div class="form-group required">

This might not be optimal as it is not working from the dataannotations but in my case here where the modal attributes do not seem to be in the model - ideal.
