### ISSUE TITLE
Event Details (Public) - Add Social Share Buttons

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#2245]
We have publicly facing events in the allReady site which can be browsed by users, including public, unauthenticated users.

e.g. http://allready-d.azurewebsites.net/Event/1

It would be nice to include social share buttons on the event details page to allow people to easily share the event. We have this behaviour on the campaign details page currently so can hopefully replicate it for events.

**Comment by stevejgordon** [comment]
Reserved for .NET South East codeathon

**Comment by dracan** [comment]
I'll take this one.
