### ISSUE TITLE
Provide Administrative Controls to Unlock Users

### ISSUE THREAD

**Issue by MisterJames** [HTBox/allReady#2246]
Per the issue logged in #1134 we are going to need the ability for organization admins (by role) to unlock users through the administrative controls. There is an existing list of users at http://localhost:[YOUR PORT]/Admin/Site that would work for this.

![image](https://user-images.githubusercontent.com/1197383/35008525-6bd09848-fac2-11e7-9273-de26bd7da6d8.png)

This issue will be considered complete when there is UI to show that a user is locked out, and a way for the Admin to unlock it.

**Comment by berthertogen** [comment]
I can take this one
