### ISSUE TITLE
Re-use component for editing Locations

### ISSUE THREAD

**Issue by morcs** [HTBox/allReady#2287]
In Campaign\Edit.cshtml the location fields are rendered using

`@Html.EditorFor(m => m.Location)`

In Event\Edit.cshtml the markup is inline. It looks like we could just re-use the EditorFor here. The only differences I can see are:

`if (Model.EventType == EventType.Rally)` it sets the "Address 1" field to have `data-val-required`, but I think we might be requiring an address on all events anyway, and using EditorFor will include this. 

There's an extra CSS class `location-address1` too but searching the code it seems to be unused.

**Comment by stevejgordon** [comment]
Looks like this can be closed
