### ISSUE TITLE
Campaigns Lister Page (Admin) Update button to use text rather than an icon

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#2291]
On the Administrator Campaigns Lister Page (e.g. http://allready-d.azurewebsites.net/Admin/Campaign) we have a publish button which is shown if the campaign is in draft.

This uses a very unclear icon. We should replace the icon with the text "Publish" instead. Here is the current button...

![image](https://user-images.githubusercontent.com/3669103/35185478-0c987fa6-fdfd-11e7-9aae-0018e654dd40.png)

**Comment by thelem** [comment]
I'll do this

**Comment by djhmateer** [comment]
Working on this too

**Comment by MisterJames** [comment]
Closed via #2292
