### ISSUE TITLE
Update publish button in Campaign Details page

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#2295]
In issue #2291 we are updating the publish icon on the Campaign Lister page. This button also appears in the Campaign details page (e.g. Campaign/Details/1) when that campaign is not marked as published.

Once #2291 is complete, we should update this button on the campaign details page as well.

**Comment by MisterJames** [comment]
I'll put my hand up on this one?

Where is the best place to start looking?

**Comment by stevejgordon** [comment]
Sure thanks for helping out.

You should be able to find this code in the "Admin" area folder > Views folder
