### ISSUE TITLE
Set Default TimeZoneId claim when a new user registers

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#2296]
It looks like when register a new user we don't set a default TimeZoneId claim. Since the claim only gets updated if the user then changes it in their My Account page (only updated if the value actually changed from the model originally rendered) it means quite often a user doesn't get a claim for this.

We should set a default for new users since we don't offer this on the registration form.

**Comment by NRKirby** [comment]
I see claims are set in the Register POST action [here](https://github.com/HTBox/allReady/blob/5364d7fbbd39f2cefded10d98884742a345d7abe/AllReadyApp/Web-App/AllReady/Controllers/AccountController.cs#L156) and there is a `TimeZoneId` claim type

- What should it be set to?
- Once this is set, where else in the app should this claim should be used?

If you could give me a broad idea of what's involved to resolve this issue I will see if I can look at it in the next week of so.

**Comment by stevejgordon** [comment]
@NRKirby Sorry for the delay.

I've just tried to replicate this and not been able to. I'm therefore going to close this out for now.
