### ISSUE TITLE
Update jQuery Libraries to Current Stable Version

### ISSUE THREAD

**Issue by MisterJames** [HTBox/allReady#2300]
We need someone to assess the web project for a bump to a stable, compatible version of jQuery in the UI.

**Comment by jonparker** [comment]
This kind of front end update is a great reason for having automated UI tests which would allow you to upgrade jQuery and then take a screenshot of each screen as part of the tests and then review them for any layout/styling issues with the new version. Obviously maintaining a suite of UI tests adds overhead to each feature but it does have its advantages.

**Comment by stevejgordon** [comment]
Looks like this is closed with #2303
