### ISSUE TITLE
STAREast: Urgent: Cannot Log In

### ISSUE THREAD

**Issue by DanniRiggin** [HTBox/allReady#2319]
*Observed Behavior* 
Attempted to log in as user, organization, eventmanager, and campaignmanager@example.com and am currently unable to log in. 
Attempted both typing the password in the box, and typing the password on another screen for copy paste to make sure to check spelling. 
Was unable to log in. 

*Expected Behavior* 
Should be able to log in. 😭

**Comment by stevejgordon** [comment]
Hi @DanniRiggin - Sorry for the delay. Is this on the live test site (http://allready-d.azurewebsites.net) or locally? I've just tested on the live site and been able to login for that user.

**Comment by DanniRiggin** [comment]
Hi @stevejgordon we were unable to log onto the test site at STAREast. I also just checked now and was able to log on. Not sure what happened!

**Comment by mk0sojo** [comment]
Can be closed?

**Comment by DanniRiggin** [comment]
@mk0sojo I believe this can be closed
