### ISSUE TITLE
Zip code to street address references

### ISSUE THREAD

**Issue by Harmonym** [HTBox/allReady#232]
The search for activities from the home page is based upon zip code, but the campaigns, tasks, & activities may have location indicated by a street address w/ city & state without a zip code. Should add geocode capabilities that would be able to pull results for a zip code-based request from the street addresses.

**Comment by Harmonym** [comment]
Similar to #193

**Comment by cecilia-donnelly** [comment]
+1 on this and #234.

**Comment by stevejgordon** [comment]
As with related issues, we no longer include the search and do have some geo-coding in place. Closing.
