### ISSUE TITLE
Rename "viewmodel" types to be model types

### ISSUE THREAD

**Issue by rockfordlhotka** [HTBox/allReady#235]
As an example, `ActivityDetailViewModel` is really a DTO that is used to flow data from the view/controller to the `EditActivityCommandHandler` where the values are used to update EF entity objects (and thus the database).

That pattern is used in several places, and the use of the term _viewmodel_ is somewhat confusing because these objects are really just DTO _models_.

This request is to change type names such as `ActivityDetailViewModel` to `ActivityDetailModel`

**Comment by bluechrometouch** [comment]
"ViewModel in ASP.NET MVC practice is the same as the DTO, however ViewModel in MVVM pattern is different from DTO because ViewModel in MVVM has behaviors but DTO does not have."

https://stackoverflow.com/questions/1982042/dto-viewmodel

**Comment by BillWagner** [comment]
Fixed in PR #253
