### ISSUE TITLE
Error when signing up to the mail list 

### ISSUE THREAD

**Issue by p0onage** [HTBox/allReady#2361]
I was hoping to get added to the mail list and look out for any work I could support around COVID-19 and brining awareness but I was got an internal error when trying to sign up

![image](https://user-images.githubusercontent.com/6472111/79337527-8fb4ee80-7f1d-11ea-9129-43d6d6fe9eea.png)

**Comment by jonparker** [comment]
Hi @p0onage,
The allready project hasn't been active for quite a few months (at least new development hasn't been happening)

If you contact Richard Campbell directly via twitter he may be organising something that he needs help with.

**Comment by jonparker** [comment]
His Twitter is (@richcampbell): https://twitter.com/richcampbell?s=09

**Comment by p0onage** [comment]
Thanks @jonparker i'll drop a message
