### ISSUE TITLE
"All registered campaigns" header capitalization

### ISSUE THREAD

**Issue by Harmonym** [HTBox/allReady#237]
Header capitalization should be "All Registered Campaigns"

![image](https://cloud.githubusercontent.com/assets/8798159/11018204/61e71378-8573-11e5-9f8e-690bf66e42ad.png)

http://allready-mvp.azurewebsites.net/Campaign

**Comment by bluechrometouch** [comment]
I can fix this.

**Comment by BillWagner** [comment]
Fixed in PR #310
