### ISSUE TITLE
5.1.1.1.2	Allow citizens to search for campaigns by organization, keyword(s), and geography covered

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#24]
zipcode for now

**Comment by binaryjanitor** [comment]
Working on this.

**Comment by shawnwildermuth** [comment]
Was this completed? (Pull requests were merged but issue wasn't closed)

**Comment by BillWagner** [comment]
Thanks for finding that. The PR didn't use the text for GitHub to pick it up.
Fixed in PR #63
