### ISSUE TITLE
Eliminate usage of GlyphIcon

### ISSUE THREAD

**Issue by shawnwildermuth** [HTBox/allReady#241]
We're using Glyphicon from bootstrap, but it's going away in Bootstrap 4 and FontAwesome looks so much better (and we're already using so the icons are mixed). 

(I'm taking this one)

**Comment by stimms** [comment]
I did a quick look through the project and couldn't find anywhere where these icons were being used.

**Comment by dpaquette** [comment]
Agreed this is safe to close
