### ISSUE TITLE
Simplify Logo/Image upload on Campaign Edit page

### ISSUE THREAD

**Issue by MisterJames** [HTBox/allReady#246]
This is already WIP, tracking it seperately now (from #35).

**Comment by MisterJames** [comment]
@joelhulen and @BillWagner it looks like this was completed and merged in via #246. Joel, can you please confirm that this is the case and we can close this off?

**Comment by joelhulen** [comment]
This is closed.

I know Simon Kittle was working on a couple of enhancements, so don't know
where he is in the process.

**Comment by ksk100** [comment]
All the stuff I was doing was merged with PR #335
