### ISSUE TITLE
Add button to populate contact info from organization on Campaign Edit page

### ISSUE THREAD

**Issue by MisterJames** [HTBox/allReady#249]
The page should load with contact information from the organization. A button should allow users to easily populate the contact details with that data. From #35.

**Comment by bcbeatty** [comment]
I take this.

**Comment by bcbeatty** [comment]
This is the workflow I'm thinking

Contact Fields
* First
* Last
* Phone
* Email
* Mailing Address -- stored in Location table

- [ ] Organization Edit - Editable
- [ ] Organization Details - read only  
- [ ] Campaign Edit - When the button is pressed copy Organization Contact fields into Campaign data entry fields, do not save automatically
- [ ] Campaign Detail - Read only view

**Comment by tonysurma** [comment]
Organizations have contact info close to your list:
* Name (maybe first last maybe "operations support" who knows)
* Phone
* Email
* Address
and then that flows down to campaigns as you stated (workflow wise)

**Comment by stevejgordon** [comment]
NDC note - Looks like this isn't completed and we need to expose a way to copy the contact information for the Org when adding a new campaign.

My proposal would be to load the org contact info into the view model and render it near the campaign Primary Contact fields. Add a checkbox to use Org info which is selected hides the specific fields in the UI.

![image](https://cloud.githubusercontent.com/assets/3669103/22020437/2dec8400-dcb0-11e6-88f2-da4aa882b363.png)

We can then use that value to determine what data to save on the post action/handlers.

Validation will also need to be reviewed and updated as appropriate.

**Comment by Diana380** [comment]
I have started looking into this.

**Comment by naeemsarfraz** [comment]
Hey, how are you getting on with this @Diana380?

**Comment by stevejgordon** [comment]
We'll consider this open for takers again now.

**Comment by c0g1t8** [comment]
I'll take a preliminary look 😄

**Comment by c0g1t8** [comment]
@tonysurma I think I have a handle on this one.  Please assign me.

@stevejgordon I'm going to implement you proposal above (Jan 17 comment).

**Comment by c0g1t8** [comment]
Looks like most of the work has been done already.  I found this in the view `Edit.cshtml`.

```
            @if (User.IsUserType(UserType.OrgAdmin))
            {
                <button type="button"
                        id="btnGetContactInfo"
                        class="btn btn-info"
                        data-toggle="modal"
                        data-target="#confirmContactModal"
                        title="Copy Contact Information from Organization">
                    Copy Contact Info
                </button>
            }
```

The button only appears only if the logged in user is an **OrgAdmin**.   The Administrator@example.com is not an **OrgAdmin**.  Thus no button appears.  I think we should simply remove the check for **OrgAdmin**.

The button does more than copy over the Primary Contact information from the organisation.  It also copies the location information.  Is that okay?  If so, we should do some renaming to make this is clear.

There is also a question of where to place the button. 
 
![image](https://cloud.githubusercontent.com/assets/23250332/24483888/c5c6a666-14af-11e7-90a8-14259c1c8753.png)

I think it should be lower down on the page closer to the location and contact information.

@stevejgordon @MisterJames Any guidance?

**Comment by c0g1t8** [comment]
@stevejgordon 

> My proposal would be to load the org contact info into the view model and render it near the campaign Primary Contact fields. Add a checkbox to use Org info which is selected hides the specific fields in the UI.

Rendering the organisation contact information looked like a good idea when I first looked at the issue.  When I looked further at the form, there is a drop down for organisations.  That would mean that the rendering should change to match the organisation selected.

**Comment by c0g1t8** [comment]
I've got the following showing on the page

![image](https://cloud.githubusercontent.com/assets/23250332/24540813/a86cba6a-15a9-11e7-9014-a208ae020676.png)

I'm using a glyph for the button to paste/copy the contact information.  I think it's let's obtrusive. 

I'm still awaiting feedback on if the location information from the organisation should also be copied over as well.

**Comment by tonysurma** [comment]
Location info should come over as well

**Comment by c0g1t8** [comment]
@tonysurma Thanks- I'll have a PR for you tomorrow.

**Comment by c0g1t8** [comment]
@tonysurma I think this issue can be closed.
