### ISSUE TITLE
5.1.1.1.3	Allow citizens to view campaign details as entered by organization as well as deliver to date vs goals information and targets

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#25]
e.g. 1500 / 39000 smoke detectors installed & plan to install ~2K per week until end of 2016

**Comment by bcbeatty** [comment]
What is the definition of a citizen?

**Comment by tonysurma** [comment]
citizen = unauthenticated users and this was before we had campaign pages that someone can see.  Once we can show campaigns this is done and requires no separate work (see @joelhulen 's work)

**Comment by MisterJames** [comment]
Already implemented as part of #250 (thermometer and display of goals).
