### ISSUE TITLE
5.1.1.1.4	Allow citizens to click through to links to other websites with related information as provided by organization

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#26]
[later functionality will include direct ‘request/decline’ interaction]

**Comment by binaryjanitor** [comment]
Working on this.

**Comment by mheggeseth** [comment]
I think this issue should be clarified and reconciled (and probably re-opened). PR #26 implements this as a list of external references (called Resources) to be displayed in the Campaign detail view `Views\Campaign\Details.cshtml` however, it's somewhat unclear how some things in the implementation align with the original issue:
* A resource is not currently associated with a campaign or any other model object.
* Looks like Resources are intended to be retrieved and shown in the Campaign detail view by a "category tag string" (`ResourceApiController.GetResourcesByCategory`) which doesn't seem to live anywhere else in the database.
* Resources have properties that suggest they are time-sensitive (`PublishDateBegin`, `PublishDateEnd`) but it's not clear why that's necessary.

The current title of this issue makes it seem like this would just be a list-o-links associated with an org/campaign/activity/task which suggests that the Resource approach (even when fully-implemented) may be overkill. 

Can you also clarify the "request/decline" workflow? That is, who requests, who declines, and why. If it's an enhancement to the original issue, it should be split off into its own issue.
