### ISSUE TITLE
Our appveyor build should precompile the razor views

### ISSUE THREAD

**Issue by BillWagner** [HTBox/allReady#260]
This is waiting on some new support from asp.net 5, but when that is supported, we should build the razor views as part of the cheks on PRs.

**Comment by dpaquette** [comment]
Experimented with this a little today and could not get the build to fail when there were errors on a razor page. I will revisit once the next version of aspnet5 is released.

**Comment by mheggeseth** [comment]
@tonysurma Can close this as dupe of #972.
