### ISSUE TITLE
Profile Set-up Prompt

### ISSUE THREAD

**Issue by Harmonym** [HTBox/allReady#262]
If a user has not set up a profile (name, e-mail, phone#, phone# type drop-down), add a symbol prompt (exclamation icon nag or similar) to the top right near the "Hello [username]" to prompt users to complete their profile.  Perhaps with a text prompt on hover.

**Comment by MisterJames** [comment]
@dpaquette Did I see you working on a feature related to this one?

**Comment by dpaquette** [comment]
Yes, I was working on something like this. The trick is doing this without adding huge overhead to every request.

**Comment by dpaquette** [comment]
Assign this one to me. I will tackle this task next

**Comment by MisterJames** [comment]
@dpaquette Let's touch base on this one (DM on Slack is fine)...I had a couple of ideas here.

**Comment by tonysurma** [comment]
@dpaquette @MisterJames is this still open or is it covered by the PRs?

**Comment by dpaquette** [comment]
This was covered in #515 . This issue can be closed
