### ISSUE TITLE
Editing Campaigns through the Admin side. 

### ISSUE THREAD

**Issue by smille1834** [HTBox/allReady#266]
The time function when creating/editing campaigns isn't working when I tried to edit times for the Pillowcase campaign I created. Since campaigns can run weeks, months, or years, do we even need times at that level? Time specificity seems most useful at the activity and task levels.

**Comment by tonysurma** [comment]
The decision was to remove times.  I can't recall if this was covered by another issue.

**Comment by dpaquette** [comment]
Is there anything to do here?

**Comment by tonysurma** [comment]
If campaigns only have dates to enter (not times) then we are good. I can verify later/tomorrow

**Comment by tonysurma** [comment]
confirmed it's done
