### ISSUE TITLE
Enable admins to set/edit time for tasks

### ISSUE THREAD

**Issue by Harmonym** [HTBox/allReady#270]
Admin should be able to set and edit the start and end time for tasks.

**Comment by dpaquette** [comment]
Related to #268

**Comment by dpaquette** [comment]
Can someone assign this to me?

**Comment by dpaquette** [comment]
Working on a solution for this and #268 that uses bootstrap datetime picker. 

Would everyone be okay with the following? Maybe not indefinitely but at least to get us through this milestone.
![DateTimePicker](https://cloud.githubusercontent.com/assets/2531875/11201341/594660b8-8cab-11e5-95b6-a5e2adbbe00d.png)

**Comment by OhMcGoo** [comment]
It's not going to bother our volunteers as we use the same one in our incident management application, DCSOps:

<img width="620" alt="date-time picker" src="https://cloud.githubusercontent.com/assets/4147733/11201488/50be80b2-8ca4-11e5-9636-0fe20453a760.png">

**Comment by tonysurma** [comment]
Yeah I'm all good with it altho you have me intrigued to what you have up your sleeve that makes this so passé :smile:

**Comment by tonysurma** [comment]
@dpaquette when you are fixing this can you verify you are also fixing #268 I think that is basically a duplicate of this one but keeping both so we make sure both scenarios work

**Comment by dpaquette** [comment]
@tonysurma  Yup, working on both
