### ISSUE TITLE
Tasks should inherit date range boundries of the Activity

### ISSUE THREAD

**Issue by Harmonym** [HTBox/allReady#276]
The start and end date for the tasks should be within range of the activity it is associated with.  The date and time of the activity can be edited by the admin within the range.

 - [ ] Default the dates on tasks to the dates of the activity
 - [ ] Display a warning to the user (an exclamation indicator, for instance) if the dates are out-of-range of the activity, but allow saving

**Comment by bluechrometouch** [comment]
I can add the validation for this area.

**Comment by MisterJames** [comment]
@Harmonym Should this be a hard rule or a warning?

For example, if an activity is set up from 6-10 pm it makes sense that most tasks are in that range. But say the organizer wanted to also have a "clean up" task or a "postmortem" task, manager meeting, etc?

Would it make sense just to put a little exclamation mark (client-side validation) during entry? And perhaps that same mark beside the list view? Hovering over the mark would say "This task is outside of the currently scheduled activity times."

In this way, the organizer doesn't have to back track out of the edit task workflow. 

As well, if you like this suggestion, I would recommend having a "Fix scheduled times" button on the activity screen...this would set the times of the activity to the outer bounds of all the combined tasks.

Thoughts?

**Comment by tonysurma** [comment]
@MisterJames of course I let @Harmonym and @smille1834 chime in but I think what you are proposing is right on as it isn't a hard limit.  That being said the activity will probably include setup and teardown times so when the volunteers are volunteering they know the possible timeframes for all tasks in that activity.

**Comment by Harmonym** [comment]
@MisterJames I agree with your recommendation and Tony's feedback.  The only thing I would add is that I think it would be nice if the calendar selector for the task starts on the month that reflects the start month for the activity.  So for example if an activity was set to run from December through February, when the admin selects to add a task the start date calendar would default to December, but would be editable.  The end date would be similar. The idea is to streamline that process a bit without restricting them.

**Comment by MisterJames** [comment]
@bluechrometouch I've added a couple of notes from this thread to the description, please feel free to run with it!

**Comment by bluechrometouch** [comment]
Back from Thanks giving. I agree that there should not be a hard limit as people might always need more time on a task or campaign. Thanks, will work on this.

**Comment by bluechrometouch** [comment]
![capture](https://cloud.githubusercontent.com/assets/14866579/11545047/b8d95146-990a-11e5-8168-17c78f8d1ba3.JPG)
