### ISSUE TITLE
Admin Edit Activity - Image Upload vs URL

### ISSUE THREAD

**Issue by Harmonym** [HTBox/allReady#278]
For the admin edit activity form, the Image field is labeled as "ImageURL", but the field is actually a Browse to upload file. This should be browse and upload across all image fields.

![image](https://cloud.githubusercontent.com/assets/8798159/11022775/70991336-861c-11e5-937f-9af65cabc8bc.png)

**Comment by ksk100** [comment]
I'll do this.

@Harmonym, did you mean that the prompt should be 'Browse and upload' across all image upload fields on the site?

**Comment by Harmonym** [comment]
I meant the field type vs image URL. When I was testing there was variance in the field types across the site.

Sent from my Windows Phone
________________________________

**Comment by ksk100** [comment]
Okay no problem; I was just checking whether you were specifying a particular prompt - 'Browse and upload' - that you wanted as a replacement for `ImageURL`.
