### ISSUE TITLE
Image upload for Activity page

### ISSUE THREAD

**Issue by Harmonym** [HTBox/allReady#281]
In my first attempt to upload an image to the Activity page as an admin, I received a 500 error.

![image](https://cloud.githubusercontent.com/assets/8798159/11022870/300e41c6-861f-11e5-8cf0-8b7231313240.png)

In my second attempt, I received an untangled exception error.
An unhandled exception occurred while processing the request.

FormatException: No valid combination of account information found.

Microsoft.WindowsAzure.Storage.CloudStorageAccount.<>c.<Parse>b__87_0(String err)
 Stack 
  Query 
  Cookies 
  Headers 
 

FormatException: No valid combination of account information found.

Microsoft.WindowsAzure.Storage.CloudStorageAccount.<>c.<Parse>b__87_0(String err)

Microsoft.WindowsAzure.Storage.CloudStorageAccount.ParseImpl(String connectionString, CloudStorageAccount& accountInformation, Action`1 error)

Microsoft.WindowsAzure.Storage.CloudStorageAccount.Parse(String connectionString)

AllReady.Services.ImageService.<UploadImageAsync>d__6.MoveNext() in ImageService.cs

61.                var account = CloudStorageAccount.Parse(_settings.StorageAccount);

--- End of stack trace from previous location where exception was thrown ---

System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

AllReady.Services.ImageService.<UploadActivityImageAsync>d__4.MoveNext() in ImageService.cs

44.            return await UploadImageAsync(blobPath, image);

--- End of stack trace from previous location where exception was thrown ---

System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

AllReady.Areas.Admin.Controllers.ActivityController.<PostActivityFile>d__12.MoveNext() in ActivityAdminController.cs

220.            a.ImageUrl = await _imageService.UploadActivityImageAsync(a.Id, a.Tenant.Id, file);

--- End of stack trace from previous location where exception was thrown ---

System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

Microsoft.AspNet.Mvc.Controllers.ControllerActionExecutor.<CastToObject>d__8`1.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker.<InvokeActionAsync>d__6.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)

Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeActionFilterAsync>d__50.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeAsync>d__41.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler.<RouteAsync>d__6.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

Microsoft.AspNet.Routing.Template.TemplateRoute.<RouteAsync>d__27.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

Microsoft.AspNet.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

Microsoft.ApplicationInsights.AspNet.ExceptionTrackingMiddleware.<Invoke>d__4.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

Microsoft.AspNet.Diagnostics.Entity.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

Microsoft.AspNet.Diagnostics.Entity.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

Microsoft.AspNet.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__6.MoveNext()

**Comment by ksk100** [comment]
This might be a configuration issue: if you run with `UseDevelopmentStorage` (it might be `DevelopmentStorage`) as `true` and attempt to access Azure storage I think this is the message you get.  But it might also arise if `AzureStorage` is misconfigured in other ways?

Running the site locally, I can successfully upload an image to Azure.

**Comment by ksk100** [comment]
I can duplicate the second error above.

Can anyone confirm the form of the connection string that is used for `Data:Storage:AzureStorage` on `http://allready-d.azurewebsites.net/`?

On my local machine I have a string of the form:

`DefaultEndpointsProtocol=https;AccountName=simonkittle;AccountKey=<removed>`

No other items, no whitespace.  And it works okay.

**Comment by tonysurma** [comment]
My goodness.  There was a space between the ; and 'A' in AccountName that was causing this :-1: 

Fixed now.  Thanks all.
