### ISSUE TITLE
Add privacy policy statement.

### ISSUE THREAD

**Issue by Harmonym** [HTBox/allReady#294]
Need to create a privacy statement, which needs to be linked from all pages in the footer.

**Comment by Harmonym** [comment]
Tony - I think Pasquale mentioned he was going to craft/find boilerplate language for this, but wanted to make sure we note it before it goes live for users & he doesn't appear to be a user I can tag.

**Comment by BillWagner** [comment]
@Harmonym @tonysurma This might be more complicated. HTBox should have a privacy statement that addressed what HTBox will / won't do with any information. In addition, each organization (tenant) should also be required (or able?) to have its own privacy statement. After all, each org admin will also be able to see private information.

**Comment by Harmonym** [comment]
Totally agree. I thought Pascale had motioned something, but you're right, makes sense to have the orgs supply one. I mostly just want to make sure it is noted & we are not taking any liability for the information handling.

Sent from my Windows Phone
________________________________

**Comment by stevejgordon** [comment]
Seeing this is a P1 in the current milestone I'd like to see if I can help here. @BillWagner Do we have any wording available we can use.

It sounds like we ideally need a AllReady page, linked from the footer that will host the general site policy.Then potentially we need a way for org admins to add their own privacy policy text and if that's available perhaps put a link within their campaigns and activities.

If this sounds like the correct approach I could get the placeholder pages and system to manage the policies started?

**Comment by BillWagner** [comment]
Assigned to @stevejgordon

**Comment by tonysurma** [comment]
pinging @Schuback on language for default privacy policy per conversation way back in November

**Comment by schuback** [comment]
Got it.  Working on it today.

On Sun, Feb 21, 2016 at 9:22 AM, Tony Surma <notifications@github.com>
wrote:

> pinging @Schuback <https://github.com/Schuback> on language for default
> privacy policy per conversation way back in November
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HTBox/allReady/issues/294#issuecomment-186862703>.
>



-- 

Pascal Schuback
pascal@schuback.com
206.414.8799
@schuback
