### ISSUE TITLE
5.1.1.2.3	Volunteer contact information is stored along with the skills/resources needed they selected within the system and a link is provided via email to campaign organization owner and recorded in system

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#30]
As a volunteer, when I offer my help to a campaign:
 - [ ] My contact details and the skills I select are stored in the system.
 - [ ] The campaign organizer is notified that there is a new volunteer registered, with a link in the email to view the list of volunteers on the site.

**Comment by MisterJames** [comment]
@tonysurma would these bullet points work as deliverables? (updated the comment)

**Comment by tonysurma** [comment]
Yes they would and this is related to the previous one so now that I think about it, if you complete this one you complete the other we just discussed #31 (given that social media logins should already be complete)

**Comment by MisterJames** [comment]
I am working on this one.
