### ISSUE TITLE
Activity and Campaign admin edit pages both calling UploadActivityImageAsync

### ISSUE THREAD

**Issue by ksk100** [HTBox/allReady#302]
The image upload code for both activities and campaigns is calling the same `UploadActivityImageAsync` method on the image service.  

This means that both are storing images to a path* of the form:

`/tenantId/entityId/imageFilename`

Where `entityId` is either `activityId` or `campaignId`.  This means that campaign images might overwrite activity images or vice versa: if the activity and campaign ids were the same and the filenames happened to match.

(*In fact, both `PostActivityFile` and `PostCampaignFile` send the `tenantId` as the second parameter, whereas `UploadActivityImageAsync` is expecting it as the first).

Suggest adjusting `UploadActivityImageAsync` to use blob paths of the form `images/tenantid/campaignid/activityid/imageFilename` and then creating `UploadCampaignImageAsync` which uploads to paths of the form `images/tenantid/campaignid/imageFilename`.

I'll get this done if that sounds sensible.

**Comment by ksk100** [comment]
@joelhulen, is this related to or covered by any of the image related work you're doing?

**Comment by joelhulen** [comment]
Yes. This item is part of what I was working on to complete the related
task. It was a partial commit.

**Comment by ksk100** [comment]
Okay no problem, I won't do anything with it.
