### ISSUE TITLE
Would tasks allow for time?

### ISSUE THREAD

**Issue by bluechrometouch** [HTBox/allReady#303]
I noticed that the start and end dates for campaign and activity only include the dates. This seems reasonable. However for tasks, I'd imagine that it could use the time part.

We could have an activity that takes place in one day with several tasks. Any thoughts?

**Comment by smille1834** [comment]
I agree that yes, we would like to have times for tasks as some tasks may start/finish before others.

**Comment by dpaquette** [comment]
The intention is for tasks to specify time parts. We have some work to do on the design of that to make sure we don't get time zones confused.

**Comment by bluechrometouch** [comment]
Question answered. Closing.
