### ISSUE TITLE
What is the status of the GeoLocation table?

### ISSUE THREAD

**Issue by ksk100** [HTBox/allReady#306]
Hi,

I'm investigating #193 and I've got stuck in my investigation/testing because some code in `AllReadyDataAccessEF7.Activity.cs` calls a stored procedure which appears to reference a table, `GeoLocation`, that is not created as part of the database setup (at least as created on my dev machine).  The `SELECT` statement in the stored procedure in question (`GetClosestActivitiesByPostalCode`) is:

```
SELECT  [GeoLocation].Lat as [Latitude]
        ,[GeoLocation].Long as [Longitude]
FROM    [PostalCodeGeo]
WHERE   PostalCode = @postalcode
```

I can't find any table, view, alias named `GeoLocation`, nor any table with columns named `Lat` or `Long`.

Is this something that has been created just on the Azure test environment?  And is there some SQL Server magic going on with the above query that allows that multipart identifier to be bound even though the name `GeoLocation` isn't mentioned in the `FROM` clause?

(Some of the other stored procedures suggest `GeoLocation` belongs to the `PostalCodeGeo` table).

**Comment by bcbeatty** [comment]
Also see #304

**Comment by bcbeatty** [comment]
Also see #183
