### ISSUE TITLE
Error when attempting to login via Microsoft Account

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#312]
Just click Login, Click Microsoft Account and get this url:

https://login.live.com/err.srf?lc=1033#error=invalid_request&error_description=The+provided+value+for+the+input+parameter+'redirect_uri'+is+not+valid.+The+expected+value+is+'https://login.live.com/oauth20_desktop.srf'+or+a+URL+which+matches+the+redirect+URI+registered+for+this+client+application.&state=CfDJ8KDKGBQpwThNmiIGCRNSeBxW2NOG9G3UvzinidSXRsDJDvxDQn_oxLpyemb7n812MS4xyTODTzNDpZYazyUlD9baSlIbC9TbTK1LFetpNePklfhQBe1I7hryWtSwYChdAz1ehazs5-XqFxhl7tLsLuDjoZoG3hIK2AAk-hfqIKOrptBfPmlsnKw345Qr4U7sAKSJiKfmKAfZWupN_5WimM7sPk8kQheibmckfOMPjq2mYFx09e05WyMLQkv_j8PAtmRpKPy5KZWieWfPdh3aJJr1-50LzRieHO3Z4NVV6_IHpHy26G5TAMqhNhqZwFS0Og

with this error:
![ms account error](https://cloud.githubusercontent.com/assets/5067595/11092976/fbd4b220-884c-11e5-9ca8-bdb4de209bbf.jpg)

**Comment by tonysurma** [comment]
@bcbeatty this happens on both -d and -mvp and several builds.  Any ideas?

**Comment by bcbeatty** [comment]
It may have something to do with registering the proper RedirectUrl in the apps' settings:
https://account.live.com/developers/applications/

A walk through is posted here: http://www.benday.com/2014/02/25/walkthrough-asp-net-mvc-identity-with-microsoft-account-authentication/
More information can be found here: http://stackoverflow.com/questions/12619532/the-provided-value-for-the-input-parameter-redirect-uri-is-not-valid

**Comment by tonysurma** [comment]
@bcbeatty okay I will look into it.  What url did you test this with your own deployment to azure?  Hopefully I can just take that and change the host name or something similar.

**Comment by tonysurma** [comment]
thanks @bcbeatty 

problem solved

The issue was that we were entering this url as approved redirect and it actually needs to be
http://allready-mvp.azurewebsites.net/account/externallogincallback
http://allready-mvp.azurewebsites.net/signin-microsoft

Fixed on -mvp and when I get a moment I will create as separate app and fix it on -d

**Comment by tonysurma** [comment]
also just fixed on -d, I had to create another app.  so it is done and live

**Comment by bcbeatty** [comment]
:+1:
