### ISSUE TITLE
Cannot register with local username & password - must use social media

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#313]
I know we have the code + db support for this but can we add UI support to login via creating a local user name and password?  Many volunteers do not want to/trust the connecting to social media accounts to log in.

**Comment by dpaquette** [comment]
I was wondering about this. It sure would make local testing easier if we had an option to create local accounts.   I will take this on.

**Comment by tonysurma** [comment]
thank you @dpaquette we already have it in some ways given the administrator@test.com sample user so hoping its just UI mostly.  Thanks again

**Comment by tonysurma** [comment]
Verified working
