### ISSUE TITLE
some indication of which commit current build is from?

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#314]
I have done this on other projects where part of the build script is generating a file with the commit hash in it that is shown in the user interface of the app so that you know which build you are working on when you have an issue.  Anyone have a quick idea how to do that in our Kudu/asp.net5 beta environment?

Labelled it lower priority as we only have two builds (-d and -mvp urls for now) but would be helpful when you are researching bugs to know what set of commits the issue happened IMHO

**Comment by stimms** [comment]
I can do this.

**Comment by mheggeseth** [comment]
@stimms So does the version only get replaced on AppVeyor? The "GITVERSION" string literal is still showing up on http://allready-d.azurewebsites.net/

**Comment by tonysurma** [comment]
This looks like it needs build support to actually put commit hash in the json file

**Comment by robrich** [comment]
https://github.com/HTBox/allReady/blob/master/appveyor.yml#L34 puts the version into version.json on every appveyor build.  How are builds deployed to allready-d.azurewebsites.net?

**Comment by tonysurma** [comment]
Azure website  auto deployment from GitHub.

Perhaps we need to duplicate that to deploy cmd or similar

**Comment by robrich** [comment]
Let's see if https://github.com/HTBox/allReady/pull/815 solves it.

**Comment by tonysurma** [comment]
It's alive!
![snip_20160607105154](https://cloud.githubusercontent.com/assets/5067595/15864748/ec297d7e-2c9d-11e6-8130-fee49afe7d24.png)

**Comment by robrich** [comment]
In my eagerness to avoid the third copy of the 1.0.0 version number, I pulled that line from version.json too, yielding a blank product version.  https://github.com/HTBox/allReady/pull/816 should solve this.  https://github.com/HTBox/allReady/pull/817 also shortens it from the full hash to the first 7 digits -- a bit less overwhelming for the non-techie who I'm sure said "get that big squashed bug out of my design."  :D
