### ISSUE TITLE
Organizations can add and maintain library of skills in addition to site wide skills

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#317]
Referenced in #316 we will also need organization level skills given variances across orgs.

**Comment by mheggeseth** [comment]
So is the idea that we'd merge the org skill list with the site skill list (or at least give org admins the option of which skill list to use)?

**Comment by tonysurma** [comment]
great q.  Idea would be that we would merge the 'pick list' from the site list + org list.  So XYZ can 'extend' standard list to also include hand to hand combat :facepunch: or sushi making skills :sushi: as they need

**Comment by mheggeseth** [comment]
Here's what I'm thinking on this one.
* Extend Skill model with an OwningOrganizationId property. Default value is null which would mean the Skill is a site-wide skill (available to all orgs; editable by site admins).
* Add OwningOrganization drop down to Skill edit view (editable by site admins; hidden for org admins).
* Make Skill CRUD views available to org admins. They can view/add/edit/delete skills owned by their org.
* When org admins edit skills, the set of valid parent skills will be the union of org skills and site skills. 

This is a nice, simple approach, however, it does prevent two orgs from using the same skill (at least the same skill ID), but it doesn't seem like we are too concerned about that.

Comments?

**Comment by tonysurma** [comment]
As they say at Coldstone Creamery: Like it. Love it! Gotta Have it!!!

Looks perfect to me and not worried about what it prevents, in fact good with that.  Thanks!
