### ISSUE TITLE
5.1.1.3.1	Allow organization ‘admins’ to register on the web application with social media/third party logins (twitter, facebook, linkedin, google, microsoft account)

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#32]
and register with name, email, organization and organization contact info including name, email, phone, website
[later functionality will allow initial admin to grant other users ‘admin’ or other perms for organization]

**Comment by BillWagner** [comment]
This is tied to #13 and should be closed in the same PR that will close #13

**Comment by dpaquette** [comment]
@shawnwildermuth are you still working on this? If not I can take a look at it tomorrow

**Comment by dpaquette** [comment]
I see now this isn't tagged as a Priority issue so I will focus on something else for now

**Comment by tonysurma** [comment]
closed when #13 was closed
