### ISSUE TITLE
Campaign Create/Edit requires image to be chosen and uploaded for each save 

### ISSUE THREAD

**Issue by ksk100** [HTBox/allReady#328]
I don't know whether this is desired behaviour, but I thought I'd post in case not: an image is now required for creating campaigns, such that they can't be created unless an image is uploaded.

A similar thing happens for editing the campaign, so that in order to update the campaign an image must be uploaded (even if the campaign already has one).

**Comment by joelhulen** [comment]
This is not desired behavior. I missed that aspect during my testing.
Should be an easy fix.

**Comment by ksk100** [comment]
Noticed another issue whereby because the image is uploaded before the `Campaign` object is saved, it is always stored with a URL of form `/tenantId/0/filename`.  I'll roll the fix into the work I'm doing on this at the moment.

**Comment by joelhulen** [comment]
Good catch. As you can see, it wasn't yet fully tested. Glad you're able to
go through it in detail, as I have not had time since Wednesday evening.

**Comment by ksk100** [comment]
I realise this was assigned to Joel, but these were small fixes as I was dealing with #48; I think they're both addressed in the pending PR.
