### ISSUE TITLE
Phone numbers could use an input mask

### ISSUE THREAD

**Issue by stimms** [HTBox/allReady#333]
![screen shot 2015-11-12 at 10 59 00 pm](https://cloud.githubusercontent.com/assets/153912/11139877/c2abec7a-8991-11e5-80b3-811412dc2a7c.jpg)

No idea how to do that for international phone numbers but I bet it is a solved problem.

**Comment by tonysurma** [comment]
For now an input mask for us phone numbers would be sufficient

**Comment by stevenschroeder** [comment]
I've got this one
