### ISSUE TITLE
There's currently no way for admins to remove an image from Campaign, Event

### ISSUE THREAD

**Issue by ksk100** [HTBox/allReady#338]

**Comment by YannickMeeus** [comment]
@tonysurma Can this be assigned to me, I've got a rough version I'd like to get some eyes on.

**Comment by YannickMeeus** [comment]
Considering the following scenario:

1. User chooses a picture and saves the campaign
2. This uploads the picture to Azure blob storage
3. User edits the campaign and uploads another picture
4. This overrides the picture saved against the campaign but doesn't delete the old picture

With regards to (4), is this acceptable at the moment, as it could leave orphaned images in blob storage?

I've been working on a soft delete scenario, so an image is flagged for deletion but doesn't actually get removed or disassociated from the campaign until the user actually clicks "Save". This ensures the user can change their mind and back out of the changes without losing the picture.

If I don't have to worry about cleaning up orphaned images, I'm very close to a working solution but if cleaning up is preferred I'll need to rethink some stuff.

**Comment by tonysurma** [comment]
Go for it @YannickMeeus I like the idea and okay with orphaned images as long as we have some way of knowing they are orphaned (and not just having to do a cross ref of current images referenced in one list and the contents of a folder in the other)  Thx

**Comment by mgmccarthy** [comment]
@YannickMeeus was there ever a PR for this Issue?

**Comment by YannickMeeus** [comment]
@mgmccarthy There hasn't been, no. I'm afraid I completely got stuck in work for the last couple of months, with little to no time to spend on AllReady I'm afraid. If someone else wants to pick up this change, they're more than welcome to it as I won't be able to address this any time soon. Apologies guys.

**Comment by tonysurma** [comment]
@YannickMeeus no need to apologize, life happens as they say 😄

**Comment by mgmccarthy** [comment]
@tonysurma do yo wan to reassign? Is this still a P3 issue?

**Comment by tonysurma** [comment]
sure, do you want to take it @mgmccarthy ?

**Comment by mgmccarthy** [comment]
@tonysurma, yep.

**Comment by mgmccarthy** [comment]
@tonysurma, can you please update the the title of this issue to that says Activity to Event?

Also, how important is this change? Right now, you can update an image, just not remove one. Worst came to worst, if you wanted no image, then upload a small write .png or something along those lines.

And it looks like we stick these images into a `CloudStorageAccount`. I'm not too familiar with how this works, or the API for it, but I'm assuming we AllReady should aim to keep the amount of storage to a minimum, hence, orphaning the images might not be the best approach?

**Comment by mgmccarthy** [comment]
@tonysurma @MisterJames 

I'm going to need some UI guidance here. 

Here is the edit Campaign page after I've uploaded an image:
![image](https://cloud.githubusercontent.com/assets/2428993/18111810/968a2c2a-6ef0-11e6-9397-26c3cf9c58e2.png)

"Browse for image" shows "no file choosen" and the image is shown on the screen. Purely from a UI perspective, how do you think we should mark this for deletion so when I click on the Save button at the bottom of the edit screen, the image associated with the Campaign will be deleted?

**Comment by tonysurma** [comment]
title updated.
For UI, the ideal would be a button next to the Image that says remove and when clicked is a seperate action from save that just removes the image.  
You could also put in a simple checkbox or something to say [] remove image and check that on save for now.
For deleting past, just log that as an issue and someone else/some when else can fix that 😸

**Comment by mgmccarthy** [comment]
@tonysurma, I like the ideal scenario; the button next to the Image that says "Remove" or "Delete". 

This is a better UI experience as the user can take care of deleting that image right from the edit page w/out having to hit the "Save" button, and send the entire Campaign back through the edit process. 

I think it's confusing to have a checkbox next to an existing image with the word "Remove", but also to have the Browse For image button in the same form powered by the same "Save" button to me.

The changes I've made to the existing functionality delete an existing image if another image is selected for upload on the edit page. 

That being said, I'm not really a javascript or a knockout guy, so I think I'm going to open a new Issue for adding a Remove button for existing images on the Campaign and Event page and let a javascript/knockout person take care of it. 

For someone with that skill set, it should be relatively straight forward as I've already written the code that deletes the image from Azure blob storage. They should just be able to use their javascript magic to invoke a controller action that will call into the `DeleteImageAsync` on IImageService. 

Sample code for how that method is used is in `Admin.Controllers.CampaignController's Edit` POST action method.
