### ISSUE TITLE
No campaign activities are showing on the site

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#351]
This campaign should show up 'publicly' and it only shows on admin:

Is in the admin list:
https://allready-mvp.azurewebsites.net/Admin/Campaign/Details/8

Should be in this list:
https://allready-mvp.azurewebsites.net/Campaign/8

That is just one example but no activities are showing up at all

**Comment by mheggeseth** [comment]
I'm on this.

**Comment by tonysurma** [comment]
Excellent!  I have been able to now test full cycle and it worked.  Once we have a confirmed email and text message the message all functionality worked.  Thank you everyone
