### ISSUE TITLE
No means to re-verify your email after initial login

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#352]
This is particularly tough for us in testing as there is no way to send emails to unverified users and all users don't have verified emails because it wasn't working until just now.

Alternatively and supplementally we could create the ability for site admins to delete users so we can at least remove users so they can go through login again.  We will need this functionality soon anyways so whichever is faster please.

**Comment by dpaquette** [comment]
I can do this today

**Comment by tonysurma** [comment]
Verified now working
