### ISSUE TITLE
Need the ability to delete users as a site admin

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#353]
Either this or #352 is needed for testing so I put both as P1.  Whichever can get done sooner is better.

**Comment by MisterJames** [comment]
I'll plunk away at this one after I get the email sorted.

**Comment by stevejgordon** [comment]
@MisterJames I was wondering if you're still working on this? One thought I do have is whether we really want a hard delete or simply a mechanism to deactivate (soft delete) so that any data/history linked to the user can remain in place? Or perhaps both scenarios are useful?

**Comment by mheggeseth** [comment]
From @tonysurma's description, it sounds like the primary need is total annihilation to make site testing easier. Soft delete is a bit more complex and should probably come later.

**Comment by stevejgordon** [comment]
Sounds fair. I'll wait on @MisterJames as I do see a branch in his repo that probably covers this.
