### ISSUE TITLE
5.1.1.3.5	Organization admins can list multiple volunteer skills/resources needed

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#36]
including optional date ranges and locations {‘skill/resource A’ needed [from ‘x’ to ‘y’ date range] [in ‘z’ location scope]}.  This listing will allow volunteers to later connect to the organization and offer to volunteer in delivery of the campaign as well as potentially be a data feed consumed by other third party apps that display volunteer needs.

**Comment by DevUnit1** [comment]
I'll try this one

**Comment by DevUnit1** [comment]
The skills/resources being listed - are they associated with a campaign, activity, or task?

**Comment by tonysurma** [comment]
Thanks, at the activity level
________________________________

**Comment by DevUnit1** [comment]
I discussed this feature with Jim and Richard.  For now, we're going to defer the resource part of this feature.  Below is my understanding of the skill system we'll be implementing - please feel free to comment on, correct, question, or add to any part of it!

* Skills will be hierarchical (i.e. Medical -> MD -> surgeon, Medical -> CPR Certified)
* Skills will exist in pre-defined templates
 * The administrator will be able to import the template into a campaign
 * The administrator will be able to search for templates
 * The administrator will be able to customize the templates
 * The administrator will be able to select the lexicon for the templates (such as using the UN names or not)
* Skills will be attributed to users
 * The administrator can add skill to user
 * The user can add the skill to themselves
   * Possible verification/override function?  TBD
* Skills will be assignable to Activities
* Skills will be assignable to Tasks

**Comment by mheggeseth** [comment]
I'll take over ownership of this issue.

**Comment by mheggeseth** [comment]
Can somebody clarify the difference (if any) in this context between a skill and a resource? In @DevUnit1's comment, "resources" are not mentioned. I want to make sure I'm not missing something.

**Comment by tonysurma** [comment]
@mheggeseth - per discussion we are focusing on skills only and delaying any work on resources to a later date.  Therefore you are not missing anything and the clarification from @DevUnit1 is complete (until we bring resources back into it at a later date).  Thanks.

**Comment by mheggeseth** [comment]
@tonysurma can you clarify what "Skills will exist in pre-defined templates" means? Is this like having "skill presets"? E.g. My organization runs a campaign each semester during finals to deliver pizza and wings to hungry college students and each time we need the same skill sets to populate that from a template.

Or does "template" mean something else in this case? Can you give an example of how a "template" would be used?

**Comment by mheggeseth** [comment]
Also, does associating skills to Activities and Tasks still include the "optional date ranges and locations {‘skill/resource A’ needed [from ‘x’ to ‘y’ date range] [in ‘z’ location scope]}" requirement? Or is that more of a "resource" thing?

**Comment by tonysurma** [comment]
@mheggeseth "date ranges and locations" that is more of a resource thing so ignore

@mheggeseth the skills templates is referencing the same idea from the crisischeckin project meaning that the goal is to have 'classification hierarchies' like the UN has the cluster system etc so an admin can say this campaign uses the blahblah hieararchy break down and then pick from there
I think for this timeframe we can skip the template hierarchy stuff and just make them ad-hoc entry and we can later add in template hierarchies and retro as needed - both to make this easier for now and so we don't have to survey all hierarchies or make a big CRUD interface for that (also we may be able to steal it from crisischeckin once that is done)

**Comment by mheggeseth** [comment]
I've got some working bits and a plan for knocking the rest of this one out (at least at the limited scope we have defined). Quick sanity check:
* Skill model just has a name and references a single parent skill (if applicable)
* Skills will have CRUD views
* A many-to-many model will be created for each skill association. These models do nothing more than associate entities but could be extended in the future.
  * Activities to Skills
  * Tasks to Skills
  * Users to Skills
* Editing associated skills in the views will be done via a simple list of drop-downs
  * Knockout will facilitate adding/removing skills and validation. Any set of skills will be allowed for an activity/task/user so long as a given skill appears at most once in the set. The Save button will be disabled if this is violated.
  * Upon saving, controller will ensure deletion of any skill associations that are no longer on the activity/task/user in addition to saving the current associations.

Anybody have any issues/concerns/comments about this?

**Comment by tonysurma** [comment]
quick review tells me this all looks good from a requirements point of view @mheggeseth

**Comment by MisterJames** [comment]
@mheggeseth Is this one complete then?

**Comment by mheggeseth** [comment]
@MisterJames Technically no. Waiting on #112

**Comment by BillWagner** [comment]
@mheggeseth Are you still working on #112?

**Comment by BillWagner** [comment]
Closing this, as the only remaining task is detailed in #112, which references this issue.
