### ISSUE TITLE
Enable resetting of passwords for not verified users

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#365]
So if you create an account and never click the link (or for some reason lose that email) and also forget your password the admin cannot reset your password

![nopwdreset](https://cloud.githubusercontent.com/assets/5067595/11202848/8c84625e-8ca1-11e5-9d9b-db072bb7d978.png)

Can we unbreak this chain either by allowing for deleting of users (nuclear option) #353 or by allowing (maybe with a second click to confirm?) to send the reset to an unverified email?

**Comment by dpaquette** [comment]
I can take this one on. Please assign to moi
