### ISSUE TITLE
Resetting Password From Admin Does Not Send Email

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#366]
Before I tag this to a milestone can you peek at it James?

I deployed changes and couldn't login as a user to verify an email so I tried to hit reset password for one of my users.  I got no error, I see it in the web job log as processing the message but nothing shows up in my inbox or in the sendgrid activity page?

UPDATE: I verified that verify email messages get out but not reset password.  Maybe something silently errors there?

UPDATED UPDATE: To be clear I don't mean resetting as a user, I mean login as site admin, click reset password next to a user.  It says it sends email and I see it in the webjob processor log just nothing in sendgrid

**Comment by MisterJames** [comment]
Investigating now.

**Comment by MisterJames** [comment]
It looks good from my standpoint @tonysurma. I got the conf email and was able to reset my password. Mail flows through the queue correctly and the HTML is properly set, the link in the email works.  

We display a "honey pot" if you type in a bad email, so it will always tell you it sent it. Can you double-check your email address and submit again?

**Comment by tonysurma** [comment]
Our updates crossed... I updated to point to the fact it was via admin resetting a password not the other way around

**Comment by tonysurma** [comment]
Lowered priority as you can just as easily do this via login screen - clunky but effective
