### ISSUE TITLE
Update Use of Local Server Time to UTC

### ISSUE THREAD

**Issue by WilliamBerryiii** [HTBox/allReady#369]
Given the possible distributed nature of this application, date times should likely be done in UTC and converted to local time as needed.  See this as a sample of DateTime.Now that should be updated: https://github.com/HTBox/allReady/blob/abe6054f3a177cf8fb0227981c40bf2acec586f4/AllReadyApp/Web-App/AllReady/Areas/Admin/Controllers/CampaignController.cs#L60-L61

**Comment by bcbeatty** [comment]
During the code-a-thin I asked Ryan from
Microsoft about DateTime vs DateTimeOffset. He said to always use DateTimeOffset because it stores the time zone.

**Comment by dpaquette** [comment]
Using DateTimeOffset alone doesn't solve all our problems. We still need to understand what timezone each event is hosted in. Once we have established the correct timezone for the event, a decision would also need to be made regarding what timezone the time should be displayed in. Do we display the time in the current user's local timezone or do we display the time in the timezone of the event?

**Comment by MisterJames** [comment]
Yes, the correct approach is to use DateTimeOffset and consider the bits that @dpaquette added.

 > Do we display the time in the current user's local timezone or do we display the time in the timezone of the event?

I think both, if there's a mismatch. For instance, "This event is at 3:00pm Eastern (2:00pm your time)", but only have that second bit if it's not aligned.

**Comment by dpaquette** [comment]
Hadn't considered displaying both. That's a great idea!

**Comment by dpaquette** [comment]
I can start working on this and tackle the whole timezone thing. Here is what I am thinking.
- Users will need a timezone associated with them. We will guess their timezone based on where they are but this would be a setting they can change in their user profile.
- A campaign will need a timezone associated with it. This would be part of the campaign setup. We could potentially have a timezone for the organization and that would be used as a default for each campaign.
- The edit views for Campaigns, Activities and Tasks would always display datetime in the timezone of the campaign. We should explicitly show the timezone to avoid confusion.
- Anywhere we display datetime for Campaigns, Activities and Tasks we should display it in both the Capaign and User's timezone.

**Comment by mheggeseth** [comment]
Suggestion: only show one time (with TZ) if the entity and user time zone are the same.

**Comment by dpaquette** [comment]
Can someone assign this to me? 

Making some good progress so far. I am able to display in both the campaign and the user's local time zone:
![Event time vs Local User Time](https://cloud.githubusercontent.com/assets/2531875/11329076/952f8ca4-9164-11e5-9d6b-8ec8006b1e04.png)

I just need to improve formatting and do a lot of testing.

**Comment by BillWagner** [comment]
assigned to @dpaquette

**Comment by dpaquette** [comment]
This was resolved by #395. Forgot to tag it to close

**Comment by BillWagner** [comment]
Thanks for the comment @dpaquette Closing now.
