### ISSUE TITLE
5.1.1.3.6	Organization admins can save campaign info revisions, update them, preview before publishing, publish and publish updates over time

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#37]
[later functionality (or in V1 if possible) would be to allow citizens to ‘report campaigns as spam/inappropriate’ and then allow admins to take them down and/or ban org admins]

**Comment by MisterJames** [comment]
Marking as P3 because MVP is to target a private preview with known organizations.

**Comment by stevejgordon** [comment]
@tonysurma I see this relates to / is a pre-requisite of #39 and may change my understanding of that requirement.

Is the goal here to create campaigns initially in an unpublished state with a toggle to publish when they are ready? 

What is the intended difference from the current Edit campaign behaviour? Do changes to the Campaign fields need to be "versions" of the campaign which can be reverted to / viewed as a history? An audit trail of sorts?

**Comment by tonysurma** [comment]
I think that is close.  In short we want to be able to have campaigns be 'built'/created before they go live and once they go live have the ability to preview a change before they push it live.  The preview could be just in a tab (like above here when I am entering a comment on an issue in GitHub) it doesn't have to be 'long lived' aka stored in system.

**Comment by stevejgordon** [comment]
@tonysurma Thanks for the extra info. I think I have an idea of how to go about this so I'll get started on this ASAP.

**Comment by stevejgordon** [comment]
@tonysurma Sorry, this one slipped from my radar. I can pick this up again but I wanted to check that the requirements remain valid?

1. Ability to create a campaign initially in an un-published state, preview it and when ready, publish it.
2. Ability to preview changes when updating a campaign (already published) before saving them.

**Comment by tonysurma** [comment]
keeping on milestone but removing it from P1-P3 as it is lowest priority and I don't want to create a P4 😅

**Comment by stevejgordon** [comment]
Added two issues to break out this piece of work:

- [ ] #1582 - Previewing a campaign
- [ ] #1583 - Concept of published campaigns

**Comment by tonysurma** [comment]
will track status as @HamidMosalla covers with two PRs.  thank you!

**Comment by tonysurma** [comment]
Thanks @HamidMosalla

**Comment by HamidMosalla** [comment]
@tonysurma Happy and proud to help.
