### ISSUE TITLE
Register: list password requirements

### ISSUE THREAD

**Issue by cecilia-donnelly** [HTBox/allReady#370]
On the "Register" page, list requirements for the password (e.g. must include a digit), so that users don't have to guess.

I would label this as an "enhancement" and maybe "jump in" -- it's not strictly necessary, but it would avoid some minimal frustration and should be easy to add.

See also #209.

**Comment by tonysurma** [comment]
Thanks

**Comment by aliiftikhar** [comment]
Questions:

1. Password length should be 10 (as specified while configuring Identity service in Startup.cs) or 6 (as specified in RegisterViewModel) ?

2. Password requirements according to Identity service configuration in Startup.cs is:
'Password should be at least 10 characters long, containing at least one 1 lowercase character and 1 number.'
Can this text be added on the page as password requirements?

**Comment by stevejgordon** [comment]
I've had a crack at this in Pull Request #398 with a view to making life easier in the future by having a single class where these are set. We could also use a config file perhaps to avoid hard coding these as constants. Architecturally I'd love feedback if this is a sensible approach!
