### ISSUE TITLE
Change/update jokey tooltip text?

### ISSUE THREAD

**Issue by cecilia-donnelly** [HTBox/allReady#371]
Some of the text in the "?" tooltips under "Needed Skills" seems a little too informal for production use -- I expect that those will be updated, but wanted to flag it anyway.  It might be that you intend the app to have a casual voice, which would be fine, of course.

Possible labels: "question," "jump in."  (I would add labels myself but GitHub doesn't let non-team-members take actions like labeling and assigning issues.)

**Comment by tonysurma** [comment]
Thanks for working with us and posting issues Cecilia.  Those are just items inside the 'sample data' entered by devs etc.  It can/will be cleaned out by our and the red cross admins and replaced with real data :)

and yeah I wish GitHub had more flexibility in perms to issues but not yet.
