### ISSUE TITLE
Email after volunteering or unenrolling

### ISSUE THREAD

**Issue by cecilia-donnelly** [HTBox/allReady#372]
The app should send the user a confirmation email after they volunteer for and/or unenroll from an event.

Labels: "question" (do we want to send people lots of emails, @OhMcGoo?), "enhancement."

**Comment by OhMcGoo** [comment]
I think you allow the user to set their own 'communication' preferences: For what do they want to be e-mailed (or texted) and how often (and how soon before an event).

**Comment by cecilia-donnelly** [comment]
Yes, that makes sense.

**Comment by mmoore99** [comment]
I will work on this.

@tonysurma @MisterJames Regarding "allow the user to set their own 'communication' preferences", this is part of the discussion in #389 and I would propose that for the **Private Preview Release 2** milestone that we just send the emails to **all** who volunteer/unenroll.
