### ISSUE TITLE
Create "My Events" Page For Volunteers

### ISSUE THREAD

**Issue by MisterJames** [HTBox/allReady#376]
Create a listing of events for which the logged-in user has volunteered for.

From #373.

**Comment by mheggeseth** [comment]
There already exists a MyActivities view but it doesn't do much. This view should replace/augment that one.

**Comment by bluechrometouch** [comment]
I'd like to augment this existing view.

**Comment by bluechrometouch** [comment]
Meetup.com has a convenient webpage for their member activities. As you can see, it lists the activities in a calendar possibly addressing #377 and #378 when members are logged in.

![capture](https://cloud.githubusercontent.com/assets/14866579/11578025/68e800aa-99e7-11e5-8108-d0bbb23b00db.JPG)

**Comment by bluechrometouch** [comment]
![capture](https://cloud.githubusercontent.com/assets/14866579/12220809/c5aa9132-b746-11e5-9657-15b66fdd9daa.JPG)

Calendar is not working yet, but here is a demo.

**Comment by tonysurma** [comment]
@bluechrometouch you still working on this?

**Comment by bluechrometouch** [comment]
@tonysurma 

I have to say no. Got a new job recently and just don't have the energy to take on any outside coding.

**Comment by tonysurma** [comment]
Congrats on the new job and thanks

**Comment by stevejgordon** [comment]
@tonysurma You can assign this to me if you like. In the interests of time I would concentrate on a more simple listing our the tasks / events that a user has volunteered for grouped/organised by date. This I imagine would look similar to what @bluechrometouch was proposing on the left hand side of his mockup. Does that sound okay as a starting point? I think that perhaps the calendar / date filtering could be a follow up issue, perhaps combined with UI / UX work.

**Comment by tonysurma** [comment]
Sounds good to me, thx

**Comment by stevejgordon** [comment]
I've finally got something going for this issue. It's pretty basic (lots that could be done with the functionality, UX and UI) and not very pretty at the moment. I have some work left to test it, refactor some code and generally clean it up but I wanted to share a screenshot of the current page to open it up for comments. Clicking on the event take the user to the event page where they can then update tasks. For ease I didn't bring in the full JS functionality to manage the tasks within this view. 

@tonysurma Let me know if you see any immediate changes to data being shown for a v1 of this page?

![image](https://cloud.githubusercontent.com/assets/3669103/15164181/194280f2-1705-11e6-8fde-1cc904e13908.png)

**Comment by tonysurma** [comment]
@stevejgordon looks good to me thanks!  FYI @joelhulen here is a UX item we can discuss

**Comment by stevejgordon** [comment]
@tonysurma Thanks! I'll try to find the time soon to clean up the code and tests to get a PR in for what I have so far.
