### ISSUE TITLE
Create a Calendar of Events

### ISSUE THREAD

**Issue by MisterJames** [HTBox/allReady#377]
See all events that are in the system in a calendar display.  Allow for filtering by zip code, within a certain distance, or all events. 

From #373.

**Comment by joelhulen** [comment]
I think we should use a library like: http://mvc.daypilot.org/daypilot-lite-for-asp-net-mvc-1-3/

What are the views that should be displayed? Month, week, work week, day...

**Comment by stimms** [comment]
Where were you thinking this would go? As part of the campaign list page? Perhaps we could have a list view (current) and a calendar view with a little toggle in the top right.

A fully featured calendar control seems kind of heavy weight to me. I would think that for most of the campaigns a monthly view would be sufficient. Certainly for our example project it is.

**Comment by bluechrometouch** [comment]
I posted this Meetup.com demo for #376. I think it would cover the needs here. What do you guys think?
![capture](https://cloud.githubusercontent.com/assets/14866579/11578247/3da8c56c-99e9-11e5-850c-db7fd569dea1.JPG)

**Comment by danielepo** [comment]
Is anyone still working on this? 
If not, I'd like to propose my solution, here's a snapshot of the dashboard:
![image](https://cloud.githubusercontent.com/assets/6214856/17742034/c2d977a6-649e-11e6-90e4-449a194b289d.png)

 - it uses [fullcalendar](http://fullcalendar.io/) to view the events
 - by clicking on an event the user is redirected to the event details page
 - it loads only the events of the month the user is looking

I still have to manage filtering by zipcode but i IMO this could be added later. what do you think?
