### ISSUE TITLE
Allow Calendar of Events to By Filtered by Logged in User

### ISSUE THREAD

**Issue by MisterJames** [HTBox/allReady#378]
Augment the calendar of events to use the logged in user (and possibly their preferences) to provide additional filtering capabilities such as "my events" or events based on skills the user has indicated they have.

Dependent on #377.
From #373.

**Comment by bluechrometouch** [comment]
Since this ties in to what I have for 376, I'd like to work this.

**Comment by stevejgordon** [comment]
I believe we have the basic functionality of this in place. The UX is poor but I suggest we close this and augment under the main UX discussion, breaking out enhancements as new issues.
