### ISSUE TITLE
5.1.1.3.7	Organization admins can provide impact updates against the impact target and interim goals

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#38]
by updating {‘x’ ‘things’ delivered by ‘y’ date} as well as checking off interim goals achieved per 5.1.1.3.4 #35

**Comment by stevejgordon** [comment]
We currently have the concept of a single campaign goal. This requirement would see us adding staged goals for campaigns and perhaps also at the event level.

We would need to add supporting tables to store multiple goals against a campaign with a way to set the bounds of that goal.

**Comment by mipre100** [comment]
This is related to #254: Design needed for goals and reporting

**Comment by stevejgordon** [comment]
@mipre100 Might be able to start with a basic dev created UI. So we first add the ability via this issue to create interim goals in the admin area. i.e. By date xyz we want to have completed X requests. We'll then need to figure out how to determine the progress towards the goal. I have a story around adding more details request history logging which will likely help with tracking actual progress against dates.

**Comment by mipre100** [comment]
OK, I'll start the work to allow adding multiple goals based on the current text and numeric goals. We can then extend it for date based goals.

**Comment by stevejgordon** [comment]
I think with #1745 merged we have the initial functionality for this one, so closing it out.
