### ISSUE TITLE
Incorrect Password minimum length validation on ViewModels

### ISSUE THREAD

**Issue by aliiftikhar** [HTBox/allReady#386]
The Password minimum length validation in ResetPasswordViewModel and RegisterViewModel is set to 6.

The actual password length has been changed from 6 to 10: #341 

Therefore Password minimum length validation in ResetPasswordViewModel and RegisterViewModel also needs to be update accordingly (i.e. set to 10).

**Comment by MisterJames** [comment]
Thanks @aliiftikhar!
