### ISSUE TITLE
Crash when creating task: TimeZoneNotFoundException

### ISSUE THREAD

**Issue by ksk100** [HTBox/allReady#402]
On `http://allready-d.azurewebsites.net/` or when running locally I get the following error when trying to create an activity:

![image](https://cloud.githubusercontent.com/assets/6615834/11508064/c36617a0-984e-11e5-8570-ad80100f4772.png)

Looks like it might just be that the `Create` method in `TaskController.cs` needs updating to set a value for `TimeZoneId` on the view model.

**Comment by dpaquette** [comment]
I will take a look at this.

**Comment by BillWagner** [comment]
Fixed in PR #407
