### ISSUE TITLE
Null Campaign data in MyActivities Error

### ISSUE THREAD

**Issue by bluechrometouch** [HTBox/allReady#403]
When a user has volunteered for activities and visits their MyActivities page, a null Campaign error will be thrown.

Campaign data needs to be included in the Activity SIgnup model that the view depends on.
".Include(x=> x.Activity.Campaign)" needs to be added to the ActivitySignup linq methods. 

This is found in AllReadtDataAccessEF7.Activity.cs.

**Comment by bluechrometouch** [comment]
Closed

**Comment by BillWagner** [comment]
@bluechrometouch Please wait to close issues until the code that fixes it is merged. (As a normal practice, I close issues when I accept the pull request.)
