### ISSUE TITLE
EF Practices - Async

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#405]
I had a couple of observations / queries around the EF code in the project currently. I'm not sure if they are actual issues but will raise them for discussion.

I see that the EF async methods are not currently being used. Is there a reason for this? I've been using these in my own projects as I understood that to be a preferred practice going forward?

**Comment by tonysurma** [comment]
@stevejgordon is this still an open issue (9 months later checkin 😄 ) ?

**Comment by stevejgordon** [comment]
@tonysurma Sorry, missed your comment here! I think we've moved most, if not all, of the code over the async methods now. I'll close this issue and if we spot any sync methods still being used we can direct specific issues and PR's to address those.
