### ISSUE TITLE
5.1.2.1.2	Allow volunteer to accept/reject task assignment

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#41]
_Requires completed implementation of #40_

As a volunteer I can:
 - [ ] Accept a task assignment
 - [ ] Reject a task assignment

**Comment by rockfordlhotka** [comment]
By way of documentation, the task sign-up status can be set to the following values:

* Assigned (assigned by an admin to a volunteer)
* Accepted (accepted by a volunteer - assumed to now be in-progress)
* Rejected (rejected by a volunteer)
* Completed (completed by a volunteer)
* CanNotComplete (marked by a volunteer as a task that can't be completed)

**Comment by mheggeseth** [comment]
Taking this over from @rockfordlhotka. Please switch assignments @BillWagner / @tonysurma
