### ISSUE TITLE
Consolidate DateTimeOffset conversion to a single place

### ISSUE THREAD

**Issue by dpaquette** [HTBox/allReady#410]
We are converting DateTimeOffset values to the Campaign timezone in a few different places. Would be nice to avoid the duplication of code here.

**Comment by dpaquette** [comment]
Examples in [TaskController.cs](https://github.com/HTBox/allReady/blob/master/AllReadyApp/Web-App/AllReady/Areas/Admin/Controllers/TaskController.cs), [ActivityEditCommandHandler.cs](https://github.com/HTBox/allReady/blob/master/AllReadyApp/Web-App/AllReady/Areas/Admin/Features/Activities/EditActivityCommandHandler.cs) and [EditTaskCommandHandler.cs](https://github.com/HTBox/allReady/blob/master/AllReadyApp/Web-App/AllReady/Areas/Admin/Features/Tasks/EditTaskCommandHandler.cs)

**Comment by dpaquette** [comment]
Assign to me please

**Comment by mgmccarthy** [comment]
we're also doing this work in [TimeTagHelper.cs:](https://github.com/HTBox/allReady/blob/53c7f60facfaaf7d016265087eadc13ac7720ac7/AllReadyApp/Web-App/AllReady/TagHelpers/TimeTagHelper.cs) and [campaign.js](https://github.com/HTBox/allReady/blob/53c7f60facfaaf7d016265087eadc13ac7720ac7/AllReadyApp/Web-App/AllReady/wwwroot/js/campaigns.jsrl), so it's pretty much all over the place at this point.

**Comment by mgmccarthy** [comment]
@dpaquette, I have a VERY simple spike of a "provider" that wraps up a lot of the duplicate code here:
https://github.com/mgmccarthy/allReady/tree/DateTimeOffsetProvider

Again, this is just a baby step towards a better DateTime solution. This spike does not address the duplicate code that has leaked into [TimeTagHelper.cs](https://github.com/HTBox/allReady/blob/53c7f60facfaaf7d016265087eadc13ac7720ac7/AllReadyApp/Web-App/AllReady/TagHelpers/TimeTagHelper.cs) and [campaigns.js](https://github.com/HTBox/allReady/blob/b370c169dc7485067519f6fbe15a563f7acf19c9/AllReadyApp/Web-App/AllReady/wwwroot/js/campaigns.js), but I don't think this code belongs in tag helpers or javascript.

My goal here was to start to "centralize" this logic. Once we have that done, it should be easier to move forward with a more mature DateTime solution for the project, whether that means implementing what I proposed in #710, using [NodaTime](http://nodatime.org/) or a combination of both.

**Comment by tonysurma** [comment]
@dpaquette @mgmccarthy still open?

**Comment by mgmccarthy** [comment]
@tonysurma we consolidated where we needed to so this can be closed
