### ISSUE TITLE
Step two to fixing home page: add campaigns list

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#417]
Step two for fixing #193 after #416 add to the home page a list of 'active/upcoming' campaigns (duplicate from campaigns page)

**Comment by pettys** [comment]
Is this still an accurate write-up of what is desired here? I was thinking of jumping in by dropping this list into the home page, using the campaigns page as a guide, but wanted to make sure this change is still in line with the current flow of the project.

Is this a web app only change, or is there a corresponding change in the cordova project as well? (I haven't gotten the cordova part running yet.)

**Comment by tonysurma** [comment]
@pettys welcome!  Thanks for checking  but yes this is still accurate.  For now we are focusing on the web project but if you want to jump into the cordova project please do.  Thanks again

**Comment by stevejgordon** [comment]
@pettys @tonysurma I agree with leaving the simpler items for new contributors to start with the project. However, as this milestone is late I'm able to pick this up if we want to get it in sooner and it's not already been started by anyone?

**Comment by mmoore99** [comment]
@pettys @tonysurma @pettys, I'm a noob to allReady and would be interested in taking a crack at this if it is not already being worked on.  I had held off in responding as I thought that @pettys may have jumped on it.

**Comment by stevejgordon** [comment]
@mmoore99 From my perspective, go for it. I've not started anything around this one. I can't see a fork of allRready from @pettys yet so I guess it's not been started but hopefully he can confirm.

**Comment by pettys** [comment]
Go ahead - sorry to hold it up.

**Comment by mmoore99** [comment]
@tonysurma @stevejgordon Ok, I am going to see what I can do with this.  First question, how do you define 'active/upcoming' campaigns? Should the list include all active campaigns and all future campaigns or all active campaigns and future campaigns within some date range?  Thanks.

**Comment by mmoore99** [comment]
**See PR #490**

**Comment by tonysurma** [comment]
closed in PR
