### ISSUE TITLE
Remove blog from main nav and place in footer

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#420]
Perhaps in the footer with #419 we can move the blog as it doesn't deserve top billing

**Comment by ksk100** [comment]
I'll do this. Would an image icon be best for the link?  

We could perhaps use something like that old universal blog icon which, in allReady colors, would be:

![allready-blog-icon-box-rev-60](https://cloud.githubusercontent.com/assets/6615834/11713694/de2feda6-9f2c-11e5-9ce3-c50be0c5b5f4.png)

What do you think?
