### ISSUE TITLE
Deemphasize About in main nave

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#421]
Can we move this off to the left, or down in the new footer from #419 or something that doesn't make it the first thing you want to click?

**Comment by junderhill** [comment]
Would it make sense to move this across perhaps after 'Campaigns' and 'Organizations'? Personally I think it should remain on the nav bar although I agree that it shouldn't be the first option on there.

**Comment by mheggeseth** [comment]
I think it should move out of the nav header. For one, if a user is logged in, they know about allReady already (I couldnt help myself :-)). For a new user, learning about the app is probably one of the first things they want to do (and then likely never again) so I think the best place for it would be in the landing page content. Just my opinion.

**Comment by manojattal** [comment]
Hi there, I want to work on this item. I see different comments for this issue. I am changing it's order to 3rd from left. Let me know if some other option should be chosen.

**Comment by BillWagner** [comment]
@manojattal Thanks for helping. Let us know if you need any help as you put together the changes.

**Comment by manojattal** [comment]
@BillWagner I am facing issues in creating pull request to GitHub. I have went through tutorials, but seems there is some issue the way in which my GitHub is setup. I am getting error "Sync failed to push local changes", May be GitHub is getting conflict with "GitLab" repository setup(my work related set up). I will give a try to commit again, tonight.

**Comment by mheggeseth** [comment]
@manojattal It doesn't look like your GitHub account has a fork of the allReady repo. You'll need to start with that. You won't be able to push directly to HTBox/allReady. If you haven't already, check out http://htbox.github.io for guidance. If you are having trouble with the instructions there, let us know and we'll make them better.

**Comment by BillWagner** [comment]
And, if the link @mheggeseth doesn't help, I wrote this blog post a while back when we had a number of people work directly from the HTBox master instead of a fork:
http://thebillwagner.com/Blog/Item/2015-08-18-IforgottoforkbeforeIstartedworkingandhowtofixit

That may help you as well @manojattal

**Comment by mmoore99** [comment]
@manojattal Are you still working on this?  If not, I would be willing to handle it.  Please advise.

**Comment by manojattal** [comment]
@mmoore99 I just committed pull request for this bug.
