### ISSUE TITLE
Home Page: Move link to /Home/Aesop to /Home/About

### ISSUE THREAD

**Issue by mheggeseth** [HTBox/allReady#424]
Learning about the the origin of the allReady logo is fun, but should probably not be the result of clicking just about anywhere on the home page (`_LayoutMainPage.cshtml`). Right now the clickable surface area of the link to `/Home/Aesop` currently spans the whole width of the page so somebody clicking in what they think is empty page space (like I do all the time) gets a folktale lesson, but may not want it at that very moment.

Move the link to `/Home/Aesop` to the about page under a section like "what's with the logo?" and take the link away from the hero image on the home page.

cc @MisterJames

**Comment by shanecharles** [comment]
I got this.
