### ISSUE TITLE
Remove unused files in AllReady solution

### ISSUE THREAD

**Issue by mheggeseth** [HTBox/allReady#425]
The following non-compiled files are not needed/used in the allReady app.
* AllReadyApp/Web-App/AllReady/Project_Readme.html
* AllReadyApp/Web-App/AllReady/data.json
* AllReadyApp/Web-App/AllReady/wwwroot/images/ASP-NET-Banners-01.png
* AllReadyApp/Web-App/AllReady/wwwroot/images/ASP-NET-Banners-02.png
* AllReadyApp/Web-App/AllReady/wwwroot/images/Banner-01-Azure.png
* AllReadyApp/Web-App/AllReady/wwwroot/images/Banner-02-VS.png

cc @MisterJames (great for somebody who's learning the fork-branch-PR workflow)

**Comment by tonysurma** [comment]
Thanks @mheggeseth for finding that!

**Comment by dylan-smith** [comment]
I'm on it

**Comment by MisterJames** [comment]
I got this one!
