### ISSUE TITLE
Death to Tenants! Long live Organizations! (Database Edition)

### ISSUE THREAD

**Issue by mheggeseth** [HTBox/allReady#426]
After the simpler renaming changes listed in #423, completing the renaming of "Tenant" to "Organization" includes renaming database entities as well. Though this will be an involved change from a testing coordination perspective, the pain of the change increases significantly the longer we put it off so let's rip this band-aid off as soon as we can.

This issue is intended to start the conversation about when and how to accomplish this change from a testing/deployment perspective so this is where folks like @tonysurma, @OhMcGoo, and @BillWagner come in.

**Comment by tonysurma** [comment]
Sooner than later is key as right now we don't have live data we need to keep and if coordinated we can do this in the next few weeks but soon after it will be much, much, much more difficult

**Comment by stevejgordon** [comment]
I can take a look at this as I go through the data access files? Would look at renaming the entity classes, column / table names and I presume any code generating the sample data. Not sure if this would run as a migration though. In theory it should work!

**Comment by mheggeseth** [comment]
My guess is that migrations would just drop and recreate the tables/columns, which is probably what we want anyway for the sake of simplicity.

**Comment by tonysurma** [comment]
@mheggeseth my assumption as well and that is fine for now and I am still manually triggering deployment to mvp site (updating branch or whatever) so it won't happen and be a surprise

**Comment by stevejgordon** [comment]
Sounds good. If it's okay I can try to look at this early next week?
