### ISSUE TITLE
5.1.2.2.1	Allow org admin to create a task and assign to one or more volunteers

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#43]
[later functionality to allow variance by volunteer aka these 5 addresses to be completed by 5 volunteers; have multiple volunteers asked and the first to accept gets it; have task matched by skill in system and/or use machine learning to predict best volunteer etc.]

**Comment by MisterJames** [comment]
@tonysurma There is already a mechanism to assign tasks to users as an admin, but the process is right now to show all volunteers in each of the task assignment drop downs. 

For the MVP, is this form of one-to-one mapping sufficient? Should we suggest volunteers based on skill sets/skill requirements?

**Comment by tonysurma** [comment]
In order of priority:
Pick from volunteers that have raised their hand like in #31 
Allow admin to add a volunteer to pick (either near drop down or somewhere else) as they may have volunteer relationships and not require existing relationship volunteer to have to go 'do work' just to be on the list
Pick from volunteers and filter/highlight those matching skills (assuming skills are set for the task)
[Future] once we have volunteer data we can highlight volunteers with track record with this type of task etc etc.

So for MVP I would really focus on that first priority and second above and the third is a P3 or lower but nice to have demo and definitely will be the next priority after this MVP if that makes sense

**Comment by mheggeseth** [comment]
Anybody working on this? I'd be happy to.

**Comment by tonysurma** [comment]
This is done now that we have the volunteer workflow working
