### ISSUE TITLE
Refactor Skills Admin to use Command/Query Pattern

### ISSUE THREAD

**Issue by mheggeseth** [HTBox/allReady#430]
Database access for skills admin (under `/Areas/Admin`) is currently using the repository pattern with an instance of `IAllReadyDataAccess` (specifically the `AllReadyDataAccessEF7` partial class  in `AllReadyDataAccessEF7.Skill.cs`) injected into `SkillAdminController`.

In general, we are moving from the repository pattern towards the command/query pattern for data access. This has some nice advantages:
* Data access stays targeted and efficient. Instead of bolting on the couple properties you need for your use case to the "GetFoo" repository method, you create a command that gets just the properties you need. This keeps data access efficient and keeps data access methods from falling victim to the [tragedy of the commons](https://en.wikipedia.org/wiki/Tragedy_of_the_commons). 
* The handler implementation for a command is loosely coupled from consuming code. That is, command handlers are swappable without changing the code that triggers the command so long as the command handler has the same parameter/return signature.

A good, simple example of this pattern is tenant/organization admin (see the classes in the `/Areas/Admin/Features/Tenant` folder and how they are consumed).

**Comment by stevejgordon** [comment]
I've started work on this one

**Comment by stevejgordon** [comment]
Update: This is nearly complete. I've just got the tests to work on and then I should be able to have a PR submitted soon.
