### ISSUE TITLE
Inconsistent Tenant Admin List

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#437]
If you choose Organizations from the Admin menu it takes you to /Admin/Tenant which includes a list in  tabular format with Edit and Delete buttons.

However, saving a new Organization directs to /Tenants which is an un-styled UL.

After creation it should redirect to the /Admin/Tenant path.

**Comment by junderhill** [comment]
I'll take a look at this, if you could assign me to it.
Thanks

**Comment by tonysurma** [comment]
missed closing this per a commit prior
