### ISSUE TITLE
Create Tenant ModelState validation fails on Id property

### ISSUE THREAD

**Issue by junderhill** [HTBox/allReady#443]
When posting to the create action of the TenantController, the ModelState.IsValid returns false as the Id property of the model is 0. I am fixing this as part of #437

**Comment by stevejgordon** [comment]
Hi @junderhill. Have you rebased on the latest code? I'd seen this and it should have been fixed by PR #436

**Comment by junderhill** [comment]
Apologies, no I've missed this one. I'll rebase.

**Comment by stevejgordon** [comment]
No worries. :-)
