### ISSUE TITLE
How do you do your issue numbers?

### ISSUE THREAD

**Issue by markstownsend** [HTBox/allReady#453]
Guys,
Sorry if it's not appropriate to raise an issue for this but I'm new to it all.  I'm doing my own OSS project and am copying the best OSS practices I see on Github.  I'm a long time dotNetRocks listener.  So I was wondering what the significance is of your issue numbers like [5.1.2.2.2](https://github.com/HTBox/allReady/issues/44)?  Some issues have numbers and some don't.  Do the numbers get added once you know what release the issue will go in to (if it's a code change)?
Thanks a lot,
Mark

**Comment by BillWagner** [comment]
@markstownsend Those match the sections in the specification. The document is in the archive here: https://github.com/HTBox/allReady/blob/master/docs/requirements/HTBox%20AllReady%20Requirements.docx

**Comment by joelhulen** [comment]
Cool. I've never seen the spec doc before. Is there a new one?

**Comment by tonysurma** [comment]
In a good way the work got ahead of the spec :) so I will be working on the updates I discussed recently with @OhMcGoo and @smille1834 so we have the definition of what we need to get to the release milestones in Jan/Feb in our hands in the next few days/week
