### ISSUE TITLE
Campaign Admin List

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#455]
On the campaign admin list (/Admin/Campaign), signed in as a user for one org I can see all campaigns from all orgs. Is that the correct behaviour or should that list be filtered to only those from the correct org?

**Comment by mheggeseth** [comment]
An org admin should only see their campaigns on /Admin/Campaigns. They wouldn't be able to do anything with the others.

**Comment by stevejgordon** [comment]
Yes it required a login if I tried to click on any from other orgs. I'll test this out a bit more and verify what's happening.

**Comment by stevejgordon** [comment]
So I've finally checked this and if I login as an org admin I can see campaigns in the admin campaign list from all orgs. If I click though I'm asked to re-authenticate. 

Example here is when logged in as org admin for Humanitarian Toolbox I can see a campaign from New Org also.

![image](https://cloud.githubusercontent.com/assets/3669103/12011089/9ec9a348-acb8-11e5-99bc-70b7026adc6d.png)

Is this correct or should the list show only those from Humanitarian Toolbox?

**Comment by dpaquette** [comment]
Definitely not correct. I have a fix for this. Can this be assigned to me?

**Comment by BillWagner** [comment]
assigned to @dpaquette
