### ISSUE TITLE
Do we need a separate Admin login?

### ISSUE THREAD

**Issue by dpaquette** [HTBox/allReady#458]
I am wondering if we really need a separate login page for administrators. I am thinking we could combine this to a single login page. Aside from the duplicate code, I could see this being confusing if people aren't sure which login they should use. 

Asking because I'm getting started on #262 and I am hoping to avoid doing this in 2 places.

**Comment by joelhulen** [comment]
I wondered about that since the beginning. Why is it separate? We're using the same authentication system.

**Comment by dpaquette** [comment]
The Admin version does some extra checks to redirect to a different page based on the usertype (Site admin vs Org admin), but we could easily do that from the main login page

**Comment by joelhulen** [comment]
Exactly. No reason to have it in a separate place.

**Comment by OhMcGoo** [comment]
I'm all for one login page.

Jim McGowan

**Comment by dpaquette** [comment]
Great! If there are not objections I will take this on before tackling #262 

Please assign to me
