### ISSUE TITLE
Getting error after taking latest code

### ISSUE THREAD

**Issue by manojattal** [HTBox/allReady#464]
I am getting error 
   
"An exception of type 'System.Data.SqlClient.SqlException' occurred in EntityFramework.Relational.dll but was not handled in user code

Additional information: The ALTER TABLE statement conflicted with the FOREIGN KEY constraint "FK_Campaign_Organization_ManagingOrganizationId". The conflict occurred in database "AllReady", table "dbo.Organization", column 'Id'."

I also tried to delete and re-create database. But issue still persists. Code was running properly on my system before taking latest code.

![issue](https://cloud.githubusercontent.com/assets/413961/12062465/18db4dbe-afc3-11e5-907d-a1aa3acdd06a.png)

**Comment by dpaquette** [comment]
I think that a recent refactoring has required that we drop any existing databases. 

 See PR #442

**Comment by mheggeseth** [comment]
Works great for me.
![image](http://mheggeseth.me/allReady/allready.gif)

Are you sure you didn't accidentally introduce divergent changes when resolving conflicts for https://github.com/HTBox/allReady/commit/a4284e4574be53fc21607960c33b5cdaa02f15dd?
You should verify that the only differences between HTBox/master and your branch are the changes you made in https://github.com/HTBox/allReady/commit/4b78a29b16830734d4bec49ae3150aea72885b11.

**Comment by mheggeseth** [comment]
@manojattal Did you get this fixed? If so, please close this issue. If you need any help getting the hang of Git(Hub), let us know how we can help.

**Comment by manojattal** [comment]
@mheggeseth Thanks for your screenshots. It is working for me now. Actually I was deleting database from "Server Explorer" windows and not "Sql Server Object Explorer" window. Deleting from the other windows was not working.
