### ISSUE TITLE
We need scenario tests in AllReady

### ISSUE THREAD

**Issue by BillWagner** [HTBox/allReady#466]
I'd like to see scenario tests done for AllReady, as we have for crisis checkin. The attached document (written by @OhMcGoo and @smille1834 ) describes two of the core workflows.

[AllReady Work Flows.docx](https://github.com/HTBox/allReady/files/76678/AllReady.Work.Flows.docx)

**Comment by BillWagner** [comment]
Pinging @pottereric to see if he wants to help with this project as well.

**Comment by pottereric** [comment]
I'd be glad to help. 

I'll be at CodeMash this week and plan to spend part of the precompiler time in the HTBox Hackathon.

**Comment by tonysurma** [comment]
Great @pottereric.  We'll see you there

**Comment by tonysurma** [comment]
assigning eric and also @pottereric if you want to split this between have scenario tests and have them working in appveyor feel free to create a separate issue

**Comment by digitaldrummerj** [comment]
@tonysurma It feels like the AllReady scenarios covers these requirements and we can close this one.  It does feel like we need more scenarios to be tested and need to create gh issues for them.  Thoughts?

**Comment by stevejgordon** [comment]
We have some basic F# tests in place which do still function. We also have a proposal in for C# Integration Tests and an issue to track that. Will close this and we can track in the new issues.
