### ISSUE TITLE
Refactor Activity and ActivityAPI controllers to use Command/Query Pattern

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#468]
Having now refactored the Skills Admin actions to the command/query pattern I was wondering if it would be valuable to start refactoring some of the existing controllers similarly?

If so I propose starting with the Activity and ActivityAPI controllers.

@mheggeseth Does this sound reasonable? If so I would be able start working on this. I'd also look to add tests in a similar style to those I created for the Skills Admin.

**Comment by mheggeseth** [comment]
Sounds good to me, although if there's any help you can provide to the current milestone https://github.com/HTBox/allReady/milestones/Private%20Preview%20UAT that would be best.

**Comment by stevejgordon** [comment]
@mheggeseth Yes thanks, will focus on picking up current milestone issues and then revisit this at a later point.

**Comment by tonysurma** [comment]
@stevejgordon still interested in this and/or has this been addressed?

**Comment by stevejgordon** [comment]
I think this can be closed out now as the controllers/actions have been updated in nearly all cases.
