### ISSUE TITLE
Organization Name - Should enforce uniqueness

### ISSUE THREAD

**Issue by featuresnap** [HTBox/allReady#469]
When creating a new organization (using Admin..Organizations and then Create New), the application allows creation of multiple organizations with the same name. This could lead to confusion among many similar organizations. Recommend addition of a uniqueness constraint at a minimum.

**Comment by manojattal** [comment]
Hello @ksk100, Are you working on this? Otherwise I can take it up!

**Comment by tonysurma** [comment]
@manojattal if you haven't heard anything go for it.  thanks

**Comment by manojattal** [comment]
I need help in testing my changes. I tried to login with admin user and org admin user, but I do not see an option to create organization. Can someone tell me steps to create an organization?

**Comment by stevejgordon** [comment]
Hi @manojattal. If you login as the administrator@example.com user then you should be able to create an organization.

The from the admin menu, choose Organizations

![image](https://cloud.githubusercontent.com/assets/3669103/13462088/762503e4-e07d-11e5-92ad-17d36d70820d.png)

Then at the bottom of that list you can choose create new

![image](https://cloud.githubusercontent.com/assets/3669103/13462106/8be65af2-e07d-11e5-9574-9c3aea75d3ca.png)

I hope that helps?

**Comment by tonysurma** [comment]
@manojattal any update?  Thx

**Comment by mgmccarthy** [comment]
@tonysurma I think this Issue can be closed. Looks like PR #757 was merged.

**Comment by digitaldrummerj** [comment]
@tonysurma bump
