### ISSUE TITLE
Invalid zip code in Campaign Edit page causes internal server error - remove error

### ISSUE THREAD

**Issue by mgregory22** [HTBox/allReady#470]
Zip code field needs graceful error recovery on /Admin/Campaign/Edit/### page.

Error message:

A database operation failed while processing the request.

DbUpdateException: An error occurred while updating the entries. See the inner exception for details. 
SqlException: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Location_PostalCodeGeo_PostalCodePostalCode". The conflict occurred in database "AllReady", table "dbo.PostalCodeGeo", column 'PostalCode'. 
There are pending model changes for AllReadyContext
Scaffold a new migration for these changes and apply them to the database from the command line:

> dnx ef migrations add [migration name] 
> dnx ef database update

**Comment by mgregory22** [comment]
Actually, it doesn't seem to accept any zipcode

**Comment by mgregory22** [comment]
Ok, it accepts zipcodes that exist in the PostalCodeGeo table

**Comment by stevejgordon** [comment]
I've seen this same issue in the Create Campaign flow also. I guess this needs some discussion on how this should function. 

* Should it be an autocomplete from the available post codes in the PostalCodeGeo table? 
* What if someone is adding a campaign and their postcode doesn't exist yet? 
* How is the PostalCodeGeo anticipated to be managed to add/remove them?

**Comment by tonysurma** [comment]
For now lets make it not error and/or pretty print an error message like 'invalid code' and I have opened up a new issue #530  to discuss the right workflow

**Comment by stevejgordon** [comment]
I'm working on a possible quick fix for this currently.
