### ISSUE TITLE
Campaign FullDescription text is not persisted after create or update

### ISSUE THREAD

**Issue by featuresnap** [HTBox/allReady#471]
Instructions to reproduce:
* Navigate to Admin..Campaigns
* Click Create New
* Fill out campaign fields, including placing some text in the FullDescription tinyMCE rich text editor
* Click Create to submit the new campaign, this returns you to the Campaign Details page
* Click "Edit" link (small pencil icon next to campaign name)
* On campaign edit page, the text of the FullDescription is now empty.
* Values entered in FullDescription field do not appear in dbo.Campaigns.FullDescription column, i.e. the text is never persisted.

**Comment by stevejgordon** [comment]
I'm taking a quick look at this issue
