### ISSUE TITLE
When a Registered User Unvolunteers, notify organizer of any tasks that have been unassigned

### ISSUE THREAD

**Issue by trayburn** [HTBox/allReady#473]
Split from #183 to create a more manage-able pull request, please see discussion there.

**Comment by mmoore99** [comment]
I would like to take a shot at this.

**Comment by mmoore99** [comment]
@mheggeseth or anyone else that wants to chime in, I have begun working on this issue and have a general question regarding approach.  When using the command/query pattern if there is an existing query that returns a model that contains all but a few of the properties that are needed what is the best/preferred practice for getting access to the additional properties? Modify the existing query model and query handler, inherit from the existing query model and create a new query handler or create an entirely new query model and query handler?

**Comment by mheggeseth** [comment]
I mostly punt this to @dpaquette or @MisterJames. My gut feel is that if both queries have the same meaning and are used for the same purpose, then update or inherit, otherwise make a new query model/handler. One of the goals of the command/query pattern is to avoid the confusion that comes from trying to cram multiple use cases into a single repository model, however I can see the potential maintenance overhead that could arise from the proliferation of many slightly different queries.

**Comment by mmoore99** [comment]
I am trying to determine where to get the email address for the campaign organizer to send the notification email referenced in this issue.  There is an "Organizer" property in the campaign, but as far as I can tell it is never being populated.  In fact, it appears that the First Name, Last Name, City, State, Postal Code, Country, Phone Number and Email fields on the create campaign page are never stored anywhere.  @stevejgordon @dpaquette I noticed that you both did some work on the "EditCampaignCommandHandler", am I totally missing something here or is this a bug?

**Comment by stevejgordon** [comment]
@mmoore99 In the "EditCampaignCommandHandler" there is a call to

campaign = campaign.UpdateCampaignContact(message.Campaign, _context);

That then updates a contact for the campaign which is stored in the Contact table and the link between the contact and the campaign is maintained in the CampaignContact table.

**Comment by mmoore99** [comment]
@stevejgordon thanks for that info.  Since there are potentially multiple contacts associated with a campaign should the notification email be sent to all contacts?
