### ISSUE TITLE
Volunteer available for closed activities

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#478]
When testing the activity process I noticed that when viewing the details for a closed activity within a campaign I could still volunteer.

Is this correct as I'd expect that once closed no new volunteers can signup? 

If this is confirmed as a bug I propose we can simply hide the volunteer link for any closed activities.

**Comment by mheggeseth** [comment]
Makes sense to me to take the volunteer link away once an activity is over.

**Comment by stevejgordon** [comment]
@mheggeseth Thanks. I'll take a look at this since it's probably a quick job to slot in.

**Comment by tonysurma** [comment]
@mheggeseth can you give the PR a once over please?
