### ISSUE TITLE
Campaign Location Display

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#479]
When viewing a campaign under the http://localhost:48408/Campaign/2 url should the location address be displayed on the page somewhere?

At the moment I cannot see this exposed in the UI except in the admin areas. There is a map link from the campaign listing page (although that itself might be broken too) but in the details page I think it would be useful to at a glance see the primary location perhaps?

**Comment by tonysurma** [comment]
Agree it should show there.  We should mock up display to get feedback as well as will need to think about overall geo issues like in #530

**Comment by stevejgordon** [comment]
Having checked this - It looks done so I'm closing this. UI and design will be covered in other issues
