### ISSUE TITLE
Using Should for unit test assertions

### ISSUE THREAD

**Issue by Sobieck** [HTBox/allReady#482]
I've been contributing to this project writing some unit tests and I was wondering if we would be interested in using the [Should](https://github.com/erichexter/Should) assertion library. 

I love using Should and I find myself missing it greatly when writing tests in the old `Assert.Equal(expectation, actual)` way. 

The library allows you to use extension methods to make your assertions. The syntax is `actual.ShouldEqual(expectation)`. This eliminates the need to remember the order of the arguments in the assertion. It also allows you to use intellisense to find assertions for the type that you are testing easily.

**Comment by robrich** [comment]
I like this syntax as well.  I've been using http://www.fluentassertions.com/ (https://github.com/dennisdoomen/FluentAssertions) which has been ported to .net core.  Fluent Assertions also makes incredibly awesome test fail messages.

**Comment by stevejgordon** [comment]
I've recently been using fluent assertions on a few work projects and do prefer the syntax and readability of the assertions. Glad to here it has a .net core port. Does that support RC2 when we are ready to move forward with a migration? Although we now have RTM date for 27th June so perhaps we skip straight to RTM.

**Comment by mgmccarthy** [comment]
we already have Shouldy installed. Does Should or FluentAssertions bring anything to the table that Shouldy does not? 

I'm only asking, b/c every library we add creates a potential learning curve for new contributors. 

@tonysurma @BillWagner @MisterJames any thoughts on adding these libraries?

**Comment by tonysurma** [comment]
@stevejgordon @mgmccarthy @MisterJames what say we on should, should and FluentAssertions?

**Comment by robrich** [comment]
I've seen more weight behind FluentAssertions, though both seem to work great on .net core.

**Comment by mgmccarthy** [comment]
Since I've never used FluentAssertions before, I defer to other's expertise that have used the framework.

**Comment by JowenMei** [comment]
I have used FluentAssertions on several projects and its very self explanatory. No worries about the learning curve here. Either way, I think the differences are pretty small between the several libraries. I would just pick one asap because they all improve readability over the standard **Assert** syntax.

**Comment by stevejgordon** [comment]
@tonysurma We have Shoudly in place already and it's used it a fair number of tests, therefore I would propose we stick with that so we have a single library in use. I've used both and the differences seem to be negligible.

If you're happy, I would propose we close this?

**Comment by tonysurma** [comment]
let's keep with Shouldly as it is current in our codebase as you said @stevejgordon
