### ISSUE TITLE
Need to use correct email address in notifications

### ISSUE THREAD

**Issue by mmoore99** [HTBox/allReady#494]
@MisterJames  While working on issue #473 it came to my attention that the previously developed code that generates email notifications when new users sign up for an activity (NotifyAdminForTaskSignupStatusChange.cs) and a task status change takes place (NotifyAdminForTaskSignupStatusChange.cs) sources the admin email address from the **Campaign.Organizer** property.  This property is not being populated anywhere in the app and I was instructed for #473 to get the email address from the **Campaign.CampaignContacts** collection.  If this is indeed correct, I have made the changes to the above two referenced routines to use the email address from **Campaign.CampaignContacts** and will submit a PR with those changes.

Is **Campaign.Organizer** a dead property?  If so, should it be removed to avoid confusion?

**Comment by mheggeseth** [comment]
I don't think we know exactly what **Campaign.Organizer** is supposed to be for, but seeing as CampaignContacts at least has the possibility of containing something, I think it's fine to go with that.
