### ISSUE TITLE
Scenario V1: Volunteer Edit Profile

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#501]
_These issues are scenarios documented for use of the application.  Likely will be the 'parent' of multiple sub issues to verify, add or fix functionality to support them._

# **Volunteer Edit Profile**
Initiation: Volunteer has registered, logged in and navigates to user profile options
Features:
- [ ] Volunteer can enter/edit name as required field
- [ ] Name appears as supplied at top next to Hello instead of email address
- [ ] Volunteer can enter/edit phone number
- [ ] App performs verification via SMS on phone number
- [ ] Volunteer can update password (if using site account)
- [ ] Skills - Volunteer can self report skills by adding/removing skills from list
- [ ] Skills - Skills list contains skills user supplied on this screen as well as any identified when they volunteer

**Comment by mmoore99** [comment]
@tonysurma After reviewing the app and the code it appears to me that the existing code supports the requirements of the above workflow with the exception of making the 'name' field required.  I am in the process of making the changes needed to do this. **Should I submit the pull request against this issue or create a sub issue referencing this issue as parent?**

Also, should 'name' be added to the new user registration page? If so, should it be required?
