### ISSUE TITLE
Scenario V2: Volunteer volunteers for Campaign

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#502]
_These issues are scenarios documented for use of the application.  Likely will be the 'parent' of multiple sub issues to verify, add or fix functionality to support them._

# **Volunteer Volunteers for Campaign**
Initiation: Volunteer has navigated to campaign at activity or task level where volunteering is an option (per campaign type)
Features:
- [ ] Volunteer link is present and worded with clarity _not just 'volunteer' but something like 'Volunteer for this Campaign'_
- [ ] If Volunteer is not logged in they are prompted to log in
- [ ] If Volunteer is not registered they are prompted to register
- [ ] Volunteer fills in fields presented (which are prepopulated from profile as possible)
- [ ] Volunteer self identifies having skills presented by checking checkboxes in list
- [ ] Skills the Volunteer have previously identified and that are in this list are already checked
- [ ] After volunteering a message is displayed on that campaign page indicating they are registered as a volunteer for this campaign and an event organizer will be in touch

**Comment by mmoore99** [comment]
@MisterJames @tonysurma With the changes being introduced to the Activity workflows in #504 (Volunteer & Org Admin Workflow Differs By Activity Type), I would propose that the workflow items shown here should be merged into in the individual issue items for each of the activity types (see #506 ) and that this issue be closed to prevent confusion.

**Comment by mmoore99** [comment]
**This is covered by PR's #518 and #523**

**Comment by tonysurma** [comment]
I need to review what all is complete per the PRs and what is open per new requirements if anything

**Comment by mmoore99** [comment]
@tonysurma the workflow described in this issue was handled in #506 & #507. This issue can be closed.
