### ISSUE TITLE
Scenario A1: Administrator Creates a Campaign

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#503]
_These issues are scenarios documented for use of the application.  Likely will be the 'parent' of multiple sub issues to verify, add or fix functionality to support them._

# **Administrator Creates a Campaign**
Initiation: User registered and logged in as a Organization Administrator 
Features:
- [ ] Administrator can click link to create Campaign from Admin->Campaign and Campaign pages

_**Scenario to be fleshed out more**_

**Comment by stevejgordon** [comment]
@tonysurma Currently creating a campaign from the Admin > Campaign page is already in place. So to meet this scenario as it stands we just need to create a link from the main Campaign page to job to the Add Campaign screen (visible to org and admins only)?

**Comment by tonysurma** [comment]
@stevejgordon yes, the 'non-admin' campaign list page should get that add button with visibility as you stated.  Thanks

**Comment by stevejgordon** [comment]
@tonysurma I think we can close this issue? Looks like it didn't auto close because of the wording of my PR.

**Comment by tonysurma** [comment]
yep, closing this per your PR
