### ISSUE TITLE
Adding a reference for unobtrusive ajax for partial view rendering?

### ISSUE THREAD

**Issue by bluechrometouch** [HTBox/allReady#517]
So it seems the ajax helper requires a reference to jquery unobtrusive ajax. What I'm trying to do is filter down event results and return it as a partial view.
Would there be any problems?

**Comment by dpaquette** [comment]
What ajax helper are you referring to?

**Comment by bluechrometouch** [comment]
Ajax.ActionLink

**Comment by dpaquette** [comment]
Ajax helpers don't exist in ASP.NET Core MVC

https://github.com/aspnet/Mvc/issues/2015

**Comment by dpaquette** [comment]
What feature are you working on? Maybe we can work together to figure out an alternative approach.

**Comment by tonysurma** [comment]
closing for now, can reopen if issue rearises
