### ISSUE TITLE
Activity Dates

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#519]
I've noticed a few odd issues with dates (always fun) when creating an activity for a campaign.

Firstly the start date defaults to the current date. If I create a Campaign for the future, then go in to create an activity the start date will never be valid since it will be today's date instead. Not major but a bit of a pain for a user who is setting up future campaigns to have to change this for each new activity.

To solve this I would propose setting the start date to the campaign start date and end date one month later?

Secondly even if you use the current date (default) for a new campaign and then add a new activity, I've noticed the validation can fail incorrectly. This is caused by the activity start date being compared to the campaign date before it has the timezone applied. So the campaign date may be negative x hours but the activity date has not had that applied at the point of comparison. To solve this I would propose fixing the ActivityAdminController to first apply the timezone to the dates before any validation logic occurs.

Secondly I would propose that we also convert the dates to UTC time when performing any comparison logic using the UtcDateTime property on the DateTimeOffset object. In rare cases when a comparison may be occurring between dates in differing timezones this would help avoid issues.

Before I start on this just wanted someone from the project to confirm this sounds reasonable?

**Comment by NotTheNull** [comment]
I have a fix in place in my fork though I had other questions regarding the validation of the dates:

1.   Should there be an error if the admin selects an Activity Start Date that exceeds the Campaign End Date?  Similarly, should there be an error if the admin selects an Activity End Date that exceeds the Campaign End Date?


2) If the Activity's defaulted End Date exceeds the Campaign End Date, should it revert to the Campaign's End Date?
3)

**Comment by tonysurma** [comment]
1) yes and yes
2) yes

thanks
