### ISSUE TITLE
No page after rejecting MS Account Login

### ISSUE THREAD

**Issue by glittle** [HTBox/allReady#521]
After clicking to log in using my Microsoft Account, I decided to click "No" and not give all the permission asked for. I was redirected to:

http://allready-d.azurewebsites.net/signin-microsoft?error=access_denied&error_description=The%20user%20has%20denied%20access%20to%20the%20scope%20requested%20by%20the%20client%20application.&state=CfDJ8JpNXGetVhVOqpGUyBpOqdZZ3TrR65z1WHOFdaMcph3fhU9aivprGUyJEqwp65kQCDfu_dXOWW8Bx9nL82W5x5uJFTlBQTGfXl5aWAj-_Ue5Khf2ADPacc12EZ0o0HEh1Lpk7GEDLffQrlk0IPX3hm6s35g11ZspO4tUPkkB8H5zD3kWBQCqxKJBS_aBx7RIslagEAiJNR8WJM06FaSjjEcSXElu0LbMUdW63tXf47g-KH04QKf74bz43L_5hGXLzXhDXGrsySGZlM39jVF-l2VIUGvq22nE5Veo86P9qcoSHNcJGwLnIt1KrwqNFDPFag

but only got a blank page.

**Comment by glittle** [comment]
Similarly, after refusing to give all the permission requested from Twitter, got a blank page at this location: 

http://allready-d.azurewebsites.net/signin-twitter?denied=u-V7uAAAAAAAikCZAAABUvU8uqQ

**Comment by glittle** [comment]
May also want to review what information is being required. Just getting the email address should be enough....

**Comment by stevejgordon** [comment]
@shahiddev do you think that change you made earlier should have fixed this?

**Comment by shahiddev** [comment]
@stevejgordon Possibly, it depends on exactly what point of auth flow was cancelled. I'll test it to be sure so we can close this out if not required.

**Comment by shahiddev** [comment]
@stevejgordon Yes works as expected after fix #1707 and returns user to login screen so we can close this one off
