### ISSUE TITLE
Locked campaign appearing on Organization homepage

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#524]
I forgot to filter out the locked campaigns on the org home page http://localhost:48408/Organization/{id} when implementing the locked campaign requirement.

I will have a PR to address this very soon.

**Comment by stevejgordon** [comment]
I will take a few extra minutes to move this action to the command/query pattern whilst I'm there.

**Comment by tonysurma** [comment]
closed in pull request #525
