### ISSUE TITLE
Typo in About section

### ISSUE THREAD

**Issue by palittle** [HTBox/allReady#528]
About page - Work together section
This sentence seems to be missing a word or something.

> allReady allows campaign coordinators to engage, contact and connect volunteers with **the that** need to be delivered.

**Comment by glittle** [comment]
@dpaquette - what wording would you like here?

**Comment by glittle** [comment]
I'll take this...

**Comment by tonysurma** [comment]
'the preparedness work that"

**Comment by glittle** [comment]
Thanks! Will do...

**Comment by palittle** [comment]
So it should read:

 allReady allows campaign coordinators to engage, contact and connect volunteers with the preparedness work that needs to be delivered.

**Comment by tonysurma** [comment]
@palittle yes
