### ISSUE TITLE
Improve UX of attempted login for admin users who have not confirmed email address

### ISSUE THREAD

**Issue by dpaquette** [HTBox/allReady#535]
As an organization admin or site admin user who has not yet confirmed their email address, I get the following error page when trying to log in.
![image](https://cloud.githubusercontent.com/assets/2531875/13198336/225f4de8-d7d4-11e5-869d-37e796b9527a.png)

I think we should display page that is a little clearer. The current page makes it look like the application has crashed.

**Comment by digitaldrummerj** [comment]
@tonysurma @dpaquette looks like this issue was fixed in PR and can be closed.
