### ISSUE TITLE
Layout issues on Create Activity page

### ISSUE THREAD

**Issue by palittle** [HTBox/allReady#540]
The descriptions are overlapping the input boxes.  `http://allready-d.azurewebsites.net/Admin/Activity/Create/7`

![image](https://cloud.githubusercontent.com/assets/17350634/13198543/f318b3a4-d7c8-11e5-8998-6f63ab9d5b85.png)

**Comment by tonysurma** [comment]
needs verification

**Comment by Daven-** [comment]
I will be working on this if no one else is yet.

**Comment by tonysurma** [comment]
@Daven- it's yours

**Comment by Daven-** [comment]
Okay so I've verified that this is fixed, tested on latest chrome, firefox and IE. That is if Activities are now called Events, could not find 'Activity'.

**Comment by tonysurma** [comment]
That is right so I will close this out.  Thanks!
