### ISSUE TITLE
Can't add location and address to Activity page

### ISSUE THREAD

**Issue by palittle** [HTBox/allReady#545]
The activity page `http://allready-d.azurewebsites.net/Activity/14` has space for the location and address to appear but the Edit activity page `http://allready-d.azurewebsites.net/Admin/Activity/Edit/14` does not have input fields to enter them.

**Comment by Inn0cu0us** [comment]
Hi, I will work on this one. I am new to the project and this looks like a good place to start.

**Comment by tonysurma** [comment]
Thanks @pboyer84

**Comment by pboyer84** [comment]
I added the input fields in the edit screen and the data persists as shown in the screenshot below. I will sleep on it and provide unit tests before submitting a PR. In addition, I will deploy to Azure for you @palittle to try out the code hands on. Keeps your eyes open for another message after it's been deployed.
![candidatefix](https://cloud.githubusercontent.com/assets/1923614/14038576/2c0273a6-f229-11e5-8985-7864c52f5f72.png)

**Comment by BillWagner** [comment]
Fixed in PR #633
