### ISSUE TITLE
Async/await improvements

### ISSUE THREAD

**Issue by SeanFeldman** [HTBox/allReady#549]
There are a few items that are related to mixing sync and async code.
This is an "umbrella" issue to span all of these.

- [x] Replace `.Wait()/.Result()` with .`GetAwaiter()/.GetResult()` #547
- [x] Make code async all the way #548

**Comment by mgmccarthy** [comment]
@SeanFeldman, could you provide any guidance as to when we should be using async/await with MediatR from controllers? For example, does it make sense to use it when we're sending a request to query for data, or only when we're sending more of a "command" to "do something"? For example, the SkillController seems to use MediatR async for both queries and commands and it's action methods are async. Should we "async await all the things", or are there some things where there is no benefit?

**Comment by SeanFeldman** [comment]
@mgmccarthy I'm following this guideline:
if the code is using async, the whole chain should be using async.
With mediator, one needs to look into the handlers to see if A) there's IO bound work B) if async code of the underlying library is used within the handler. If answer is yes to either, then I'm going with async.

In regards to query or command. The above still applies. Both command and query are IO bound (command does `.SaveChangesAsync();` and query does `.SingleOrDefaultAsync(s => s.Id == message.Id);`

**Comment by SeanFeldman** [comment]
@tonysurma both issues are merged. We're good on this one. If you'd like me to work anything related, please let me know.
