### ISSUE TITLE
Missing Campaign Organizer info on Activity page

### ISSUE THREAD

**Issue by palittle** [HTBox/allReady#555]
The activity page `http://allready-d.azurewebsites.net/Activity/14` has a place for Campaign Organizer info but it is blank even though info was added on the Campaign page `http://allready-d.azurewebsites.net/Admin/Campaign/Details/7`

![image](https://cloud.githubusercontent.com/assets/17350634/13199213/5e72b4c0-d7dc-11e5-8b64-5b69d9b34314.png)

**Comment by tonysurma** [comment]
needs verification

**Comment by stevejgordon** [comment]
This no longer appears to be an issue.

![image](https://cloud.githubusercontent.com/assets/3669103/22027543/18798c96-dccc-11e6-86ff-98a736a714fa.png)
