### ISSUE TITLE
Swap input boxes to make meaning more clear

### ISSUE THREAD

**Issue by palittle** [HTBox/allReady#556]
On this page:  [http://allready-d.azurewebsites.net/Admin/Campaign/Edit/7](http://allready-d.azurewebsites.net/Admin/Campaign/Edit/7)

I think it would be better to have the Campaign Impact Goal input box appear before the Impact Type dropdown as that will always show (not dependent on what is chosen in the dropdown). In other words, swapping the two top boxes should make it less confusing to the user.

![image](https://cloud.githubusercontent.com/assets/17350634/13199261/c0ee4622-d7dd-11e5-9ff9-fd7987f634cc.png)

**Comment by GitaGunnam** [comment]
I am taking this
