### ISSUE TITLE
Saving Activity without Name throws DbUpdateException

### ISSUE THREAD

**Issue by mikesigs** [HTBox/allReady#557]
Name is a required field so we should do some Model Validation before trying to save to the DB.

**Comment by MisterJames** [comment]
@tonysurma / @BillWagner if you get a chance can you add @mikesigs to the repo so we can assign him issues? Thanks!

**Comment by mikesigs** [comment]
The controller/action in question is ActivityAdminController.Create

**Comment by tonysurma** [comment]
@MisterJames done

**Comment by MisterJames** [comment]
Looks like this was cleaned up as a side effect of other work:

![image](https://cloud.githubusercontent.com/assets/1197383/13724291/a22be4dc-e846-11e5-98c5-df7664fad58b.png)
