### ISSUE TITLE
Show Required Skills on Admin/Activity/Details and Admin/Task/Details

### ISSUE THREAD

**Issue by mheggeseth** [HTBox/allReady#559]
The set of required skills for an activity or task is not displayed on the task admin details (`Admin/Task/Details`) or the activity admin details (`Admin/Activity/Details`) views.

Activity details:
![image](https://cloud.githubusercontent.com/assets/775229/13199440/feff3c3e-d7ea-11e5-83ef-6a6b55de667e.png)

Activity edit:
![image](https://cloud.githubusercontent.com/assets/775229/13199442/0d2e4a84-d7eb-11e5-886c-e4460c93ca59.png)

Task details:
![image](https://cloud.githubusercontent.com/assets/775229/13199452/26a6d170-d7eb-11e5-80d4-5e682d6b3ec7.png)

Task edit:
![image](https://cloud.githubusercontent.com/assets/775229/13199454/389a4362-d7eb-11e5-8bdc-ebdb765d4311.png)

**Comment by YannickMeeus** [comment]
I'm working on this. Once it's relatively stable I'll open a PR and add some screenshots of how I've got it displaying right now.

**Comment by tonysurma** [comment]
Thx @YannickMeeus

**Comment by YannickMeeus** [comment]
@mheggeseth - When displaying the Required Skills, are we only interested in the child-most skill in the skill hierarchy or is there a requirement to display any higher levels in the tree?

I would imagine that displaying at least the closest parent is reasonable. I can imagine some skills being quite confusing without the parent skill to provide context. Any thoughts?

**Comment by mheggeseth** [comment]
@YannickMeeus notice that `HierarchicalName` is a computed property and only works if the `ParentSkill` relation has also been loaded so watch out for that.
