### ISSUE TITLE
Assignee and Status not showing  on Activity Details page

### ISSUE THREAD

**Issue by palittle** [HTBox/allReady#561]
On the Activity Details page `http://allready-d.azurewebsites.net/Admin/Activity/Details/16` the assignee and status aren't showing even though there was a volunteer assigned to it and the task was completed on the Activity page `http://allready-d.azurewebsites.net/Activity/16` See 2 screenshots below:

![image](https://cloud.githubusercontent.com/assets/17350634/13199515/ccc70158-d7e4-11e5-9dd3-9971fc0242a1.png)

![image](https://cloud.githubusercontent.com/assets/17350634/13199533/a5b4f5ce-d7e5-11e5-98a8-489555fb1829.png)

**Comment by stevejgordon** [comment]
@tonysurma You can assign this to me if you want and I'll try to take a look at it.
