### ISSUE TITLE
Didn't receive email

### ISSUE THREAD

**Issue by palittle** [HTBox/allReady#566]
On the Admin Activity page `http://allready-d.azurewebsites.net/Admin/Activity/Details/16` you can send an email to the volunteers. I sent one to myself but did not receive it (not in junk mail either). I, however, did receive email from allReady when I became a volunteer.

![image](https://cloud.githubusercontent.com/assets/17350634/13199704/7d9a003a-d7e9-11e5-974c-a49839a93c12.png)

**Comment by palittle** [comment]
The email arrived the following morning at 10:04. Don't know what the delay was.

**Comment by SeanFeldman** [comment]
Unfortunately, email is not a reliable mechanism for notifications. The fact that it did show up is good, means things do work :)

**Comment by MisterJames** [comment]
Closing as email arrived. Thanks for the report!
