### ISSUE TITLE
Show Campaign Impact Goal status?

### ISSUE THREAD

**Issue by palittle** [HTBox/allReady#568]
Should the Campaign page show the Campaign Impact Goal status in the green box as it does on the Admin Campaign page? The green box on the Campaign page looks incomplete so I am assuming that it show this.

`http://allready-d.azurewebsites.net/Campaign/7`
![image](https://cloud.githubusercontent.com/assets/17350634/13199768/a6beb0f8-d7eb-11e5-98e0-3019c6dc74f9.png)

`http://allready-d.azurewebsites.net/Admin/Campaign/Details/7`
![image](https://cloud.githubusercontent.com/assets/17350634/13199753/413107fe-d7eb-11e5-901c-7e2e843555ab.png)

**Comment by danielepo** [comment]
this was fixed by PR https://github.com/HTBox/allReady/pull/1047

**Comment by digitaldrummerj** [comment]
@tonysurma looks like this can be closed since it was fixed in the PR.
