### ISSUE TITLE
add focus selector on tabs

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#573]
This is documented in comment on pull request #569

**Comment by mheggeseth** [comment]
https://github.com/HTBox/allReady/pull/569#discussion-diff-53570426 to be precise.

**Comment by mheggeseth** [comment]
@tonysurma Assign this to me

**Comment by tonysurma** [comment]
@mheggeseth was this taken care of in one of your PRs?  Thx

**Comment by mheggeseth** [comment]
@tonysurma I'm pretty sure this isn't fixed yet. I'll do it real quick though. Been a while since I did a PR.
