### ISSUE TITLE
Removed unused usings from files...

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#574]
There a a good amount of unused usings in file across the solution. Tools like ReSharper make cleaning these up a breeze, make the code more readable and reduce the size of the code. 

I realize it's low-priority but wanted to bring it up as a simple way for someone to get involved.

**Comment by YannickMeeus** [comment]
I don't mind picking this up to get my feet wet with this project. Quick question still, is there a specified project-specific order to using statements or can I just remove unused statements and alphabetize them?

**Comment by mgmccarthy** [comment]
@YannickMeeus, I know that ReSharper has an "organize usings" refactoring (or something along those lines) that you could probably use, but it's not a requirement that the order of the using statements be changed. It's more important to go in there and delete all unused usings for now. That's really going to help clean up the code.

**Comment by tonysurma** [comment]
Thanks @YannickMeeus and @mgmccarthy

**Comment by YannickMeeus** [comment]
The web app changes have been merged into master, do you guys think it'd be good if I just run the same type of cleanup on the Tests project? If not, this issue can probably be resolved.

**Comment by tonysurma** [comment]
PR was merged, can I consider this closed @YannickMeeus

**Comment by YannickMeeus** [comment]
@tonysurma Go for it.
