### ISSUE TITLE
Mediator is called a bus, but it's not

### ISSUE THREAD

**Issue by SeanFeldman** [HTBox/allReady#580]
Looking at the code, `IMediator` is called a `bus` throughout the base code.
While it's sending commands and raises events, it does it in a way that couples caller and callee within the same process. This encourages a thought that a bus should behave like this, where a typical bus would send a command or raise an event in an asynchronous way. To process response it would do it via handler registration. Perhaps all instances should be called what they represent, `mediator`?

**Comment by mgmccarthy** [comment]
@SeanFeldman, I didn't want to say anything, so I'm glad you did! Thanks for explaining why it's not a bus. I'm in favor of refactoring to mediator.

**Comment by mikesigs** [comment]
I agree. I thought the choice of name "bus" was odd. But didn't go beyond that thought. I just figured it might be called that because MediatR was inspired by ShortBus? But even then, ShortBus is an "in-process mediator."

+1 for calling instances `mediator` then.

**Comment by SeanFeldman** [comment]
@tonysurma any objections?

**Comment by SeanFeldman** [comment]
@tonysurma ping :)

**Comment by tonysurma** [comment]
Hmm, I guess the i a days didn't stick.  I have no objections, @canadianjames ?

**Comment by tonysurma** [comment]
Err @misterjames ?

**Comment by mgmccarthy** [comment]
@tonysurma @SeanFeldman did you want want PR that just contains these re-namings? Might be easier to close the issue with one PR that does it across the solution.

**Comment by SeanFeldman** [comment]
@mgmccarthy that was the intent.

**Comment by mgmccarthy** [comment]
@SeanFeldman, you can close this request
