### ISSUE TITLE
add missing unit tests to ActivityApiControllerTest

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#587]
Issues #567, #59 and #580

**Comment by mgmccarthy** [comment]
@tonysurma @BillWagner 

looks like the unit tests in this controller rely on standing up actual pieces of infrastructure via the serviceProvider:
.AddEntityFramework
.AddInMemoryDatabase
.AddDbContext

and then sets up a hosting environment?

it also inherits from a class called "TestBase" which stands up other pieces of run-time infrastructure like   in asp.net/mvc like DefaultHttpContext, HttpAuthenticationFeature and HttpContextAccessor.

Unless ASP.NET 5/Core 1 (or whatever Microsoft is calling it) takes a VERY different approach to unit testing (you involve pieces of infrastructure or run-time environment provided items), then isn't this test really an integration test?

I guess I'm a little confused coming from strictly unit test background. I an under the assumption we use a mocking framework like Moq to "mock" out run-time dependencies so the unit tests test the business functionally without relying on any other type of providers, services, databases, etc...

I might be off base here b/c this is something the allReady project wants to do. I just don't see a consistent approach to how to unit test things like database connections... some code uses TestBase, other code is purely using mocks (which is how unit testing "should" be done) in order to run unit tests...

any feedback?

**Comment by mgmccarthy** [comment]
@tonysurma. I have a question on the inital commit of ActivityApiController. The public ActivityViewModel Get(int id) method seems to return null, yet calls to HttpNotFound before doing so:
```
public ActivityViewModel Get(int id)
{
    var dbActivity = _prepOpsDataAccess.GetActivity(id);

    if (dbActivity != null)
    {
        return new ActivityViewModel(dbActivity);
    }
    this.HttpNotFound();
    return null;
}
```

in no other controllers are we returning null when using HttpNotFound when we can't find the entity we're looking for on the lookup query. 

Should be instead be returning HttpNotFound here and not be returning null?

**Comment by mgmccarthy** [comment]
@stevejgordon, @BillWagner, @mmoore99, @MisterJames, @TonySurma. I some questions on IAllReadyDataAccess vs.direct AllReadyContext usage in the code.

1. I see some classes (such as SkillListQueryHandlerAsync) that work directly with AllReadyContext instead of IAllReadyDataAccess. Is there a reason why we have two ways to access and work with the database in the project? In order to unit test SkillListQueryHandlerAsync, it looks like the test method needs to spin up an in-memory DbContext during unit test execution and populate some test data.  There are also some base classes I noticed; TestBase, InMemoryContextTestBase, etc... What are the expect usage patterns around these base classes? Should only handlers use them, controllers, etc... When writing my unit tests, should I be aiming for one of the other?

2. why doesn't IAllReadyDataAccess expose its read methods as async? Looks like EF7 has full async support, and I see .ToListAsync and .SingleOrDefaultAsync usage in classes that use AllReadyContext instead of IAllReadyDataAccess.

I'm new to both ASP.NET Core 1 and EF7 (although I did get to watch Julie Lerman's EF7 tutorial on Plurasite last night). It looks like EF7 now has an in-memory configuration which allows you to work with a database without anything being written to disk. It seems some of our unit tests do in-memory database set up and then run the sut using that test data setup. 

I'm accustomed to writing unit tests by mocking db access and not relying any type of dependent services (aka, db servers), yet here, we're not really relying on sql server b/c the context is run in-memory (but we are relying on EF7).

Any thoughts/feedback?

**Comment by BillWagner** [comment]
Re 1: I'd like to see us move to one method of access in the app. My conjecture is that the reason we have two is that we are developing against a moving target. I'll let other speak to which method should be preferred going forward:

Re 2: We had been moving toward all async access. I believe that what you are seeing is artifacts from the first (synchronous) implementation. When you are working in those areas, we should move those to the async usage. When possible, please make those changes their own commit. It helps with the review when determining what is new behavior, and what represents moving to the preferred implementation.

That said, we are close to a pilot with the Red Cross, so care should be taken so that change don't jeopardize the release.

**Comment by mgmccarthy** [comment]
@BillWagner thanks for the feedback. Seeing as Red Cross pilot is close, I'll take care not to make any changes to those API's that are used throughout the system (like IAllReadyDataAccess). In the meantime, I'll continue my ActivityApiController refactor to mediator as well as finish up all unit tests for it.

Maybe after the pilot, there could be more of a overall push towards changing to async as well as getting unit test coverage up? Refactoring is tough when you don't have at least basica unit test coverage in place.

**Comment by mgmccarthy** [comment]
@BillWagner, I'm ready for a PR for this issue. It's a good amount of changes. Lots of refactoring to ActivityApiController, lots of unit tests added, lots of command/queries/handlers and related tests added. You mentioned you're close to the Red Cross pilot. Do you want me to hold off until after?

**Comment by BillWagner** [comment]
@mgmccarthy We have a big enough window before the pilot, let's merge sooner rather than later (it gets us much better test coverage.)
