### ISSUE TITLE
TaskApiController: adding unit tests and refactoring to mediator

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#604]
@mmoore99 @mikesigs 
Issue #59 and Issue #567

**Comment by mgmccarthy** [comment]
@mmoore99 @mheggeseth @MisterJames is there any reason we're returning `Task<object>` from the action methods on the TaskApiController instead of returning `Task<ActionResult>` (like ActivityApiController), or better yet, returning `Task<JsonResult>` from api controller actions that return json?

**Comment by mmoore99** [comment]
@mgmccarthy yes, it probably should be `Task<JsonResult>`

**Comment by mgmccarthy** [comment]
@mmoore99, does POST, PUT and DELETE on the TaskActivityController actually work? If so, do you have some sample data (maybe in json) that I could use to call these methods via Fiddler? Or maybe there is a different way you smoke tested this code where I could actually run it?

**Comment by mmoore99** [comment]
@mgmccarthy I did not write the `POST, PUT and DELETE` methods.  The only methods that I wrote are  `RegisterTask`, `UnregisterTask` and `ChangeStatus`.  I'm not positive, but i don't think that `POST, PUT and DELETE` are used by the web app.  They may be used by the mobile app, which I have not looked at yet.

**Comment by mgmccarthy** [comment]
@mmoore99, thanks for the background info. I just want to make sure I have all my bases covered before submitting a PR for the TaskApiController refactoring

**Comment by mgmccarthy** [comment]
@mmoore99, are `RegisterTask, UnregisterTask` and `ChangeStatus` used by the web app? If they are, is there a certain view they're invoked from? I',m assuming b/c this is web api controller this is just going to handle http requests, but I'm not too sure what the client is that will be sending these. mobile app?

**Comment by mmoore99** [comment]
@mgmccarthy yes, `RegisterTask`, `UnregisterTask` and `ChangeStatus` are used by the web app in the view `ActivitityWithTasks.cshtml`.  They are called from `Activitity.js`.

```
self.submitForm = function () {
            // TODO: set up a spinner
            self.isSubmitting(true);
            var dataToSend = ko.mapping.toJS(self);
            self.validationErrors([]);
            dataToSend.__RequestVerificationToken = $('input[name=__RequestVerificationToken]').val();
            $.ajax({
                type: "POST",
                url: isTaskSignup ? '/api/task/signup' : '/api/activity/signup',
                data: dataToSend,
                contentType: "application/x-www-form-urlencoded"
            }).done(function (result) {
                self.isSubmitting(false);
                switch (result.Status) {
                    case "success":
                        if (isTaskSignup) {
                            self.UpdatedTask = result.Task;
                        }
                        self.modal.close(self);
                        break;
                    case "error":
                        self.validationErrors(result.errors);
                        break;
                    default:
                }
            }).fail(function(fail) {
                self.isSubmitting(false);
                console.log(fail);
            });
        }

```
```
self.unenrollFromTask = function (task) {
            hideAlert();
            self.errorUnenrolling(false);
            $("#enrollUnenrollSpinner").show();
            $.ajax({
                type: "DELETE",
                url: '/api/task/' + task.Id + '/signup',
                contentType: "application/json"
            }).then(function(result) {
                initializeTask(result.Task);
                self.tasks.push(result.Task);
                self.userTasks.remove(task);
                $("#enrollUnenrollSpinner").hide();
                showalert("<strong>Thanks for your interest. Your request has been processed and you are no longer signed up for this task. We hope to see you soon!.</strong>", "alert-success", 30);
            }).fail(function(fail) {
                self.errorUnenrolling(true);
                console.log(fail);
            });
        }
```

```
self.changeTaskStatus = function (newStatus, statusDescription, task) {
            hideAlert();
            self.errorUnenrolling(false);
            $("#enrollUnenrollSpinner").show();
            var viewModel = new TaskStatusChangeViewModel(task.Id, task.AssignedVolunteers[0].UserId, newStatus, statusDescription);
            viewModel.__RequestVerificationToken = $('input[name=__RequestVerificationToken]').val();
            $.ajax({
                type: "POST",
                url: '/api/task/changestatus',
                data: viewModel,
                contentType: "application/x-www-form-urlencoded"
            }).then(function(result) {
                self.userTasks.remove(task);
                initializeTask(result.Task);
                self.userTasks.push(result.Task);
                $("#enrollUnenrollSpinner").hide();
                showalert("<strong>Your request to change the status of task: '" + task.Name + "' has been successfully processed.</strong>", "alert-success", 10);
            }).fail(function(fail) {
                self.errorUnenrolling(true);
                console.log(fail);
            });
        }
```

**Comment by mgmccarthy** [comment]
@BillWagner @tonysurma @mheggeseth can any of you shed some light on where or what calls into the Post/Put/Delete methods on TaskApiController?

**Comment by mgmccarthy** [comment]
@mmoore99 can you tell me a controller/action entry point that would end up returning me to `ActivitityWithTasks.cshtml`? I'm used to working with `return View([MODEL]);` and for some reason, when an action methods return a View, in Visual Studio 2015, my right-click menu option for "go to view" is gone, so I'm having a hard time stringing together the views, the javascript calls, and the controller actions. Thanks

**Comment by BillWagner** [comment]
@mgmccarthy I don't think anything does use those yet. We are heading toward more responsive web design, so we expect JavaScript code to use them.

I think that means leaving them in place for now, but that's not a strong preference.

**Comment by mmoore99** [comment]
> @mmoore99 can you tell me a controller/action entry point that would end up returning me to ActivitityWithTasks.cshtml?

@mgmccarthy `ActivityController/ShowActivity`

```
return viewModel.ActivityType == ActivityTypes.ActivityManaged
                ? View("Activity", viewModel)
                : View("ActivityWithTasks", viewModel);
```
