### ISSUE TITLE
EventAdminController: finish unit tests

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#617]
tied to #620

**Comment by mgmccarthy** [comment]
@tonysurma you can assign this issue to me as well

**Comment by dangle1** [comment]
Heads up @tonysurma I'm working in the same area for this issue: #619 and will have some unit tests to commit for the fix as well. The unit tests will focus particularly on the `Create` Post action.

**Comment by mgmccarthy** [comment]
@dangle1, I haven't written any unit tests, just stubbed them out to try to get #620 started. While you're in there, you can finish the unit tests if you want. If you're going to finish up the tests, let @tonysurma  know so he can reassign this issue to you. Thanks!

**Comment by dangle1** [comment]
@mgmccarthy I was actually going to look at a P1 issue that cropped up (#618) and write some additional unit tests for that fix as well. If the stubs are still around when I'm finished with that I'd be happy to start working through them. 

Additionally, I have a pull request ready for #619 which has the start for `ActivityControllerTest`. I'd like to avoid merge conflicts if possible, so how would you like to handle that file? I can revert my tests and wait for your stubs to be pulled in, if that's easier, or would you prefer I go ahead with the pull request I have ready?

**Comment by mgmccarthy** [comment]
@dangle1, the P1 change is more important than the test stubs. Commit your change, and when the PR is accepted, I'll fetch and rebase on my local  branch and handle the conflicts locally. When everything looks good, I'll commit the rest of the stubs for another sev to pick up.

**Comment by mgmccarthy** [comment]
@tonysurma can you please un-assign me and label "jump-in?"

**Comment by mgmccarthy** [comment]
@tonysurma, this is a dupe of Issue #684. One of these should be closed and just leave the one open to represent the work that still needs to be done

**Comment by GitaGunnam** [comment]
I am working on it
