### ISSUE TITLE
TaskController: adding unit tests and refactor to mediator

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#621]
I am currently working on this. Issue #620

**Comment by tonysurma** [comment]
thanks! can you reference the 'uber' issue this is a sub issue to so we can all track the sub items.  Thanks again

**Comment by mgmccarthy** [comment]
@tonysurma let me know if you want this also to be just a bunch of stubs for someone to pick up. We can mark it "up for grabs"

**Comment by tonysurma** [comment]
IMHO if you want to do that and then we can mark them as you said that would be great and you could always grab some as well yourself :smile:
