### ISSUE TITLE
Refactor all read operations on IAllReadyDataAccess to async

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#622]
Since EF 7 supports async/await ops, we should be able to update all read ops on IAllReadyDataAccess to be async.

**Comment by mgmccarthy** [comment]
@BillWagner @MisterJames @tonysurma 

Another idea here would be to do away with the CRUD-based IAllReadyDataAccess altogether, and just allow people to write LINQ against DbContext. We already have half the unit tests using the in-memory DbContext, and half mocking out IAllReadyDataAccess.

Since basic CRUD ops sometimes obfuscate the intent of the original use case that is using IAllReadyDataAccess on the read/write end, it's probably better to do away with a CRUD based approach, and instead encapsulate use case specific db ops in query and command handlers via MediatR.

This whole thing really has to do with the two ways allReady allows access to the database... via direct DbContext usage (which allows for testability b/c of in-memory EF7) and the IAllReadDataAccess abstraction.

Thoughts?

**Comment by BillWagner** [comment]
I think @MisterJames had written up some thoughts here. I'll defer to him.

**Comment by mgmccarthy** [comment]
I did a local spike of this moving only the repository methods that return a single object (not IEnumerable<T>) to async, and the changeset is large. It would take an immediate review, collaboration and merge in order to pull it off b/c there are so many moving parts.

**Comment by mgmccarthy** [comment]
@BillWagner @MisterJames @tonysurma @stevejgordon @VishalMadhvani 

as I continue to work with AllReady, I'm starting to see `IAllReadyDataAccess` as a problem. We should be injecting `AllReadyContext` directly into handlers that need it in order to do query ops. Since we can now rely on EFCore's in-memory provider, our unit tests are moving in that direction, so the database abstraction is not even useful from a unit testing point of view.

The problem with the repository approach is it's a CRUD-based API which obscures business intent. Also, there are sometimes "Includes" done in the repository implementations which means someone might be pulling back a LOT more data than they need to build a ViewModel for a UI.

I'd like to get rid of `IAllReadyDataAccess` altogether at this point. We should be composing ViewModels specific to a view and optimizing our LINQ (aka, sql) in our handlers for building those views.

for those of you about to say something about code duplication:
![image](https://cloud.githubusercontent.com/assets/2428993/17070001/a6618a68-5027-11e6-9dfe-2bb3e6fb87ae.png)
(http://www.sandimetz.com/blog/2016/1/20/the-wrong-abstraction)

I believe that `IAllReadyDataAccess` is the wrong abstraction...

if we duplicate some query code, no big deal. That's part of optimizing reads... that' why we use LINQ projections, etc... it's all compile time safe anyhow. If something changes something on a model (renames a property, removes a property, etc...), we'll know it right away b/c of the compiler.

Any thoughts on this are welcome and appreciated.

**Comment by VishalMadhvani** [comment]
👍 agreed.
I suggest we mark it obsolete to prevent future usage and refactor it out piece by piece.

**Comment by BillWagner** [comment]
I think this is a great idea. 

This project started before the in memory EF context was supported. Now that it is here, it is a better solution.

I'd like to defer to @tonysurma and @OhMcGoo on timing. No of us wants to have a bad customer experience because this is in progress, and we have a regression. 

@mgmccarthy Do you have a proposal for a set of tasks and ordering that would make this safer during a rollout? 

I know nothing is risk-free. I just want to be smart about when and how much risk we accept.

**Comment by mgmccarthy** [comment]
@BillWagner I don't know the rollout schedule. Understanding that would help me come up with a set of tasks that made sense to minimize risk in conjunction with the rollout. Maybe it makes sense to do this after the rollout?

@VishalMadhvani I say we mark the interface obsolete now. That will let other devs know to stay away/not use it.

**Comment by dpaquette** [comment]
@mgmccarthy We had been slowly working to remove `IAllReadyDataAccess` as we felt it was the wrong abstraction (as you pointed out). We were doing this slowly while still trying to deliver on new features which is always a challenge. I haven't looked at it in a while but will try to review the status over the weekend.

**Comment by mgmccarthy** [comment]
@dpaquette under \AllReady\Features\Events, there is extension usage of `IAllReadyDataAccess`... let me know if you want my help with the refactoring or any tasking that needs to take place in an order which would minimize impact/risk to the existing system.

**Comment by mgmccarthy** [comment]
@BillWagner @dpaquette I say we can slowly retire the usage of `IAllReadyDataAccess` as we go through code building new functionality or refactoring existing code. Easiest would be to start with those methods on the interface that are not used in many places.... if you want more of a detailed "plan" I can spend the time to figure out the easiest to change to the most difficult to change...

just not too sure how this info would be used. Would you want to create an issue per refactoring and have contributors work on it that way?

**Comment by BillWagner** [comment]
@mgmccarthy I'd consider marking `IAllreadyDataAccess` and its methods with the `Obsolete` attribute. Configure the warning message so that anyone working on the project can see what should be done, and can also know what time frame we want for removing it. 

Thoughts?
