### ISSUE TITLE
finish unit tests/implement skipped tests in ManageControllerTests

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#641]
@tonysurma please label with "jump-in". Part of Issue #620

stubs are provided in:
ManageControllerTests.

**Comment by mgmccarthy** [comment]
@tonysurma @BillWagner please label with "jump-in" when you get a chance

**Comment by reecebradley** [comment]
Looking at it...we shall see how far I get :-)

**Comment by mgmccarthy** [comment]
@reecebradley, good luck. It's one of the tougher controller to unit test.

Looking at unit tests from other controllers that use `UserManager<ApplicationUser>` and `SignInManager<ApplicationUser>` can help guide you b/c IMO, those are tough things to mock. Many of those unit tests have good setups either for the whole controller instance, or for creating mocks of `ApplicationUser` and `SignInManager` that are used in test setup.

Feel free to commit as many PR's against this issue as you need to keeping in mind smaller PR's make it easier for code reviewers.

Also, if you want to update this issue with the name of the unit tests you're working on, or plan to work on, that will keep other developers that want to contribute from working on the same tests you might be working on. I know it's not optimal, but with this many unit tests for a controller, it would be helpful.

If you have any question, feel free to ping me

**Comment by reecebradley** [comment]
Thanks Michael. Presently I am working on IndexGetAddsCorrectMessageToViewDataWhenMessageEqualsChangePasswordSuccess

**Comment by mgmccarthy** [comment]
@tonysurma, there is still a lot of work to do here.

**Comment by Chris-Wooder** [comment]
Hi, I have have started on these and will submit a pr shortly before doing anymore.

**Comment by mgmccarthy** [comment]
@Chris-Wooder, sounds good. Let me know if you have any questions.

@reecebradley, are you still working on any of these tests? I want to make sure we're not duplicating work here.

**Comment by Chris-Wooder** [comment]
@mgmccarthy I am looking at the tests for the POST ResendEmailConfirmation() and have a couple of questions.

For test ResendEmailConfirmationInvokesFindByIdAsyncWithCorrectUserId()
I'm not sure which method 'InvokesFindByIdAsync' is referring to.  I am assuming it's something to do with retrieving the ApplicationUser object...

The method calls UserManager.GetUserAsync(ClaimsPrincipal), is it referring to this?

Secondly this is inconsistent with rest of Controller which calls it via the Mediator pattern.  Should the method actually be calling Mediator.SendAsync(UserByUserIdQuery) and therefore test this is invoked instead?

**Comment by mgmccarthy** [comment]
@Chris-Wooder that unit test stub name is probably old. We used to name all our method/messages that used the async API for MediatR with "async" in the name, then moved away from that convention b/c it was too noisy. Please update the name of those tests to (and write the code) to test the following scenarios:

- _userManager.GetUserAsync(User)
- await _userManager.GenerateEmailConfirmationTokenAsync(user)
- Url.Action(new UrlActionContext { Action = nameof(ConfirmNewEmail), Controller = "Account", Values = new { userId = user.Id, code },
                Protocol = HttpContext.Request.Scheme });

As far as some of these action methods not relying on the Mediator pattern like most other controllers, most likely, we decided to go with the _userManager call directly in the controller instead of using a query message/handler to get the data we need for us. This is a decision we made a while back as well. The _userManager and _signInManager stuff we use directly from the controller b/c adding the layer of CRRS/Mediator didn't really get us anything here. 

The only place we use the mediator for this particular action method is to send a command to SendConfirmAccountEmail.

Let me know if you have any other questions. Thanks

**Comment by DavidArno** [comment]
I shall take a look at (and hopefully even do something with) this issue during the NDC London codeathon.

**Comment by DavidArno** [comment]
Looking at this file in more detail, it is already 1400+ lines long and has dozens of stubbed tests in it, so will grow hugely when finished. Should it therefore be split up into a number of separate test classes, eg separate test classes for email, phone, password tests, etc?

**Comment by Chris-Wooder** [comment]
Note, to prevent duplication, I am currently working on the SetPassword tests, but haven't created a PR yet

**Comment by DavidArno** [comment]
@Chris-Wooder,

Whilst I'm really unlikely to cover all the missing tests here, that's handy to know. Luckily I'm focusing on the telephone number tests, so we shouldn't clash.

**Comment by mgmccarthy** [comment]
@DavidArno, splitting up the unit tests into separate classes sounds like a good idea.

**Comment by DavidArno** [comment]
@mgmccarthy, 
OK, thanks.

@Chris-Wooder,
I'll split out all the test methods that mention PhoneNumber in their names only, so as not to affect you.

**Comment by DavidArno** [comment]
@Chris-Wooder,

Just to check, are you only working on the SetPassword tests, or have you worked on the email ones too? If just the password ones, then I'll raise another new issue to split the email ones out to a new class and will implement them.

**Comment by thomfresn** [comment]
I'd like to start contributing on the project and thought it might be a good idea to start by writing some unit tests.  
Is anybody working on this issue too or can I implement any of the tests with the Skip attribute?

**Comment by mgmccarthy** [comment]
@thomfresn try to take unit tests with the Skip attribute. Although I haven't been actively contributing for a while now, I believe there were a good amount marked with Skip (and maybe some classes that have no unit tests at all)

**Comment by thomfresn** [comment]
Ok I will start with the `ManageControllerTests `which contains quite a few tests with the `Skip` attribute.
