### ISSUE TITLE
write unit tests for AllReady.Controllers.EventController

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#662]
@tonysurma please label with "jump-in". Part of Issue #620

stubs are provided in:
AllReady.UnitTest.Controllers.EventControllerTests.

**Comment by digitaldrummerj** [comment]
@tonysurma I see in the PR that has been merged that you put a closes this issue comment in but the issue is still open.  Is it still a valid issue?

**Comment by mgmccarthy** [comment]
@tonysurma @digitaldrummerj the unit tests exist and this Issue can be closed
