### ISSUE TITLE
AllReady.Areas.Admin.Controllers.ActivityController checks for "OrgAdmin" multiple times?

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#667]
I'm currently doing some refactoring work for this controller. The controller is decorated with:
`[Authorize("OrgAdmin")]`

which leads me to believe that only users that have the `ClaimType.UserType` set to "OrgAdmin" will be able to access any action method in this controller.

Yet, in every action method, this call is being made:
```
if (!User.IsOrganizationAdmin(...))
{
    return HttpUnauthorized();
}
```

Looking into the `IsOrganizationAdmin` extension method, it appears to determine if a user is an "organization admin", there is more to it then just the claim check I mentioned above. Here is the code:
```
public static bool IsOrganizationAdmin(this ClaimsPrincipal user, int organizationId)
{
    var userOrganizationId = user.GetOrganizationId();
    return user.IsUserType(UserType.SiteAdmin) || (user.IsUserType(UserType.OrgAdmin) && userOrganizationId.HasValue && userOrganizationId.Value == organizationId);
}
```

determining is a user is an org admin also means the user is a SiteAdmin OR is an OrgAdmin where `userOrganizationId.HasValue` (is it possible for a user to be created without an OrganizationId?) and the user's organizationId is equal to the organizationId passed into the extension method.

So, my question is, do I keep the calls to the extension method in each action method and delete the controller-level attribute or vice-versa? 

Seeing how checking to see if a user is an "OrgAdmin" entails other checks besides just the `ClaimType.UserType` beign set to "OrgAdmin", I'd say I can safely remove the controller level attribute?

@BillWagner @MisterJames @tonysurma any ideas on the right way to go here?

**Comment by tonysurma** [comment]
from my perspective you are right with some nuance.

OrgAdmin check is more than if they have that role as we need to verify they are an org admin for the org of the activity.  Therefore you definitely can't remove the code check as it is nuanced but perhaps having the controller level check helps to stop any 'non-org admin' from even getting to that point, thoughts @MisterJames ?

As for the HasValue there are two thoughts here: a) if we have the controller check we don't need that as every orgadmin has to be part of an organization and b) if we remove that check then we need it as a site admin or random 'end-user' won't be associated with an organization.

**Comment by mgmccarthy** [comment]
@tonysurma, you are correct. I just read through this Issue and I don't know what I was thinking this day. The way things work now if fine. If you could please close this Issue so I know longer have to be embarrassed for opening it. :blush:
