### ISSUE TITLE
Getting the unit tests to work?

### ISSUE THREAD

**Issue by darrencauthon** [HTBox/allReady#678]
I have Visual Studio 2015, Resharper 9.2.... is there some trick that I would have to do to get the xunit tests to run?

I have many years of exp in testing, NUnit, Moq, etc... but not DNX nor XUnit.

**Comment by BillWagner** [comment]
The simplest way is to run 'dnx test' from the command line.

If you're running Visual Studio, they should show up in Test Explorer, because we have the xunit.runner.dnx NuGet package as part of the project.

If this helps, feel free to close the issue. If not, let me know what you still need.

**Comment by mgmccarthy** [comment]
@darrencauthon, check Issue #59 for a full explanation of why unit test won't work with ReSharper/dnx/Visual Studio 2015. The conversation starts about a little more than halfway down in the thread. Basically, until https://github.com/xunit/resharper-xunit/issues/38 is resolved, you will not be able to run xUnit tests in Visual Studio 2015 for dnx. I've been using MSTest for my unit tests. There is also another way to run the unit test from the command line using dnx test via nodemon. That information is also in the thread.

**Comment by darrencauthon** [comment]
![screenshot_041116_050858_pm](https://cloud.githubusercontent.com/assets/148768/14443945/14f0d918-0008-11e6-8422-9d47e9cfd59f.jpg)

**Comment by darrencauthon** [comment]
I have Resharper on the brain so much -- I never thought to try the test runner built into Visual Studio.

It took a little bit to get them to load, even after I built the solution... but they appeared and they all run.  Thank you!

**Comment by mgmccarthy** [comment]
:+1:
