### ISSUE TITLE
6.1.1.1	Feature single campaign on front page of app

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#689]
Feature an upcoming/current campaign with its picture, summary description and link to campaign page on the home page.  For this release we can just select first campaign that fits the criteria as we will have only one campaign ‘in production’ and for future we will likely add filters, possibly site admin tagging for highlight and featuring more than one campaign.

See below for an example of how to display/feature on home page (subject to UX discussion in #693)
![volunteer views](https://cloud.githubusercontent.com/assets/5067595/14565269/dc53edb2-02ef-11e6-9620-1f4170f6ad50.png)

**Comment by stevejgordon** [comment]
@tonysurma I can take a look at this one. Please assign to me.

**Comment by stevejgordon** [comment]
Update from me on this. The work to implement is mostly complete. I have some tests to write and a little tidy up and should be able to get my PR in soon.
