### ISSUE TITLE
6.1.1.2	Remove/hide search functionality

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#690]
Simply don’t delete functionality but remove the search box and resulting ‘stuff’ on home page. This will also ‘pause’ work on several active issues with search for this release.

**Comment by mgmccarthy** [comment]
@tonysurma please assign this to me

**Comment by mgmccarthy** [comment]
@tonysurma, so I've looked at the home page both logged in as an admin, and not logged in, and I cannot find any "search box and resulting stuff" on the home page:

![image](https://cloud.githubusercontent.com/assets/2428993/14612080/705d367e-0563-11e6-9d57-8ac36d559beb.png)

![image](https://cloud.githubusercontent.com/assets/2428993/14612090/7d2302d0-0563-11e6-9c9e-41040f51716b.png)

so am I missing something here?

There are "search boxes" on the Campaigns and Organization pages, but nothing on the home page.

**Comment by tonysurma** [comment]
Okay, then I think you just verified this requirement is met without any work - nice!
