### ISSUE TITLE
6.1.1.3	Display link to list of campaigns on home page

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#691]
Below the featured campaign provide a link to the campaign list page which shows campaigns that are current/upcoming.  Remove map link and add in logo/image of campaign on home page

**Comment by sudhakarssd** [comment]
You can assign this to me.

**Comment by sudhakarssd** [comment]
@tonysurma logo/image of campaign is a image from Campaign table or just a common map icon

**Comment by stevejgordon** [comment]
@sudhakarssd - Can I check if you are still working on this one? I believe the logo should be the campaign's logo from the Campaign table.

**Comment by sudhakarssd** [comment]
@stevejgordon yes, been away for a while.

**Comment by MisterJames** [comment]
@sudhakarssd I'm going to jump on this one because it's "low hanging" and I'm doing a demo at a code-a-thon!  Sorry for trumping anything you've started!

**Comment by MisterJames** [comment]
@tonysurma Are we going to remove the list of campaigns entirely from the home page? Should it *just* be the link (under the featured campaign)?

**Comment by tonysurma** [comment]
good either way - remove or leave for now
