### ISSUE TITLE
6.1.1.4	Add external link and highlight it on campaign display page

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#692]
Update campaign display page to display and highlight an external link for the campaign to link to an outside page that displays information about the campaign and/or allows folks to request the services of the campaign.  Also verify that the image/logo and rich content description is displayed as well.

**Comment by dpaquette** [comment]
@tonysurma Are you picturing "external link" as a new property of the Campaign?

**Comment by tonysurma** [comment]
Assuming it's not there, yes.

**Comment by tonysurma** [comment]
Url and text for the link display

**Comment by dpaquette** [comment]
ok, please assign to me
