### ISSUE TITLE
6.1.3	Data Integration with getasmokealarm.org (pull data)

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#695]
Placeholder for requirement around data integration (details & sub requirements being filled asap)

**Comment by mgmccarthy** [comment]
@tonysurma I'd be interested in getting involved with this integration is some way. You could probably delegate more technical tasks to me as I don't think I would really be able to be a part of the details/reqs/meetings required to talk to the getasmokealarm.org people

**Comment by tonysurma** [comment]
thanks!  We will be putting subitems up here soon and will get a connection with the others to net out details so stay tuned.

**Comment by tonysurma** [comment]
duplicate of #700
