### ISSUE TITLE
6.1.6	Support Rally Type Events for Registration and Signup

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#699]
Placeholder for requirement around registering & organizing volunteers for rally type events in campaigns (details & sub requirements being filled asap)

**Comment by stevejgordon** [comment]
@tonysurma Do you have any further details about this requirement? I'm wondering if this could be a good issue to break up into some more potential jump-in issues?

**Comment by stevejgordon** [comment]
@tonysurma - Do you have some more details so I can create some sub-issues to get this on the list for next week?

**Comment by tonysurma** [comment]
@schuback @OhMcGoo can you take a look at how we want to document the requirements for this/walk through what works/doesn't right now? cc @EmilyLuijbregts

**Comment by stevejgordon** [comment]
@tonysurma Is this intended to enable the volunteers from rally events, to easily signup new volunteers for future events? If so I can see us using a system similar to the invite process we'll be adding to invite people to be a campaign manager for example. If that's the requirement I can stub out issues to make it happen.

Also, if that's correct, v1 or vNext?

**Comment by tonysurma** [comment]
this is rather old and is covered by existing functionality in the app so we can consider it closed
