### ISSUE TITLE
Add filtering to most views

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#7]
Currently there isn't filtering for, say, Activites / Tasks /Campaigns whose end dates are in the past.

Implement past due filtering to fix the bug and additional filters for user functionality.

**Comment by mheggeseth** [comment]
Dibs. Gonna create child issues: one for each view.

**Comment by mheggeseth** [comment]
Child Tasks:
#50 Filter old tasks from activity view
#51 Filter old activities from campaign view
#52 Filter old campaigns from tenant view

**Comment by BillWagner** [comment]
Leaving open to check List views just to make sure we found anyone.

Ping @tonysurma
