### ISSUE TITLE
6.1.3.1	Implement a webjob/service to pull incremental net new requests from getasmokealarm.org

### ISSUE THREAD

**Issue by MKSessions** [HTBox/allReady#701]
This is likely to be ‘hardcoded’ to this one source now for expediency and as we get more sources we will need to abstract an approach.  The API to pull is being defined by the getasmokealarm.org folks so we will pull them into this issue to discuss how to work together.  The requests should be incrementally added to the database of Requests and be associated with the proper campaign.

**Comment by tonysurma** [comment]
Here is the link to the [repo for getasmokealarm.org](https://github.com/redcross/smoke-alarm-portal)

I have email into a contact there provided by @OhMcGoo to start the discussion and will get them connected to this issue

**Comment by MisterJames** [comment]
I'd like to take this one.

**Comment by tonysurma** [comment]
@MisterJames any update?

**Comment by tonysurma** [comment]
@mgmccarthy safe to say this is covered in issues/work you are doing and can be closed?

**Comment by mgmccarthy** [comment]
@tonysurma, this can be closed. The issue actually ended up being a "push" by GASA to AllReady (they invoke our endpoint), instead of a "pull" from AllReady to GASA.

But either way, it can be closed.
