### ISSUE TITLE
6.1.3.2	Maintain database of Requests

### ISSUE THREAD

**Issue by MKSessions** [HTBox/allReady#702]
Request schema is TBD but will consist of contact information, address, service requested, notes and status and be related as a sub-entity list under a campaign.  Initially we will need to work with the getasmokealarm.org folks to see what they capture, how we would model it and what it needs to look like for our needs.

**Comment by MisterJames** [comment]
Data captured is as follows:

````
name, // the name of the person requesting the alarm
address, // their address
assigned_rc_region, // the Red Cross region associated with their zip code
city,
state,
zip,
phone,
email,
serial, // our unique identifier: Red Cross region code - 2-digit fiscal year - integer
status // currently: new, in progress, installed, or canceled
````

I'm working with them to get more details as we go.
