### ISSUE TITLE
6.1.3.4	Allow viewing of status by requestor (lowest priority)

### ISSUE THREAD

**Issue by MKSessions** [HTBox/allReady#704]
Push the status updates back to getasmokealarm.org so the requestor can check status of requests over time.

**Comment by tonysurma** [comment]
Here is the link to the [repo for getasmokealarm.org](https://github.com/redcross/smoke-alarm-portal)

I have email into a contact there provided by @OhMcGoo to start the discussion and will get them connected to this issue

**Comment by MisterJames** [comment]
@MKSessions @tonysurma Would the use case here be:

 - User requests smoke alarm from site
 - GASA sends us the request
 - We create local data to track, assign, complete

...and then at some point after step one above, until the task is complete, that they would like to go somewhere to see where their status currently is?

We are going to be sending the status to GASA, and I think we'd also be able to send them an email and let them know when someone's been assigned, a phone number they can call for info, a web page they could go to, something...just not totally clear on what that might include. Thoughts?

**Comment by tonysurma** [comment]
Sending status back to GASA is cool and new and unknown at the point of writing this.  The original thought was once something was created on our side we would be able to send an email to the contact info provided by GASA to allow them to check status at any time - generic status with no private info shown.  All 'contact back' from them would go to the ARC in this case and not be provided by us.

So thinking of it like an un-authenticated 'order status' page they can click on

**Comment by MisterJames** [comment]
Perfect, we should be able to do something to that effect. Since they track the status on their end, we need a way to let them know we're progressing things. It also makes for an interesting analytics point (AllReady was able to assist in x% of install completions).

**Comment by stevejgordon** [comment]
@MisterJames - Following on from our conversation yesterday, I think I could pick up the sending of statuses back to GASA once my current piece of work is completed. If anyone else get's here first though I'm good with them picking this up.

Perhaps we need to break this out into two issues?
1. Send status updates to GASA
2. A URL (no private info shown) which shows the current status, and if assigned to an itinerary, planned deployment date for a request.

@tonysurma - Does that sound reasonable? If so I can create a second issue to track one of these and update this current issue with the other part specifically.

**Comment by stevejgordon** [comment]
@tonysurma - I believe @mgmccarthy is covering point 1 from my last message. For point 2, would a page to view a request status and scheduled date be useful for this version? If so, it's a simple story we can add for the code-a-thon.

**Comment by mgmccarthy** [comment]
@stevejgordon, I'd be fine breaking these two items apart. I don't know if item 2 would depend on item 1 code being submitted and merged before your code-a-thon though.

**Comment by tonysurma** [comment]
@stevejgordon I think point 2 would be helpful for debugging/viewing etc as we first launch

**Comment by tonysurma** [comment]
@stevejgordon @mgmccarthy still a thing?

**Comment by mgmccarthy** [comment]
@tonysurma the URL part still needs to be done.  I like the URL approach where they can check the status and/or send them an email with a link to the URL that points to the specific request would be cool. Just not too sure where the email would go. A contact at GASA?

**Comment by stevejgordon** [comment]
@mgmccarthy Correct, and we have an issue for updating GASA as well so I think we can close this and use those two issues to track the work?
