### ISSUE TITLE
6.1.2.1	Entities have new names from user experience discussions – P2

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#705]
Campaigns are Campaigns
***Activities are Events***
Tasks are Tasks
***Deployments are Itineraries***

These changes need to be reflected in the UI and secondarily in the system/database for consistency & code clarity (and yes we know we are talking entities named Events and Tasks in C# :smile_cat:)

**Comment by stevejgordon** [comment]
@tonysurma @BillWagner Please assign to me, I'll tackle this next.

**Comment by stevejgordon** [comment]
My plan of attack! I figure I may as well get everything done for this to avoid any confusion for people. Not sure if it's easier as one big PR or smaller chunks? @MisterJames - Your thoughts? I'm happy to do whatever makes reviewing / testing easier.

- [ ] Rename activities in UI elements
- [ ] Rename activities in js elements
- [ ] Rename activities in code
- [ ] Rename activities in database
- [ ] Rename activities in folder structure and files

- [ ] Rename deployments in UI elements
- [ ] Rename deployments in js elements
- [ ] Rename deployments in code
- [ ] Rename deployments in database
- [ ] Rename deployments in folder structure and files

**Comment by BillWagner** [comment]
@stevejgordon Great plan.  My experience is that several smaller PRs is much easier. If @MisterJames feels different, he can override though.

**Comment by tonysurma** [comment]
@MisterJames and I have discussed this several times and definitely smaller 'bite sized' are better.  Thanks

**Comment by stevejgordon** [comment]
@tonysurma This can hopefully be closed now since all 5 PR's have been merged.
