### ISSUE TITLE
6.1.2.3	Itinerary Campaigns are the new name/functionality for Deployment Managed Tasks – P1

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#707]
How do they work (known changes indicated by \* at start)
- [ ] Tasks are still shown to volunteers 
- [ ] Volunteers volunteer for Tasks – example: “’Tony’ volunteers for ‘Install Driver’ on Tuesday 8-4”
- [ ] *Volunteers can be assigned to tasks by Organizers (which requires acceptance by volunteer similar to reassignment below)
- [ ] Admins can re-assign tasks to volunteers
- [ ] Re-assignment communication is only sent to Volunteers when it results in change outside of assigned timeframe and they can accept/reject task assignment
- [ ] *Reminder sent ahead of Task with option to respond as ‘no longer able to volunteer’
- [ ] *Volunteers from multiple Tasks (in same Event with same timeframe) are collected into an Itinerary along with a set of requests (in same campaign) [[Note this replaces everything referring to Deployments]]
- [ ]  *A Request can be in a single Itinerary only - unless it is marked incomplete from a previous Itinerary in which case it can be recollected into a new Itinerary  (e.g. 1313 Mockingbird Lane install set for Tuesday, on Tuesday it is marked incomplete because no one was home so now it is in the Itinerary for next Thursday installs)
- [ ] *A Volunteer on a Task can be in only one Itinerary (e.g. Tony volunteers as driver on Tuesday so can only be collected into one itinerary – now of course they can have separately signed up for multiple Tasks across multiple days and be in more than one itinerary that way (e.g. Tony volunteered to drive Tuesday, Thursday and next Friday))

**Comment by mmoore99** [comment]
@tonysurma  in your above description you introduced a new entity term "Request" and I would like to ask for some additional clarification.  When we were using the term `deployments` in issue #508 I had put together an example structure for clarification purposes that I am including below for the purpose of this discussion.

Is what I have called a `deployment` below equivalent to an `itinerary` or a `request` in the new terminology?  If it is a `request` then is an `itinerary` a collection of `requests`?  If it is an `itinerary`, then what is a `request`?  Hope I am not just being dense here, but need some help understanding.  Thanks. 

> `DeploymentManaged` Activity Structure:
> - `Activity`: Install fire detectors in Queen Ann District
>   - `Task`: Sunday Driver, VolunteersNeeded: 2
>     - `TaskSignup`: Tony Surma
>     - `TaskSignup`: James Chambers
> 
>   - `Task`: Sunday Installer, VolunteersNeeded: 6
>     - `TaskSignup`: Bill Wagner
>     - `TaskSignup`: Steve Gordon
>     - `TaskSignup`: Mike Moore
>     - `TaskSignup`: David Paquette
>     - `TaskSignup`: Charles Barkley
>     - `TaskSignup`: Steph Curry
> 
>   - `Task`: Monday Driver, Volunteers Needed: 2
>     - `TaskSignup`:
>     - `TaskSignup`:
> 
>   - `Task`: Monday Installer, VolunteersNeeded: 6
>     - `TaskSignup`:
>     - `TaskSignup`:
>     - `TaskSignup`:
>     - `TaskSignup`:
>     - `TaskSignup`:
>     - `TaskSignup`: 
> 
> - Deployments
>   - `Deployment`: Install Smoke Detector at 1313 Mockingbird Lane
>     - `DeploymentTask`: Sunday Driver, VolunteersNeeded: 1
>       - `TaskSignup`: Tony Surma
>     - `DeploymentTask`: Sunday Installer, VolunteersNeeded: 2
>       - `TaskSignup`: Bill Wagner
>       - `TaskSignup`: Steve Gordon
>   - `Deployment`: Install Smoke Detector at 2300 Main St.
>     - `DeploymentTask`: Sunday Driver, VolunteersNeeded: 1
>       - `TaskSignup`: James Chambers
>     - `DeploymentTask`: Sunday Installer, VolunteersNeeded: 2
>       - `TaskSignup`: Mike Moore
>       - `TaskSignup`: Steph Curry
> 
>   - `Deployment`: Install Smoke Detector at 1212 Locust St.
>     - `DeploymentTask`: Sunday Driver, VolunteersNeeded: 1
>       - `TaskSignup`: Tony Surma
>     - `DeploymentTask`: Sunday Installer, VolunteersNeeded: 2
>       - `TaskSignup`: David Paquette
>       - `TaskSignup`: Charles Barkley
> 
>   - `Deployment`: Install Smoke Detector at 3677 Marsh Drive
>     - `DeploymentTask`: Sunday Driver, VolunteersNeeded: 1
>       - `TaskSignup`: James Chambers
>     - `DeploymentTask`: Sunday Installer, VolunteersNeeded: 2
>       - `TaskSignup`: Bill Wagner
>       - `TaskSignup`: Mike Moore
> 
>   - `Deployment`: Install Smoke Detector at 1312 Norris Canyon Rd.
>     - `DeploymentTask`: Sunday Driver, VolunteersNeeded: 1
>       - `TaskSignup`: James Chambers
>     - `DeploymentTask`: Sunday Installer, VolunteersNeeded: 2
>       - `TaskSignup`: Steve Gordon
>       - `TaskSignup`: David Paquette
> 
>   - `Deployment`: Install Smoke Detector at 9865 Glendale Drive
>     - `DeploymentTask`: Sunday Driver, VolunteersNeeded: 1
>       - `TaskSignup`: Tony Surma
>     - `DeploymentTask`: Sunday Installer, VolunteersNeeded: 2
>       - `TaskSignup`: Charles Barkley
>       - `TaskSignup`: Steph Curry

**Comment by tonysurma** [comment]
@mmoore99 I will have a 'fuller' answer later when I am really on line but for now here are a couple of quick notes:

Requests come from this requirement #700 and represent an individual/family requesting a service (in this case a smoke alarm install.

Deployment is closer to Itinerary but the difference is Deployment as we spoke to it prior was a 1:1 to location (aka request in new words) and Itinerary is now a collection of requests and volunteers that make up the itinerary of installs for a day (aka Tony, Bill, Mike will deliver on requests abc, def, ghi, and jkl on 6/1/2016.

You are not being dense at all.  Hope this helps a bit for now and will get more in when I am not tapping on a screen :)

**Comment by mmoore99** [comment]
@tonysurma Just a "heads up".  I was hoping to be able to make some significant contributions toward the development of the newly defined requirements.  Unfortunately, I have some personal commitments from now through the end of May that will make it impossible for me to bite off any significant chunks.  I may be able to pick up some smaller issues along the way.

**Comment by tonysurma** [comment]
thanks for the heads up and most importantly thanks for all the contributions!

**Comment by stevejgordon** [comment]
@tonysurma Needs double checking but I believe the features now implement at least an initial version of these requirements and perhaps this can be closed?
