### ISSUE TITLE
6.1.2.4	Events can be duplicated easily to allow for campaigns that consist of repetitive tasks - P2

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#708]
Effectively this is a UX where I can take an Event and ‘copy/paste or duplicate’ it changing the start date and the dates of the Event and underlying Tasks are updated accordingly).  All other data remains the same in the duplicate but any volunteer assignments do not travel with the duplicate

e.g. Event ABC is from 6/1/2016 to 6/2/2016 and has Task 1 on 6/1, Task 2 on 6/1 and Task 3 on 6/2.  When it is duplicated to 6/8/2106 the new Event is from 6/8 to 6/9 and the Tasks are now Task1 on 6/8, Task2 on 6/8 and Task3 on 6/9)

**Comment by vishal123** [comment]
working on this

**Comment by vishal123** [comment]
Here's what I've got so far.

![image](https://cloud.githubusercontent.com/assets/1994627/15377286/a65b371c-1d28-11e6-8737-99824ada276c.png)
Duplicate Button.

![image](https://cloud.githubusercontent.com/assets/1994627/15377293/af23384a-1d28-11e6-9649-4cf02272867f.png)
Duplicate Form allowing changes to be made to the new event before it is created.

![image](https://cloud.githubusercontent.com/assets/1994627/15377291/abcb8c06-1d28-11e6-9b25-64bc39958751.png)
New Event Details Page with events.

**Comment by tonysurma** [comment]
discussing this with @adedonato

**Comment by digitaldrummerj** [comment]
@tonysurma looks like the PR for this issue has been merged.  Can we close the issue?
