### ISSUE TITLE
Un-enrolling from a task fails

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#720]
I was able to produce this locally by enrolling to a task and then clicking the un-enroll option.

I see the following js console error

![image](https://cloud.githubusercontent.com/assets/3669103/14755776/84b9ed52-08dc-11e6-819f-47fe25c4b66f.png)

**Comment by stevejgordon** [comment]
@tonysurma You can assign to me if you want and I'll take a proper look after my renaming work gets done.

**Comment by stevejgordon** [comment]
@tonysurma I've been having a look at this one and see the main issue. A couple of the related entities were not included when pulling the record from the database which caused some issues. However, even with that fixed the behaviour might not be quite right. The records have their task or event id nulled out rather than being fully deleted. This doesn't seem quite right. Can I confirm; on un-enroll, should the task signup record be fully deleted from the db?

If so I'll probably rework the EF code a little and put some tests in around this.

@mmoore99: If you're available to comment you may be able to fill in the blanks as I know you contributed a lot to this part of the code and I could well be misunderstanding the intended behaviour. :-)

**Comment by mmoore99** [comment]
> The records have their task or event id nulled out rather than being fully deleted.

@stevejgordon I noticed this, as well, when I was doing the development.  I am not an expert on Entity Framework, but as I recall I did some googling and came to the conclusion that this was how EF handled this kind of relationship.  I am afraid that's about all I can add.

**Comment by stevejgordon** [comment]
@mmoore99 Thanks for the quick reply. EF core I believe tracks entity states a bit differently but I have a few thoughts depending on what the behaviour needs to be. Cheers!

**Comment by mmoore99** [comment]
@stevejgordon Not sure, but the `CascadeDelete` setting may be related to this issue.  See http://ef.readthedocs.org/en/latest/saving/cascade-delete.html
