### ISSUE TITLE
Remove Dependency on Microsoft.Extensions.DependencyInjection for any unit tests that test classes that inherit from InMemoryContextTest

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#724]
In most unit tests that test classes that inherit from `InMemoryContextTest`, the context is retrieved using this code:
```
var context = ServiceProvider.GetService<AllReadyContext>();
```

`InMemoryContextTest` inherits from `InMemoryContextTestBase`, which exposes `AllReadyContext` as public getter `Context`:
```
protected AllReadyContext Context { get; private set; }
```

Therefore, instead of taking a dependency on Microsoft.Extensions.DependencyInjection in unit test code, this line of code:
```
var context = ServiceProvider.GetService<AllReadyContext>();
```

should be changed to this:
```
var context = Context;
```

- cleaner code
- reducing unneeded dependencies
- taking a singular approach to tests inheriting from `InMemoryContextTest`

**Comment by digitaldrummerj** [comment]
@mgmccarthy @tonysurma can this issue be closed?  it looks like a PR was merged that fixes the issue.
