### ISSUE TITLE
getting started - can't figure out how to log in as a regular user

### ISSUE THREAD

**Issue by sJhonny-e** [HTBox/allReady#73]
(disclaimer: not sure if opening an issue is the right way to get help here; if not- I apologize in advance, and please direct me to the correct channel of communication. thanks :) )

I'm trying to get started contributing to this repository.

I was able to get the website up on my local machine with no problem, and I'm able to log in as the default administrator, but I've no idea how to go about logging in as a regular user; all I have are the twitter / facebook / MS options, which don't work because I don't have an app ID for any of them.

Surely I'm missing something trivial here. what is it?

**Comment by BillWagner** [comment]
Bump to @tonysurma

**Comment by sJhonny-e** [comment]
guys this seems like a very worthy cause, and i'm interested in contributing, but if you're not going to respond here at all I simply can't do that :(

**Comment by tonysurma** [comment]
Hello, apologies for delays.  We have a few open issues that are blocking allowing login as regular users as integration with those providers require app keys etc as you noted and there's no good solution (that we and our community has yet found at least) to support this in development by many individuals.  There are a couple of folks working on those issues like #3, #15 and #31 

In the meantime there are a number of issues and a lot of functionality that only requires Admin/non-social logins so any of those areas might be good ones to start with.

Thank you for wanting to contribute to our project and let me know what else I/we can do to help you do that.  My email is first.last at HTBox.org if you want to ping directly

**Comment by BillWagner** [comment]
@sJhonny-e There has been quite a bit of work here, and the volunteer logins work for Twitter and Facebook integration. The Microsoft Integration is in progress, and noted in issue #245
