### ISSUE TITLE
RC2 / RTM Updates

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#740]
Thought I'd throw in a placeholder issue now that we have dates for RC2 and RTM of ASP.NET Core. Hopefully when RC2 lands we'll get a view of the required changes.

https://blogs.msdn.microsoft.com/dotnet/2016/05/06/net-core-rc2-improvements-schedule-and-roadmap/

**Comment by stevejgordon** [comment]
RC2 landed yesterday. I've initially tested running allReady in VS 2015 after removing RC1 and installing RC2 + the preview tooling. It builds and runs but I did hit an interesting issue when I wanted to run an EF migration.

Ultimately we need to start thinking about when is the right time to update the project to be a formal RC2 project, targeting the correct dependencies etc. Once that change is made all devs working on the project would need RC2 tooling. Too late and people may have removed the RC1 dnx bits and may struggle with the dnx ef command not being available.

@MisterJames Any thoughts on planning this in? Leaving it until after the pilot probably makes sense but much longer starts to feel like we get a bit behind?

**Comment by MisterJames** [comment]
We can talk about this on the standup today...it's a big shift and we have to get the PRs merged in before we make this cut. We can also dump the existing migrations (right @tonysurma?) and rebuild the migration set as we're going to purge the database.

**Comment by stevejgordon** [comment]
RTM date is June 27th so perhaps we wait and skip straight to that to avoid two sets of work?

**Comment by tonysurma** [comment]
As @stevejgordon and I talked before, RTM is on Monday so soon after that we should start an investigative thread to see what the impact is for our application - the major assumed/known aspect so far will be migrations but I am sure there will be more.

**Comment by tonysurma** [comment]
From today's announcements for reference here:
[.net core annoucement](https://blogs.msdn.microsoft.com/dotnet/2016/06/27/announcing-net-core-1-0/)
[visual studio update 3](https://www.visualstudio.com/news/releasenotes/vs2015-update3-vs)
[asp.net core announcement](https://blogs.msdn.microsoft.com/webdev/2016/06/27/announcing-asp-net-core-1-0/) _has a section on migration from RC2_
[ef core announcement](https://blogs.msdn.microsoft.com/dotnet/2016/06/27/entity-framework-core-1-0-0-available/)
[ef core rc2 to rtm](https://docs.efproject.net/en/latest/miscellaneous/rc2-rtm-upgrade.html)

including @BillWagner & @shawnwildermuth who have also talked with me at some point regarding this.

Recently @MisterJames and I discussed just doing a new 'Day 1' Migration after we move to the new ef core RTM as the history of migrations no longer has values and should save us a lot of transition work if we don't migrate the migrations :)

**Comment by tonysurma** [comment]
also good news is that rtm is up on azure web apps already so we should have no problems deploying to that

**Comment by stevejgordon** [comment]
Time permitting I plan to take a branch and have a go at moving it over to RTM as I'm keen to see what's involved. The changes between RC1 and RC2 where the biggest, with RTM it looks less complex. I know @shawnwildermuth wrote a great post about his experience migrating so happy to take direction from an expert or just watch and learn!

**Comment by BillWagner** [comment]
I like the idea of a "Day 1" migration if it does not affect any existing data. 

If I understand correctly, that would mean developers would need to delete any local DBs, and recreate them with the new version. We (HTBox admin) would need to do the same in our Azure subscriptions.

@tonysurma can you verify those assumptions?  if correct, I'm good.

**Comment by tonysurma** [comment]
Correct and the sooner the better

**Comment by shawnwildermuth** [comment]
I'm happy top tale this one and resolve them this weekend

**Comment by shawnwildermuth** [comment]
Unless someone else is working on it

**Comment by BillWagner** [comment]
I assigned it to you @shawnwildermuth 
If anyone wants to help out, ping @shawnwildermuth

**Comment by tonysurma** [comment]
Great, I will try to review and merge as many PR's as possible by tomorrow am so we don't have many open across the upgrade.  @billwagner can you post in slack this will happen this weekend so folks know if they start or are working on a pr?  I think the real conflict we will want to manage would be migrations primarily

**Comment by shawnwildermuth** [comment]
Awesome!

**Comment by stevejgordon** [comment]
Hey @shawnwildermuth - When are you thinking of working on this? I've got quite a hectic weekend but would love to pair / watch / assist with the steps if you'd be up for that. I'm unavailable today but should be able make some time tomorrow. Don't want to hold things up though, so not to worry if it's not possible. Also I'm in the UK so it may be that time differences make it more difficult still.

**Comment by shawnwildermuth** [comment]
I've upgraded most of the project, just trying to fix about 200 tests I broke. Luckily we have tests for that. Some APIs changed and we might want to revisit how we implement some things (where UserManager and SignInManager needs to be injected into a lot more places than it used to).

**Comment by tonysurma** [comment]
I have merged all immediately mergable PRs and verified none of the open ones have migrations for EF so we should be good to move on this.  Thanks all for helping out.

@shawnwildermuth if you have done some work already (which it looks like you have and thanks!) than, as you know, please rebase off of the current master to pick up changes from those merged PRs.

**Comment by shawnwildermuth** [comment]
I've rebased it, but we have an issue with some of the assumptions of the database have changed in RTM. What is our plan going forward on migrations? I can try to fix up migrations or we can take the big pill now and delete all the migrations and start fresh now that we're at a stable build.  Opinions?

**Comment by shawnwildermuth** [comment]
I'd also like to talk about maybe reviewing our creation and running of Migrations during the site. I've moved away from doing this in code, and just using the "ef database update" instead so I can debug it right and not some random build to the release server inadvertently updating the database in ways we don't want.

**Comment by tonysurma** [comment]
No need to fix migrations, we should just do a new "day one" migration now on rtm.

And I do auto migrate on dev site that auto deploys from github and for prod sites I run the cmd so we are aligned there already

**Comment by tonysurma** [comment]
Thx @shawnwildermuth

**Comment by shawnwildermuth** [comment]
Sweet.  I'm working through some of the tests that were put in to test EF bugs, hope to have that done tomorrow night.

**Comment by stevejgordon** [comment]
Closing as we're picking up any left over skipped tests in specific issues
