### ISSUE TITLE
login email does not accept empty space

### ISSUE THREAD

**Issue by manojattal** [HTBox/allReady#743]
Adding an extra space in login email textbox gives error. Ideally it should accept space character in the username textbox.

**Comment by ofirgeller** [comment]
I tested this by adding spaces before and after the email and I can't make it fail. looking at the http request shows the email has been trimed.

![image](https://cloud.githubusercontent.com/assets/4271135/17079908/d0fa3374-5126-11e6-9f48-e7f2fbafa2f5.png)

Are we talking about a different form? or has this been fixed without the issue closing?

**Comment by gordanac** [comment]
this appears to be browser specific -got error in  IE but not in Chrome

**Comment by ofirgeller** [comment]
tnx, ill take another look

**Comment by ofirgeller** [comment]
Pull request #1116
