### ISSUE TITLE
EF exception being thrown trying to start up project...

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#750]
@stevejgordon 

In `SampleDataGenerator.cs`:
`at AllReady.Models.SampleDataGenerator.InsertTestData() in D:\Projects\allReady\AllReadyApp\Web-App\AllReady\DataAccess\SampleDataGenerator.cs:line 382`

`Invalid column name 'PostalCode'.`

line 382 looks like this:
`_userManager.CreateAsync(user1, _settings.DefaultAdminPassword).GetAwaiter().GetResult();`

I'm not too sure if the user manager deals with PostalCode at all, but I can't get past this line without and exception being thrown...

maybe it's a problem with one of the migration scripts?

**Comment by mgmccarthy** [comment]
In AllreadyContextModelSnapshot.cs:
![image](https://cloud.githubusercontent.com/assets/2428993/15302483/39d34448-1b81-11e6-82f2-51d3020c3ab0.png)

but looking at the Location entity, the name of the column is not `PostalCodePostalCode`, it's `PostalCode`

**Comment by stevejgordon** [comment]
@mgmccarthy Yep, that looks to be the issue. The changes were introduced in a prior PR to remove the link between the postcode field in locations and the PostCodeGeo table which included the column name change, however a migration was needed to ensure the database is updated accordingly.

I've done the smallest change possible which is adding a migration here. I'll open a new issue to discuss if the PostcodeGeo table is even relevant now and to verify the behaviour of locations.

It now seems to seed fine for me with no changes to the seed data.
