### ISSUE TITLE
Add / Edit Task Postcode DB Error

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#753]
Since the changes for the postcode field occurred it seems that trying to add or edit a task for an event causes the following error on the GET request for the create/edit page.

![image](https://cloud.githubusercontent.com/assets/3669103/15312237/37dfa1d0-1bfa-11e6-914c-fac855004def.png)

**Comment by vishal123** [comment]
I had a look at this at submitted a pull request. #756

**Comment by stevejgordon** [comment]
@vishal123 Cool, thanks. :-)

**Comment by tonysurma** [comment]
closed by #756
