### ISSUE TITLE
Error copying contact Info when creating new campaign

### ISSUE THREAD

**Issue by curts** [HTBox/allReady#766]
0. Logged on as administrator
1. Click to create a new campaign
2. Click the Copy Contact Info button and select "Overwrite Existing Details"
3. You receive an error:

![error](https://cloud.githubusercontent.com/assets/1950836/15371318/7aaff080-1d00-11e6-8a32-47e7260b4b7f.png)

**Comment by tonysurma** [comment]
included in #910
