### ISSUE TITLE
Remove MobileViewModels

### ISSUE THREAD

**Issue by shawnwildermuth** [HTBox/allReady#78]
I don't see what this project is for and it isn't referenced by the rest of the projects. Mixing a .NET app and a DNX app can cause a lot of reference issues and unless someone can explain what the project is for, I'm happy to remove it (at least for now).

**Comment by dpaquette** [comment]
Would be great if we could remove this one

**Comment by dpaquette** [comment]
This issue can be closed

**Comment by BillWagner** [comment]
Yes it can. I did not catch that PR #99 did not explicitly reference that it fixed this issue.
