### ISSUE TITLE
Admin campaign index page throws exception when dates for campaign is not set

### ISSUE THREAD

**Issue by manojattal** [HTBox/allReady#781]
1. Login using "organization@example.com"
2. With default data, some of campaigns do not have start and end dates.
3. While displaying campaigns list, it throws exception as in screenshot.

![loginissue](https://cloud.githubusercontent.com/assets/413961/15415697/0bd5974c-1e62-11e6-9f05-8d9617c0c11d.png)

**Comment by robrich** [comment]
Can't reproduce with git hash a598be2.  Can you explain more about how to reproduce this or what git version you're using?

**Comment by kgipson** [comment]
I am not able to reproduce this issue either.

The AllReady.dbo.Campaign table defines StartDateTime and EndDateTime as not null.  It looks like commit fb6f00c2 updated the AllReady.DataAccess.SampleDataGenerator.InsertTestData() method to make sure test Campaigns are being initialized with valid StartDateTime and EndDateTime values.

**Comment by zimplicity** [comment]
The UI also fails validation if Start or End Date are not provided.  Looks like this has already been solved in several places.

**Comment by tonysurma** [comment]
yep thx @zimplicity and @kgipson marking it closed
