### ISSUE TITLE
write unit test for NotifyVolunteerForUserUnenrolls

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#783]
@tonysurma please label with "jump-in". Part of Issue #620

**Comment by nedruk** [comment]
If nobody is looking at this, I would like to pick it up.

**Comment by recumbent** [comment]
This looks like its intended for NotifyVolunteerForTaskUnenrollHandler (there is no NotifyVolunteerForUserUnenrolls or near equivalent) in which case its covered by tests and this could be closed /cc @stevejgordon @mgmccarthy

**Comment by stevejgordon** [comment]
@recumbent Thanks, looks like this is correct so I will close this issue.
