### ISSUE TITLE
write unit test for NotifyVolunteerForEventSignup

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#784]
@tonysurma please label with "jump-in". Part of Issue #620

**Comment by binaryjanitor** [comment]
@tonysurma Working on this

**Comment by tonysurma** [comment]
okay after you accept my invite we will assign to you

**Comment by TheTopher** [comment]
I thought that I did.  Stop by.

**Comment by binaryjanitor** [comment]
@tonysurma not done. Shifted gears. Still open

**Comment by sanilpaul** [comment]
@mgmccarthy @tonysurma I don't see this class anymore. Is it same as **NotifyVolunteerForTaskSignup** 
@binaryjanitor are you still working on this?

**Comment by BillWagner** [comment]
Looking through history and code, it looks like this is now part of NotifyVolunteerForVolunteerTaskSignupHandler and NotifyVolunteerForVolunteerTaskUnenrollHandler.

Both of those have unit tests, so closing.  

Let's open a new issue if some of the code moved into a different class.
