### ISSUE TITLE
write unit test for CheckValidPostcodeQueryHandlerAsync

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#785]
@tonysurma please label with "jump-in". Part of Issue #620

**Comment by samqty** [comment]
Volunteering to pick up this one!

**Comment by mgmccarthy** [comment]
@samqty, go for it! If you have any questions, please feel free to ask.

**Comment by sanilpaul** [comment]
@mgmccarthy @samqty @tonysurma Looks like this has been done. May be we should clean up by closing the issue.

**Comment by BillWagner** [comment]
Closed in PR #1168
