### ISSUE TITLE
write unit test for DeleteOrganizationHandlerAsync 

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#786]
@tonysurma please label with "jump-in". Part of Issue #620

**Comment by ankurMalhotra** [comment]
I'l pick this up if no one else has already done it.

**Comment by mgmccarthy** [comment]
@ankurMalhotra, I don't see a file with that name anymore. It probably was renamed. There is a `DeleteOrganizationHandlerAsync` handler that does not have a unit test, you can work on that one.

**Comment by sanilpaul** [comment]
@ankurMalhotra Are you working on this?

**Comment by ankurMalhotra** [comment]
I checked in a couple of tests for this. Not working on it anymore.
