### ISSUE TITLE
Go Live Release Scenario

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#799]
This is an overall issue to document the scenario we are trying to go live with in June.

The key requirements are collecting data from getasmokealarm, the organizer workflow for itinerary type events, volunteers interaction with itinerary type events and tracking status of requests (incomplete, complete, pending, etc.)

**Comment by stevejgordon** [comment]
@tonysurma I still have more to do on the Org Admin journey, but have started thinking on the next steps. For the volunteer stage of this story and initial release are we safe to assume that any volunteer added to an itinerary as a team member, should then have permission to view the request details for any assigned requests and also update the request status (completed / failed etc)?

**Comment by stevejgordon** [comment]
@tonysurma - Anything left on this one which we need to break out?

**Comment by tonysurma** [comment]
@stevejgordon @schuback @OhMcGoo can you document out the scenarios so we can see if there are any additional gaps? cc @EmilyLuijbregts

**Comment by stevejgordon** [comment]
Closing as we have now reviewed flows and requirements document and I believe created issues for any gaps.
