### ISSUE TITLE
Add initial Itinerary DB Model schema

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#809]
Links to master issue #799 

In order to persist itineraries into the database we need some additional models to define the database schema and the relationships.

I'm proposing at this stage we create an Itinerary model which stores the date an itinerary is scheduled to occur. An event can have 0 or more itineraries.

I propose we then have a many to many relationship between requests and itineraries. Whilst we should only allow a request to be attached to one future itinerary we may have cases where a request in itinerary 1 is not completed (home owner not available for example). In that case an org admin will need to be able to link the request to a new itinerary.

I propose we leave the request linked to the original (in the past) itinerary for tracking purposes.

@OhMcGoo @tonysurma @MisterJames - A few questions

1. Does this sound reasonable to you all and meet the business rules? 
2. Would being able to create a friendly name an itinerary be a useful feature (i.e. Zone X installations)?
3. When assigning volunteers as part of the team for the itinerary, would it be useful to be able to define additional properties such as the role(s) they will perform? (i.e. Installer) or should we assume that based on the task they're assigned against? I'm thinking a join table which holds this and any other information might be useful?

I've started work on this locally while I experiment with an itinerary creation process.

**Comment by tonysurma** [comment]
Quick  answers from phone: Yes, yes, assumed from task

**Comment by stevejgordon** [comment]
@tonysurma Thanks, that should get me going. I'll try to get a PR in with the initial bits so it can be sanity checked as I go.

**Comment by stevejgordon** [comment]
@tonysurma I tagged the PR incorrectly (always seem to do that) so this didn't auto close!

**Comment by tonysurma** [comment]
@stevejgordon no worries 😄
