### ISSUE TITLE
Enhance quick add team member UX

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#839]
Follow up from PR #837 

At the moment the structure of the AddTeamMember action and the form which calls it from Itinerary Details does not provide UI feedback in the case of a failure.

We should implement the form post via ajax and handle better display of any errors.

We should enhance the AddTeamMemberCommandHandlerAsync to return details of any failures so that an appropriate error response can be sent by the action.

**Comment by Daven-** [comment]
I'll be working on this if no one else is already.

**Comment by Daven-** [comment]
Leaving this to someone else, not experienced with asp.net to go about it. 

To save the next person time you could do the following instead of logging back in with user and organization to try and get the scenario going.

Web-App/AllReady/Areas/Admin/Controllers/Views/Itenaerary/Details.cshtml

```
@* @if (Model.HasPotentialTeamMembers)
{ *@
    <div class="row">
        <div class="col-md-12">
            <form asp-area="Admin" asp-controller="Itinerary" asp-action="AddTeamMember" method="post">
                <input type="hidden" asp-for="Id" />
                Add team member:
                <select asp-for="SelectedTeamMember"
                        asp-items="Model.PotentialTeamMembers" required>
                        <option value='0'>Volunteer1</option>
                </select>
                <button type="submit" class="btn btn-default submit-form">Add</button>
            </form>
        </div>
    </div>
@* }
else
{
    <p>There are no potential team members to add to this itinerary</p>
} *@
```

**Comment by dchristensen** [comment]
I am working on this.

**Comment by tonysurma** [comment]
thank you.   If you accept our invitgation to the repository we can then assign you to the issue cc @emilyluijbregts
