### ISSUE TITLE
Data Access Concerns

### ISSUE THREAD

**Issue by MisterJames** [HTBox/allReady#84]
I have a few reservations about how we're doing our data access. I think it would be great if we could switch to something like MediatR and use commands/queries, for example, but coming down the stretch we're going to run into trouble with merge conflicts on our `DataAccess` class.

I was just talking with @dpaquette and we're thinking a reasonable interim fix would be to split the class into partials to help with that problem.

Does anyone have any objections to this idea? It's functionally non-impacting, but might save us some headaches.

**Comment by dpaquette** [comment]
I will submit a PR for this later today
