### ISSUE TITLE
Mobile-App Events Page Lists Fake Events

### ISSUE THREAD

**Issue by SteveKennedy** [HTBox/allReady#842]
The events page on the TACO (Tools for Apache Cordova) project appears to have a number of false event entries immediately following real one(s). They are labelled with "Missing Date" as shown in first attached image.

![events](https://cloud.githubusercontent.com/assets/12101125/15953925/4e68ddbe-2e96-11e6-8ddc-7b6c54bb5e51.png)

Remove the extraneous events and the screen should look something like the second attached image.

![events2](https://cloud.githubusercontent.com/assets/12101125/15953958/a20e12b8-2e96-11e6-9b51-b7d516dfd901.png)

**Comment by tonysurma** [comment]
fixed by #843
