### ISSUE TITLE
Split User "name" property

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#846]
We currently have a name property on the user. This should be broken up into Forename and Surname and any uses of name updated.

Any forms where the user can add their name will need to be adjusted also.

**Comment by mgmccarthy** [comment]
@stevejgordon, we're talking about making this change on `AllReady.Models.ApplicationUser`?

**Comment by stevejgordon** [comment]
Yes I think so.

Sent from my Windows Phone
________________________________

**Comment by mgmccarthy** [comment]
@stevejgordon, I'll take this and work on it. I'll reach out to you with any questions, thanks

**Comment by mgmccarthy** [comment]
@stevejgordon, I'm hung up on my work b/c of dnx ef migration stuff. Even though I fixed it once on this machine before, and when I check my PATH environmental variables there is an entry for dnx, I can't get a cmd prompt or powershell prompt to recognize "dnx ef". 

I THINK I need a migration for `ApplicationUser`, b/c that's the entity I'm changing. However, this inherits from `IdentityUser`, so maybe there is a different process is adding this?

**Comment by mgmccarthy** [comment]
@stevejgordon, never mind. Got it working

**Comment by mgmccarthy** [comment]
@tonysurma @stevejgordon  do we want these fields called "Forename" and "Surname", or "First Name" and "Last Name"?

**Comment by tonysurma** [comment]
We have no hard requirements one way or other and there is no clear worldwide solution for the naming of 'names' that I can identify.  Pick one and we can edit later if needs be.

**Comment by stevejgordon** [comment]
I'm out currently but perhaps can chat tomorrow if you still have issues? Was it when creating a migration or trying to update database with the new ones?

As for naming, I personally prefer forename / surname but I don't think it matters too much. Both are pretty clear.

Sent from my Windows Phone
________________________________
