### ISSUE TITLE
Add request to itinerary

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#851]
Implement a lister of available requests with some method to add them to the itinerary.

v1 will be quite simple but could be extended to include searching and location grouping etc.

When a request is added it's status should be updated to assigned.

**Comment by stevejgordon** [comment]
I'll work on this next

**Comment by stevejgordon** [comment]
@tonysurma When a request is assigned to an itinerary are we requiring the ability to set planned start time and end time against each request? This feels like it might be useful for organizers to manage the planning? If it is something we expect this may add quite a lot of extra behavior and logic so it would be useful to know if it's key for this initial release or more of a future requirement to bare in mind?

**Comment by tonysurma** [comment]
Not key for this, maybe someday.

What would be good for now is ordering of requests in itinerary so can specify first second etc

**Comment by stevejgordon** [comment]
@tonysurma Sounds good. Cheers
