### ISSUE TITLE
ViewModel organization under "ViewModels" directory

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#857]
first off, this is low priority, but I wanted to record it while I was thinking of it.

we currently have come classes in here (AccountViewModels) that contain multiple ViewModel classes for the same controller.

We should organize the ViewModels folder to have the name of the controller as a directory, and then all relevant ViewModel classes go under that directory. The View folder is organized in such a way.

Using AccountViewModels as an example. Here is what it looks like right now:
![image](https://cloud.githubusercontent.com/assets/2428993/16042564/59238968-3209-11e6-9ff8-35cda72abbdf.png)

This is what I'm proposing it would look like:
![image](https://cloud.githubusercontent.com/assets/2428993/16042637/c08341f2-3209-11e6-9d03-5697d3301424.png)

**Comment by stevejgordon** [comment]
@mgmccarthy Yep, I very much agree. We're starting to build up a lot of models for the various areas. I've actually started doing this with some of my itinerary pieces

**Comment by mgmccarthy** [comment]
seems that some of our ViewModels are shared. I'm not a big fan of this as I'd rather deal with discreet ViewModels that are targeted to specific controller actions rather than "shared" ViewModels used across controllers.

Sharing ViewModels encourages the class to become a dumping ground for things that do not belong there, such as business rules, db/mediator code etc... 

This pattern really breaks down when some of the properties are populated for one controller to use and some other properties are populated by another controller to use etc....

I also believe we have a separate issue for breaking apart/simplifying some of our ViewModel code.

**Comment by tonysurma** [comment]
Feels like this could be labeled jumpin or am I crazy?

**Comment by mgmccarthy** [comment]
@tonysurma, could be labeled as such. I guess any ViewModels that are shared between more than one controller should be put into a Shared folder and any ViewModels that are not really tied back to any controller could be left directly under the existing /ViewModels folder.

I have ReSharper installed on my system, so I could probably knock this out today if you want to assign it to me

**Comment by tonysurma** [comment]
done
