### ISSUE TITLE
write unit tests for NotifyAdminForTaskSignupStatusChange

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#861]
@tonysurma please label with "jump-in". Part of Issue #620

**Comment by rayhiker** [comment]
I am working on this one.

**Comment by mgmccarthy** [comment]
ping @rayhiker, did you ever submit a PR for this?

**Comment by ExoltenOne** [comment]
Could I take this one?

**Comment by mgmccarthy** [comment]
@ExoltenOne, please do. I just looked at the latest code and it looks like there was never a test written. Thanks

**Comment by rayhiker** [comment]
Yes, please do. I got too busy to finish this up.
Thanks,
Ray
