### ISSUE TITLE
write unit tests for NotifyAdminForUserUnenrolls

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#862]
@tonysurma please label with "jump-in". Part of Issue #620

**Comment by bsstahl** [comment]
I'm working on this

**Comment by mgmccarthy** [comment]
@tonysurma, my dev machine is toast. I have to wait until next Tuesday to get it fixed by our comapany's service desk, so I will be unable to do any code reviews until then

**Comment by digitaldrummerj** [comment]
@tonysurma looks like a PR has already been merged for this issue.

**Comment by mgmccarthy** [comment]
@tonysurma, @digitaldrummerj this test has been written and this Issue can be closed
