### ISSUE TITLE
write unit tests for CampaignSummaryQueryHandler

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#863]
@tonysurma please label with "jump-in". Part of Issue #620

**Comment by nedruk** [comment]
I'll look at this one if nobody is working on it.

**Comment by recumbent** [comment]
Reviewing this at NDC London will add more tests /cc @stevejgordon

**Comment by recumbent** [comment]
Upon reflection - and having read enough code now - I'm not sure I can add much in the way of value here. Probably ought to be closed @stevejgordon @mgmccarthy
