### ISSUE TITLE
write unit tests for OrganizationDetailQueryHandler

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#865]
@tonysurma please label with "jump-in". Part of Issue #620

**Comment by ankurMalhotra** [comment]
Please code review.
Thanks

**Comment by mgmccarthy** [comment]
@ankurMalhotra my Dev machine is out of commission until Tuesday at the earliest. I'll try to get to it sometime this week.

**Comment by mgmccarthy** [comment]
@tonysurma this Issue can be closed.
