### ISSUE TITLE
write unit tests for EditTaskQueryHandler

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#869]
@tonysurma please label with "jump-in". Part of Issue #620

**Comment by samqty** [comment]
I have started working on this one

**Comment by samqty** [comment]
I see a potential implementation of a unit test for this

\allReady\AllReadyApp\Web-App\AllReady.UnitTest\Areas\Admin\Features\Tasks\EditTaskQueryHandlerAsyncShould.cs ?

is this already implemented?

**Comment by mgmccarthy** [comment]
@samqty, if there is a test class there for `EditTaskQueryHandlerAsync`, and if the test code:

1. is correct
2. tests everything that needs to be tested

then yes, this is already implemented. It's tough for the project owners to keep up with all the Issues label/statuses b/c there is a lot of work going on right now.

**Comment by samqty** [comment]
In that case, I guess this issue would serve to double check unit test coverage.

The unit test for "EditTaskQueryHandlerAsync" is correctly implemented and covers everything. If I can say something is missing would be the fact that there is some in consistency with naming convention of the unit test classes. I was expecting to find EditTaskQueryHandlerAsyncTest but found EditTaskQueryHandlerAsyncShould. Just wondering if that is considered something worth the time and effort at this time?

**Comment by mgmccarthy** [comment]
@samqty since there is a lack of naming conventions right now, I'd say that unit tests for handlers should end in "Should" and unit tests for Controllers end in "Tests".

**Comment by mgmccarthy** [comment]
@tonysurma this Issue can be closed
