### ISSUE TITLE
write unit tests for TaskListQueryHandler

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#870]
@tonysurma please label with "jump-in". Part of Issue #620

**Comment by digitaldrummerj** [comment]
@tonysurma Is this one still valid? I see a PR that references this issue that has been merged.

**Comment by mgmccarthy** [comment]
@tonysurma @digitaldrummerj, hard to tell on this one. The name `TaskListQueryHandler` doesn't exist anymore in the project b/c it has likely been renamed. Althought, I'd go with @digitaldrummerj and close this one b/c it looks like there are two PR's that are closed/merged with work that took place
