### ISSUE TITLE
write unit tests for UserQueryHandler

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#871]
@tonysurma please label with "jump-in". Part of Issue #620

**Comment by tonysurma** [comment]
thx for all of these, done in one big swoop 💪

**Comment by mgmccarthy** [comment]
@tonysurma, I've had a compiled list on my machine of all missing unit tests for awhile now, I just needed to get them into allReady. I figured our "jump-in" labels have been attracting new programmers that have been doing an excellent job on unit tests, so might as well just create all of them.

That being said it is a lot to look at on the Issues page, but at least they're in the system now.

**Comment by mgmccarthy** [comment]
I am currently working on this

**Comment by mgmccarthy** [comment]
@tonysurma, I am not working on this. Please unassign me. Thanks!

**Comment by SarahMarz** [comment]
Working on this
