### ISSUE TITLE
Notify volunteer if assigned/unassigned to an itinerary

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#874]
We should notify a volunteer if they are assigned or unassigned to an itinerary.

There are already some classes handling notifications within the current code so perhaps we can base this code off of those / reuse?

**Comment by mgmccarthy** [comment]
@stevejgordon, if you want me to have a crack at this, I will. I'm assuming we want to know if we should reuse the current handling classes though... would that be something @MisterJames @BillWagner  or @tonysurma could give us guidance on?

**Comment by tonysurma** [comment]
I would reuse and @MisterJames should be your contact for that

**Comment by stevejgordon** [comment]
@mgmccarthy Yes please have a go at this one. I've not looked at the existing ones in detail myself but  can do if you need any advice as you dive into it.

**Comment by mgmccarthy** [comment]
@stevejgordon, I'm assuming the place in the system where a voluteer is assigned or unassigned a to an itinerary is the IntineraryController's AddTeamMember action method?

**Comment by stevejgordon** [comment]
Assignment occurs from AddTeamMember, that's correct. I haven't managed to put in a remove team member flow yet. It's on my list!

**Comment by mgmccarthy** [comment]
@stevejgordon, after poking around a bit, I'm a little confused about what some of the variable names actually mean here. For example, we take a `selectedTeamMember` in the `AddTeamMember` action method on `ItineraryCotroller`, yet that gets set to a `TaskSignupId` on the `AddTeamMemberCommand`...

so how, in the context of `AddTeamMemberCommandHandlerAsync`, would I get a list of volunteers that have been assigned to an Itinerary? 

I see that the `TaskSignup` entity has a User property, so I'm assuming I would send to one volunteer at a time? In other works, the `AddTeamMemberCommandHandlerAsync` handler's transaction is scoped to adding one volunteer(aka, "user") at a time to an Itinerary?

sorry about the questions, I don't fully yet have a firm grip on the whole domain, especially the newly added Itinerary stuff

**Comment by mgmccarthy** [comment]
@tonysurma any idea of what the subject/body of this SMS/Email notification should contain?

**Comment by stevejgordon** [comment]
@mgmccarthy No worries on the questions at all. This piece of functionality crosses a few areas so it's not super clear what's happening.

At a high level we have the event which can have one or more tasks and one or more itineraries created against it. Under those tasks, users can volunteer and when they do they are added to the TaskSignup table. Users can/will be able to be assigned to a task via an Org admin also so there is the concept of a TaskSignup status which confirms if the user has actually accepted an assignment.

Rather than linking a user specifically to an itinerary I chose to link the TaskSignup since this was the single point where we control their ability to work for a task. They may for example later be reassigned or be unable to attend so when that happens we'd need to clear the TaskSignup link to the itinerary or if the signup record is deleted the link is implicitly no longer there.

To build up the Itinerary Details page which includes the drop down of potential team members, what happens behind the scenes is we look for all volunteer tasksignups to tasks from the same event as the itinerary, on the same date and which are not already linked to an itinerary. This occurs in PotentialItineraryTeamMembersQueryHandlerAsync

What we actually build up is a dropdown showing the user's email and the task name, and the value is the tasksignupid. I considered anyone in this list a potential team member.

On selecting one of these potential team members and clicking the add button the AddTeamMemberCommandHandlerAsync kicks in. The message of this command includes the itineraryid and the tasksignupid (selected from the dropdown). After the various checks for existence of records matching the values from the message we actually update the TaskSignup record to set the itinerary id. This way a TaskSignup can only be linked to one itinerary which matches the business rules. This command as you mention, controls the linking of a single TaskSignup (and therefore user) to an Itinerary at a time.

The code actually updating the TaskSignup is perhaps also not very obvious since I'm using some EF techniques to avoid having to query the DB for the full TaskSignup record before we update it.

`var taskSignup = new TaskSignup
                {
                    Id = message.TaskSignupId,
                    ItineraryId = message.ItineraryId
                };

                _context.TaskSignups.Attach(taskSignup);
                _context.Entry(taskSignup).Property(x => x.ItineraryId).IsModified = true;
                await _context.SaveChangesAsync();`

What this does is create a basic TaskSignup object with the TaskSignupId set to match the one we know exists in the database. The ItineraryId is also set. I then attach it to the EF context so this becomes a tracked object. I manually mark the ItineraryId field as a modified property with the change tracker and save the changes. Under the hood EF will work out that this is an existing record with one changed property (the ItineraryId) which it should then send a SQL command to update.

I must admit I haven't checked exactly how EF7 manages this piece as the behaviour may differ from my experience with EF6.

I hope that make some sense, any questions let me know or we can try to chat through it at some point.

**Comment by mgmccarthy** [comment]
@stevejgordon, here is my high level plan:
- add new MetiatR notification (IAsyncNotification) to the system, `VolunteerAssignedToItinerary`
- this will be published from `AddTeamMemberCommandHandlerAsync`
- the handler for `VolunteerAssignedToItinerary` will query `TaskSignup` by `TaskSignupId`, and then attempt to use the `PreferredEmail` and/or the `PreferredPhoneNumber` in order to construct a `NotifyVolunteersViewModel` which will be attached to a `NotifyVolunteersCommand` (existing command and handler in the system) and then send from the handler.

a couple questions:
- does it make sense to create a `VolunteerAssignedToItinerary` MediatR notification? I like the approach, b/c it's worded like an SOA "event" in the fact that the volunteer has already been assigned. The only thing "subscribing" to this event is the handler that will build up the `NotifyVolunteersCommand`. I'm not too sure if there is anything else in the system that is interested in knowing whether or not a volunteer has been assigned to an itinerary.
- if that's too heavy handed, I can instead write a `NotifyVolunteerWhenAssignedToItinerary` command that will be sent directly from `AddTeamMemberCommandHandlerAsync`.

The difference between these two approaches is that commands can have only one logical handler, where MediatR notifications can have 1 to n subscribers (aka, handlers)...

Also, are my queries correct? For example, do I query `TaskSignup` by just the `TaskSignUpId` or do I need to query using both `TaskSignupId` and `ItineraryId`?

I should have a PR ready for this by tomorrow.

Thanks

**Comment by stevejgordon** [comment]
@mgmccarthy Your plan sounds good to me. While we will probably only have one subscriber for now, I can see potential to have another work we might do when a new team member is added. If the overhead and complexity is not much higher, leaving it more extensible with pub/sub feels like a good approach for these type of events.

In regards to querying for the TaskSignup, you should be able to use just the TaskSignupId as that is the unique Primary Key and should get you all the info you need.

**Comment by mgmccarthy** [comment]
@stevejgordon @tonysurma any idea on what the sms/email body and email subject should say?

**Comment by tonysurma** [comment]
sorry for delay, when the assign/unassigned happens do we have a link for the volunteer to see the itinerary they are on?  That will guide the content of the email/sms.  Thanks @mgmccarthy

**Comment by mgmccarthy** [comment]
@tonysurma @stevejgordon. We could build a url to put into the message to bring the user to the Details view of IntineraryController. Not too sure what else the body should say... and for an email, we'll need a subject.

**Comment by stevejgordon** [comment]
@mgmccarthy @tonysurma At the moment we don't have a non admin view of an itinerary.

**Comment by mgmccarthy** [comment]
@stevejgordon do you want me to build one? I actually watched the standup YouTube vid link you sent yesterday, and it looks like the overall plan here is have a dashboard for each volunteer where when they log in, they can see information like this aggregated across the site into one page. 

I can start by building the simplest possible thing... controller that takes itineraryId and returns a view that shows the data about an itinerary.

When the dashboard starts takes shape, we can incorporate using partial views and/or whatever javascript library magic might be used to make the UI a bit more cool.

**Comment by tonysurma** [comment]
For now lets **not** build a non-admin way to view an itinerary.

For the messages lets go with the ones below - we can always edit.

And separately, if you want to start working on a volunteer dashboard showing what they have volunteered for and/or itineraries they are in etc - please do.  I will dig it up but we have an issue somewhere for that.  And I like your idea of starting small and then building it up.

For messages:
SMS: _You’ve been assigned to a team for [date] [link to volunteer dashboard]_
(assuming we can put in the date of the itinerary and later we will include a short link to the volunteer dashboard but for now not include it)
Email:
Subject _You've been assigned to a team for [date]_
Body _The volunteer organizer has assigned you to a team for [date].  See your [allReady Volunteer Dashboard] for more information._
(assuming same substitutions as above)

Thanks!

**Comment by mgmccarthy** [comment]
@tonysurma, thanks for the feedback. I'll get to work on those messages for the assignment/un-assignment handlers...

**Comment by stevejgordon** [comment]
@tonysurma @mgmccarthy I do have some code in flight for the MyEvents page which was to close out #376 

I'd put it on the backburner since the itinerary stuff was taking priority. I need to load it up, but I think it was mostly there (al-be-it) quite ugly and basic. It was just listing out events that the user had volunteers for (taskSignups).

I can quickly review it and see if it's good enough to get checked in (sans tests) if you want so we can then start with some issues to expand it?I'd actually branched off a couple of days ago for a basic itinerary view page as well (needing to check if the user is assigned before displaying that) etc, It was very bare bones. Happy to hand that over though.

Back to MyEvents, should we rename this page and it's route to something like VolunteerDashboard?

**Comment by tonysurma** [comment]
cool @stevejgordon the itinerary stuff is definitely the priority (I am going through and reprioritizing/populating the milestone as well) but if you have a start so you or @mgmccarthy can build on that, that's great.

and yeah something like VolunteerDashboard would be great.  We will likely want to also create a short redirect like /v for SMS codes (like above)

**Comment by stevejgordon** [comment]
@tonysurma I'll try and check it out tonight when i get home and if it looks good enough get a PR in so at least we have the page we can start to enhance.

Also I'm hoping to chat to @OhMcGoo with regards to UX/design. I think it might pay to think about how the user needs to interact with things on the dashboard to be able to give direction for the items we need to display etc. Ultimately that will help determine the view model data etc.

A redirect page also makes sense, I'll create an issue for that.

**Comment by mgmccarthy** [comment]
I'll keep the itinerary notifications at top of my list for now. @stevejgordon, if there are pieces you need help with for itinerary work that are not based around notifications, I can help with those first instead of working on the notifications.

I'm thinking @tonysurma should accept my outstanding PR #892, even though I'm half-way done my work with the notification of assign/unassign for itineraries on this issue.

Might be good for use both to rebase b/c we could be stepping in each other's toes with ItineraryController/Tests and AddTeamMemberCommandHandlerAsync.

**Comment by tonysurma** [comment]
@mgmccarthy so accept now and you'll keep working on next steps of notifications in another PR?

**Comment by mgmccarthy** [comment]
here is the to-do list and where I am as far as getting this Issue closed

- [ ] notify on assignment to itinerary
- [ ] notify on unassignment to itinerary
- [x] @tonysurma:I need verbiage for the SMS/Email body and the email subject for both assign and unassign
- [ ] unit tests for newly added handlers/changed code

**Comment by mgmccarthy** [comment]
@tony yeah, let's do that. I moved my to-do list out of the PR and into this Issue (where is belongs). This issue should be handled across multiple PR's.

**Comment by stevejgordon** [comment]
@mgmccarthy Sounds good. I'll rebase my branches later (hopefully) and see if I can at least check in the bone of what will become the VolunteerDashboard.

I've got about 3 branches on the gone with the itinerary bits (delete, reorder and a view page). Those are part done but need a few hours on each I think. I'll probably get them in without tests etc in the interests of speed and seeing if the functionality is meeting the requirements. So we'll certainly need some test stubs for those.

@tonysurma Are there other bits around itinerary you can think of that can be broken out for other contributors? Are there any issues from your list on slack that could use some focus from @mgmccarthy perhaps

**Comment by mgmccarthy** [comment]
@stevejgordon. It looks like there is a `NotifyVolunteerForEventSignup` class that does sms/email notification for an event.

Just so I understand... a volunteer volunteers for an event, and they get this sms/email communication as a confirmation of them volunteering.

What I'm building is another sms/email communication the volunteer receives when an "admin" of some sort assigns/un-assigns the volunteer to an itinerary.

The difference between these two notifications is that the notification for volunteering for an event is something the volunteers receives as a result of something the volunteer did in the UI on their own. The notification that the volunteer receives when assigned/unassigned to an itinerary is the result of another user (and "admin"-type user) selecting them (or deselecting them) as a "team member" for a given itinerary?

**Comment by mgmccarthy** [comment]
@tonysurma. for the messages you listed above:

> For messages:
> SMS: You’ve been assigned to a team for [date] [link to volunteer dashboard]
> (assuming we can put in the date of the itinerary and later we will include a short link to the volunteer dashboard but for now not include it)
> Email:
> Subject You've been assigned to a team for [date]
> Body The volunteer organizer has assigned you to a team for [date]. See your [allReady Volunteer Dashboard] for more information.
> (assuming same substitutions as above)

is the date shown in these messages the StatusDateTimeUtc of the TaskSignup or the Date of the Itinerary?

**Comment by tonysurma** [comment]
Itinerary
