### ISSUE TITLE
ItineraryController (admin area) tests

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#878]
We need some tests around the logic and behaviour of the new actions added for the ItineraryController in the admin part of the site.

**Comment by stevejgordon** [comment]
@mgmccarthy Perhaps something you can look into and create some stubs for others to be able to pick up?

**Comment by mgmccarthy** [comment]
@stevejgordon, I'll work on stubbing out the test names for the controller, then we can add an jump-in label to a new issue.

**Comment by stevejgordon** [comment]
@mgmccarthy Thanks. If you have any questions about the logic I've tried to implement just let me know. I think the controller is reasonable straightforward. I left some comments in my latest commited code as well.
