### ISSUE TITLE
AddRequestsCommandHandlerAsync tests

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#879]
We need some tests to validate the behaviour of adding requests via this handler.

**Comment by adam-gligor** [comment]
I created the unit tests for this class

**Comment by tonysurma** [comment]
thanks @adam-gligor for contributing! I apologize if I missed it but have you made a pull request to have us pull those changes into the project?  If you have any questions on that @stevejgordon has a great blog post and is super helpful as well as @mgmccarthy has helped with a lot of our unit tests so would be happy to review them as well.

Thanks again for your contributions and welcome to the project!

**Comment by sanilpaul** [comment]
@stevejgordon @adam-gligor @tonysurma  Any reason why this is still open? I see that tests are already written for this handler

**Comment by adam-gligor** [comment]
Hi, the issue ca be closed as far as I know, though I can't do it myself.

**Comment by stevejgordon** [comment]
@sanilpaul Yes looks like the code from the above commit is in the master branch so it must have been merged in. Good spot!

@adam-gligor Thanks for the contribution.

I'll close this issue now.
