### ISSUE TITLE
Upgrade to Beta 8

### ISSUE THREAD

**Issue by dpaquette** [HTBox/allReady#88]
Beta 8 was released this week. 

Breaking Changes to be aware of  -> https://github.com/aspnet/Announcements/milestones/1.0.0-beta8

**Comment by dpaquette** [comment]
I can take this one on

**Comment by tonysurma** [comment]
Thx for posting the issue and taking it @dpaquette I was going to post it like we did for 6 & 7

**Comment by shawnwildermuth** [comment]
Sorry, I just added a pull request for this upgrade. Should have checked the issues first. Feel free to reject the PR if you need.
