### ISSUE TITLE
Viewing a task after you volunteered gives you an error

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#886]
cc @stevejgordon and @dpaquette 

So I can volunteer now - good news.
I can't go to a task after I volunteered - bad news.

![js error 2](https://cloud.githubusercontent.com/assets/5067595/16135964/84ae51e6-33ec-11e6-8aa3-13fc04fa5dc0.png)
bridged from #884

**Comment by tonysurma** [comment]
actually I can't look at any of those tasks on that campaign now

I can look if I am not logged in so think it has to do with the same skills matching stuff that @dpaquette looked at maybe

**Comment by dpaquette** [comment]
Oh yeah, @stevejgordon did mention this part but I didn't get that far after fixing the first part. Let me see if I find a quick fix

**Comment by dpaquette** [comment]
@tonysurma How do you "go to a task"? I can see the tasks on the event page. I can also view and edit the tasks in the admin section. I must be missing something.

**Comment by tonysurma** [comment]
fixed now, thx all
