### ISSUE TITLE
Remove PreferredEmail and PreferredPhoneNumber on TaskSignup/EventSignUp

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#894]
this results in handlers needing to first check if PreferredEmail/PreferredPhoneNumber is null, and if it is, to include User into the query in order to get at ApplicationUser's Email and PhoneNumber values (which also could be null).

We go through an email vaildation for ApplicationUser email (there is EmailConfirmed field) to validate the user's email, but do we also validate email's/phone numbers added to TaskSignup?

**Comment by mgmccarthy** [comment]
@tonysurma, any time to look at why we're supporting a Preffered Email and Phone number on Tasks when a user is forced to provide both to use when they register with the site? I don't think users can volunteer for a task unless they're registered with the site, correct?

**Comment by mgmccarthy** [comment]
@tonysurma @MisterJames 

the reason I'm asking this is b/c we are not requiring either:
1. that the user confirm their email when registering with the site before they start to volunteer
2. preferred email need to have legit email when volunteering

this is resulting in a lot of code in communication-based handlers (aka, handlers that send email and/or sms texts) further down the pipeline that has to check first if the user's email has a value, then check if the preferred email for the given event has a value, and if neither do, then to silently not send a message.

I good example of this type of check is in NotifyVolunteerForUserUnenrolls. There is a bunch of code that deals with all the checks I just mentioned before getting to the task of building the message and sending it:
![image](https://cloud.githubusercontent.com/assets/2428993/18005214/8df09866-6b66-11e6-9af1-3b240b871098.png)

it would be nice to not have to check for the existence of a user's email. Things like

- not allowing the user to volunteer until they confirm their email with us
- not allowing the user to voluntter if they have not confirmed their email with us by makign Preferred Email a required UI field

could get rid of a lot of this type of "null/whitespace/existance" checking code that has propogated into a lot of our controllers and handlers.

thoughts?

**Comment by tonysurma** [comment]
preferred was a previous concept. High level thoughts:
a) we should require that they complete the email and phone prior to volunteering but to think on workflow there so we don't potentially get user drop off
b) we can drop preferred altogether from UI and model and show current email/phone number when you volunteer and link/allow edits if that has changed since you registered
c) that should simplify it down to you have to have emial & phone to volunteer and the only ones are the ones on your account

**Comment by mgmccarthy** [comment]
my feeback on:

a), I'd check with the Red Cross to see if they think this is going to be the user experience they want. If they want to verify email addresses before users volunteer, then they know they can communicate with each voluntter. If they want to optimize for volunteers, with the caveat that some of those volunteers will be impossible to contact, we can build it that way too. To me, this is more of a business questions/use case/requirement thing than a technical problem

b) I'd LOVE to drop preferred. I don't know why we'd want the same physical person to be represented by three different "preferred" email across multiple Events/Tasks. This will be especially easy to get rid of if we can put a rule into the system that does not allow a user with an unverified email address to volunteer (check my answer on a) for what that should involve)

It would be good to talk to a business owner/domain expert (someone from the Red Cross) on this one. 

I think the question do you want to optimize your volunteers to have a verified email address (which might scare some volunteers away b/c they don't want to deal with the "hassle" of registering and verifying their email address) or optimize for the "ease" of volunteering, knowing that x% of those people might be unreachable to communicate with them would be some good information to have.

**Comment by mgmccarthy** [comment]
@tonysurma, to summarize.

- remove PreferredEmail and PreferredPhoneNumber properties any entity/model that currently uses it.
- currently, both the `TaskSignup` and `EventSignup` models have these properties
- update impacted code to use the user's email/phone provided to us at the point they registered regardless of whether or not that email/phone is verified or not.

In order for this refactoring to work, I'm assuming that we can never have an `ApplicationUser` volunteering via TaskSignup/EventSignUp that will have a `null` Email or Phone b/c we require both of those items upon registeration (via regular site registration or external provider)

For example, I'm assuming code like this:
`PreferredEmail = appUser?.Email,` (appUser here is an `ApplicationUser`)

should go away as we should never have an ApplicationUser w/out an email address. Any impacted UI that currently asks for a PreferredEmail /Phone will be changed to remove that field.

**Comment by mgmccarthy** [comment]
I'm holding off working on this until #919 is finished.

**Comment by mgmccarthy** [comment]
@tonysurma, now that @stevejgordon knocked out #919, I'm going to start this up again. have you had a chance to read through my last comment on 8/29? Let me know if any of my assumptions there look incorrect. Thanks
