### ISSUE TITLE
Finish unit test for ItineraryController

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#895]
finish unit tests for #878 (stubs provided). Unit tests live in ItineraryAdminControllerTests. Please reach out to me with any questions

**Comment by cj-taylor** [comment]
Caught the standup this morning and now looking for a place to jump-in. Mind if I start here just to get acquainted/ramped-up or would you prefer I start elsewhere? 

cc: @mgmccarthy @tonysurma

**Comment by tonysurma** [comment]
Thanks for jumping in.  This would be a great place to start.

**Comment by mgmccarthy** [comment]
@cj-taylor, the unit tests are a great way to start getting familiar with the source code, so please jump in!

If u have any implementation questions, feel free to reach out to me.
