### ISSUE TITLE
Virtual url action with redirect for SMS

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#896]
To support short SMS links we should have a route such as:

allready.com/v?id=f6HGx8

which can map and redirect a user to the full page. We could probably approach this in a couple of ways.

1. We create an action and route for each page we'll shorten and then store a unique id against the record which the action can use to build up it's redirect. In that scenario we might have one for volunteer dashboard, one for event details etc. It does mean maintaining more actions and having to have routes for each defined.

2. We try and create something more general (a single route/action) which can map any short code to a controller, action and route id's. We could also map directly to a full url. In both cases though we'd have to think about what happens if our routes or controllers change. Using action and controller names is probably less brittle as those would be unlikely to be renamed and are internal the application.

I'm sure there may be other ways to do this also so up for discussion.

**Comment by mgmccarthy** [comment]
:+1: for number 2 sms "router" idea. 

Could we instead just store controller name/view name using nameof() in a static dictionary with the "smsShortLink" as the key?

(I'm just spitballing here)

```
public static class SmsShortLink
{
    public static string VolunteerDashboard = "f6HGx8";
    public static string EventDetailsDashboard = "56HYh2";
    //etc...
}
...
internal static readonly Dictionary<string, string> Routes = new Dictionary<string, string>
{
    { SmsShortLink.VolunteerDashboard, $"{nameof([CONTROLLER_NAME_FOR_VOLUNTEER_DASHBOARD])}/{nameof([CONTROLLER_NAME_FOR_VOLUNTEER_DASHBOARD].[VIEW_NAME_FOR_VOLUNTEER_DASHBOARD])}" }, //volunteer dashboard
    { SmsShortLink.EventDetailsDashboard, $"{nameof([CONTROLLER_NAME_FOR_EVENT_DETAILS_DASHBOARD])}/{nameof([CONTROLLER_NAME_FOR_EVENT_DETAILS_DASHBOARD].[VIEW_NAME_FOR_EVENT_DETAILS_DASHBOARD])}" } //event details
    //etc...
};
```

This way, the compiler lets us know about breaking name changes and we don't have to involve the database. If we put this info into the database, then the compiler won't catch the name change at design time, but instead it could result in a runtime error (maybe 404) when the sms "router" directs to a controller/view name that doesn't exist.

In this scenario, we'd have a dedicated SmsRoutingController set up that takes a "smsShortLink" as an argument to its Index method, then uses the "Routes" dictionary to construct the appropriate redirect based on the value associated with the "smsShortLInk" key.

**Comment by stevejgordon** [comment]
@mgmccarthy That sounds pretty reasonable to me. We just need to consider the route data such as the id's etc. In my first thoughts (and the reason I was thinking db) was to create a unique route id that maps to a specific itinerary such as /itinerary/2 and itinerary/3 etc.

You're approach would still need us to pass those I guess as additional querystring items to be able to direct onto the correct page? so /v?r=asdsad&id=1 and  /v?r=asdsad&id=2

**Comment by mgmccarthy** [comment]
@stevejgordon I see what you're saying now in supporting the id's...hmmm...

with the id append to the end of the url, we could still use the lookup dictionary and SmsRouterController entry point. After the route was found in the dictionary, would redirect still carrying the id ,and then do the lookup via mediator using id in the appropriate action method.

but now our "short" link just got longer...

To back up to a higher level, why do we want to use sms short links?
- to put an abstraction between the full URL we sound out to volunteers and potential change to our controller/view names?
- to control the length of the link we send out to volunteers? 
- Why is the length something we're concerned with? Is it b/c the size of the message costs the volunteer money on their phone bill?

I'm only asking this b/c i have not written code before that pushes to SMS, so I want to know everything before i just start throwing solutions out there.

**Comment by stevejgordon** [comment]
@mgmccarthy I think primarily it would be SMS length.

@tonysurma What were your thoughts on this?

**Comment by tonysurma** [comment]
will type more later but in short, was just thinking if we could have a simple short url for volunteerdashboard so the link could be '/v'

For SMS, yes less messages means less costs to sender and receiver.  Also if you can keep it under one message you don't have to worry about out of order stuff as that is funky accross senders and receivers.

So for now a simple controller or route (or even url rewrite rule in web.config) that sends /v to volunteerdashboard would be enough (as volunteerdashboard) is a lot of letters :)

**Comment by stevejgordon** [comment]
@tonysurma Oops, I went off at a bit of a tangent. A simple redirecting action should be fine.

**Comment by mgmccarthy** [comment]
@stevejgordon @tonysurma. I'm not too familiar with routing, especially b/c it has changed in asp.core 1. 

I did manage to get a "/v" trailing slash working for clicking on a link and landing them in the VolunteerController's Dashboard action method. I added another Route attribute to the action method on the controller like this:

```
[HttpGet]
[Route("/v")]
[Route("~/Volunteers/Dashboard")]
public async Task<IActionResult> Dashboard()
{
    var viewModel = await _mediator.SendAsync(new GetMyEventsQuery { UserId = User.GetUserId() });

    return View("Dashboard", viewModel);
}
```

this is the simplest possible thing that could work, and I think that's what we're shooting for right now. Let me know if there are any concerns. If not, I'll just be sending out a link for volunteers when assigned/unassigned from an itinerary with just the trailing "/v" which will land them on the /Volunteers/Dashboard page.

**Comment by tonysurma** [comment]
No worries on tangent :) and simple solution sounds great. Thx

**Comment by stevejgordon** [comment]
@mgmccarthy Sorry, read your comment after popping in a quick PR for this. I just added an action with the /v route and a redirect to action on that. Your approach probably worked also, although I suspect it left the url in the browser with just /v showing?

**Comment by mgmccarthy** [comment]
it did the the /v in there... which is not as nice as seeing the real url. When I rebase I'll make sure to pick your changes. Thanks

**Comment by tonysurma** [comment]
@mgmccarthy @stevejgordon I merged it.  Thanks.
