### ISSUE TITLE
Create/Edit campaign - Copy contact errors if user is site admin

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#910]
We should hide this option for a site admin

**Comment by stevejgordon** [comment]
@tonysurma Looking at this very briefly, shouldn't this still work for site admins, as the functionality would be to copy from the event's owning organization contact I believe?

I haven't seen or used this feature before so I may be misunderstanding the intended functionality.

**Comment by tonysurma** [comment]
site admin = admin of all of allready (so not an option)
org admin = admin of an org

so in short should work and be allowed for everyone except for site admins

**Comment by stevejgordon** [comment]
@tonysurma What should actually happen when this button is used?

**Comment by tonysurma** [comment]
when you are an org admin then the contact info for your org should be copied into the campaign (like a nice starting point) if you are a site admin this button should not appear as it doesn't make logical sense etc.

**Comment by Daven-** [comment]
working on this

**Comment by Daven-** [comment]
Leaving this for someone else, error still present when logged in as an organization.

**Comment by dchristensen** [comment]
I was going to try and take a look at this one, but it looks like it is functioning properly.  For site admin the button is not visible.  For org admin the button is visible and is correctly filling the contact information.  I believe this can be closed.
