### ISSUE TITLE
Create event

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#918]
In create event, during create second date box should default to first date box date

**Comment by tonysurma** [comment]
I just looked at the PR and that works partially.  The further solution (if we could do it and I note that we didn't articulate that) is to update the end date on exit of the start date by the user so it will be the same (or a day later) as whatever they entered.  Like an airline website does.  Thanks.

**Comment by stevejgordon** [comment]
Now you're getting fancy @tonysurma! I'm sure a little JS can do it for us. I'll need to research. If anyone wants to jump in that's cool too. I'll try and take a look this weekend.
