### ISSUE TITLE
Events - Remove concept of volunteers req at event level

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#919]
Only tasks should require input of the volunteer amounts required.

**Comment by stevejgordon** [comment]
@tonysurma Do we also want to remove the enforce volunteer limit at this level and put all control over this purely within the tasks?

**Comment by mgmccarthy** [comment]
@stevejgordon, if this is something @tonysurma wants to do for the upcoming launch, I'd be happy to volunteer

**Comment by tonysurma** [comment]
YES! Please remove this.  Makes no sense.  If you wanted to show an event level amount which is total of tasks that is cool but not necessary.  Went ahead and presumptively assigned you @mgmccarthy 🔮

**Comment by mgmccarthy** [comment]
looks like @vishalmadhvani is going to pick this up. @tonysurma, can you re-assign?

**Comment by VishalMadhvani** [comment]
Started looking at this yesterday. Just wanted to confirm this means deleting the following from the Event Model.

```c#
    public int NumberOfVolunteersRequired { get; set; }
    public List<EventSignup> UsersSignedUp { get; set; } = new List<EventSignup>();
    public bool IsLimitVolunteers { get; set; } = true;
    public bool IsAllowWaitList { get; set; } = false;
    public int NumberOfUsersSignedUp => UsersSignedUp.Count;
    public bool IsFull => NumberOfUsersSignedUp >= NumberOfVolunteersRequired;
    public bool IsAllowSignups => !IsLimitVolunteers || !IsFull  || IsAllowWaitList;
```

And hence remove all functionality around volunteers on events?

**Comment by tonysurma** [comment]
@VishalMadhvani double check with @stevejgordon but that seems right as there is no real concept of volunteers at event level other than a sum of needs and who signed up so far for the tasks.

also I just invited you to the repo so I can assign you to issues.  thanks.

**Comment by stevejgordon** [comment]
@VishalMadhvani - Those look correct. I'm sure we'll have quite a few uses of these across various view models and the handlers related to them. We will also be able to remove some of the database columns storing this data for Events as well. That will require a migration which would be best after the RTM stuff is merged in.

We'll just need to ensure anything coming from the task level remains in place and working.

**Comment by tonysurma** [comment]
@VishalMadhvani wanted to check in if you are still working on this.  Thanks in advance

**Comment by tonysurma** [comment]
FYI @stevejgordon is working on this and we chatted today on the approach he is taking (making this note as @mgmccarthy just mentioned that will work on #894 post this change

**Comment by stevejgordon** [comment]
@tonysurma - Started on this last night and a fair way into this. Will continue later during my lunch break. I think I can and will leave the settings for enforce limit and enable waiting list which will then still apply to task signups. Looking at the code, it's easier to leave that in and strip back / refine if we later decide to do so.
