### ISSUE TITLE
Message All from Task

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#920]
Also have message all for task level (is there for event)

**Comment by mgmccarthy** [comment]
@stevejgordon, looks like there is NotifyVolunteerForEventSignup for single volunteer for an event. 

Are you looking for a way to message all volunteers that are currently associated with a Task?

Looks like there is a "Message All" button at the Event level.
![image](https://cloud.githubusercontent.com/assets/2428993/16316688/b17086cc-3955-11e6-88b8-be6e9adf7be7.png)

**Comment by stevejgordon** [comment]
Yep I think that's the goal. So we'd have a similar button on the task which would then send out to all volunteers assigned to that task.

Sent from my Windows Phone
________________________________

**Comment by mgmccarthy** [comment]
@tonysurma please assign to me

**Comment by mgmccarthy** [comment]
@tomysurma, do you have a "P" label for his one so I can prioritize?

**Comment by tonysurma** [comment]
Sorry did this one from mobile, P3

**Comment by mgmccarthy** [comment]
@stevejgordon, it looks like this already exists in the system. I added a couple volunteers for one of the seeded Tasks:
![image](https://cloud.githubusercontent.com/assets/2428993/16436709/1e02f57e-3d6e-11e6-8cbb-d1384ea7bade.png)

You can see as soon as there are some volunteers that need to be "approved" by admin, we can see the "Message All" button. When clicking the button:
![image](https://cloud.githubusercontent.com/assets/2428993/16436760/8876516c-3d6e-11e6-9a05-ebe21e933306.png)

then MessageTaskVolunteersHandlerAsync handler is invoked.

So I think this task can be closed

**Comment by mgmccarthy** [comment]
@stevejgordon can you verify this Issue can be closed based on my research above? Thanks

**Comment by stevejgordon** [comment]
@mgmccarthy Sorry Mike, missed this question. Yep, looks like this can be closed. I've just checked and see it passing through a notify handler.

@tonysurma I'll close this down. This is a question in the code comments around what task info should be included in the message, however it might be better to open a fresh issue defining any changes needed after some beta testing?
