### ISSUE TITLE
Campaign/Event Headlines

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#922]
Allow org admins to specify a "headline" such as 'Currently looking for more electricians...' to generate interest.

**Comment by stevejgordon** [comment]
@tonysurma I started a part of this during my lunch break earlier. Did you have views on where we'd surface this on the site? For example, would including it under the campaign/event name in listers be useful? 

Would limiting the length to around 150 chars be enough do you think so it doesn't too complex to display in smaller spaces?

Note: I'm thinking during redesign we loose the list views on the volunteer parts of the site and move to more UI friendly 'tiles' / 'blocks' to present the data.

**Comment by tonysurma** [comment]
I think 150/tweet length is a good idea.  the idea was to put it on the featured list and under the campaign/event names where they appear so it gives a headline of what is needed/motivation/whatever  Thanks
