### ISSUE TITLE
AllReadyTask model naming

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#927]
It's always bothered me a little that the class name and table name for tasks is AllReadyTask, when every other object does not prefix with AllReady. Any reason not to update the model and db schema to make this just Task? If we're going to do it, before we have live data is the best time.

@tonysurma - What do you think?

**Comment by dpaquette** [comment]
I suspect this was due to an annoying naming collision with System.Threading.Tasks.Task which is referenced anywhere we do async/await.

**Comment by stevejgordon** [comment]
@dpaquette Very good point. We now have event also but have gotten away with that one. I'll just try to stop getting mildly annoyed by it for no valid reason! :smile:
