### ISSUE TITLE
Task start and end times nullable on Model

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#939]
Currently the db model for tasks defines the start datetime and end datetime as optional. This then cascades for the need to check these have values before assigning them in the system to our other models and views.

I can't see a good reason to keep these optional. In fact our validation on the create/edit side, forces these to be completed and valid.

Anyone against me tweaking the db schema / model + trying to rid uses of .HasValue when assigning these to other model properties?

**Comment by tonysurma** [comment]
Unless someone else has a reason, go for it.  They shouldn't be optional.
