### ISSUE TITLE
Add Continuous Integration builds 

### ISSUE THREAD

**Issue by dpaquette** [HTBox/allReady#94]
Would be nice if we could have a CI build setup to automatically compile and run unit tests on each pull request. This would make it easier for those merging pull requests since they would know automatically if a particular pull request has broken the build.

Suggest using App Veyor for this. http://www.appveyor.com/.

**Comment by dpaquette** [comment]
I can help with the setup but this will require someone with admin access to the repo.

**Comment by tonysurma** [comment]
I can help with that as I have admin and have done similar for other repos

FYI we currently direct deploy from repo to azure website at http://allready-d.azurewebsites.net/ so just let me know what you want changed to use AppVeyor (which I have used before but not yet for htbox and I am there)

Lastly I can start an htbox account there and give you access as it is free for open source etc but won't get to that until later this evening

**Comment by dpaquette** [comment]
Deployment from Repo to azure website is great. I don't think we need to change that.  What I would like to enable is a workflow we trigger a CI build (compile and run unit tests) for each pull request. That way we would have more confidence that the code being merged to master isn't breaking something. Setting this up involves creating an App Veyor account, configuring the App Veyor build and enabling integration via Web Hooks. 

It would be great if we can create an App Veyor account and then we can work together on the configuration.

**Comment by tonysurma** [comment]
Yep makes snese, I was trying to type out that response while in the middle of something else so thank you.  You should be connected to our AppVeyor account now

**Comment by dpaquette** [comment]
Will extend as needed. Basics builds are in place now
