### ISSUE TITLE
Startup config registers AddEnvironmentVariables twice

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#942]
Looks like a redundant repetition of the AddEnvironmentVariables call.

![image](https://cloud.githubusercontent.com/assets/3669103/16339897/09b8a752-3a1d-11e6-8b55-47ddd803b48e.png)

**Comment by stevejgordon** [comment]
I have a PR for this, just waiting to ensure this isn't by design and that appSecrets should override env vars.

**Comment by tonysurma** [comment]
I am not seeing the duplication, where is it?  I see only one call for that and one for a config.{environment}.json like config.dev.json (at least in the screenshot above)

Also user secrets should override which is how you can override stuff in your dev box without putting them in config.json and getting them accidentally checked in. (I learned this during our last on campus hackathon)

**Comment by stevejgordon** [comment]
Oops! I screenshotted my fixed version!

![image](https://cloud.githubusercontent.com/assets/3669103/16340570/c5894d1c-3a20-11e6-9327-7bd0d20271af.png)

In the original it adds them before and after the user secrets. So really it should be one or the other.

**Comment by tonysurma** [comment]
Whew, my world makes sense again.  The second one (below the if(env.IsDev)) should be removed

**Comment by stevejgordon** [comment]
Cool, I'll push that in shortly as I have code prepared.
