### ISSUE TITLE
SendAccountSecurityTokenSmsHandler and SendSecurityCodeSmsHandler do the same thing...

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#946]
both send sms security code to user's phone number...

this action should be consolidated to one handler and refactor to use single command/handler.

**Comment by mgmccarthy** [comment]
@tonysurma you can assign this to me

**Comment by mgmccarthy** [comment]
@tonysurma @MisterJames @BillWagner (r u still on the project?) I can't conslidate this code until there is a decision about the content of the message.

`SendAccountSecurityToken/Handler` 
- sent from `AccountController` and `ManageController`
- contains this code: `$"Your allReady account security code is: {message.Token}")`

`SendSecurityCodeSms/Handler` 
- sent from `AdminController`
- contains this code:`$"Your security code is: {message.Token}")`

Both handlers do the exact same thing, but one message contains the word **allReady,** the other does not.

to consolidate to one command/handler, I need a decision on the message (unless you want to keep the two separate messages)

**Comment by BillWagner** [comment]
I'm still here. (Lots of travel last week.)  

On this issue, I'll defer to @MisterJames This is not an area of the code I've looked at.

**Comment by tonysurma** [comment]
So sorry for long delay in simple response.  use the message with allReady please

**Comment by mgmccarthy** [comment]
@tonysurma: closing PR's like it's his job! 🏆
