### ISSUE TITLE
Display issue for org logo on admin pages

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#951]
A large org logo overlaps the details content for an organization currently.

![image](https://cloud.githubusercontent.com/assets/3669103/16357362/60d9a21e-3aec-11e6-8db4-00712c0e02ef.png)

I thought I had this working okay when I added the logo so I'll check if perhaps I missed checking in some css.

**Comment by tonysurma** [comment]
should be closed now per the PR
