### ISSUE TITLE
Send Email and Sms confirmation messages when authenticating using external providers

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#955]
@tonysurma, please assign to me.

this is an Issue that grew out of #840, I've moved my final comment from the last thread on #840 and broke it out into this issue.

@tonysurma, just to clarify the functionality of what was merged in #945. Currently, when authenticating via Facebook, we are NOT sending out a message to confirm email or confirm phone. For regular AllReady registration, we're sending out both messages at the point the user registers.

For Facebook auth, after authenticating, the First, Last, and Email fields are all prepopulated, and the user only has to fill out Phone:
![image](https://cloud.githubusercontent.com/assets/2428993/16356713/9183ab58-3ab0-11e6-8af9-8f18a3a2ecb2.png)

after they click register, we redirect them to the home page, where they can click on their manage account link and this is the page they will see:
![image](https://cloud.githubusercontent.com/assets/2428993/16356725/d18c19e2-3ab0-11e6-8121-35e281656a16.png)

I wanted to outline this for you, b/c regardless of which external auth provider we use, the user still lands on this page after authenticating with the external auth provider:
![image](https://cloud.githubusercontent.com/assets/2428993/16356713/9183ab58-3ab0-11e6-8af9-8f18a3a2ecb2.png)

and they're still required to fill out all four fields in order to continue registration with AllReady, **regardless of what information is made available to us for the given auth provider**. Again, Facebook gives us more info to pre-populate those fields, and Twitter gives us hardly anything (at least from what I've been able to figure out so far).

**I'm thinking since all auth providers use this form page, and since all four fields are required, we should still be able to send an email and sms confirmation message when they hit register.**

**Comment by tonysurma** [comment]
Agree on approach.  If there was a way to detect the email was prepopulated and therefore not send verification for the email that would be even nicer but not required.

**Comment by mgmccarthy** [comment]
"If there was a way to detect the email was prepopulated and therefore not send verification for the email that would be even nicer but not required."

@tonysurma, I'll break that out into another issue and you can assign priority.

**Comment by MisterJames** [comment]
closed via #969
