### ISSUE TITLE
Exception on loading a Task from the Event details page

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#970]
@tonysurma, please assign this to me. I'll be trying to get a PR in for this tonight.

Clicking on any existing seeded Task in any seeded Event (also happening on creating new Campaign/Event/Task) from this page:
![image](https://cloud.githubusercontent.com/assets/2428993/16432758/9d92092a-3d54-11e6-88f1-e871b86df308.png)

results in an exception being thrown on this page:
![image](https://cloud.githubusercontent.com/assets/2428993/16432777/ae59e2fa-3d54-11e6-8199-192be0285847.png)

I believe it's related to the `TaskSummaryModel`'s `StartDateTime` and `EndDateTime` being changed to not allowing null values.

The model properties in /Areas/Admin/Views/Task/Details.cshtml still are accessing those two fields as if they're nullable:
![image](https://cloud.githubusercontent.com/assets/2428993/16432825/0292fdac-3d55-11e6-9c98-f94ccf057123.png)

**Comment by VishalMadhvani** [comment]
Yeah I missed this :oops:

**Comment by mgmccarthy** [comment]
@VishalMadhvani, no problem. I don't even want to know how many exceptions my insane refactorings have caused since I've joined the project :stuck_out_tongue_winking_eye:
