### ISSUE TITLE
Build Razor Views 

### ISSUE THREAD

**Issue by VishalMadhvani** [HTBox/allReady#972]
The CI build should also build razor views.
I know it was possible on the old big fat ASP.NET, not sure about Core.

**Comment by dpaquette** [comment]
yes, it is possible. The documentation is lacking at the moment. I will try to dig something up from the aspnet GitHub repos

**Comment by gdereese** [comment]
This should be possible once the project is upgraded to .NET Core 1.1.  Looks like adding some NuGet packages and changing the build command line:

http://stackoverflow.com/a/37691843/2005951

**Comment by stevejgordon** [comment]
@tonysurma - Given that this is 1.1 only and we've decided to stick on LTS for a while at least, do we want to keep it on the backlog as a hint for "future us" or do we close this issue for now?

**Comment by mk0sojo** [comment]
This is on by default in asp.net core 2.
When we publish the app AllReady.PrecompiledViews.dll is created.

https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?tabs=aspnetcore2x

**Comment by stevejgordon** [comment]
@mk0sojo yes you are correct. I think we can close this now that it's on by default.
