### ISSUE TITLE
pull email and name from Twitter external login provider

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#977]
@tonysurma please assign to me.

I'm currently working on this.

**Comment by dpaquette** [comment]
I was under the impression that twitter didn't provide email addresses.

**Comment by mgmccarthy** [comment]
@dpaquette, it doesn't. But, apparently, there is some extra work involved to fetch it. I've been following this blog to see if it's possible:
http://www.bigbrainintelligence.com/Post/get-users-email-address-from-twitter-oauth-ap

It is a good amount of extra work, and I don't know if it's feasible for AllReady.

We can always throw this Issue on the backlog with low priority, or it will never be a priority, delete it.

**Comment by dpaquette** [comment]
I was hoping you had found an easy way to get the email address. I'm having this same problem on another project right now.

**Comment by mgmccarthy** [comment]
update on this, apparently, [LinqToTwitter](https://github.com/JoeMayo/LinqToTwitter) is not compatible with asp.net core, at least, not yet. I checked the repository, and there is an open issue for it, but nothing from the project owner as to when he'll be updating the library (if he updates it at all).

Which means I might need to dive into building the OAuth requests myself using HttpClient. Also, there are time restraints between the time you authenticate and the time you make an additional request to get the user's email, additional steps to white-listing your application with Twitter to allow for querying for user's email and a cap on how many times you can make the query in a given time span.

Not too sure if it's worth it.
