### ISSUE TITLE
Resource Based Authorization

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#982]
I spent a bit of time yesterday reading up on Resource Based Authorization which is part of the ASP.NET Core authorization stack.

In short this provides a standardised way to authenticate that a user has permission to perform an action on a specific resource. Within allReady we do this often to ensure that admin users have permission to modify only the objects which belong to their organization. E.g. An org admin can only view/edit an event if it belongs to their organization.

We have a useful extension method on the ClaimsPrinciple which checks if a user can access an object based on the OrganizationId. At the moment we have to rely on this method being called by most of the admin actions, in some cases having to handle code to first query for the OrganizationId based on an event, itinerary or task.

Resource based authorization feels like a good approach to clean the code a little and start to rely on the underlying authorization design within ASP.NET Core. What it means is that we have a few authorization handlers than can accept an object and then perform the relavant checks to ensure the user is authorized. These handlers are regsitered within the DI container and ASP.NET Core will check for appropriate handlers when we call the _authorizationService.AuthorizeAsync method. We just need to inject the IAuthorizationService into our admin controllers.

This feels like a sensible approach as in some cases it will simplify our code. We can move the logic that queries the db (where it needs to) to get an org Id and utilise the existing plumbing to manage the authorization. We can write tests around the auth handlers so that once they are defined we can ensure that they work as expected. Our logic lives in one place and has a single responsibility. Our controller actions will be slightly simplified in some cases as we won't need to use the Mediator to query for the org id. The controller should not really own that activity.

Also I think it should simplify our controller testing as well since I can't see that we'd need to mock up the User claims. We can mock the IAuthorizationService and verify it a) gets called where it should and b) mock the return from AuthorizeAsync to validate the success and failure behaviours.

There is a bit of a caveat for RC1 code in that the handler requires an override on the sync Handle method as well as the async one. This has been fixed in RTM I believe.

I spent a bit of time to put in an example PR where I have created some of the structure for using resource based auth. I have utilised this on a few sample actions to show how it would fit together. I'll submit the PR for easier discussion and review of this issue.

Ultimately, if it's agreed this feels like the proper approach I can flesh out my code a little more and we can begin to implement it on new actions, plus over time tidy up the existing actions.

Please let me know your thoughts.

See https://docs.asp.net/en/latest/security/authorization/resourcebased.html for more info.

**Comment by mgmccarthy** [comment]
This looks great. My favorite part here is the centralization of calls like `User.IsOrganizationAdmin` that is spread all over the controller code. This centralization allows us to write tests for the given policy ONCE, instead of having to "drag" that setup code around our controller unit tests.

Pretty cool that MS decided to build this as part of the framework... if not, we'd have to write/wire up something like this in the system ourselves (which would be possible, but Microsoft has taken care of the plumbing for us)

**Comment by VishalMadhvani** [comment]
Be interesting to see if this could be wired up as an attribute.

**Comment by stevejgordon** [comment]
I'd taken a look at the attribute option. From what I'd read attributes might be a bit tricky since attribute evaluation occurs prior to data binding and before any code runs within the action. I suspect this means that route data is also might be available (although I didn't conclusively see an answer to that so far). I'd prefer attributes in some respects but the approach MS seem to guide us on is the imperative auth via the authorization service.

Where we need to load an object from the db it feels better to call the service inline after we've loaded it as we can pass it into our authorization handler. An attribute approach would likely see us double querying the DB in some cases which feels less efficient unless we get some caching in front of those calls (which in itself isn't a bad idea to start thinking about - although may be a bit of an ealy optimisation at this time)

I'll revisit the docs and have a play around to see if the route data is available as from that we might be able to do something in attributes.

**Comment by tonysurma** [comment]
pinging @MisterJames and @BillWagner for thoughts
