### ISSUE TITLE
build error Event is a namespace but is used like a type - high priority

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#985]
3579‍C:\projects\allready\AllReadyApp\Web-App\AllReady.UnitTest\ViewModels\Campaign\CampaignViewModelShould.cs(102,68): DNX,Version=v4.5.1 error CS0118: 'Event' is a namespace but is used like a type
 3580‍C:\projects\allready\AllReadyApp\Web-App\AllReady.UnitTest\ViewModels\Campaign\CampaignViewModelShould.cs(102,81): DNX,Version=v4.5.1 error CS0118: 'Event' is a namespace but is used like a type

**Comment by tonysurma** [comment]
line of code is
_var campaign = new Models.Campaign { Events = new List<Event> { new Event { Id = 1} }};_

looks like conflict of Event from _AllReady.ViewModels.Event_ and the class name

**Comment by mheggeseth** [comment]
@tonysurma This can be closed. Wasn't auto-closed by PR because software.

**Comment by tonysurma** [comment]
because software is hard
