### ISSUE TITLE
Mark request completed

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#991]
Add functionality to allow requests within an itinerary to be marked completed.

@tonysurma Would adding this initially on the org admin itinerary management page suffice for the pilot? I've got some time to kill at the office tonight before a .net meetup so thought I'd have a go at this.

**Comment by tonysurma** [comment]
Yes it would, and later we can figure out a plan for the volunteers on the itinerary to be able to do it.  Thx

**Comment by stevejgordon** [comment]
Thanks. I'll try and get something done on this later.
