### ISSUE TITLE
Use Fody and ConfigureAwait NuGet Packages to automate .ConfigureAwait(false)

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#996]
this issue was created by breaking out @SeanFeldman's comments about Fody from Issue #892

Fody: https://github.com/Fody/Fody/
ConfigureAwait: https://github.com/distantcam/ConfigureAwait

Although this does use IL weaving, it might be worth adding these libraries so we can use an attributes to decorate handler classes (where must of .ConfigureAwait(false) calls are made) so we don't have a bunch of .ConfigureAwait(false)'s all over our code.

**Comment by SeanFeldman** [comment]
ATM there's no support for .NET core, but it will be coming shortly.

**Comment by stevejgordon** [comment]
Closing this as we have done away with ConfigureAwait
